### ISSUE TITLE
Google cloud print

### ISSUE THREAD

**Issue by daanporon** [googleapis/google-api-nodejs-client#101]
Can i use this for google cloud print? i presume i can use the oAuth2 stuff to get an access token and then make the requests to google cloud print myself by setting the right Authorization header (Authorization: OAuth YOUR_ACCESS_TOKEN). Google cloud print doesn't support the discovery as far as i know.

kind regards,
Daan

**Comment by alexiskattan** [comment]
+1
Would love official fix.  Check https://github.com/postmen/cloud-print-nodejs and https://github.com/postmen/cloud-print-nodejs for a patched version.

**Comment by ryanseys** [comment]
Sorry, if it's not yet available via Discovery then it will not be added to this library. Please use your work around until it becomes available.

**Comment by alexiskattan** [comment]
Thanks for the answer.  I have a quick question that I tried googling for..  What is Discovery?

**Comment by ryanseys** [comment]
Discovery is the Google service this library uses to get access the the APIs and their specifications so that it can generate the client code for the APIs. You can learn about it here: https://developers.google.com/discovery/
