### ISSUE TITLE
Empty files in GCS when running dataprep template using the google api

### ISSUE THREAD

**Issue by noamackerman** [googleapis/google-api-nodejs-client#1058]
Hi!
I am using dataprep templates and a cloud function with a GCS trigger (when a new file arrives) to invoke dataflow jobs. There is constantly a strange behavior where the results of running a job using googleapis creates only empty files in the output folder in GCS. When using BigQuery as the output, it works when I invoke only one job at a time. When I try to invoke multiple jobs at the same time (e.g. adding multiple files together to a bucket), I get empty tables as well. It works when I run it manually in dataprep. I'm using the code below to create the job from a template:

            dataflow.projects.templates.create({
                projectId: 'my projectId',
                resource: {
                    parameters: {
                        "inputLocations":  my inputLocation,
                        "outputLocations":outputLocation 
                    },
                    jobName: 'cloud-fn-dataflow-test-' + timeStamp,
                    gcsPath: 'my gcsPath'
                }

Highly apricate your help,
Noam

**Comment by JustinBeckwith** [comment]
Greetings!  Taking a look at the API, these are the right parameters and match up with what we'd expect.  I'd suggest following some of the guidance here to get this in front of the product team:
https://cloud.google.com/dataflow/docs/support/getting-support

Best of luck!
