### ISSUE TITLE
High memory usage when uploading large file.

### ISSUE THREAD

**Issue by datnguyencse** [googleapis/google-api-nodejs-client#1107]
Env: Nodejs v8.9.1, googleapis v28.1.0, Windows 10.
I tried to upload a large files around 2GB, I notice that the process is up to 3GB RAM. My code upload that file to Drive successful on 8GB ram system, failed on 1GB ram system.

```javascript
      var fileMetadata = {
         "name": fileName
      }

      var media = {
          mimeType: mineType,
          body: fs.createReadStream(path)
      }

      self.drive.files.insert({
          resource: fileMetadata,
          media: media,
          fields: "id"
      }, function (err, file) {
        if (err) {
          logger.error("Error: " + err.message)
        }
        logger.info("Finished, id: " + file.data.id)
      })
```
8GB RAM
![untitled](https://user-images.githubusercontent.com/11866125/38407024-1afd7160-39a2-11e8-8d78-f6637a80a2c5.png)
1GB RAM
![image](https://user-images.githubusercontent.com/11866125/38407003-056e9a5e-39a2-11e8-9080-734991f9c4ef.png)

**Comment by datnguyencse** [comment]
Hi Fengmao, I'm using Oauth2:
```
let googleAuth = new OAuth2(
            token.client_id,
            token.client_secret
          )

          googleAuth.setCredentials({
            access_token: token.access_token,
            refresh_token: token.refresh_token,
            expiry_date: token.expiry_date
          })

          // auto refresh token itself
          this.drive = google.drive({ version: 'v3', auth: googleAuth })

```

**Comment by ghjbnm** [comment]
I think it's an issue with axios/follow-requests.
There is a buffer array in the globalAgent that seems to grow without ever being deallocated.
As a workaround using the following code in the onProgress function of the readStream seems to work:

```
https.globalAgent.sockets["www.googleapis.com:443::::::::::"][0]._httpMessage._redirectable._requestBodyBuffers=[];
https.globalAgent.sockets["www.googleapis.com:443::::::::::"][0]._httpMessage._redirectable._requestBodyLength=0;
```

**Comment by ghjbnm** [comment]
Related axios issue:
https://github.com/axios/axios/issues/1045

**Comment by dipu-bd** [comment]
I am using `NodeJS.ReadableStream` to upload file from my server. I do not have access to locally downloaded file. Is there any way to solve this issue for me?

**Comment by ghjbnm** [comment]
Did you try using `maxRedirects: 0`, works for me fine.
Should look somewhat like this:
```
google.youtube('v3')["videos"]["insert"](
	{
		auth: oauth2Client,
		part: 'id,snippet,status',
		requestBody:requestBody,
		media:
		{
			body: readStream
		}
	},
	{
		maxContentLength: 128 * 1024 * 1024 * 1024,
		maxRedirects: 0
	});
```

**Comment by dipu-bd** [comment]
it worked! thank you @ghjbnm

**Comment by JustinBeckwith** [comment]
Pretty sure we have this fixed on master, and it's going to be in v37 :)
