### ISSUE TITLE
Documentation on how to write monitoring metrics doesn't help much

### ISSUE THREAD

**Issue by jinwoo** [googleapis/google-api-nodejs-client#1142]
The document clearly says I have to use `monitoring.projects.timeSeries.create()`, which is good: https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/create

But it doesn't have any sample code for what the actual payload should be within the `resource` field: what `timeSeries`, `timeSeries/metric`, and `timeSeries/metric/labels` fields should be like, etc. It's really frustrating to figure them out by trials and errors.

**Comment by JustinBeckwith** [comment]
I have some good news :) . See #1141.

**Comment by jinwoo** [comment]
Awesome. But even with that change, things are still not clear. E.g. what the `timeSeries/metric/labels` field should look like? The type definition says just `any` :(

**Comment by AVaksman** [comment]
@jinwoo 
Please see TimeSeries docs [page](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeSeries).
I believe there is a good description of all TimeSeries object components.

Please confirm if this helps you.
