### ISSUE TITLE
File encoding with drive API broken

### ISSUE THREAD

**Issue by JaakkoL** [googleapis/google-api-nodejs-client#1151]
Google Drive API allows specifying file encoding for the response data. Underneath it's overriding Axios options, like the [documentation states](https://github.com/google/google-api-nodejs-client#request-level-options).

However, with the current latest Axios release (0.18.0), which this library is using, this is not implemented. This https://github.com/axios/axios/pull/869 PR has that feature implemented, but it's not part of the released package. Also, it seems that even with these changes included, the Google Node Client implementation regarding file encoding doesn't work in the documented way (how it used to work prior to the switch to Axios from Request).

**Comment by JaakkoL** [comment]
Sure thing @JustinBeckwith !

So basically what were using is Google Drive API for downloading a single file.

```
const { data } = await drive.files.get({ fileId: '<redacted>', alt: 'media' }, { encoding: 'latin1' });
```

In the documentation on [request level options](https://github.com/google/google-api-nodejs-client#request-level-options) of the client, it says:

> You can also override axios options per request, such as `url`, `method`, and `encoding`.

Passing the encoding in request options used to work at least before `googleapis` switched from `request` to `axios`.

I digged into `axios` code and found out some issues on their current release, which is not even supporting the encoding options (which is btw `responseEncoding` instead of `encoding`), but they're working on to resolve this. See https://github.com/axios/axios/issues/1519

So I think that in order to resolve this, and continue supporting response encoding option, `axios` needs to first resolve issues on their side and after that probably updating documentation and examples to the correct request level options format (`responseEncoding` etc.) should be enough.

In the meanwhile, this can be resolved (at least on our end) in the application logic by returning array buffer from the request and handling the encoding in the application logic itself instead relying on the library. E.g.

```
const { data } = await drive.files.get({ fileId, alt: 'media' }, { responseType: 'arraybuffer' });
data.toString('latin1')
```

**Comment by JustinBeckwith** [comment]
Since we last took a look here, we switched our underlying transport layer from `axios` to our own client, `gaxios`.  I suspect the problem is solved, but wanted to check in :) 

Are you still having issues here?

**Comment by JaakkoL** [comment]
I think this can be considered resolved.
