### ISSUE TITLE
ML Engine API predict request body ill-defined

### ISSUE THREAD

**Issue by jsnowacki** [googleapis/google-api-nodejs-client#1168]
I try to write Firebase/Google Cloud Function in TypeScript to call existing model published in ML Engine, for which remote calls with Python API works fine; thus, there are no issues with the model.

Some previous online samples I've found have requests in form as follows:
```javascript
{
    name: "projects/" + project+ "/models/" + model,
    resources: {
        instances: [{b64: "some-base64"}]
}
```
When I try to make such request in TypeScript I get an error, as interface `Params$Resource$Projects$Predict` doesn't have a property `resources`. The interface has `resourceBody` but it requires interface `Schema$GoogleCloudMlV1__PredictRequest`, which only has property `httpBody?: Schema$GoogleApi__HttpBody`. 

Overall, there is no clear way how to define a proper request body as defined in https://cloud.google.com/ml-engine/docs/v1/predict-request, maybe apart from serializing data manually e.g.:
```
requestBody: {
            httpBody: {
                data: JSON.stringify({instances:  [{b64: "some-base64"}]})
            }
        }
```
I'm not sure if the above is intended, as it is a bit backward compared to the previous approach or e.g. Python API. Other APIs. e.g. drive one, seem to have request body interfaces defined more along their API definitions in the manuals.

**Comment by marcorei** [comment]
@jsnowacki Did you find an answer to this? 

`GeneratedAPIs.ml` has now the type `any` which effectively removes type errors when using the request format from the examples (but of course also all types).

An interface that contained a method with the signature of the examples would be great. `ml_v1.Ml.Resource$Projects` doesn't seem to be the one though.

**Comment by jsnowacki** [comment]
@marcorei The second request seems to work fine, though, you have to effectively make manual call with JSON body. Other than that I haven't find any other solution. From what I see and my understanding of the problem, to get close to the example shown above interface `Schema$GoogleCloudMlV1__PredictRequest` should have property `instances`. It seems like `httpBody?: Schema$GoogleApi__HttpBody` is some generic fallback property from some generator. For other APIs it seems to work fine as in the documentation. Speaking of which, there is also no documentation for ML Engine API in this package documentation. All of the above solutions are based on reverse engineering and online posts.  

If you have a suggestion of useful PR for this issue, let me know. I'm happy to help.

**Comment by willbattel** [comment]
I just migrated my project over to Typescript and am now running into this problem. Curiously, this docs page doesn't show the `resources` parameter- but I could've sworn that it used to, or that it was listed on a similar page. https://cloud.google.com/ml-engine/reference/rest/v1/projects/predict

Not quite sure how to get past this one.

**Comment by swayam18** [comment]
I am running into the same problem. @marcorei Did the team get a chance to investigate this issue?

**Comment by JustinBeckwith** [comment]
Greetings folks - checking in.  Are y'all still having issues?
