### ISSUE TITLE
Fitness dataset aggregate 500 error

### ISSUE THREAD

**Issue by pradz39** [googleapis/google-api-nodejs-client#1176]
I am using v30.0.0, following code snippets ends in 500 Backend error

```js
async get(tokens) {
  this.oauth2Client.setCredentials(tokens);
  const res = await this.fitness.users.dataset.aggregate({ 
    userId: 'me', 
    requestBody:  {
      startTimeMillis: 1526560938021, 
      endTimeMillis: 1526560948021 
    }
  });
console.log(res)
```

```
  code: 500,
  errors: 
   [ { domain: 'global',
       reason: 'backendError',
       message: 'Backend Error' } ] }
```

**Comment by hilliao** [comment]
I have the same error with API explorer just getting a list of data sources. I started to happen today under my username:

Request
 
GET https://www.googleapis.com/fitness/v1/users/me/dataSources?key={YOUR_API_KEY}
 
 
Response
 
500
 
- Show headers -
  
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "backendError",
    "message": "Backend Error"
   }
  ],
  "code": 500,
  "message": "Backend Error"
 }
}

**Comment by JustinBeckwith** [comment]
Greetings folks!  If this is a problem with the backend API - sadly there's just not a lot we can do here :(  I would suggest creating an issue here:
https://developers.google.com/fit/support

Hope this helps!
