### ISSUE TITLE
Cannot specify alt=media on v3 drive.files.get API

### ISSUE THREAD

**Issue by jacobdufault** [googleapis/google-api-nodejs-client#1193]
I'm trying to download a file using v3 drive API, and from the [docs](https://developers.google.com/drive/api/v3/manage-downloads) it sounds like I need to specify `alt=media` to download a file.

However, doing so seems impossible, looking at the API for `drive.files.get` - hopefully I'm not missing something obvious. Thanks!

https://github.com/google/google-api-nodejs-client/blob/82920f4731eb16140f8bb7fabc9e06a3777a1d65/src/apis/drive/v3.ts#L2820-L2839

**Comment by JustinBeckwith** [comment]
This is a TypeScript type bug.  We generate interfaces looking at the method specific discovery metadata.  However, there's also a top level `parameters` object in the root of the discovery metadata that outlines querystring parameters available for each request.  For example:
https://www.googleapis.com/discovery/v1/apis/drive/v3/rest

The fix here is to generate the top level parameters interface, and use a union type for params. 

All that aside....

This sample sets alt to media, and does work:
https://github.com/google/google-api-nodejs-client/blob/master/samples/drive/download.js

So your code is fine :)

**Comment by JustinBeckwith** [comment]
This is fixed :)
