### ISSUE TITLE
Problems determining serial appointments

### ISSUE THREAD

**Issue by MrCodeGarage** [googleapis/google-api-nodejs-client#1217]
Hello,
I'm having the following problem right now.
I would like to use the Goolge Calendar API to find out all serial appointments that belong to an appointment. My starting point is that I have a Google Event Id. (Not the serial appointment ID). Since you don't have a serial appointment id, and this is not provided as a feature when retrieving the Google event, I haven't been able to get all serienterime via API yet. It's also strange to say that I get this info on new appointments but existing appointments that no longer exist now the question is that an API error? Anybody have an idea? I thank you in advance Dear Greetings Asan

**Comment by grant** [comment]
Hi @MrCodeGarage,
Do you have a specific question?
Can you provide an example request that is failing?
