### ISSUE TITLE
Scoped package installs do not work (yet)

### ISSUE THREAD

**Issue by mhuebert** [googleapis/google-api-nodejs-client#1260]
The @google/iam install instructions in the [README](https://github.com/google/google-api-nodejs-client/blob/master/src/apis/iam/README.md) do not appear to work:

```bash
$ npm install @google/iam
npm ERR! code E404
npm ERR! 404 Not Found: @google/iam@latest
```

Using npm v6.2.0, node v6.14.0.

**Comment by JustinBeckwith** [comment]
Greetings!  The scoped package installs ( `@google/iam`, etc) do not work quite yet :) Lets use this issue to track that.

**Comment by JustinBeckwith** [comment]
Tracking this in #806
