### ISSUE TITLE
Could not update post labels (BLOGGER)

### ISSUE THREAD

**Issue by lbngoc** [googleapis/google-api-nodejs-client#1262]
Today, I try patch post labels with new value but got this error:

> Error: We're sorry, but the value for field labels was not valid.

This is also appear when I can `.update` function

I pass array of string to labels value `["a", "b"]` as image below for my testing, it is working with `.insert` function

![](https://i.imgur.com/1F2Z36d.png)

**Comment by lbngoc** [comment]
Hi, Is there anyone face this issue and have a solutions for this case?

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share the code you're trying right now?  It looks like the `labels` string array needs to be included in the `requestBody` :)

**Comment by lbngoc** [comment]
Here is my code:
```
 const blogger = google.blogger('v3')
...
  async patchPost(blog: blogger_v3.Schema$Blog | any, post: blogger_v3.Schema$Post | any, patchedData: blogger_v3.Schema$Post | any) {
    // this.filterLabels(patchedData)
    let res = await blogger.posts.patch({
      blogId: blog.id || blog,
      postId: post.id || post,
      requestBody: patchedData
    })

    return res.data
  }
...
let res = await this.patchPost('XXXXX', 'YYYYY', { labels: ['label_1', 'label_2'] }).catch(err => console.error(err))
```

**Comment by lbngoc** [comment]
Look like I found the core issue here. At current, my blog has 4500+ labels and 2500+ posts:
- When I put some exists labels for the post and update/patch, the function is working correctly
- When I try update/patch a post with some new label, the API always return this error (It means that Blogger does not allow creating new label via API when a blog reached a some limitation)

**Comment by JustinBeckwith** [comment]
Got it.  I don't think there's a ton we can do about the backend limitations here sadly.  If you're still having trouble and think the library can help - please do let us know!
