### ISSUE TITLE
Wrong type for /v1/people/getBatchGet parameter `resourceNames`. Should accept `string[]`

### ISSUE THREAD

**Issue by joonhocho** [googleapis/google-api-nodejs-client#1266]
As stated in title, `resourceNames` should accept `string[]` as well as `string`:

https://github.com/google/google-api-nodejs-client/blob/master/src/apis/people/v1.ts#L2399

Detailed discussion: https://stackoverflow.com/questions/51588465/is-resourcenames-comma-separated-in-google-people-getbatchget?noredirect=1#comment90144867_51589512

Thanks!

**Comment by JustinBeckwith** [comment]
Yup, this is a bug!  The generator doesn't know what to do with the `repeated` flag in the discovery doc format:

In here:
https://people.googleapis.com/$discovery/rest?version=v1

```js
"resourceNames": {
              "location": "query",
              "description": "The resource names of the people to provide information about.\n\n- To get information about the authenticated user, specify `people/me`.\n- To get information about a google account, specify\n  `people/`\u003cvar\u003eaccount_id\u003c/var\u003e.\n- To get information about a contact, specify the resource name that\n  identifies the contact as returned by\n[`people.connections.list`](/people/api/rest/v1/people.connections/list).\n\nYou can include up to 50 resource names in one request.",
              "type": "string",
              "repeated": true
            }
```
