### ISSUE TITLE
Support webpack

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-api-nodejs-client#1286]
Currently the library does not support webpack.  We should fix that!

Currently blocked on https://github.com/google/google-auth-library-nodejs/pull/371

**Comment by douglasward** [comment]
hey @JustinBeckwith any news on supporting webpack now that googleapis/google-auth-library-nodejs#371 is merged?

**Comment by JustinBeckwith** [comment]
This has landed!

**Comment by iantalarico** [comment]
@JustinBeckwith I just tried webpacking with `3.1.2` and it failed. Is this the correct release where webpack should work?

**Comment by iantalarico** [comment]
@JustinBeckwith Nevermind it works, I wasn't including the right bits, please ignore.

**Comment by CiriousJoker** [comment]
> @JustinBeckwith Nevermind it works, I wasn't including the right bits, please ignore.

Can you elaborate please? It doesn't work for me either...
