### ISSUE TITLE
BackendError code: 500

### ISSUE THREAD

**Issue by maxbrodie** [googleapis/google-api-nodejs-client#129]
I am executing a simple client.drive.files.get for one file ID. I don't believe the request is malformed since it will work as expected for 100s of requests before inconsistently returning the error. I also don't believe the issue is an invalid access token or an invalid file ID as I've seen the (far more specific) errors for both of those cases. The error response:

{ errors:
   [ { domain: 'global',
       reason: 'backendError',
       message: 'Backend Error' } ],
  code: 500,
  message: 'Backend Error' }

or sometimes:

 { code: 500, message: null }

is inconsistently generated by:

  googleapis
  .discover('drive', 'v2')
  .execute(function(err, client){
    if(err) {
        console.log('call_google err 1')
        return next(err)
      } 
    }
    else {
      client.drive.files.get({fileId:fid})
      .withAuthClient(oauth2Client)
      .execute(function(err, results){
       if (err) {
        // BACKEND ERROR 500 LOGGED HERE
       }
       // ...

I realize this may be a problem with the API itself, but thought I would start here.

**Comment by Alina707** [comment]
I am getting this error
An client error occurred: Error calling GET https://www.googleapis.com/youtube/v3/channelSections?part=snippet%2CcontentDetails&mine=true: (500) { "error": { "code": 500, "message": null } }

And my Code is:

<?php

$htmlBody="";
// Call set_include_path() as needed to point to your client library.
    require_once ('google-api-php-client-master/src/Google/Auth/OAuth2.php');
    require_once ('google-api-php-client-master/src/Google/autoload.php');
    require_once ('google-api-php-client-master/src/Google/Service/Resource.php');
require_once 'google-api-php-client-master/src/Google/Client.php';
require_once 'google-api-php-client-master/src/Google/Service/YouTube.php';
session_start();

/*
 * You can acquire an OAuth 2.0 client ID and client secret from the
 * Google Developers Console <https://console.developers.google.com/>
 * For more information about using OAuth 2.0 to access Google APIs, please see:
 * <https://developers.google.com/youtube/v3/guides/authentication>
 * Please ensure that you have enabled the YouTube Data API for your project.
 */
$OAUTH2_CLIENT_ID = '401380652438-dv995betukgul17vacbs08j92ia8ocu4.apps.googleusercontent.com';
$OAUTH2_CLIENT_SECRET = 'hhVZOe7FJOxsElTFjRKtX35t';

$client = new Google_Client();
$client->setClientId($OAUTH2_CLIENT_ID);
$client->setClientSecret($OAUTH2_CLIENT_SECRET);
$client->setScopes('https://www.googleapis.com/auth/youtube');
$redirect = 'http://localhost.vozax.com/tutorials/shuffleExistingChannel.php';
$client->setRedirectUri($redirect);
//$client->approval_prompt=force;

// Define an object that will be used to make all API requests.
$youtube = new Google_Service_YouTube($client);

if (isset($_GET['code'])) {
  if (strval($_SESSION['state']) !== strval($_GET['state'])) {
    die('The session state did not match.');
  }

  $client->authenticate($_GET['code']);
  $_SESSION['token'] = $client->getAccessToken();
  header('Location: ' . $redirect);
}

if (isset($_SESSION['token'])) {
  $client->setAccessToken($_SESSION['token']);
}

// Check to ensure that the access token was successfully acquired.
if ($client->getAccessToken()) {
  try {

    // Call the YouTube Data API's channelSections.list method to retrieve your channel sections.
    $listResponse = $youtube->channelSections->listChannelSections('snippet,contentDetails', array('mine' => true));
    $channelSections = $listResponse['items'];

    // This will randomly reorder the items in the channel_sections list.
    shuffle($channelSections);

    $htmlBody .= "<h2>Sections Shuffled</h2><ul>";
    
    foreach ($channelSections as $channelSection) {
      // Each section in the list of shuffled sections is sequentially
      // set to position 0, i.e. the top.
      $channelSection['snippet']['position'] = 0;

      // Call the YouTube Data API's channelSections.update method to update a channel section.
      $updateResponse = $youtube->channelSections->update('snippet,contentDetails', $channelSection);

      $htmlBody .= sprintf('<li>%s "%s"</li>',
          $updateResponse['id'], $updateResponse['snippet']['title']);
    }

    $htmlBody .= '</ul>';

  } catch (Google_ServiceException $e) {
    $htmlBody .= sprintf('<p>A service error occurred: <code>%s</code></p>',
        htmlspecialchars($e->getMessage()));
  } catch (Google_Exception $e) {
    $htmlBody .= sprintf('<p>An client error occurred: <code>%s</code></p>',
        htmlspecialchars($e->getMessage()));
  }

  $_SESSION['token'] = $client->getAccessToken();
} else {
  // If the user hasn't authorized the app, initiate the OAuth flow
  $state = mt_rand();
  $client->setState($state);
  $_SESSION['state'] = $state;

  $authUrl = $client->createAuthUrl();
  $htmlBody = <<<END
  <h3>Authorization Required</h3>
  <p>You need to <a href="$authUrl">authorize access</a> before proceeding.<p>
END;
 }
    ?>

    <!doctype html>
    <html>
    <head>
    <title>Sections Shuffled</title>
    </head>
    <body>
      <?=$htmlBody?>
<!----------script
  (function() {
    var cx = '011303393276708622642:t3ubxx__zlo';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//www.google.com/cse/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script
<gcse:search </gcse:search>
    </body>
    </html>



Kindly help me to resolve it

**Comment by Alaneor** [comment]
@Alina707 Perhaps the google-api-php-client community would be a better place to look for help? This is JavaScript repository.:-)

PS. It might be a good time now to revoke your client secret, now that you made it public...

**Comment by PrakashKumar0143** [comment]
Hi i am also facing the same problem in my Sitekit plugin.
