### ISSUE TITLE
Multiple Dimensions not possible?

### ISSUE THREAD

**Issue by smyth64** [googleapis/google-api-nodejs-client#1291]
I tried this:
```
  const paramsEvents = {
    'auth': authClient,
    'ids': 'ga:178260168',
    'metrics': 'ga:uniqueEvents',
    'start-date': start.format('YYYY-MM-DD'),
    'end-date': end.format('YYYY-MM-DD'),
    'dimensions': [{ name: 'ga:eventAction' }, { name: 'ga:date' }]
  }
// And also this
    'dimensions': [ 'ga:eventAction', 'ga:date']
```

I expect to get multiple dimensions in the results but I only get 1 dimension.

**Comment by grant** [comment]
This seems like an API question. Have you tried using the [API Explorer](https://developers.google.com/apis-explorer/#p/)?

Can you provide the name of the specific endpoint you're trying to hit?

**Comment by cbratschi** [comment]
I have the exactly same problem. The API Explorer works fine but the Node API only uses the first parameter.

**Comment by bcoe** [comment]
@cbratschi @smyth64 according to the documentation, dimensions should be a:

_A comma-separated list of Analytics dimensions. E.g., 'ga:browser,ga:city'._

I think if you switch to this approach you should find it works :ok_hand: 

https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/analytics/v3.ts#L2523

**Comment by smyth64** [comment]
Yeah it works now :)

**Comment by cbratschi** [comment]
Yes, here too.
