### ISSUE TITLE
Sample Request: Google Cloud Talent API

### ISSUE THREAD

**Issue by tetreault** [googleapis/google-api-nodejs-client#1296]
Would be great to have samples for the Cloud Talent API

**Comment by JustinBeckwith** [comment]
Sure!  What exactly are you trying to do with it?

**Comment by tetreault** [comment]
My use case is ideally building an API using NodeJS. From a call to the server the Cloud Talent API would fetch job search results based off of a keyword or category (like searching "creative director jobs"). I appreciate the quick response @JustinBeckwith ! I went thru the docs on Friday, trying to integrate a simple cloud talent api search via AWS API Gateway/AWS Lambda but am having some difficulties (I can elaborate more when I'm back at my desktop, am on mobile at the moment!)

**Comment by tetreault** [comment]
Back at my laptop now, to expand on my post I was wondering/hoping I can use the Cloud Talent API to search any and all publicly available job posts. 

Use case: 
User goes to this site, the add in keywords or job name they're searching for. They submit the form, it sends a req to my API Gateway proxying my lambda script. The Cloud Talent API returns some of the publicly available job posts and renders it in some fashion for them on my page.

**Comment by nwkeeley** [comment]
@JustinBeckwith I was looking for a sample as well - I have an issue open - I am not sure of the syntax for POSTing data (like creating companies, jobs or issuing a search request) - I see how to pass the `parent` for V3 but I am not sure how to pass the requesting body

**Comment by christiancannata** [comment]
> @JustinBeckwith I was looking for a sample as well - I have an issue open - I am not sure of the syntax for POSTing data (like creating companies, jobs or issuing a search request) - I see how to pass the `parent` for V3 but I am not sure how to pass the requesting body

Hi Guys, here is an example for a create request, you have to add requestBody to json object!

```
 await jobService.projects.companies.create({
          parent: projectId,
          requestBody: {
            //here your body
          }
        }
```
