### ISSUE TITLE
 Invalid topicName on Gmail watch() method

### ISSUE THREAD

**Issue by willsnake** [googleapis/google-api-nodejs-client#1301]
Hi!
I'm using the latest version of [googleapis](https://github.com/google/google-api-nodejs-client/releases/tag/v32.0.0) and I think the function watch() for the gmail api is not working properly.
I have created a topic on my project, as shown in the image below.

<img width="931" alt="captura de pantalla 2018-08-20 a la s 13 44 03" src="https://user-images.githubusercontent.com/3495043/44360718-53e43000-a481-11e8-8123-cbcbc1ddd4ef.png">

Once I have the name of the topic, I try to call the watch function of the gmail api as shown on the README [here](https://github.com/google/google-api-nodejs-client/tree/v32.0.0#specifying-request-body)

The code that I'm trying is here:
```
subscribeAccount: async () => {
      try {
        // Connect to gmail API
        const gmail = await google.gmail({
          version: 'v1',
          auth: oauth2Client,
        });

        const result = await gmail.users.watch({
          userId: 'me',
          requestBody: {
            topicName: `projects/metal-figure-210815/topics/gmail`,
          },
        });
        console.log('subscribeAccount result', result);
        return null;
      } catch (e) {
        console.error('subscribeAccount error', e);
        return null;
      }
    },
```
So far I've only get an error:
```
{ Error: Invalid topicName does not match projects/robotic-idiom-205921/topics/*
...}
```

I checked the issues closed on the github for the googleapis and I found this one:

[Gmail API: users.watch - topicName required](https://github.com/google/google-api-nodejs-client/issues/976)

I've tried everything on that issue, but it still not wotking.
Also I've searched on the stackoverflow section for issues, [here](https://stackoverflow.com/questions/tagged/google-api-nodejs-client) but I can't seem to find any help anywhere.

That's why I decided to create a new issues, cause I'm lost, I don't know what to do.
Could you help me?

Thanks!

**Comment by willsnake** [comment]
![image](https://user-images.githubusercontent.com/3495043/45051920-048a2c00-b04b-11e8-8e4c-07efe0efe8b9.png)

**Comment by Jefftopia** [comment]
This isn't working for me either, same code from the example.

**Comment by AVaksman** [comment]
@willsnake 
Please verify that `project_id` in your `credentials.json` file conforms with `project_id` of your `topic`.
Looks like you have a `project_id` mismatch,
`project_id` picked up from `credentials.json` file -> **_robotic-idiom-205921_ **
`project_id` of your `topic` in Cloud Pub/Sub -> **_metal-figure-210815_**

Does that solve you issue?

**Comment by grant** [comment]
Hi @willsnake, does https://github.com/googleapis/google-api-nodejs-client/issues/1301#issuecomment-449107856 solve your issue?

**Comment by developmentalmadness** [comment]
Worked for me. Thanks!

**Comment by grant** [comment]
Closing due to a solution being provided and no upvotes since the original issue post.

Let us know if this is still an issue though by commenting!

**Comment by HBouch** [comment]
Hello Guys,

Facing the same issue and can not find in valuable input online

My topic name (as copied from the topic itself and verified project id): "projects/my-project/topics/new-topic"

The response is a project i do not recongize: Invalid topicName does not match projects/expanded-goal-380009/topics/*

Any help please ?
