### ISSUE TITLE
Supporting my business API

### ISSUE THREAD

**Issue by binarytracer** [googleapis/google-api-nodejs-client#1303]
Is there any plan, when this API be available in the package?

as this: https://developers.google.com/my-business/,
with the scope: https://www.googleapis.com/auth/plus.business.manage

Thanks!

**Comment by grant** [comment]
It looks like someone could manually build this API from the discovery doc as it's not in discovery service yet.

Discovery docs: https://developers.google.com/my-business/reference/rest/
Build API instructions: https://github.com/google/google-api-nodejs-client/blob/master/.github/CONTRIBUTING.md#generating-apis

**Comment by oliverjessner** [comment]
Did someone implement the GMB Api? Could not find anything in CHANGELOG.

**Comment by avillegasn** [comment]
Related #1961 

Now news on this?

**Comment by JhonnyJason** [comment]
Humm the reference to : https://github.com/google/google-api-nodejs-client/blob/master/.github/CONTRIBUTING.md#generating-apis
is 404 :-(

**Comment by sofisl** [comment]
There is no immediate date for when this will be available, but the library will automatically receive an update when it becomes available!
