### ISSUE TITLE
Request: Fitness API Samples

### ISSUE THREAD

**Issue by marcusds** [googleapis/google-api-nodejs-client#1308]
Hi,

I am struggling with the Fitness API so it would be great if we could get some samples!

Particularly around recording a workout: https://developers.google.com/fit/rest/v1/workout

Thanks

**Comment by fr3fou** [comment]
any news?

**Comment by bcoe** [comment]
@fr3fou unfortunately haven't been able to prioritize adding any samples for the fitness API; we would happily accept community contributions if anyone is interested.

**Comment by rahulj3716** [comment]
please help anyone.

**Comment by JustinBeckwith** [comment]
If y'all can provide examples of what you've tried, and what problems you are running into, it goes a long way :) We're happy to help answer questions, but it's unlikely we'll get to hand writing samples for this API any time soon.

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
