### ISSUE TITLE
Feature request: GPhotos API

### ISSUE THREAD

**Issue by SchizoDuckie** [googleapis/google-api-nodejs-client#1315]
Now that you there is a proper gphotos api, can we get some love for the nodejs version in this client?

**Comment by grant** [comment]
@SchizoDuckie I am attempting to add this in #1375.

**Comment by 63716472** [comment]
evelynperezflores110198@gmail.com

**Comment by 63716472** [comment]
Quiero recuperar mi cuenta podrá ayudarme

**Comment by sofisl** [comment]
There is no immediate date for when this will be available, but the library will automatically receive an update when it becomes available!
