### ISSUE TITLE
Have invalid grant error

### ISSUE THREAD

**Issue by funnywebdev** [googleapis/google-api-nodejs-client#1317]
```
Error: invalid_grant
    at createError (/user_code/node_modules/googleapis/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/user_code/node_modules/googleapis/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/user_code/node_modules/googleapis/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

I first get the authenticationCode in front end using
`gapi.auth2.getAuthInstance().grantOfflineAccess()` and send the code to server side (server side is firebase cloud functions)

and in server side, I tried like following.
```
const oauth2Client = new google.auth.OAuth2(
  "XXX",
  "XXX",
  "XXX"
);

oauth2Client.getToken(authenticationCode)  // authenticationCode  is from front end
```

When I got the error.
Any idea how to fix it?

**Comment by JustinBeckwith** [comment]
Greetings!  This generally happens when you're passing incorrect arguments to the `OAuth2` constructor.  Could you share a few details?

1. What version of nodejs are you using?
2. What version of `googleapis` are you using?
3. Can you share the code you're using to get the authentication code?

**Comment by funnywebdev** [comment]
1. nodejs: v8.9.0
2. googleapis: v33.0.0
3. 
```
gapi.auth2.getAuthInstance().grantOfflineAccess().then(function(res) {
    console.log(res.code);
 });
```

**Comment by JustinBeckwith** [comment]
Thanks!  All that looks good.  What arguments are you passing to the `OAuth2` constructor?

**Comment by funnywebdev** [comment]
just followed the document.
```
const oauth2Client = new google.auth.OAuth2(
  CLIENT_ID,
  CLIENT_SECRET,
  REDIRECT_URL
);
```

**Comment by funnywebdev** [comment]
Do I need to generate auth URL with scopes?
I thought I don't need it as the authenticationCode is from front end.

**Comment by JustinBeckwith** [comment]
So to be honest, I have no idea how/if these two libraries will work together.  But yes - when you generate the auth url used to get the code, you do need to pass a list of required scopes.

**Comment by funnywebdev** [comment]
Can this library be used to get authenticationCode in front end?

**Comment by JustinBeckwith** [comment]
Sadly not quite yet - we're very close though!
https://github.com/google/google-auth-library-nodejs/pull/371

**Comment by gabgagnon** [comment]
Is there any news about this problem? I am in the same situation. My OAuth2 has scopes.
Having the redirectUri value has "http://localhost:3000/" can be a problem?

**Comment by JustinBeckwith** [comment]
Greetings!  We haven't heard anything on this issue in a while, so we're going to go ahead and close it out.  Starting with the 3.x release, this library, and google-auth-library should be working in the browser :) If you are still having issues ... please let us know!

**Comment by reidark** [comment]
I'm having this **same** problem right now. My front-end is running with ReactJS to get code token (GAPI).

```js
window.gapi.load('auth2', function() {
  window.auth2 = window.gapi.auth2.init({
    client_id: OAUTH2_CLIENT_ID,
    scope: OAUTH2_SCOPES
  });
});

window.auth2.grantOfflineAccess().then((code) => console.log(code));
// Returns -> { code: 'XXXXXX...XXXX' }
```

In my Express server I run the googleapis to get token, but not working.

```js
const code = { code: 'XXXXXX...XXXX' };
const OAuthClient = new OAuth2(
  ID,
  SECRET,
  REDIRECT
);

OAuthClient.getToken(code, (error, tokens) => {
  if (error)  return console.log(error);

  OAuthClient.setCredentials(tokens)
});
```

Error data:
```
data: { error: 'invalid_grant', error_description: 'Bad Request' }
```

**Comment by rafaismyname** [comment]
So me and a friend were facing exactly the same issue as everyone in this thread, and we were already going crazy after checking 10x every single param but still ending up with a `invalid_grant` error...

We were also using this library with callbacks, just like you did here:
```javascript
OAuthClient.getToken(code, (error, tokens) => {
  if (error)  return console.log(error);

  OAuthClient.setCredentials(tokens)
});
```

Turns out that, after almost giving up, we gave a shot trying using promises (using async/await) instead of callbacks...
And it actually worked! Yup, miraculously...
After seeing it working with promises, we moved back to callbacks, just to confirm, and *BOOM!* there was that despicable `invalid_grant` again!
This might not work for you or for others, but it worked for us... so i think you should give it a try:
```javascript
try {
  const response = await OAuthClient.getToken(code);
  console.log('response', response);
} catch (e) {
  console.log('error', e);
}
```

I'll update this reply with the current `googleapis` package version we're using as soon as possible.

**Comment by rhpereda** [comment]
@reidark, maybe this will help: https://medium.com/@chaimmw86/thanks-for-the-article-really-helpful-36970b83e8a9
