### ISSUE TITLE
Youtube - Don't wait for processing to complete

### ISSUE THREAD

**Issue by brownbl1** [googleapis/google-api-nodejs-client#1325]
#### Environment details

  - OS: Windows 10
  - Node.js version: 8.11.3
  - npm version: 5.6.0
  - `googleapis` version: 33

#### Steps to reproduce

  1. Setup the youtube upload sample (provided in this repository)
  2. Upload large file (>2 GB)

Uploading a large file to youtube and listening to the `onUploadProgress` event gives file upload progress, but after all of the bytes are read (progress === 100%) I still wait 10s of minutes for the promise to resolve and return upload metadata. Checking the youtube studio shows that videos have been uploaded (before the promise resolves) and are processing, but if the promise is rejected after all bytes have been (presumably) uploaded due to network issues, etc, the entire video upload process is aborted. This seems to be different from how the youtube uploader UI works. You can upload a file fairly quickly (and see accurate progress) and once the bytes have been transferred, leaving the page doesn't cause the upload to be aborted.

I am looking for a way to resolve the promise as soon as all bytes are uploaded as I have no need to wait for the processing to complete. Is this possible using the current API or can it be added?

Because of the fantastic job this API does of abstracting the complexity of the upload process, it's a bit difficult for me to tell what is causing the delay. And at a minimum, it renders the progress event fairly useless for my purposes.

**Comment by JustinBeckwith** [comment]
Greetings!  I'm pretty sure we fixed this when we upgraded to `gaxios`.  If you're still having trouble with v37 and up - let me know!
