### ISSUE TITLE
Dialogflow: Error 404 The requested URL was not found on this server.

### ISSUE THREAD

**Issue by beaudoinjk** [googleapis/google-api-nodejs-client#1335]
#### Environment details

  - OS: Windows 7
  - Node.js version: 10.2.1
  - npm version: 6.0.1
  - `googleapis` version: 33.0.0

#### Steps to reproduce

  0. Prerequisites: Have a node project, a dialogflow agent with API enabled and working credentials (JSON private key), and install googleapis from npm.

  1. Configure a JWT auth client and make a authentification request:

<pre>var google = require('googleapis');
var privatekey = require('[PATH_TO_YOUR_PRIVATE_KEY].json');
var dialogflow = google.google.dialogflow('v2');
var parent = "projects/[YOUR_PROJECT_NAME]";

let jwtClient = new google.google.auth.JWT(
    privatekey.client_email,
    null,
    privatekey.private_key,
    ['https://www.googleapis.com/auth/cloud-platform']);
jwtClient.authorize(function (authorizeError, tokens) {
    if (authorizeError) {
        console.log(authorizeError);
        return;
    } else {
        console.log("\tConnected to DialogFlow as admin");
    }
});</pre>

  2. Call 'getAgent()' (other functions have the same issue):

<pre>dialogflow.projects.agent.entityTypes.list({
    auth: jwtClient,
    parent: parent
}, function (dialogflowError, dialogFlowResponse) {
    let response = {};
    if (dialogflowError) {
        response.header = "Dialogflow API returned an error";
        response.body = dialogflowError.response.data;
    }
    else {
        response.header = "Dialogflow API responded successfully";
        response.body = {
            status: dialogFlowResponse.status,
            data: dialogFlowResponse.data
        }
    }
    console.log(response);
});</pre>

I used this tutorial as reference: http://isd-soft.com/tech_blog/accessing-google-apis-using-service-account-node-js/

#### Error

Observed message (shortened with "[...]"):

<pre>{
	"header": "Dialogflow API returned an error",
	"body": "[...]Error 404[...]The requested URL[...]was not found on this server.[...]"
}</pre>

The same error message appeared for other methods under dialogflow.projects.agent and dialogflow.entityTypes

#### Suggestion

Change the "parameters.options.url" part of each concerned method to be conform to its API endpoint (this works for me). 

Example for "dialogflow.projects.agent.entityTypes.list()", shown previously:

`url: (rootUrl + '/v2/{+parent}/entityTypes').replace(/([^:]\/)\/+/g, '$1')`

Change to above url to:

`url: (rootUrl + '/v2/{+parent}/agent/entityTypes').replace(/([^:]\/)\/+/g, '$1')`

**Comment by sanchosa** [comment]
The same issue with client.revokeToken(token), which generates the GET request instead of POST

**Comment by bcoe** [comment]
@beaudoinjk @sanchosa sorry for the slow response (_hopefully you found a workaround in the interim_).

The [documentation is a bit buried](https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/dialogflow/v2.ts#L3293), but I believe the underlying issue is that `parent` should include the `/agent` suffix. so:

```
const parent = "projects/[PROJECT-NAME]/agent";
```

I tested your example code, making this substitution, and things worked like a charm.

As another recommendation, I also suggest you check out our slick _new(ish)_ [standalone dialogflow client](https://github.com/googleapis/nodejs-dialogflow).

I'm closing this issue as resolved, but please feel free to reopen if you're continuing to bump into any issues.
