### ISSUE TITLE
analytics report - batch - not displaying error properly

### ISSUE THREAD

**Issue by gabrielstuff** [googleapis/google-api-nodejs-client#1336]
Hello,

While trying the report API, I encounter an issue where I malformed the query. Unfortunately I was not able to see it. I discover that the `try catch` statement was catching well but the `console.error` was not called correctly.

May I suggest to change the example to `console.error(err)` instead of `console.error`

#### Environment details

  - OS: macOS High Sierra
  - Node.js version: 8.9.1
  - npm version: 6.1.0
  - `googleapis` version: 33.0.0

#### Steps to reproduce

  1. run samples/analyticsReporting/batchGet.js
  2. Do not see any error

there: https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/analyticsReporting/batchGet.js#L55

it should be `console.error(e)` instead of `console.error`

Thanks!

**Comment by JustinBeckwith** [comment]
Nice catch!  Thanks for reporting this.
