### ISSUE TITLE
Google Places?

### ISSUE THREAD

**Issue by strarsis** [googleapis/google-api-nodejs-client#1349]
Does the official Google API client for nodejs support the Google Places API?
Currently I have to use the [`googleplaces package`](https://github.com/Srirangan/googleplaces.js) for sending requests to the Google Places API.

**Comment by JustinBeckwith** [comment]
Greetings!  For the maps based APIs (they're their own thingy), check this out:
https://github.com/googlemaps/google-maps-services-js

Hope this helps!
