### ISSUE TITLE
Delete event not fired for shared files by drive.changes.list

### ISSUE THREAD

**Issue by mrvik** [googleapis/google-api-nodejs-client#1370]
#### Environment details

  - OS: `ArchLinux (Linux 4.18.10) x86_64`
  - Node.js version:` v10.11.10`
  - npm version: `6.4.1`
  - `googleapis` version: `32.0.0`

#### Steps to reproduce

  1. Add a loop to watch for changes with `drive.changes.list`. The one having the issue can be found at the [GitLab repo](https://gitlab.com/mrvik/jdrive/blob/dc983324cef55077909d6e76a8d3ce8072d2a3df/lib/drive.js#L139)
  2. Share a file with that user. A event appears.
  3. Unshare (or remove) the file. There's _no_ event.

**Comment by AVaksman** [comment]
@mrvik Do you still experience this issue?

I have tested with the following 

**Environment details**

- Node.js version: `v10.11.10`
- npm version: `6.4.1`
- `googleapis` version: `32.0.0`

**Followed the following steps**

- Initiated a loop for changes with `drive.changes.list`
- Created a file -> _response received_
- Shared the file with one user -> _response received_
- Shared the file with second user -> _response received_
- Unshared the file with one user (file is still shared) -> _response received_ 
- Unshared the file with second user (file is not shared) -> _response received_
- Removed file (into Trash) -> _response received_
- Deleted file from Trash (forever) -> _response received_
 
**Some notes:**

- When file is **shared** `change.file.shared` flag is tripped to `true` and `change.file.permisisons` array gets another entry. 
- When the file is **unshared** with every other user `change.file.shared` is tripped to `false` and  `change.file.permissions` will remain with only one entry `role: "owner"`.
- When file is **removed** to Trash -> `change.file.trashed` flag is tripped to `true`.
- When file is **deleted** from Trash forever -> `change.removed` flag is tripped to `true` and `change.file` no longer exists.

Please respond if this helps you.

**Comment by AVaksman** [comment]
On separate occasion tried
`create` -> `share` -> `remove` to trash -> `delete` forever
And I received response on every operation.

**Comment by mrvik** [comment]
Yes, now it's working with same version `32.0.0`. Thanks
