### ISSUE TITLE
Callback-based call errors raise UnhandledPromiseRejectionWarning incorrectly in node 8.11

### ISSUE THREAD

**Issue by RLuckom** [googleapis/google-api-nodejs-client#1371]
#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: 8.11.3
  - npm version: 5.6.0
  - `googleapis` version: 34.0.0

Observed behavior:

The documentation states that if you provide a callback, the error and response will be passed to the callback. When there is an error, however, the library raises an UnhandledPromiseException.

Expected Behavior

When there is an error while calling an API with a callback, the error should be passed to the callback; it should not be an UnhandledPromiseException (which in future releases will exit the node process).

#### Steps to reproduce
Run the following example from the docs exactly (i.e. with the garbage API key).

```
const {google} = require('googleapis');

// Each API may support multiple version. With this sample, we're getting
// v3 of the blogger API, and using an API key to authenticate.
const blogger = google.blogger({
  version: 'v3',
  auth: 'YOUR API KEY'
});

const params = {
  blogId: 3213900
};

// get the blog details
blogger.blogs.get(params, (err, res) => {
  if (err) {
    console.error(err);
    throw err;
  }
  console.log(`The blog url is ${res.data.url}`);
});
```

Output:

```
(node:7483) UnhandledPromiseRejectionWarning: Error: Bad Request
    at createError (/home/raphael/workspace/exploranda/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/raphael/workspace/exploranda/node_modules/axios/lib/core/settle.js:18:12)
    at Unzip.handleStreamEnd (/home/raphael/workspace/exploranda/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:111:20)
    at Unzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:7483) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7483) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by RLuckom** [comment]
Possibly related to https://github.com/googleapis/google-api-nodejs-client/issues/432 ?

**Comment by JustinBeckwith** [comment]
Greetings!  As best I can really tell, this is working as intended.  You're getting an unhandled promise rejection because the app is throwing :)  Now the invocation of the callback *happens* to be coming from a promise, but that doesn't really affect the way you would do error handling in your app.  In this case - the error is passed to the callback. For example, this doesn't throw:

```js
// get the blog details
blogger.blogs.get(params, (err, res) => {
  if (err) {
    console.error(err);
    return;
  }
  console.log(`The blog url is ${res.data.url}`);
});
```

Please let me know if I'm missing something :)
