### ISSUE TITLE
drive.files.list 'fields' parameter is missing

### ISSUE THREAD

**Issue by grant** [googleapis/google-api-nodejs-client#1374]
The `drive.files.list`'s `fields` parameter is missing in the Drive V3 d.ts.

#### Environment details

  - OS: OSX
  - Node.js version: v9.4.0
  - npm version: 5.6.0
  - `googleapis` version: 34.0.0

#### Steps to reproduce

  1. Use `drive.file.list` with a `fields` param.

```ts
  const res = await drive.files.list({
    pageSize: 50,
    fields: 'nextPageToken, files(id, name)',
    q: 'mimeType="application/vnd.google-apps.script"',
  });
```
  2. Notice that the `fields` param is not supported.

Perhaps there's a new way of using this param, but I don't see it in the `v3.d.ts`.

---

### Docs

- https://developers.google.com/drive/api/v3/search-parameters#using_client_libraries

### Drive V3 discovery:
- https://developers.google.com/discovery/v1/reference/apis/getRest
  - drive, v3
- Notice `parameters.fields` string:
```js
  "fields": {
   "type": "string",
   "description": "Selector specifying which fields to include in a partial response.",
   "location": "query"
  },
```

**Comment by vijay-qlogic** [comment]
> The `drive.files.list`'s `fields` parameter is missing in the Drive V3 d.ts.
> 
> #### Environment details
> * OS: OSX
> * Node.js version: v9.4.0
> * npm version: 5.6.0
> * `googleapis` version: 34.0.0
> 
> #### Steps to reproduce
> 1. Use `drive.file.list` with a `fields` param.
> 
> ```ts
>   const res = await drive.files.list({
>     pageSize: 50,
>     fields: 'nextPageToken, files(id, name)',
>     q: 'mimeType="application/vnd.google-apps.script"',
>   });
> ```
> 
> 1. Notice that the `fields` param is not supported.
> 
> Perhaps there's a new way of using this param, but I don't see it in the `v3.d.ts`.
> 
> ## Examples
> ### Docs
> * https://developers.google.com/drive/api/v3/search-parameters#using_client_libraries
> 
> ### Drive V3 discovery:
> * https://developers.google.com/discovery/v1/reference/apis/getRest
>   
>   * drive, v3
> * Notice `parameters.fields` string:
> 
> ```js
>   "fields": {
>    "type": "string",
>    "description": "Selector specifying which fields to include in a partial response.",
>    "location": "query"
>   },
> ```
@grant 
I think instead of `fields` we need to use `pageToken`, looking at documentation [here](https://developers.google.com/drive/api/v3/reference/files/list)

@JustinBeckwith  Am I correct?
