### ISSUE TITLE
Invalid JSON payload received. Unknown name "requests": Cannot find field.

### ISSUE THREAD

**Issue by simonepri** [googleapis/google-api-nodejs-client#1380]
#### Environment details

  - OS: macOS 10.14
  - Node.js version: 10.2.1
  - npm version: 5.6.0
  - `googleapis` version: 34.0.0

#### Steps to reproduce
I tried to follow [this example](https://github.com/gsuitedevs/node-samples/blob/master/sheets/snippets/snippets.js#L74) to use the batchUpdate API but I'm not able to use the API successfully.

```js
const {google} = require('googleapis');
const sheets = google.sheets('v4');
try {
  const options = {
    auth: new google.auth.JWT(
      'client_email',
      null,
      'private_key',
      ['https://www.googleapis.com/auth/spreadsheets']
    );
    spreadsheetId: 'spreadsheetId',
    resource: {
      requests: [{
        addSheet: {properties: {title: 'title'}}
      }]
    }
  };
  await new Promise((resolve, reject) => {
    sheets.spreadsheets.values.batchUpdate(options, (err, res) => err ? reject(err) : resolve(res));
  });
} catch (error) {
  console.error(error);
}
```

**Comment by simonepri** [comment]
Solved, I was using the wrong API.
`sheets.spreadsheets.values.batchUpdate` -> `sheets.spreadsheets.batchUpdate`

**Comment by lschnoller** [comment]
Spent 5 hours for this. Google API is awful.
