### ISSUE TITLE
Poor Typings for Schema$InstanceAggregatedList

### ISSUE THREAD

**Issue by david-cannady** [googleapis/google-api-nodejs-client#1383]
#### Environment details

  - OS: N/A
  - Node.js version: N/A
  - npm version: N/A
  - `googleapis` version: "34.0.0"

#### Steps to reproduce
None.
Schema$InstanceAggregatedList.items is defined as `?: any`.
This should be something like `?: { [key: string]?: Schema$InstancesScopedList }`.
The same is true for Schema$*.warning. It would be better to have those properly defined.

**Comment by ajaaym** [comment]
@JustinBeckwith Can you please reopen this issue again as there is another change required in generator after [googleapis-common](https://github.com/googleapis/nodejs-googleapis-common) is released with [change](https://github.com/googleapis/nodejs-googleapis-common/pull/34)
