### ISSUE TITLE
Change Google+ mentions from the README.md to a Google service that still exists ;-)

### ISSUE THREAD

**Issue by oliviermills** [googleapis/google-api-nodejs-client#1387]
For example: 

https://github.com/googleapis/google-api-nodejs-client#generating-an-authentication-url
https://github.com/googleapis/google-api-nodejs-client#using-api-keys

**Comment by vijay-qlogic** [comment]
@JustinBeckwith  Do we need to check all(around 153) repositories under googleapis?
I raised 2 PR: 
https://github.com/googleapis/google-api-nodejs-client/pull/1458,
https://github.com/googleapis/google-api-php-client/pull/1553
