### ISSUE TITLE
Does the google-api-nodejs-client provides Exponential Backoff?

### ISSUE THREAD

**Issue by kvv002** [googleapis/google-api-nodejs-client#1388]
Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick
fixes":

  - Search the issues already opened: https://github.com/google/google-api-nodejs-client/issues
  - Search the issues on our "catch-all" repository: https://github.com/GoogleCloudPlatform/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as
possible:

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `googleapis` version:

#### Steps to reproduce

  1. ???
  2. ???

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  We do not perform retries or backoff today.  We're tracking this over in #482 though!
