### ISSUE TITLE
Missing gmail.users.settings.delegates

### ISSUE THREAD

**Issue by ad-m** [googleapis/google-api-nodejs-client#1397]
In API documentation: https://developers.google.com/gmail/api/v1/reference/users/settings/delegates/list

It is not available in source code, other settings is there: https://github.com/googleapis/google-api-nodejs-client/blob/86de4909f69da9d5ea446053375ab3105a0c675f/src/apis/gmail/v1.ts#L904-L915

https://github.com/googleapis/google-api-nodejs-client/blob/86de4909f69da9d5ea446053375ab3105a0c675f/src/apis/gmail/v1.ts#L3540-L3550
#### Environment details

  - OS: Linux
  - Node.js version: NA
  - npm version: NA
  - `googleapis` version: master

**Comment by ad-m** [comment]
That actions is available & works in Python SDK:

```python
from __future__ import print_function
import googleapiclient.discovery
from google.oauth2 import service_account
import sys


def main():
    """Shows basic usage of the Gmail API.
    Lists the user's Gmail labels.
    """
    SCOPES = [
        'https://mail.google.com/',
        'https://www.googleapis.com/auth/gmail.settings.sharing'
    ]
    SERVICE_ACCOUNT_FILE = 'keys/vacationreplymanager-7dbf49809e60.json'
    is_delete = '--delete' in sys.argv


    credentials = service_account.Credentials\
        .from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=SCOPES)\
        .with_subject(sys.argv[1])

    service = googleapiclient.discovery.build('gmail', 'v1', credentials=credentials)

    print("Delegates so far:", service.users().settings().delegates().list(userId="me").execute())

    if is_delete:
        print("Dedelegation result:", service.users().settings().delegates()
              .delete(userId="me", delegateEmail=sys.argv[2]).execute())
    else:
        body = {
            "delegateEmail": sys.argv[2],
            "verificationStatus": "accepted"
        }

        print("Delegation result:", service.users().settings().delegates()
              .create(userId="me", body=body).execute())

if __name__ == '__main__':
    main()
```

**Comment by AVaksman** [comment]
@ad-m 
Please verify what `googleapis` version you are currently using.
`gmail.users.settings.delegates` have been added with release of `googleapis` version 34.0.0
Please see the source code snippet below

https://github.com/googleapis/google-api-nodejs-client/blob/8d900f14f4848e19e94cc047628e3c2928778416/src/apis/gmail/v1.ts#L4544-L4691

**Comment by grant** [comment]
This can be closed @JustinBeckwith.
(It's since been fixed as noted by @AVaksman.)
