### ISSUE TITLE
v4 spreadsheets.values.get

### ISSUE THREAD

**Issue by anleo** [googleapis/google-api-nodejs-client#1400]
Issue with **Range** in **spreadsheets.values.get**

```
{
      spreadsheetId: spreadsheetId,
      range: sheetTitle,
}
```

When **sheetTitle** is Cyrillic or has different name (in french with character like **è** etc -- request will fail.

Interesting moment:

When range specified as Cyryllic name it will response with `OK`, but strange HTML page with 400-like error like (part of it):
```
<ins>That’s an error.</ins>\n  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>
```

If it will use these **è**-like chars it will fail with another error:
```
code: 400,
app_1  |   errors: 
app_1  |    [ { message: 'Request contains an invalid argument.',
app_1  |        domain: 'global',
app_1  |        reason: 'badRequest' } ] }
```

Summary: if you using titles in any other languages than English -- these requests will fail.

Big question to me: we have **sheetId**s... why we should use these unstable title related requests?

Sorry if i missed this somewhere. 
And big thanks for attention to this question!

**Comment by ajaaym** [comment]
why are you using sheetTitle in range? Why not use like "A1:B2" for range?

**Comment by anleo** [comment]
> why are you using sheetTitle in range? Why not use like "A1:B2" for range?

> A1 notation
> Some API methods require a range in A1 notation. This is a string like Sheet1!A1:B2, that refers to a group of cells in the spreadsheet, and is typically used in formulas. For example, valid ranges are:
> 
> Sheet1!A1:B2 refers to the first two cells in the top two rows of Sheet1.
> Sheet1!A:A refers to all the cells in the first column of Sheet1.
> Sheet1!1:2 refers to the all the cells in the first two rows of Sheet1.
> Sheet1!A5:A refers to all the cells of the first column of Sheet 1, from row 5 onward.
> **A1:B2** refers to the first two cells in the top two rows **of the first visible sheet**.
> **Sheet1** refers to all the cells **in Sheet1**.

Because I need to specify other than first visible sheet of the spreadsheet document.

**Comment by Vd3185** [comment]
I just tried below and it worked fine.

```js
function getSheetRange(auth) {
  const sheets = google.sheets({version: 'v4', auth});
  sheets.spreadsheets.values.get({
    spreadsheetId: '1FxllgP8zQlktB65zbI5_UDoLmYwtVv-Y6bfqGehGXTg',
    range:  'équipage!A1:B10',  
  }, (err, res) => {
    if (err) return console.log('The API returned an error: ' + err);
    const rows = res.data.values;
    if (rows.length) {
      console.log('Name, Major:');
      // Print data
      rows.map((row) => {
        console.log(`${row}`);
      });
    } else {
      console.log('No data found.');
    }
  });
}
```

**Comment by ajaaym** [comment]
@anleo Do you still have this issue? If yes can you please provide the sheet thats not working for you?

**Comment by anleo** [comment]
> @anleo Do you still have this issue? If yes can you please provide the sheet thats not working for you?

Hey @ajaaym ! Haven't checked this again (as I remember -- it wasn't work anyway, with latest changes), but I'll try to find this spreadsheet when I have some free minute. 

Thanks for your attention!

**Comment by anleo** [comment]
@ajaaym here is XLSX of that spreadsheet I tried to process: https://www.dropbox.com/s/yuyilp1p2cvarqf/test.xlsx?dl=0

**Comment by ajaaym** [comment]
@anleo thanks, will check out with this file and let you know.

**Comment by AVaksman** [comment]
@anleo I used your XLSX file to run a test with the same code provided by @Vd3185 above.
I also tried naming sheets using some other special characters in different languages, all seem to work properly.
```javascript
function getSheetRange(auth) {
  const sheets = google.sheets({version: 'v4', auth});
  sheets.spreadsheets.values.get(
    {
      spreadsheetId: '1ZV3m9aiXyv8pkGMRHhnzO8VJI4kwUT-qMcfwrtw5wvI',
      range://'ère - fr!A1:B10',
            // '問候 -  chineeze!A1:C10',
            // 'تحية طيبة!A1:C10',
            // 'ಶುಭಾಶಯಗಳು!A1:C10',
               'АКВАЛАНГ_000 - rus',
    },
    (err, res) => {
      if (err) {
        console.error('The API returned an error.');
        throw err;
      }
      const rows = res.data.values;
      if (rows.length === 0) {
        console.log('No data found.');
      } else {
        console.log('Greeting, Name:');
        for (const row of rows) {
          // Print columns A, B and C, which correspond to indices 0, 1, and 2.
          console.log(`${row[0]}, ${row[1]}, ${row[2]}`);
        }
      }
    }
  );
}
```
I used `googleapis` version 34.0.0.

Please tell if you are still experiencing a problem.

**Comment by datichto** [comment]
I've had the same problem. But update to `34.0.0` version helped me

**Comment by AVaksman** [comment]
@datichto thank you for confirmation!

**Comment by anleo** [comment]
@AVaksman, thank you for attention to this question, updating to `34.0.0` helped me too.
