### ISSUE TITLE
batchDelete requestBody param is incorrect

### ISSUE THREAD

**Issue by lamperti** [googleapis/google-api-nodejs-client#1418]
#### Environment details

  - OS: macOS 10.14
  - Node.js version: 8.12.0
  - npm version: 6.4.1
  - `googleapis` version: 27.0.0

#### Steps to reproduce

In the Gmail API, I was puzzled that `Users.messages.batchDelete` didn't work (I either got a `Backend error` or a `Bad request`). I found out the request body parameter to pass isn't `requestBody:` but `resource:`. It works if you use the latter.

Thanks!

**Comment by AVaksman** [comment]
@lamperti The documentation specifies `param.resource` argument
https://github.com/googleapis/google-api-nodejs-client/blob/fd9eb79544ab3187f50cdef675169f898992c73f/src/apis/gmail/v1.ts#L2490-L2501
Please elaborate more on the issue you have experienced.

**Comment by lamperti** [comment]
The documentation in the source file is correct, the mistake is in https://github.com/googleapis/google-api-nodejs-client (see `requestBody:`).

**Comment by AVaksman** [comment]
@lamperti This issue is fixed starting with googleapis version 30.0.0. Starting from googleapis version 30.0.0 both `resource` and `requestBody` parameters are equally accepted.

**Comment by lamperti** [comment]
🎉👍 thank you!

**Comment by JustinBeckwith** [comment]
@lamperti can you verify this worked for you?  Want to make sure before we close this issue :)
