### ISSUE TITLE
Can't retrieve token with code when using one-time code flow. 

### ISSUE THREAD

**Issue by ivanzhaowy** [googleapis/google-api-nodejs-client#144]
``` JavaScript
    var code = req.body.code;
    var oauth2Client = new gapis.OAuth2Client(CLIENT_ID, CLIENT_SECRET, REDIRECT_URL);
    oauth2Client.getToken(code, function(err, tokens) {
        oauth2Client.setCredentials(tokens);
        callback.call();
    });
```

I'm sure of that all the three parameters of `new OAuth2Client()` are correct, but still got a `redirect_uri_mismatch` error.

**Comment by mhaagens** [comment]
How awesome that this is undocumented.

**Comment by HoldYourWaffle** [comment]
This should definitely be added to the documentation. I luckily stumbled upon this via [this StackOverflow answer](https://stackoverflow.com/a/48121098/10434371), but the documentation it refers to was for the old Google+ sign-in and is not even available anymore.

So I 100% agree with @jcward here:
> It is absolutely unforgivable that the doc page for Offline Access doesn't mention this.
