### ISSUE TITLE
I m trying to Impersonating users from admin in Calendar

### ISSUE THREAD

**Issue by vinothmoorthkumar** [googleapis/google-api-nodejs-client#1452]
Hi,
     I m trying to Impersonating users from admin in Calendar, i provided all required access to this resource still i m getting  404 Not found error unless sharing calendar to specific person option from the user side. Can any give me example or solution to solve this issue.

```js
const { google } = require('googleapis');
const calendar = google.calendar('v3');
const key = require('./gsuite.json');
const CALENDAR_ID = 'xxxx@example.com';
const jwtClient = new google.auth.JWT(
    key.client_email,
    null,
    key.private_key,   
  ['https://www.googleapis.com/auth/admin.directory.user','https://www.googleapis.com/auth/calendar'],
    key.client_email
);
jwtClient.authorize(function (err, tokens) {
    if (err) {
        console.log(err);
        return;
    }
});

  // Make an authorized request to list Calendar events.
    calendar.events.list({
        auth: jwtClient,
        calendarId: CALENDAR_ID
    }, function (err, resp) {
        console.log(err)
        res.send(resp.data);
    });
```

**Comment by AVaksman** [comment]
@vinothmoorthkumar Just for reference please see [this](https://developers.google.com/admin-sdk/directory/v1/guides/delegation#delegate_domain-wide_authority_to_your_service_account) documentation about granting a domain-wide authority to your service account.

Also looking at your code snippet
```javascript
const jwtClient = new google.auth.JWT(
  key.client_email,
  null,
  key.private_key,   
  ['https://www.googleapis.com/auth/admin.directory.user',
   'https://www.googleapis.com/auth/calendar'],
  key.client_email
);
```
The forth argument (the email address after scopes) as per documentation should be the **impersonated account's email address** rather then than the service account email from your key file.

Please respond if this helps you.

**Comment by JustinBeckwith** [comment]
Greetings!  We haven't heard anything on this issue in a while.  We're going to go ahead and close it out - but please do reach out if you're still having issues!
