### ISSUE TITLE
Google namespace installs are not on npm (yet?)

### ISSUE THREAD

**Issue by rdmurphy** [googleapis/google-api-nodejs-client#1463]
Hello! 👋 

I was poking around in the Google Drive API files and came [across the README](https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/drive/README.md) that mentioned you could in theory install just that with the following:

```sh
npm install @google/drive
```

It looks like that file got added back in `v33`. (I assume it's similar for all the other packages.) Maybe I'm poking a little too far into the source, but at least at a glance it reads like that should be available today. May not be a true "bug" — but could be worth adding a note that they aren't publicly available in that way yet? (Super excited though at the idea of being able to install only the API I need!)

Wanted to raise the flag _just in case_ this was actually an error and it **should** be possible now. 😁

**Comment by JustinBeckwith** [comment]
Greetings!  Nope, these don't exist quite yet :) You can `npm pack` from the sources if you want to build a small one for yourself, but we're not publishing them yet.  Still a few things to work out.  You can track this over in https://github.com/googleapis/google-api-nodejs-client/issues/1260!

**Comment by rdmurphy** [comment]
Gotcha, thanks! 👍
