### ISSUE TITLE
What's the correct way to set "user-agent" header?

### ISSUE THREAD

**Issue by mayurkale22** [googleapis/google-api-nodejs-client#1468]
Hello,

This is Mayur from [OpenCensus](https://opencensus.io/) team. Recently we've been working on adding the user-agent header to our Stackdriver Monitoring exporters for all languages. This allows Stackdriver Monitoring to group the uploaded metrics by different sources (e.g from OpenCensus vs. from other libraries), by looking at the value of the user-agent header.

This is my Pull Request : https://github.com/census-instrumentation/opencensus-node/pull/214

Is this the correct way for setting headers?

**Comment by mayurkale22** [comment]
any update here?

**Comment by mayurkale22** [comment]
Any advice would be appreciated...

**Comment by mayurkale22** [comment]
any update here?

**Comment by JustinBeckwith** [comment]
The short answer is that today you can't.  However - I have a PR over here that will add the ability to do it:
https://github.com/googleapis/nodejs-googleapis-common/pull/76

Once that gets merged we'll cut a release, upgrade the version here, and then we'll be set :)

**Comment by crwilcox** [comment]
@bcoe recommended the following to another user. It seems this should work.

```
const {google} = require('googleapis');
google.options({
  userAgentDirectives: [{product: 'frog', version: '1.0', comment: 'jumps'}]
});
const blogger = google.blogger({
  version: 'v3',
  // All requests made with this service client will contain the
  // blogId query parameter unless overridden in individual API calls.
  params: {
    blogId: 3213900
  }
});
```

**Comment by crwilcox** [comment]
Closing for now since this seems more a question. Feel free to reach out further if needed though.

**Comment by JustinBeckwith** [comment]
👋 we did actually go do that work, and it's available now
