### ISSUE TITLE
File upload not working when name is set.

### ISSUE THREAD

**Issue by martin-starosta** [googleapis/google-api-nodejs-client#1470]
Hi, thank you for this library. I have issue with uploading file to Google Drive. When name is not specified, file is uploaded correctly (77 kB). When I specify name, file is uploaded only partially (64 kB)

#### Environment details

  - OS: Windows 10 PRO
  - Node.js version: 10.13.0
  - npm version: 6.4.1
  - `googleapis` version: 27.0.0

#### Steps to reproduce

  1. Remove name from resource object and run code
  2. Add name to resource object

![image](https://user-images.githubusercontent.com/18583382/49341052-52adcc00-f648-11e8-8b2f-e45e4029643f.png)

```
const upload = async (fileName) => {
    const drive = await getDrive();
    const fileSize = fs.statSync(fileName).size;
    const fileMimeType = mime.getType(fileName)

    const res = await drive.files.create({
        resource: {
            'name': 'test.jpg', //When this is present, file is not uploaded successfuly
            mimeType: fileMimeType,
        },
        requestBody: {
            
        },
        media: {
            body: fs.createReadStream(fileName),
            mimeType: 'application/octet-stream',
        },
    }, {
        // Use the `onUploadProgress` event from Axios to track the
        // number of bytes uploaded to this point.
        onUploadProgress: evt => {
            const progress = (evt.bytesRead / fileSize) * 100;
            readline.clearLine();
            readline.cursorTo(0);
            process.stdout.write(`${Math.round(progress)}% complete`);
        },
    });
    console.log(res.data);
    return res.data;
}
```

**Comment by AVaksman** [comment]
@martin-starosta 
* Promises are only supported effective `googleapis` version 28 and above.
* `requestBody` parameter was only introduced effective `googleapis` version 30 and above.
  * It should be ether/or -> `requestBody` or `resource`, not both.

It is best to update `googleapis` to the latest version.
Please refer to this [examples](https://github.com/googleapis/google-api-nodejs-client#media-uploads) (second exmaple) for media uploads.

Please respond whether you are still experiencing an issue.

**Comment by martin-starosta** [comment]
@AVaksman 
I have updated googleapis to version 35.0.0. Progress is now working, but image is still not complete.
![image](https://user-images.githubusercontent.com/18583382/49408467-b45f5a80-f75c-11e8-9775-96b582bc1537.png)

Code:
```
const upload = async (fileName, parent = 'Trello') => {
    const drive = await getDrive();
    const fileSize = fs.statSync(fileName).size;
    const fileMimeType = mime.getType(fileName)

    const res = await drive.files.create({
        resource: {
            name: 'test.jpg',
            mimeType: fileMimeType,
        },
        media: {
            body: fs.createReadStream(fileName),
            mimeType: 'application/octet-stream',
        },
    }, {
        // Use the `onUploadProgress` event from Axios to track the
        // number of bytes uploaded to this point.
        onUploadProgress: evt => {
            const progress = (evt.bytesRead / fileSize) * 100;
            readline.clearLine();
            readline.cursorTo(0);
            process.stdout.write(`${Math.round(progress)}% complete`);
        },
    });
    console.log(res.data);
    return res.data;
}
```

File is not complete on drive:
![image](https://user-images.githubusercontent.com/18583382/49408565-19b34b80-f75d-11e8-980d-1cc148cc34fa.png)

When resource name or requestBody name is not specified, file is uploaded complete:
![image](https://user-images.githubusercontent.com/18583382/49408630-54b57f00-f75d-11e8-9a15-65277b6672d0.png)

**Comment by AVaksman** [comment]
@martin-starosta 
Thank you for update and I am sorry to hear that you still have a problem.
Below is fully functional code that I have tested with. I was not able to replicate same issue you are experiencing. Please check my example and perhaps you can help me replicate the issue you are experiencing, this way we can prioritize and take care of it.

**Environment details**

- OS: Windows
- Node.js version: 10.13.0
- npm version: 6.4.1
- googleapis version: 35.0.0
- testFile format: jpeg
- testFile size: 3 MB
- `credentials.json` downloaded from `console.developers.google.com`

```javascript
const {google} = require('googleapis');
const http = require('http');
const url = require('url');
const opn = require('opn');
const destroyer = require('server-destroy');
const fs = require('fs');
const readline = require('readline');
const mime = require('mime')
const path = require('path');

const keyfile = path.join(__dirname, 'credentials.json');
const keys = JSON.parse(fs.readFileSync(keyfile));

const oauth2Client = new google.auth.OAuth2(
    keys.installed.client_id,
    keys.installed.client_secret,
    keys.installed.redirect_uris[0]
);

const scopes = [
    'https://www.googleapis.com/auth/drive',
    'https://www.googleapis.com/auth/drive.file',
    'https://www.googleapis.com/auth/drive.readonly',
];

// Open an http server to accept the oauth callback. In this
// simple example, the only request to our webserver is to
// /oauth2callback?code=<code>
async function authenticate(scopes) {
    return new Promise((resolve, reject) => {
        // grab the url that will be used for authorization
        const authorizeUrl = oauth2Client.generateAuthUrl({
        access_type: 'offline',
        scope: scopes.join(' '),
        });
        const server = http
        .createServer(async (req, res) => {
            try {
                if (req.url.indexOf('/oauth2callback') > -1) {
                    const qs = new url.URL(req.url, 'http://localhost:3000')
                    .searchParams;
                    res.end(
                    'Authentication successful! Please return to the console.'
                    );
                    server.destroy();
                    const {tokens} = await oauth2Client.getToken(qs.get('code'));
                    oauth2Client.credentials = tokens;
                    resolve(oauth2Client);
                }
            } catch (e) {
            reject(e);
            }
        })
        .listen(3000, () => {
            // open the browser to the authorize url to start the workflow
            opn(authorizeUrl, {wait: false}).then(cp => cp.unref());
        });
        destroyer(server);
    });
}

async function upload(auth) {
    console.log("Uploading image")
    const fileName = 'test-2.jpeg'
    const fileSize = fs.statSync(fileName).size;
    console.log(`file size: ${fileSize}`)
    const fileMimeType = mime.getType(fileName)
    const service = google.drive({version: 'v3', auth});
    const response = await service.files.create({
        resource: {
            name: `test.jpg`,
            mimeType: fileMimeType,
            parents: ['1RExy32fq9fIAx--lKTlOcEVrTjyHm5WJ'] // folder id to upload a picture into a specific folder

        },
        media: {
            body: fs.createReadStream(fileName),
            mimeType: 'application/octet-stream',
        }
    }, {
        // Use the `onUploadProgress` event from Axios to track the
        // number of bytes uploaded to this point.
        onUploadProgress: evt => {
            const progress = (evt.bytesRead / fileSize) * 100;
            readline.clearLine();
            readline.cursorTo(0);
            process.stdout.write(`${Math.round(progress)}% complete`);
        },
    })
    // log the result
    console.log(response.data);
    console.log(`\nstatus: ${response.status}, text status: ${response.statusText}`);
}

async function main() {
    const client = await authenticate(scopes);
    await upload(client).catch(console.error);
}
main().catch(console.error);
```

**Comment by martin-starosta** [comment]
Hi @AVaksman ,
result is same with your code. Here is my code [Files](https://labzone.sk/share/trello-attachment-backup.zip)

I will also try different machine.

**Comment by martin-starosta** [comment]
Here are my results, when there is no resource or requestBody, file is complete:
![image](https://user-images.githubusercontent.com/18583382/49498285-cb8c6e00-f86a-11e8-9dc7-a318883c2dd7.png)

When this part is commented, it works fine (only issue is that file is called Untitled):
![image](https://user-images.githubusercontent.com/18583382/49498321-f5de2b80-f86a-11e8-90a0-0aae10f0b5e0.png)

**Comment by AVaksman** [comment]
@martin-starosta 
As long as `token` is valid and not expired, the code you have provided works by me with or without specified `resource` param.
Have you had any success with different machine?

**Comment by martin-starosta** [comment]
@AVaksman 
Hi Alex, on my other (Linux Ubuntu) machine, it works properly.

**Comment by JustinBeckwith** [comment]
Greetings!  I think this was resolved with our move over to `gaxios`, and a variety of other stream related bug fixes.  If this is still a problem on version 40 or above... please do let us know and we'll re-open this!
