### ISSUE TITLE
Got ECONNRESET error when using vpn

### ISSUE THREAD

**Issue by qiulang** [googleapis/google-api-nodejs-client#1471]
I just tried https://github.com/googleapis/google-api-nodejs-client#first-example (with my key of course) and hit the error ECONNRESET. 

If I switch to node 10 sometime I will hit the error "Client network socket disconnected before secure TLS connection was established" but ECONNRESET is more common.

I am using vpn but I can get the correct result in chrome

<img width="573" alt="googleapi" src="https://user-images.githubusercontent.com/516243/49380750-5119fc00-f74d-11e8-8fd3-f0adb4582737.png">

#### Environment details

  - OS: macOS 10.14
  - Node.js version: 8.14 & 10.12
  - npm version: 6.4.1
  - `googleapis` version:  35

#### Steps to reproduce

  1. https://github.com/googleapis/google-api-nodejs-client#first-example
  2. start vpn and run node

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  Sadly I don't think there's a lot we can do with this.  We're not doing anything special, and just relying on underlying networking in nodejs.

**Comment by kribby** [comment]
Have there been any updates on this issue? I keep getting this all the time.

**Comment by jjhesk** [comment]
please add the api for this please..
