### ISSUE TITLE
Server key authentication

### ISSUE THREAD

**Issue by IonicaBizau** [googleapis/google-api-nodejs-client#148]
How can I authenticate providing a server key?

**Comment by aleen42** [comment]
It seems that using a private key with plus Google is easier than authorizing with JWT by providing a JSON file.

**Comment by aleen42** [comment]
But is there any sample for usig plus authorization to access api of Google Analytics like checking pageviews?

**Comment by flaviocopes** [comment]
I wrote a piece on how to authenticate to any Google API if anyone has issues https://flaviocopes.com/google-api-authentication/
