### ISSUE TITLE
Google API authentication hell

### ISSUE THREAD

**Issue by nicgirault** [googleapis/google-api-nodejs-client#1493]
This is a desperated message. I'm not expecting help but I hope your team will consider improving this part of your services.

# Google API authentication is a hell.

It's the main reason I avoid to use Google APIs. I admit that I didn't go deep enough to understand all the code I read but authentication examples are 100s of lines of code... Seriously???  In addition doc is outdated and typescript types are wrong. API token does not work and I've no feedback to understand why... I can't find a simple example so that a script download a Drive file... I would consider being dump if Google API was not the only API that challenge me so hard to authenticate. This is not a joke: I spent more than a day on this issue.

Sorry for this message but this is really what I feel right now.

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for posting!  Listen - I'd be more than happy to help, but this issue really isn't at all productive.  I understand that you may be frustrated, but I'd urge you to remember that the folks who work on these libraries are humans as well :)  Yelling at us about how unusable it is isn't very likely to get you where you want to go. 

Now that we have that out of the way - how can I help!  We have a sample of downloading a file from drive here:
https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/drive/download.js

That uses an example oauth2 client here:
https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/sampleclient.js

Lets start there.  If you run into trouble, please don't bang your head against the wall for days :) We're here to help!  Just create a new issue with the following info:
1. What you're trying to do
2. The code that you have right now
3. What kind of error you're getting
4. The version of the API you're using, version of node.js, etc

Given the tone of this one is a tad abrasive, I'm going to close this issue.  If there's a specific way we can help - please do open a new one ❤️
