### ISSUE TITLE
Classroom invitations are sent but email is never received. 

### ISSUE THREAD

**Issue by misterwalrus** [googleapis/google-api-nodejs-client#1497]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hello,

After creating a classroom invitation the method classroom.create returns with the return status 200 but the user never receives email with the invitation message.

I have given the the client id associated with the service account that I am using,  the scopes classroom.roster and mail.google.com, but nothing seems to work.  
Am I missing something? 

Thank you very much,
Andres
This is the fragment of code that creates the invitation:
```js
//get authorization client
const auth = await google.auth.getClient({
  scopes
});
//impersonate teacher account
if (auth instanceof google.auth.JWT) {
  auth.subject = 'teacher_email@dom.edu';
}


const options = {
  auth,
  requestBody: {
    courseId: '19220887720',
    role: 'STUDENT',
    userId: 'student_email@dom.edu'
  }
};
//send invitation
try {
  const invitation = await classroom.invitations.create(options);
  console.log('invitation was sent:', invitation);
} catch (err) {
  console.error('error: ', err);
}
```

Response: status 200.

--------------
EDIT:

The invitation is really created. If you check on the ClassRoom home page->people you can see the correct student was invited.

**Comment by JustinBeckwith** [comment]
Greetings @misterwalrus!  Is this still a problem for you?  Is the issue that the invitation gets created, but an email just never gets sent?  Or is all good?
