### ISSUE TITLE
server to server auth failure - firebase - dialogflow - actions on google - user entity v2

### ISSUE THREAD

**Issue by malikasinger1** [googleapis/google-api-nodejs-client#1507]
here is the code I'm using for getting access-token for making session entity as described here: https://dialogflow.com/docs/reference/api-v2/rest/v2/projects.agent.sessions.entityTypes 
previously the code was working find but suddenly it stopped working and now it is returning access-token as undefined in firebase functions, here is the code which is not working: 

    export const rough = functions.https.onRequest((request, response) => {

    var { google } = require('googleapis');

    const cred = {
        serviceAccountEmail: "dialogflow-abc@abc-abc.iam.gserviceaccount.com",
        privateKey: "-----BEGIN PRIVATE KEY-----abcdkey---END PRIVATE KEY-----\n"
    }

    // getting server to server OAuth token
    const serviceAccountAuth = new google.auth.JWT({ // key is private key, extracted from service-account json file
        email: cred.serviceAccountEmail,
        key: cred.privateKey,
        scopes: ['https://www.googleapis.com/auth/cloud-platform']
    })

    console.log(serviceAccountAuth);
    const _tokenData = serviceAccountAuth.authorize().then(tokenData => {
        console.log("tokenData: ", tokenData)
    }) })

code is correct because **this code is still working fine in my machine** have a look:

**code in my machine: (WORKING)**

[![enter image description here][1]][1]
[![enter image description here][2]][2]

**same code in firebase function: (NOT WORKING)**

[![enter image description here][3]][3]
[![enter image description here][4]][4]

if i run this same function in firebase function emulator it works fine

**local Emulator (WORKING)**

[![enter image description here][5]][5]

stackoverflow: https://stackoverflow.com/questions/53759892/server-to-server-auth-failure-firebase-dialogflow-actions-on-google-user

  [1]: https://i.stack.imgur.com/w8mJ1.png
  [2]: https://i.stack.imgur.com/EATkW.png
  [3]: https://i.stack.imgur.com/O4pKr.png
  [4]: https://i.stack.imgur.com/f8xcq.png
  [5]: https://i.stack.imgur.com/GQhMb.png

**Comment by agosto-thomasbohmbach** [comment]
I too am dealing with previously working code suddenly not working. In my case I'm authing calls to IoTCore via a service account from a firebase http-triggered cloud function.

**Comment by malikasinger1** [comment]
my code started working like before, I dont know what happened to that code but it is now working like before, some are saying it was not working because of a recent incident in google

**Comment by JustinBeckwith** [comment]
Greetings folks!  It looks like this was a change in the backend.  If you're still running into issues - please do let us know!
