### ISSUE TITLE
calendar.events.watch not working

### ISSUE THREAD

**Issue by DeCryptinWeb** [googleapis/google-api-nodejs-client#1509]
Hi

A few days ago I started working with the Google Calendar API. First I went through the [nodeJS quickstart guide](https://developers.google.com/calendar/quickstart/nodejs) and got the example working on my local environment. Now my goal is to get notified on my server when a new event is created or an existing event changes. If I understand the Google Calendar docs correctly I should use the [watch endpoint](https://developers.google.com/calendar/v3/reference/events/watch) which can be accessed by the calendar.events.watch method in the context of the quickstart guide.

Currently I'm trying to invoke calendar.events.watch like this:

```javascript
  import {google} from 'googleapis' // v 36.0.0
  import uuid from 'uuid/v1'
  const SCOPES = ['https://www.googleapis.com/auth/calendar']

  // I didn't include the code which is doing the auth related stuff as it is exactly 
  // the same code as in the quickstarte guide

  function watch () {
    const calendar = google.calendar({version: 'v3', auth});

    const options = {
        "id": uuid(),
        "token": "myToken123",
        "type": "web_hook", // Don't know if web_hook is a valid type. I just copied it from other examples.
        "address": "http://mywebsite.com",
        "params": {
            "ttl": "3600"
        }
    }

    calendar.events.watch({calendarId: 'primary'}, options, (err, res) => {
        console.log({err})
        console.log({res})
        return null
    })
  }

  watch()
```

When I run the code above, the logged err-object contains "Error: entity.resource" and the res-object is undefined. Am I doing something wrong or is this a bug?

Thanks in advance!

**Comment by DeCryptinWeb** [comment]
@vishald123 Worked! I missed that part completely.
Many Thanks!

**Comment by vishald123** [comment]
@DeCryptinWeb Glad that helped you!
