### ISSUE TITLE
How do I Verify access tokens work?

### ISSUE THREAD

**Issue by angelxmoreno** [googleapis/google-api-nodejs-client#1512]
my code (inside an async function):
```js
    const user = await db.models.User.findById(req.user.id);
    const creds = {
        access_token: user.access_token,
        refresh_token: user.refresh_token
    };

    const oAuth2Client = new google.auth.OAuth2(
        Config.get('google.client_id'),
        Config.get('google.client_secret')
    );

    oAuth2Client.setCredentials(creds);
    const gmail = await google.gmail({ version: 'v1', oAuth2Client });
    const labels = await gmail.users.labels.list({ userId: 'me' });
    console.log(labels);
```
I get an error stating "Login Required". 

My question is: How can I verify that the access token and refresh token are good? I only see `verifyIdToken()` as an option but I am not storing that value. Is there a way to generate one from an access token and refresh token ?

**Comment by JustinBeckwith** [comment]
👋 The easiest way to verify an access token is to use the `tokenInfo` method:
https://googleapis.github.io/google-auth-library-nodejs/classes/OAuth2Client.html#getTokenInfo

This will let you know if the access token is valid, and if so, what scopes were used to provision the token.  

The easiest way to check a refresh token is to do what you're doing, and then calling the `getRequestHeaders` method:
https://googleapis.github.io/google-auth-library-nodejs/classes/OAuth2Client.html#getRequestHeaders

If that throws, we weren't able to acquire a refresh token :) Hope this helps!
