### ISSUE TITLE
Replacement for people.get

### ISSUE THREAD

**Issue by amsmu** [googleapis/google-api-nodejs-client#1513]
Today, I received an email from Google, stating that they'll be deprecating Google+ Sign in on 7th March 2019, and any API using "plus.people.get" will start failing from 28th January 2019. 

So, I would request you to please add a Google Sign In alternate for "plus.people.get".
Thank you!

**Comment by nodegin** [comment]
same question, why is google deprecating the API without providing any migration details?

**Comment by JustinBeckwith** [comment]
Greetings!  You should be able to use the people API independent of Google Plus.  See this:
https://apis-nodejs.firebaseapp.com/people/classes/People.html

Hope this helps!
