### ISSUE TITLE
Add Node.js Samples for Calendars API

### ISSUE THREAD

**Issue by stephencweiss** [googleapis/google-api-nodejs-client#1516]
The [Google Calendar Documentation](https://developers.google.com/calendar/v3/reference/calendarList/list?apix_params=%7B%7D) has poor support for Node.js. There are also *no* samples included in this repository.

While some examples exist (e.g., the [QuickStart](https://developers.google.com/calendar/quickstart/nodejs)), these can be extended to provide greater visibility into *how* these APIs can be used with Node.js.

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the feedback!  Are there specific things you're trying to do, where you think a sample could be helpful?

**Comment by stephencweiss** [comment]
Hi Justin,

Yes - just generally, there were no Calendar API samples (though they exist elsewhere on the web - like the quickstart linked to above). 

When I was exploring the API, however, I wasn't sure how they could interact, and I find it useful to be able to dig through a whole example. 

I actually tried to scratch my own itch with the PR #1517 . 

If you have a chance to look at that and think that I should add/modify things, please let me know. I'd love to contribute and not create work for you - since this is already an amazingly valuable repo!

Cheers!

**Comment by grant** [comment]
@JustinBeckwith Close this too?
Same reason: https://github.com/googleapis/google-api-nodejs-client/pull/1517#issuecomment-458802647
