### ISSUE TITLE
OAuth2, v3 (userinfo)

### ISSUE THREAD

**Issue by oleg-codaio** [googleapis/google-api-nodejs-client#1529]
With the recent Google+ deprecation, the new approach to getting user info (for instance, as done in https://github.com/jaredhanson/passport-google-oauth2/pull/51) seems to be to use the `https://www.googleapis.com/oauth2/v3/userinfo` endpoint. While `v2` also works for now, but it'd be great to have support for this endpoint here (including TS definitions) and in https://developers.google.com/apis-explorer/.

See also #490, which was created 3 years ago back when (I'm guessing) that API weren't released.

**Comment by stokito** [comment]
why exactly the `https://www.googleapis.com/oauth2/v3/userinfo` ?
It looks like the `userinfo_endpoint` from the https://accounts.google.com/.well-known/openid-configuration is `https://openidconnect.googleapis.com/v1/userinfo`
I checked and both endpoint are working and returns the same but the `https://openidconnect.googleapis.com/v1/userinfo` is advised in the discovery 

some details https://developers.google.com/identity/protocols/OpenIDConnect#validatinganidtoken

**Comment by tugrul** [comment]
Google People API looks suitable to resolve this issue

```javascript
{scope: ['email', 'profile']}
```

```javascript
google.people({version: 'v1', auth}).people.get({resourceName: 'people/me', 
personFields: 'emailAddresses'}))
```

**Comment by kamranhossain** [comment]
@tugrul, thanks, man. Work for me.

**Comment by sofisl** [comment]
Seems like there's a solution, feel free to reopen if needed!

**Comment by TithSambath** [comment]
Is there any way we can get `UserInfo` using access_token provide by google in this `google-api-nodejs-client` ?
