### ISSUE TITLE
Incorrect URL for stopping admin directory channel

### ISSUE THREAD

**Issue by jacobpgn** [googleapis/google-api-nodejs-client#1530]
Hey there!

The URL for stopping a directory channel is [documented](https://developers.google.com/admin-sdk/directory/v1/reference/channels/stop) as:
 `POST https://www.googleapis.com/admin/directory_v1/channels/stop`

but the [library is using something else](https://github.com/googleapis/google-api-nodejs-client/blob/4115c0f5d7a257a8767c3602bf03421d057072ae/src/apis/admin/directory_v1.ts#L2742): 
`POST https://www.googleapis.com/admin/directory/v1/admin/directory_v1/channels/stop`

Until today, this "incorrect" URL in the library was actually working, but now requests are failing with a 404! Maybe someone "fixed" this strange inconsistency in the backend?

Testing manually, the documented URL does appear to work correctly while the library URL does not.

Specifying the correct URL in the options arg gets it working again, e.g.

```js
await directory.channels.stop(
  {
    auth,
    resource: {
      id,
      resourceId
    }
  },
  {
    url: "https://www.googleapis.com/admin/directory_v1/channels/stop"
  }
);

```

**Comment by AVaksman** [comment]
@JustinBeckwith 
Looks like the issue is in `discovery` document
```json
"channels": {
   "methods": {
    "stop": {
     "id": "admin.channels.stop",
     "path": "/admin/directory_v1/channels/stop",
     "httpMethod": "POST",
     "description": "Stop watching resources through this channel",
```

the path should just be `"path": "channels/stop"`

**Comment by AVaksman** [comment]
@JustinBeckwith could you check `discovery` please.

**Comment by jacobpgn** [comment]
As an external consumer of the API, I see a bigger issue in the previously-functional endpoint going missing!

The path in the discovery doc used to function correctly (even if the "new" path seems more consistent and correct), so as a user it's more frustrating that the endpoint became 404 without warning than it is for the library to not have been updated.

**Comment by JustinBeckwith** [comment]
So sadly - there isn't much we can do with this in the node.js library.  From everything here, it sounds like a bug in the back-end discovery document that's used to generate this API.  

Just so you can follow along - would you mind creating a bug for the team here?
https://issuetracker.google.com/issues/new?component=191635&template=824102

Just include all of the information here, and link to the GitHub issue.  When the team fixes the discovery document, this library will be automatically generated with the relevant changes :)

**Comment by lucasharron** [comment]
I have encountered this issue as well. I was wondering if there is a suggested workaround for this or if I should switch to a different library?

**Comment by jacobpgn** [comment]
Hey @lucascdsilva – my original comment above includes a workaround!

I don't think there are any alternative libraries unless you use an HTTP lib to make the request yourself, and it seems unlikely that this issue will be fixed soon (apparently there have been several issues with these paths for many years)

Hopefully the example above will work for you though 😀

**Comment by lucasharron** [comment]
Thanks @jacobpgn. My apologies, the workaround you listed should work well for me!
