### ISSUE TITLE
Spelling mistake in Readme!

### ISSUE THREAD

**Issue by adomoshe** [googleapis/google-api-nodejs-client#1539]
Hi!

Just wanted to point out a small spelling error I found in the readme.

The first paragraph in the Support and maintenance section reads as follows:

These client libraries are official supported by Google. However, these libraries are considered complete and are in maintenance mode.

**Correction: change official to officially**

Thanks!
Ado

**Comment by Dzhuneyt** [comment]
Seems to be already fixed.

**Comment by JustinBeckwith** [comment]
Thanks!
