### ISSUE TITLE
Send HTML body 

### ISSUE THREAD

**Issue by odaymard** [googleapis/google-api-nodejs-client#1545]
I want to send an HTML instead of plain text, I did not find a way to do that, could you please help?

**Comment by JustinBeckwith** [comment]
Greetings!  Can you please share:
- Which API you are using
- What version of nodejs you are using
- What you have already tried
- What error messages (if any) you're getting

If you can give us this stuff - we'd be happy to help!

**Comment by sohanlalpareek** [comment]
My Api Account 2015 closed,why?
