### ISSUE TITLE
How to enable Oauth2 to access account data on youtube data v3 via Angular 7

### ISSUE THREAD

**Issue by gary-deshayes** [googleapis/google-api-nodejs-client#1553]
Hello, I have a big issue, for my school work i have to enable an authentification with **Oauth2** to Youtube, but after reading the **docs** and try a lot of solutions i don't see how to do that, i try the way of **including javascript**, **install the node module googleapis** and now **the tutorial of this repository** and all my test **doesn't works**, if someone has do that explain me pleaseee.

**Comment by JustinBeckwith** [comment]
Greetings!  We'd be happy to help.  We need a few things from you first though :) Can you please provide:
1. What code do you have today?  What have you tried?
2. Are you getting any sort of error?  If so, what is it?
3. What version of nodejs are you using? 
4. What version of the npm module?

**Comment by grant** [comment]
Hi @gary-deshayes,
Any updates on this issue?

Here's a sample that you might find useful:
https://developers.google.com/youtube/v3/quickstart/nodejs
