### ISSUE TITLE
deprecation of plus authorization 

### ISSUE THREAD

**Issue by svarughese91** [googleapis/google-api-nodejs-client#1561]
#### Environment details

  - OS: Mac OS X
  - Node.js version: v 10.8.0
  - npm version: v6.5.0
  - `googleapis` version: 33

#### Steps to reproduce

I got a email from Google saying that the use of all Google+ APIs are being shut off.  I currently use googleAPI.google.plus to sign people in using Google.  Is this plugin going to add a update to support the new way of authorizing users with Google?

Thanks!

**Comment by svarughese91** [comment]
any updates on this?

**Comment by JustinBeckwith** [comment]
Greetings!  When you say "I currently use googleAPI.google.plus to sign people in using Google" - what exactly does that mean?  Are you using this library?  If so, can you share a code snippet?

**Comment by svarughese91** [comment]
yes sorry i should of clarified that, I am using this library.  here is my snippet of code:

```

const googleAPI = require('googleapis');

const plus = googleAPI.google.plus({
            version: 'v1',
            auth: configs.googleAPIKey // specify your API key here
        });
```

**Comment by JustinBeckwith** [comment]
Got it.  After you get the `plus` API, what methods are you trying to call on it?  It's possible they're available on the People API:
https://developers.google.com/people/
