### ISSUE TITLE
Access to Google Play Publisher API using OAuth

### ISSUE THREAD

**Issue by j3k0** [googleapis/google-api-nodejs-client#1572]
I'm using this module to develop a service that requires access to the _Google Play Developer API_ on behalf of my users (specifically, to request subscription status).

I created an API project of type _Web Application_. It can successfully request the users' `androidpublisher` permission using an OAuth consent screen, and it works fine with my account.

However, requests to the API fail for other users with the following error:

`The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.`

From my understanding, the API Project needs to be linked to the Google Publisher Account from the Console (_Settings -> API access -> Linked projects_). However, my API project doesn't appear in the list of options for the users (since it's not owned by the user).

Does anyone know a solution to this? Thanks!

**Comment by j3k0** [comment]
OK I ended up using Service Accounts, which I believe is the correct solution as it gives the users more granular control of what the server can access.

**Comment by j3k0** [comment]
@JustinBeckwith Need more information? Just wondering why I got assigned here.

**Comment by JustinBeckwith** [comment]
No worries - just a robot run amok.  Feel free to ignore!  🤖
