### ISSUE TITLE
Changing Authorization Bearer Token per API call

### ISSUE THREAD

**Issue by vicatcu** [googleapis/google-api-nodejs-client#1578]
I'm trying to implement using the Google Classroom API on behalf of my users. I've gone around on it in my head a bunch over the last couple of months, and I think I've landed on the following. In order to do this with a rigorous chain of trust, I want my own server to be the make the authoritative requests to the Google APIs. As such, my client side will use the client side Google API library to do the whole OAuth2 workflow of gaining consent and an obtaining an access_token with the appropriate scopes. It will then convey this access token to my server to make a request, on the user's behalf, to the Google Classroom API.

So on my server I'll get a request to GET /google/classrooms/classroom/list for example, and that request will both have JWT token that represents that user in my system, and an access_token that I can use to make a request to the analogous Google API. Is _this_ library suited to being used in that workflow, or am I better off essentially implementing proxy routes using something request.js or express-http-proxy?

Ref: https://stackoverflow.com/questions/54315894/google-classroom-api-object-authentication
Ref: https://stackoverflow.com/questions/54117586/trusting-google-api-response-objects-and-ownership

**Comment by ajaaym** [comment]
@vicatcu you can pass the token with every request call in options like this ``` client.users.drafts.get({ userId: 'me' }, { auth: 'token'})```

**Comment by grant** [comment]
You have two options,

Using a specific `auth` type when creating the request:

Example:

```ts
const driveFile = await drive.files.create({
  requestBody: {
    mimeType: driveFileType,
    name: title,
  },
  auth: '', // OAuth Client
});
```

Or just create a new client with an `auth` token that you'd like:

```ts
const drive = google.drive({ version: 'v3', auth: myCustomAuthClient });
```

This library can work for your workflow. If you have more specific questions, you can ask them in a new bug or follow-up here.
