### ISSUE TITLE
Issue with gmail Rest API or Node.js Client

### ISSUE THREAD

**Issue by SpicySyntax** [googleapis/google-api-nodejs-client#1579]
#### Environment details

  - OS: Windows x64
  - Node.js version: 10.15.0
  - npm version: 6.4.1
  - `googleapis` version: v1

#### Steps to reproduce

Tried running following code with my own crednetials

```js
import { google } from "googleapis";
const fs = require("fs");
const main = async () => {
    const emailer = google.gmail("v1")
    const messages = await emailer.users.messages.list({
        auth: "API_KEY",
        userId: "EMAIL_FOR_API_KEY"
    });
    console.log(JSON.stringify(messages));
};

// Invoke main if Main.js is being run directly
if (require.main === module) { main(); }
```

I checked this with the API docs and it seems to look right but when I run it I get:

```
_(node:17044) UnhandledPromiseRejectionWarning: Error: Login Required
    at Gaxios.<anonymous> (D:\git_projects\iModelDevServicesFunctionApp\imodel-developer-services-function-app\iModelDevServices\node_modules\gaxios\build\src\gaxios.js:64:27)
    at Generator.next (<anonymous>)
    at fulfilled (D:\git_projects\iModelDevServicesFunctionApp\imodel-developer-services-function-app\iModelDevServices\node_modules\gaxios\build\src\gaxios.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17044) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code._
```

Any help is appreciated,
Thanks

**Comment by JustinBeckwith** [comment]
Greetings!  I don't believe the gmail API supports API key based authentication.  You would have to go through the OAuth2 type workflow:
https://developers.google.com/gmail/api/auth/about-auth

**Comment by SpicySyntax** [comment]
I followed that link and created OAuth 2.0 client IDs and Service Account Keys.
However I am not sure how to work this into my code using the [Google APIS Node.JS Client](https://github.com/googleapis/google-api-nodejs-client#google-apis-nodejs-client) do you know of any examples or instructions to do this?

**Comment by mrwillis** [comment]
Does Drive support API key auth?

**Comment by JustinBeckwith** [comment]
@mrwillis sadly, it does not

**Comment by JustinBeckwith** [comment]
@SpicySyntax there is a full example of working with the gmail API here:
https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/gmail/list.js

Pay special attention to the `sampleClient` used to do the OAuth2 dance with the user :) Hope this helps!
