### ISSUE TITLE
Closure of the Google+ API

### ISSUE THREAD

**Issue by MAPESO** [googleapis/google-api-nodejs-client#1590]
As some will know the [Google+ disappears on April 2 ](https://support.google.com/plus/answer/9195133?hl=en&authuser=0)officially by logic affects the `Google + API` 😿 

> [On March 7](https://developers.google.com/%2B/api-shutdown), 2019, all Google+ APIs will stop working.

What scope can I use to replace that API ?

**NOTE:** This affects many developers who use that API. I think this news should spread more 🙏

**Comment by MAPESO** [comment]
I recommend to **stop using** `Google + API` I made a migration . Because the code I returned in the callback route sent it to me as `undefinden`

Use [People API](https://developers.google.com/people/) does the same job as `Google + API`.
> If the app needs information for a specific person, it can then call people.get, passing in a resource name, to get the person resource for that person.

small migration [guide](https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/people/me.js) 🌮  ❤️ 

@JustinBeckwith They should remove `Google + API` from the console options. That this option keeps appearing only causes confusion regarding the support that the API has (it is currently deprecated)

<img width="777" alt="Screen Shot 2019-03-30 at 02 56 13" src="https://user-images.githubusercontent.com/16585386/55273911-67693c00-5297-11e9-8509-8f347cd91d44.png">

**Comment by JustinBeckwith** [comment]
Greetings folks!  It looks like you found your way to the People API, so that's good :) As far as removing  the Google+ from the console, it *is* still available for GSuite customers, so it's probably sticking around for a whilesies. 

I'm going to go ahead and close this out for now.  If there's anything else we can help with, let me know!
