### ISSUE TITLE
npm install instructions

### ISSUE THREAD

**Issue by grant** [googleapis/google-api-nodejs-client#1591]
The installation instructions for specific APIs is incorrect:

## Installation

```sh
$ npm install @google/slides
```

https://github.com/googleapis/google-api-nodejs-client/tree/master/src/apis/slides

---

Error:

```sh
npm install @google/slides
npm ERR! code E404
npm ERR! 404 Not Found: @google/slides@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-02-09T00_35_57_016Z-debug.log
```

---

Are there specific modules for every service?

**Comment by avevlad** [comment]
```
npm i @google/youtube
```

Error:
```
npm ERR! code E404
npm ERR! 404 Not Found: @google/youtube@latest
```

https://github.com/googleapis/google-api-nodejs-client/tree/master/src/apis/youtube

![image](https://user-images.githubusercontent.com/2889662/53474171-71700300-3a7d-11e9-958c-34007bc69ec4.png)

**Comment by JustinBeckwith** [comment]
This has been fixed!
