### ISSUE TITLE
docs: properly document usage of `google.auth.getClient`, remove reference to `google.auth.getApplicationDefault`

### ISSUE THREAD

**Issue by NolanChan** [googleapis/google-api-nodejs-client#1595]
#### Environment details

  - OS: OSX 10.11.6 (15G22010)
  - Node.js version: v9.11.2
  - npm version: 5.6.0
  - `googleapis` version: 37.2.0

#### Steps to reproduce

  1.  Invoke `const authClient = await google.auth.getApplicationDefault();`
  2. Pass the authClient into another google api:

```
await compute.globalAddresses.insert({
    project: 'projectId',
    resource: {
      name: 'name',
    },
    auth: authClient,
  },
```

3. Receive the error:

```
TypeError: authClient.request is not a function
    at /.../node_modules/googleapis-common/build/src/apirequest.js:238:31
    at Generator.next (<anonymous>)
    at /.../node_modules/googleapis-common/build/src/apirequest.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/.../node_modules/googleapis-common/build/src/apirequest.js:15:12)
    at createAPIRequestAsync (/.../node_modules/googleapis-common/build/src/apirequest.js:56:12)
    at Object.createAPIRequest (/.../node_modules/googleapis-common/build/src/apirequest.js:48:9)
    at Resource$Globaladdresses.insert (/.../node_modules/googleapis/build/src/apis/compute/v1.js:2151:37)
```

Note: I am certain that `authClient` exists and is properly filled, as printing out the `authClient` before sending it into the request shows my personal keys.

Workaround:

`google.auth.getClient` seems to pass a proper `authClient`

```
const authClient = await google.auth.getClient({
  scopes: ['https://www.googleapis.com/auth/compute'],
});

console.log({auth});

const response = await compute.globalAddresses.insert({
  project: 'projectId',
  resource: {
    name: 'name',
  },
  auth: authClient,
});
```

Also, just wanted to say thank you for writing up this `api`!

**Comment by NolanChan** [comment]
I'd also be very happy to fix the issue if someone could point me to the right location. Searching up `getApplicationDefault` inside the repository didn't turn up any function results...

**Comment by JustinBeckwith** [comment]
Greetings!  Calling `google.auth.getClient` is absolutely the right thing to do :) Are you finding instructions to use `getApplicationDefault` anywhere in the docs?

**Comment by NolanChan** [comment]
Hi @JustinBeckwith , on the bottom of https://cloud.google.com/compute/docs/reference/rest/v1/globalAddresses/insert it recommends to use  `google.auth.getApplicationDefault`.

**Comment by jbdemonte** [comment]
same problem and workaround on https://cloud.google.com/talent-solution/job-search/docs/before-you-begin#how-to-install-sample-nodejs

**Comment by bcoe** [comment]
@jbdemonte @NolanChan, are you unblocked by using the (correct) approach that @NolanChan and @JustinBeckwith outline?

I've updated this issue to indicate that we should remove reference in docs to `const authClient = await google.auth.getApplicationDefault();`.

**Comment by jbdemonte** [comment]
Yes, works like a charm with `getClient`

**Comment by JustinBeckwith** [comment]
@bcoe the sample here comes from this page:
https://cloud.google.com/compute/docs/reference/rest/v1/globalAddresses/insert

It's an auto-generated sample that I think is created here:
https://github.com/googleapis/discovery-artifact-manager/tree/master/toolkit/src/main/resources/com/google/api/codegen/nodejs

We need to:
- update the `snip` files to show the correct usage
- work with the actools team to figure how to run this thing
- work with the docs team to figure out how they're shipped

🙃

**Comment by bcoe** [comment]
@jbdemonte @NolanChan I apologize for the out of date docs, we've landed a PR to dust them off here:

https://github.com/googleapis/discovery-artifact-manager/pull/117

Which will be rolled out to cloud.google.com soon.
