### ISSUE TITLE
How does this work? (directory API sample)

### ISSUE THREAD

**Issue by fredrikj83** [googleapis/google-api-nodejs-client#1606]
This is regarding the directory api sample: https://github.com/googleapis/google-api-nodejs-client/blob/b00bf4200d254b87e3c5b81ba867abe7ab9343ad/samples/directory_v1/group-delete.js

```js
const auth = await google.auth.getClient({
    keyFile: path.join(__dirname, '../jwt.keys.json'),
    scopes: [
      'https://www.googleapis.com/auth/admin.directory.group',
      'https://www.googleapis.com/auth/admin.directory.group.member',
    ],
  });

  // obtain the admin client
  const admin = google.admin({
    version: 'directory_v1',
    auth,
  });

  // delete the group key
  const res = await admin.groups.delete({
    groupKey: 'some_group@example.com',
  });
```

I cannot get this to work when trying it out myself. My understanding is that in order to perform directory api calls, you need to delegate authority to the service account being used and then also add the e-mail which you are trying to impersonate when creating the JWT client. In this sample, there is nothing that looks like that, and I didn't see any mention regarding delegating authority.

Have I misunderstood the concept, or can someone please explain how this sample works? Thanks.

**Comment by grant** [comment]
@fredrikj83 Perhaps this docset and sample would help with your question:
https://developers.google.com/admin-sdk/directory/v1/quickstart/nodejs
https://developers.google.com/admin-sdk/directory/v1/guides/prerequisites

I believe you need to be a G Suite admin of a G Suite EDU/Gov edition for this sample to work.

Can you state the errors you are seeing or ask some more specific questions?
