### ISSUE TITLE
How can I set access_token expired time?

### ISSUE THREAD

**Issue by mrdulin** [googleapis/google-api-nodejs-client#1608]
**Is your feature request related to a problem? Please describe.**

`getToken` and `revokeToken` work fine.

But I want to test refresh token workflow. So, I need set access token expired time shortly for testing. How can I do this?

I don't want to test every 1 hour.

**Comment by AVaksman** [comment]
@mrdulin 
Assuming you save tokens to a file `tokens.json`.
Then you can locally change `expiry_date` to a timestamp closer than 1 hour from now via something like this
```js
    const data = fs.readFileSync("tokens.json");
    const tokens = JSON.parse(data);
    console.log(tokens.expiry_date);
    tokens.expiry_date = new Date().getTime();
    fs.writeFileSync("tokens.json", JSON.stringify(tokens));
```

**Comment by mrdulin** [comment]
@AVaksman wonderful. Why didn't I think of that? thanks.
