### ISSUE TITLE
Need clear the refresh token workflow.

### ISSUE THREAD

**Issue by mrdulin** [googleapis/google-api-nodejs-client#1609]
I want to store the `tokens` in my database and before call google apis, I want use `refresh_token` to get a new `access_token` so that user don't need redirect to the consent screen.
 
Here is my workflow: 

```ts
router.get('/oauth/callback', async (req, res) => {
  const { code: authorizationCode } = req.query;
  const { tokens } = await oauth2Client.getToken(authorizationCode);
  oauth2Client.setCredentials(tokens);
 
   // store tokens in database
  db.save(tokens);
 
   //...
});
```

And, before every google api call, I will set `refresh_token` to oauth2Client like this:

```ts
router.get('/plus/:userId', () => {
  //get refresh token from database
  db.get(tokens);

  oauth2client.setCredentials({ refresh_token: tokens.refresh_token });

  // call google+ api
  const plus = google.plus("v1");
  const { data } = await plus.people.get({ userId });

  //...
})
```

1. Is the workflow correct? 
2. Is it necessary to set `refresh_token` before every api call?
3. Should I check the expired time of `access_token` by myself? 
4. `refreshAccessToken` is deprecated. Is that mean I don't need refresh `access_token` by myself?

Need clear the doc.

**Comment by AVaksman** [comment]
@mrdulin 
Just saving tokens and providing them them on the next run is sufficient. If `access_token` is expired or about  to expire, it will be refreshed internally automatically. User will not be redirected to the consent window.

To always save new `access_token` when it gets refreshed you should add an event listener to `tokens` event as such.

```js
oauth2client.on('tokens', (tokens) => {
  // store the refresh_token in my database!
}
```
Does that help you?

**Comment by supertiger1234** [comment]
Is adding an tokens event to every client fine? Because I feel like it is not efficient

**Comment by mrdulin** [comment]
@AVaksman Thanks for reply.

The `readme` says: 

> This library will automatically use a refresh token to obtain a new access token if it is about to expire. 

I think the refresh token should be attached to a `user` context. Which means each user will have a refresh token. Which refresh token the library will automatically use?  So I think I should set the refresh token to this library manually.  Like below:

```ts
const refreshToken = db.findRefreshTokenByUserId(1);
oauth2Client.setCredentials({refresh_token: refreshToken});
```

**Comment by wanderSX** [comment]
@AVaksman 
In 'tokens event' callback, do you know why refresh_token might not be present in tokens object? I need it because I'm using refreshToken as a key to store my accessToken.

**Comment by grant** [comment]
1. Is the workflow correct?
    - To ensure your client has the appropriate token, call `oauth2client.setCredentials(token)` one time before the API client uses methods.
1. Is it necessary to set refresh_token before every api call?
    - [You don't need to refresh](https://github.com/googleapis/google-api-nodejs-client#handling-refresh-tokens). 
> Once the client has a refresh token, access tokens will be acquired and refreshed automatically in the next call to the API.
1. Should I check the expired time of access_token by myself?
    - No.
1. refreshAccessToken is deprecated. Is that mean I don't need refresh access_token by myself?
    - Correct, so long as you provide the token file (with the access and refresh token) with the client.
    - i.e. `.setCredentials(token)`

See this example CLI I write for an example:
https://github.com/google/clasp/blob/master/src/auth.ts

**Comment by brandonros** [comment]
Do you *need* to store the refresh_token? It's a whole lot simpler to just always get a fresh one in some cases. Is that supported/allowed? I know it is frowned upon, but is it possible?

**Comment by apoorva-shah** [comment]
Hello @grant,
From consent page when i give permission token.json was generated.
I am generating new access_token by refresh_token. ( By `oAuth2Client.on('tokens', (tokens) => {})` )

Will refresh_token will ever expire?

Thanks,
Apoorva Shah

**Comment by bcoe** [comment]
@apoorva-shah a refresh token does not expire (or should expire very rarely, e.g., if a user revokes credentials on their account). If the goal is to perform background processing for a user with your application, store the `refresh_token` when first authorizing, and then use this when instantiating the client in the future (the auth library will handle refreshing the token automatically).
