### ISSUE TITLE
Refactored the Quickstart example with async/await, use it if you'd like.

### ISSUE THREAD

**Issue by vdavid** [googleapis/google-api-nodejs-client#1613]
The Node.js Quickstart example (https://developers.google.com/sheets/api/quickstart/nodejs) contains a callback hell that might be difficult to understand for beginners. Also, the example code contains two parts that are coupled: 1. the auth functionality, 2. the example Sheets access code.

I've refactored the code so that it's async/await-based, and the auth part is decoupled from Sheets usage.
I've posted the code on StackOverflow: https://stackoverflow.com/questions/54882145/is-there-an-async-await-node-js-google-auth-module/54882146
Then someone suggested that I also post it here so that you guys can update the example if you agree that this is a more modern solution.

I've tested the code, it worked for me just the way your code did, both in the case of having a saved token and not.

Thanks for your work!

**Comment by JustinBeckwith** [comment]
Thanks so much! These samples live over in this repository:
https://github.com/gsuitedevs/node-samples

Would you mind creating this issue over there?
