### ISSUE TITLE
Not working with react

### ISSUE THREAD

**Issue by yankopetrov** [googleapis/google-api-nodejs-client#1614]
The base example is not working with react

When you include `const { google } = require('googleapis')` in the code, the application stop with an error:

```
TypeError: Expected `input` to be a `Function` or `Object`, got `undefined`
```
```
  53 | var objType = typeof input;
  54 | 
  55 | if (!(input !== null && (objType === 'object' || objType === 'function'))) {
> 56 |   throw new TypeError("Expected `input` to be a `Function` or `Object`, got `".concat(input === null ? 'null' : objType, "`"));
     | ^  57 | }
  58 | 
  59 | var filter = function filter(key) {
```

Found an issue exactly for this in stackoverflow, made 25 days ago and no answer/workaround yet: https://stackoverflow.com/questions/54468809/what-is-causing-typeerror-expected-input-to-be-a-function-or-object-issue

**Comment by sohwendy** [comment]
i have the same issue with react and googleapi. 
Manage to solve it

```
npm i --save-dev @babel/preset-react @babel/cli @babel/core
```
Create .babelrc file
```
{

  "presets": ["@babel/preset-react"]
}
```
Edit package.json
```
"scripts": {
    "start": "nodemon --exec babel-node src/server.js",
    "build": "babel src --out-dir dist",
    "serve": "node dist/server.js"
  },
```

Use the transpiled files in dist/ instead of src/

😁Kudos to https://hackernoon.com/using-babel-7-with-node-7e401bc28b04

**Comment by guangchao0831** [comment]
I also got similar error message when I tried to use googleapis in chrome extensions. I want to access org unit of current login user with a service account, BUT blocked with this problem.

**Comment by Crowbrammer** [comment]
I'm wondering if fs is the issue or if it's pify.

The two lines most suspect in the traceback are 21-22 in the gtoken index.js file.

```
const pify = require("pify");
const readFile = pify(fs.readFile);
```

When I tested the function in Jest (sorry Mocha fans and myself), the require('googleapis') worked perfectly. But in the browser it does not. What about fs or pify renders the browser unable to handle it? 

My full traceback:

```
vue.runtime.esm.js?2b0e:1888 TypeError: Expected `input` to be a `Function` or `Object`, got `undefined`
    at module.exports (index.js?364d:45)
    at eval (index.js?f447:22)
    at Object../node_modules/gtoken/build/src/index.js (VM506 app.js:9346)
    at __webpack_require__ (VM506 app.js:724)
    at fn (VM506 app.js:101)
    at eval (jwtclient.js?d465:26)
    at Object../node_modules/google-auth-library/build/src/auth/jwtclient.js (VM506 app.js:3847)
    at __webpack_require__ (VM506 app.js:724)
    at fn (VM506 app.js:101)
    at eval (googleauth.js?0a40:37)
```

**Comment by panchalnv** [comment]
Hello,

I am still getting the same issue, does anyone have this fix?

Thanks,
Nikunj
