### ISSUE TITLE
Detect removed access

### ISSUE THREAD

**Issue by TeodorKolev** [googleapis/google-api-nodejs-client#1616]
I am using this client for calendar, and everything works perfect except that if I remove access from google account security settings, calendar is still connected. Is there any method to check for removed access from google account? How to handle those cases?

**Comment by grant** [comment]
What do you mean that the calendar is still connected?

You can remove application access (including applications using this Node client) from Calendar by following the instructions here:
https://support.google.com/accounts/answer/112802?co=GENIE.Platform%3DDesktop

You can see who you've shared your calendar and view permissions/revoke access here:
https://support.google.com/calendar/answer/37082

If there are further questions that aren't answered with the above, feel free to re-open this issue so we can answer them.
