### ISSUE TITLE
How to export Google Spreadsheets as PDFs in landscape mode using Drive API

### ISSUE THREAD

**Issue by chaitu20** [googleapis/google-api-nodejs-client#1622]
We are using drive.files.export method to export Google Spreadsheets as pdfs. By default we are only getting them in 'portrait' mode. Is it possible to change their orientation to 'landscape'?

**Comment by chaitu20** [comment]
anybody with more information on landscape mode?

**Comment by vishald123** [comment]
Hi @chaitu20 Instead of `drive.files.export` you can use `spreadsheets.get` method. I tried the following way. It worked for me. Let me know if it works for you. Below is my code 

```js
function execute(auth) {
    var sheets = google.sheets({version : 'v4', auth});
    sheets.spreadsheets.get({
      "spreadsheetId": "[YOUR-SPREADSHEET-ID]"//TO-DO
    })
        .then(function(response) {
                var url = response.data.spreadsheetUrl;
                url = url.replace(/edit$/, '');
                var url_ext = 'export?exportFormat=pdf&format=pdf&portrait=false'
                url = url + url_ext;
                var file = fs.createWriteStream("landscape.pdf");
                var request = require('request');
                var headers = {
                    method: 'GET',
                    headers: {
                        Authorization: 'Bearer ' + auth.credentials.access_token,
                        'Content-Type': 'text/pdf'
                    }
                }

                var req = request(url, headers, function (err, res, body) {
                    res.on('data', (d) => {});
                    res.on('end', () => {
                        file.end();
                    })
                }).on('error', (e) => {
                        console.error(e);
                    }).pipe(file);
                },
                function (err) {
                    console.error("Execute error", err);
                });
}
```

**Comment by chaitu20** [comment]
Worked like a charm, thanks a ton.

Only one issue with this approach is that it only exports the first sheet of the workbook.

**Comment by nbdn** [comment]
Any plan to support this within the `export` method? 

The provided solution works well, but seems a bit like a dirty hack...

**Comment by sabbirsam** [comment]
export const setPdfUrl = (url) => {
	const spreadsheetID = getSpreadsheetID(url);
	const gridID = getGridID(url);
	
	/* const pdfUrl = "https://docs.google.com/spreadsheets/d/" + spreadsheetID + "/export?format=pdf&portrait=fals&id=" + spreadsheetID + "&gid=" + gridID; */

	const pdfUrl = `https://docs.google.com/spreadsheets/d/${spreadsheetID}/export?format=pdf&gid=${gridID}&size=letter&portrait=false&fitw=true&sheetnames=true&printtitle=true&pagenum=true&gridlines=true&fzr=false&horizontal_alignment=center`;

	const createTablesWrapper = document.getElementById("create_tables_wrapper");
	const dtButtons = createTablesWrapper.getElementsByClassName("dt-buttons")[0];

	if (!dtButtons.getElementsByClassName("pdf_btn").length) {
		const pdfBtn = document.createElement("a");
		// pdfBtn.className = "ui dt-button inverted red button transition hidden pdf_btn";
		pdfBtn.className = "ui dt-button inverted button transition hidden pdf_btn";
		pdfBtn.href = pdfUrl;
		pdfBtn.download = "";

		const span = document.createElement("span");
		pdfBtn.appendChild(span);

		const img = document.createElement("img");
		img.src = SWPTLS_APP.icons.filePdf;
		span.appendChild(img);
		//Tooltip for pdf. 
		pdfBtn.setAttribute("title", getStrings('export-pdf'));
		
		dtButtons.appendChild(pdfBtn);
	}
}


Can anyone help me with my code, i want similar Google Spreadsheets as PDFs in landscape mode, but its not working.
