### ISSUE TITLE
400 - Missing required field: member

### ISSUE THREAD

**Issue by IonicaBizau** [googleapis/google-api-nodejs-client#163]
``` js
{ errors: 
   [ { domain: 'global',
       reason: 'required',
       message: 'Missing required field: member' } ],
  code: 400,
  message: 'Missing required field: member' }
```

I get this error when I run the following:

``` js
var request = client.admin.members.insert({
    groupKey: "some_group@example.com"
  , email: "me@example.com"
});
```

I was authenticated successfully (I received the access token and so on) but when I execute the request above it callbacks that error.

What `member` field am I supposed to add?

It works fine in [API Explorer](https://developers.google.com/apis-explorer/#search/directory/admin/directory_v1/directory.members.insert) using `groupKey` and `email` fields.

**Comment by erikbern** [comment]
I struggled with the same issue. Had to do this to get it working

```js
client.members.insert({
  auth: jwtClient,
  groupKey: 'foo@bar.baz',
  resource: {
    email: 'test@test.com'
  }
}, function(err, res) { });
```

Seems like the syntax changed since the thread above?

**Comment by rpavez** [comment]
**Update, use like this now***
```    const response = await directory.groups.insert(
      {
        auth: jwtClient,
        resource: {
          name: "Foo Foo",
          email: 'testing12345@foo.com'
        }
      }
    );```
