### ISSUE TITLE
Google Drive unable to upload large images

### ISSUE THREAD

**Issue by hanselsen** [googleapis/google-api-nodejs-client#1647]
#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: 10.15.3
  - npm version: 6.4.1
  - `googleapis` version: "27.0.0"

#### Steps to reproduce

Using this script, which I believe is an almost identical one from the example, gives me the error `The API returned an error:  Error: Request body larger than maxBodyLength limit`. It seems to happened in the past in the community, but it seems not to be working again.

```
const maxContentLength = maxBodyLength = 10000 * 1024 * 1024;

function uploadFile(file, folder) {
  authorize(auth => {
	  const drive = google.drive({version: 'v3', auth, maxContentLength, maxBodyLength});
	  const resource = {
		name: path.basename(file)
	  };
	  if(folder) {
		resource.parents = [folder];
	  }
	  const media = {
		body: fs.createReadStream(file)
	  };
	  drive.files.create({media, resource}, (err, res) => {
	    if (err) {
		return console.log('The API returned an error: ' + err);
	    } else {
		console.log('success!');
	    }
	  });
  });
}
```

**Comment by JustinBeckwith** [comment]
Greetings!  This was resolved in later versions of `googleapis`.  Can you please upgrade to v38 and try again?  If you're still having issues, let us know!

**Comment by hanselsen** [comment]
Wow. That's so weird. Why would it have 27 installed? Anyway, it works! Thanks for this.
