### ISSUE TITLE
Search Console API returning wrong/incomplete data

### ISSUE THREAD

**Issue by Slind14** [googleapis/google-api-nodejs-client#1664]
Hi Google API Team,

when using the search console API to query the search analytics data, it sometimes occurs that some of the data is wrong or incomplete.

When retrieving data for a short date range it always matches the UI. When using longer date ranges or dates from 2018 for example the result no longer matches the UI. The API also only returns a small chunk of the rows it did return before.

e.g. 

```javascript
        requestBody: {
            startDate: '2019-01-01',
            endDate: '2019-03-31',
            dimensions: [
                "date",
                "query",
                "device",
                "country"
            ],
            rowLimit: 25000,
            startRow: offset,
            aggregationType: "byProperty"
        }
```
**Returns** +175k records with + 400k impressions

```javascript
        requestBody: {
            startDate: '2018-06-01',
            endDate: '2019-03-31',
            dimensions: [
                "date",
                "query",
                "device",
                "country"
            ],
            rowLimit: 25000,
            startRow: offset,
            aggregationType: "byProperty"
        }
```
**Returns** < 25000 records with +30k impressions

**Comment by ingogbe** [comment]
I have this same issue on analytics, with short date ranges the values matches analytics dashboard but when I use long date ranges the values don't match.

For example is this data range (2016-04-15 and 2019-04-15):

```javascript
var analyticsreporting = google.analyticsreporting({
    version: 'v4',
    auth: oauth2Client,
});

return analyticsreporting.reports.batchGet({
    requestBody: {
        reportRequests: [{
            viewId: '999999999',
            dateRanges: [{
                startDate: '2016-04-15',
                endDate: '2019-04-15',
            }],
            metrics: [{
                expression: 'ga:users',
            }]
        }]
    }
});
```

Returns me this value:

```json
{
    "reports": [
        {
            "columnHeader": {
                "metricHeader": {
                    "metricHeaderEntries": [
                        {
                            "name": "ga:users",
                            "type": "INTEGER"
                        }
                    ]
                }
            },
            "data": {
                "rows": [
                    {
                        "metrics": [
                            {
                                "values": [
                                    "8"
                                ]
                            }
                        ]
                    }
                ],
                "totals": [
                    {
                        "values": [
                            "8"
                        ]
                    }
                ],
                "rowCount": 1,
                "minimums": [
                    {
                        "values": [
                            "8"
                        ]
                    }
                ],
                "maximums": [
                    {
                        "values": [
                            "8"
                        ]
                    }
                ]
            }
        }
    ]
}
```

And in Analytics the correct value is 978 users, using the same date interval.

**Comment by bcoe** [comment]
@ingogbe @Slind14 thank you for the bug report :+1: 

 `google-api-nodejs-client` is a thin layer on top of the upstream analytics API. I believe that any inconsistencies in the data returned are going to originate in the upstream API (not this wrapper).

I recommend opening an issue in the tracker linked to on this page:

https://developers.google.com/analytics/help/

Sorry that I can't be of more help, but I don't think there's a ton we will likely be able to do at this layer.

**Comment by Slind14** [comment]
@bcoe I opened a ticket there. Unfortunately, they weren't able to help because it is for Google Analytics and not GS. They couldn't provide us with a contact nor issue tracker for GSC. The help document around the product doesn't allow feedback outside the scope of the help desk either.
Can you help or is this a lost cause?
