### ISSUE TITLE
Deprecate healthcare/v1alpha

### ISSUE THREAD

**Issue by raywainman** [googleapis/google-api-nodejs-client#1679]
The Cloud Healthcare v1alpha branch is deprecated, could we please have it deleted?
https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/healthcare/v1alpha.ts

Thanks!

**Comment by JustinBeckwith** [comment]
👋 We automatically generate these based on what's visible here:
https://www.googleapis.com/discovery/v1/apis/

As long as it's visible there, we're going to end up generating a client for it.

**Comment by raywainman** [comment]
Looks like this was taken care of, thanks Justin!
