### ISSUE TITLE
How to create Node.js Rest Api for uploading file to Google Drive using Angular

### ISSUE THREAD

**Issue by buseodaci** [googleapis/google-api-nodejs-client#1681]
Hi, i can upload using drive [samples](https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/drive/upload.js) to Google Drive. But i want to upload this files from Angular. How can i create an rest api method in node.js for uploading files to google drive ? How to handle auth ? 
I find a similar [question](https://github.com/googleapis/google-api-nodejs-client/issues/1633) but not useful answer.

**Comment by vishald123** [comment]
Hi, @buseodaci can you please add some information. Are you uploading directly from your node.js server to drive or directly from Angular to google drive?

**Comment by buseodaci** [comment]
@vishald123 I want to upload doc file over using Angular UI  and Node.js Rest API for uploading to Google Drive. So my issue is how to create node.js rest api for uploading files to google drive ?

**Comment by HiteshSalavi** [comment]
@buseodaci,
You have to use Service account for authorization. You will also need domain wide delegation on the service account if you want to upload the doc as any user from the domain and the scopes will need to be authorized(https://developers.google.com/admin-sdk/directory/v1/guides/delegation#delegate_domain-wide_authority_to_your_service_account)

Then your code will be
`
const { google } = require('googleapis');
const stream = require('stream');
app.post('/upload', upload.single('my file'), (req, res, next) => {
    let stream = require('stream');
    let fileObject = req.file;
    let bufferStream = new stream.PassThrough();
    bufferStream.end(fileObject.buffer);

    const jWTClient = new google.auth.JWT(
       serviceAccount.client_email,
       null,
       serviceAccount.private_key,
       [<COMMA SEPARATED SCOPES WHICH ARE AUTHORIZED>]
);
    google.drive({ version: 'v3'})
        .files.create({
            auth: jWTClient 
            media: {
                mimeType: 'application/pdf',
                body: bufferStream
            },
            'resource': {
                name: 'test.pdf',
            },
            fields: 'id',
        }).then(function (resp) {
            console.log(resp,'resp');
        }).catch(function (error) {
            console.log(error);
        })
    res.send(`File uploaded`);
});`

Do share what kind of uploading you're implementing.
whether you need to implement uploading to Google Drive from a single user or from any user in the domain. Basis on this need, the auth may change.

Also, You'll encounter issues with **stream** if you're using NodeJS 8.x.x. DOn't forget to upgrade NodeJS to 10.x.x for the seamless implementation.

**Comment by buseodaci** [comment]
Thank you.

**Comment by HiteshSalavi** [comment]
- [ ] Create Service Account
- [ ] Authorize fdsfdf
