### ISSUE TITLE
Service account authentication issue on App Engine

### ISSUE THREAD

**Issue by tokmak** [googleapis/google-api-nodejs-client#1686]
Getting authentication error when running this code on App Engine Standard ENV.

 `A Forbidden error was returned while attempting to retrieve an access token for the Compute Engine built-in service account. This may be because the Compute Engine instance does not have the correct permission scopes specified. Request had insufficient authentication scopes.`

#### Environment details

  -  App Engine Standard Env, runtime: nodejs10
  - `Node.js` version: 10
  - `npm` version: 6
  - `googleapis` version: 27.0.0

#### Steps to reproduce
On local I have `GOOGLE_APPLICATION_CREDENTIALS` in .env set to the path to key file(App Engine default service account), but same code throws error on App Engine (standard env node 10). Confirmed that it's the same key, so eliminating possibility of scope or permissions misconfiguration.

Here is the code:

```js
import { google } from 'googleapis';

export default function readSpreadsheet(spreadsheetId, tabName, range) {
    return new Promise((resolve, reject) => {
        google.auth.getClient({ scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly'] })
            .then((authClient) => {
                google.sheets('v4').spreadsheets.values.get({
                    auth: authClient,
                    spreadsheetId,
                    range: `${tabName}!${range}`
                }, (err, { data }) => {
                    if (err) {
                        reject(new Error(`The API returned an error: ${err}`));
                    } else {
                        resolve(data);
                    }
                });
            });
    });
}
```

Did anyone ran into similar issue?

On the side note, I also use Datastore api client and same service account credentials work well.

**Comment by JustinBeckwith** [comment]
Before we get to the auth stuff, you can really simplify this code :)

```js
import { google } from 'googleapis';

export default async function readSpreadsheet(spreadsheetId, tabName, range) {
  const authClient = google.auth.getClient({ 
    scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly'] 
  });
  const {data} = google.sheets('v4').spreadsheets.values.get({
    auth: authClient,
    spreadsheetId,
    range: `${tabName}!${range}`
  });
}
```

Now onto the auth question!  Are you packaging a service account credential file along with your build to app engine?  

In your `npm start` script, are you setting the `GOOGLE_APPLICATION_CREDENTIAL` variable there?

**Comment by tokmak** [comment]
thanks, async/await is neat. I'm not packaging it during the build.
Only on local in the `.env` file I have variable `GOOGLE_APPLICATION_CREDENTIAL=path-to-key/key.json` and assume in prod this variable should be exposed automagically.

**Comment by JustinBeckwith** [comment]
Sadly that isn't the case.  You would need to explicitly change your `npm start` script to something like:

```js
"start": "GOOGLE_APPLICATION_CREDENTIAL=path-to-key/key.json node server.js"
```

Or something like that.  We're working on a change that allows the default credentials (when you don't pass a keyfile) to get access to non-cloud scopes (like sheets), but it's not there *quite* yet. 

Hope this helps!

**Comment by tokmak** [comment]
make sense, but then I'd have to commit it to version control and expose the key?

I ended up switching to JWT authentication, creating different service account with limited access, grabbing private key from there and exposing it in app.yaml

**Comment by JustinBeckwith** [comment]
Excellent.  Glad you worked it out!

**Comment by sseppola** [comment]
>We're working on a change that allows the default credentials (when you don't pass a keyfile) to get access to non-cloud scopes (like sheets), but it's not there quite yet.

Finally! I've been running into a wall for hours, but I was expecting the feature described above to "just work" like most Google-to-Google service requests.

@JustinBeckwith, what's the status on this? Is there an issue I can follow?

**Comment by JustinBeckwith** [comment]
It landed! You can create your auth client with a set of scopes, just like you'd do for a service account.  If you're relying on application default credentials in App Engine or Cloud Functions, your token should be provisioned with yh appropriate scopes.

**Comment by sseppola** [comment]
That's odd, because like tomak when I set `GOOGLE_APPLICATION_CREDENTIAL=./path/to/appEngineDefaultKeyfile` and run it locally it works flawlessly. As soon as I deploy it to AppEngine it throws the same error tomak is describing.

This is the code I'm running:

```js
const values = [...];
const spreadsheetId = '...';

const authClient = await google.auth.getClient({
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

const sheets = google.sheets({ version: 'v4', auth: authClient });

const res = await sheets.spreadsheets.values.append({
  spreadsheetId,
  range: 'Sheet1',
  valueInputOption: 'USER_ENTERED',
  requestBody: {
    values: [values],
  },
});
```

I'm not setting a custom service role for my AppEngine service, and access to cloud services like KMS is working fine.

Is there a way to check what scopes the `authClient` above is provisioned with?

**Comment by masakinpo** [comment]
I'm having the exactly same issue with @sseppola 

Any update?

**Comment by sseppola** [comment]
I worked around it by encrypting the credentials with KMS and storing it in my (private) repo. Then when needed I decrypt it and create a JWT client.


Here's the code:
```ts
async function createGoogleAuthJWT(scopes: string[]) {
  const filename = 'path/to/[project-id]-sheets-934557fc6523.json.enc';

  const privatekey = await decryptFile<PrivateKeyT>(
    await readFile(path.join(__dirname, filename))
  );

  const jwtClient = new google.auth.JWT({
    email: privatekey.client_email,
    key: privatekey.private_key,
    scopes,
  });

  return jwtClient;
}

export const appendToSpreadsheet = async (
  spreadsheetId: string,
  values: Array<string | number | undefined>
) => {
  const scopes = ['https://www.googleapis.com/auth/spreadsheets'];
  const authClient = await createGoogleAuthJWT(scopes);

  const sheets = google.sheets({ version: 'v4', auth: authClient });
  const res = await sheets.spreadsheets.values.append({
    spreadsheetId,
    range: 'Sheet1',
    valueInputOption: 'USER_ENTERED',
    requestBody: {
      values: [values],
    },
  });

  return res.data;
};
```

Hope that helps.

**Comment by masakinpo** [comment]
Thank you for the suggestion 

I actually gave up using app engine, instead I use cloud functions. 

Though cloud functions are based on the same default service account with app engine,  apis  successfully worked in the way you coded [here](https://github.com/googleapis/google-api-nodejs-client/issues/1686#issuecomment-552248351)

So, I guess this issue is due to app engine, not this library.
