### ISSUE TITLE
Search API

### ISSUE THREAD

**Issue by raphaelarias** [googleapis/google-api-nodejs-client#1688]
Nodejs is now fully supported by AppEngine, but the Search API is not available.

Any possibility to use the Search API with Nodejs?
There is one very old issue already closed about the subject https://github.com/googleapis/google-api-nodejs-client/issues/668

**Comment by dimitar-mihov** [comment]
I also want to know.

**Comment by bcoe** [comment]
thanks for the feature request, I'll make an effort to dig into this for you.

**Comment by JustinBeckwith** [comment]
Greetings folks!  Sadly, the Search API is very specific to App Engine Standard.  I don't believe you can access that API from the newer App Engine runtimes, but @steren would know that for sure :)

Even if the API *was* accessible - any client written for it would have to be hand written.  All of the APIs in this project are auto-generated based on our discovery index, here:
https://www.googleapis.com/discovery/v1/apis/

While we'd love to hit every API, this is just something we're not likely to take on.

**Comment by raphaelarias** [comment]
Hi @JustinBeckwith 

Thanks for the reply. I guess this type of API is not available in REST format, right? 

If it's available in a REST format or somehow I can discover how to use it in an undocumented form. I don't mind creating an open source community run wrapper for it.

**Comment by raphaelarias** [comment]
Like this?

https://www.youtube.com/watch?v=7B7FyU9wW8Y#t=2088

**Comment by JustinBeckwith** [comment]
You should absolutely try if it's possible!
