### ISSUE TITLE
Add Support for Google Photos API

### ISSUE THREAD

**Issue by prabhuomkar** [googleapis/google-api-nodejs-client#1695]
After the launch of Google Photos API in Google I/O 2018, I was expecting this library will come with photos library soon.
**If it is not officially rolling out soon, can I contribute to this library with Google Photos API?**

**There are no Node.js packages available for google photos library as of now.
Community needs this API badly!**

Link: [Library Guide](https://developers.google.com/photos/library/guides/overview)

_PS: Currently, Google Photos API officially supports PHP and Java.
Would like to work on it for Javascript as well!_

**Comment by bcoe** [comment]
@prabhuomkar thank you for the feature request 👍Hearing your demand loud and clear 😄

**Comment by prabhuomkar** [comment]
How can I contribute to this repository with Google Photos API library support?

**Comment by grant** [comment]
I think Justin had more context on this request.
Related: #610 #1375

**Comment by JustinBeckwith** [comment]
So sadly, there's nothing we can really do for this with changes to backend.  I filed a public feature request with the Photo Library team to expose their API in a way such that we could consume it and generate a client:
https://issuetracker.google.com/issues/138224490

For updates - please subscribe to that issue.  As soon as they make a fix on the backend, we can automatically generate a client.

**Comment by ManuCart** [comment]
Hi,
Why this issue blocked ?
Because Google Photo API exist.
see : https://developers.google.com/photos/library/guides/overview

**Comment by bcoe** [comment]
@ManuCart this library uses the discovery API, there's an open feature request to add photos to this API 👍

**Comment by bcoe** [comment]
@prabhuomkar I've added this request to a central issue @stephenplusplus has been maintaining:

https://github.com/googleapis/google-cloud-node/issues/1338

As @JustinBeckwith mentions, it would also be worth commenting on the issue tracker:

https://issuetracker.google.com/issues/138224490
