### ISSUE TITLE
Incorrect Case readme

### ISSUE THREAD

**Issue by GiampieroMarrosu** [googleapis/google-api-nodejs-client#1701]
Here
https://github.com/googleapis/google-api-nodejs-client#oauth2-client

oauth2Client has different case in different position

**Comment by Giampy86** [comment]
Here
https://github.com/googleapis/google-api-nodejs-client#oauth2-client

oauth2Client has different case in different position

**Comment by bcoe** [comment]
:wave: hey @Giampy86 are you talking about the casing of the heading:

`# OAuth2 client`

vs., the sample code:

```js
const oauth2Client = new google.auth.OAuth2(
  YOUR_CLIENT_ID,
  YOUR_CLIENT_SECRET,
  YOUR_REDIRECT_URL
);
```

If this is what you had in mind, this is intentional. As, in JavaScript code (don't ask me why), you usually start the name of a variable with a lower-case letter.

If this isn't what you were thinking of, perhaps you could open up a pull-request, pointing out the editing issues?

**Comment by Giampy86** [comment]
Hy benjamin,

so sorry, I was in late and I didn't give you enough information.

The case mismatch that I notified is between the two portion code:
[Retrieve access token](https://github.com/googleapis/google-api-nodejs-client#retrieve-access-token)
`// This will provide an object with the access_token and refresh_token.
// Save these somewhere safe so they can be used at a later time.
const {tokens} = await oauth2Client.getToken(code)
oauth2Client.setCredentials(tokens);`

and
[Handling refresh tokens](https://github.com/googleapis/google-api-nodejs-client#handling-refresh-tokens)
`oauth2client.on('tokens', (tokens) => {
  if (tokens.refresh_token) {
    // store the refresh_token in my database!
    console.log(tokens.refresh_token);
  }
  console.log(tokens.access_token);
});`


as you can see in both the code above you can find oauth2client object but, the first time it is written with the C in upper case and the second time in lower case.

I know that this is not a real issue but if someone(as me :D ) uses this guide to test something could worst some time looking for the wrong object

**Comment by bcoe** [comment]
@GiampieroMarrosu good catch! Do you feel like submitting a fix, alternatively I can keep this open and we can try to address soon.
