### ISSUE TITLE
Drive create folder typescript parameters missing 'resource'

### ISSUE THREAD

**Issue by fellars** [googleapis/google-api-nodejs-client#1714]
The `Params$Resource$Files$Create` interface is missing 'resource', which is needed for creating a folder according to documentation:

https://developers.google.com/drive/api/v3/folder#about_folder_files

Error I get on compile:  Object literal may only specify known properties, and 'resource' does not exist in type 'Params$Resource$Files$Create'.

**Comment by JustinBeckwith** [comment]
Ok - so turns out this is a docs bug.  Instead of `resource` you can use `requestBody` :) We will work on updating the docs!

**Comment by JustinBeckwith** [comment]
This is a dup of https://github.com/googleapis/google-api-nodejs-client/issues/1885, so closing this so we can track it there.

**Comment by eladcandroid** [comment]
The docs are still deprecated:

https://developers.google.com/drive/api/guides/folder#node.js
