### ISSUE TITLE
GaxiosError syntax error ie11

### ISSUE THREAD

**Issue by Emiliano-Bucci** [googleapis/google-api-nodejs-client#1718]
Hello! I'm working on a project with Next.JS, typescript, Apollo and GraphQL and i'm using the `googleapis` to generate a `token` to the use it to fetch Google Analytics data. I'm facing issues in IE, since i'm getting the error `Syntax Error` and the breakpoint points to the `GaxiosError extends Error` class...
Any clues on this?
Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  Apologies for the trouble - but there's just no way we can support IE11.  We use es6 classes, which never made it to IE:
https://caniuse.com/#feat=es6-class
