### ISSUE TITLE
Drive API V3 - Drive.list : only few fields of the drive_v3.Resource$Drives

### ISSUE THREAD

**Issue by jeromeSH26** [googleapis/google-api-nodejs-client#1719]
Hi, when running the `drives.list()` function, the resources send back have only 3 fields (kind, id, name), whereas the [doc](https://developers.google.com/drive/api/v3/reference/drives#resource) lists a whole bunch of fields for the drive resource.
Do I miss some parameters in the api call or in the console ? I'm using a service account to run the apis.  Here is my code and the result :

```js
const drive: drive_v3.Drive = google.drive({ version: "v3", auth });

  const t: GaxiosResponse<drive_v3.Schema$DriveList> = await drive.drives.list({
    pageToken: "",
    useDomainAdminAccess: true
  });
```
Result  :
```
{ kind: 'drive#drive',
       id: '0ABKKMZoA22DPUk9PVA',
       name: ' test },
```

**Comment by JustinBeckwith** [comment]
So I'm guessing here, but I suspect the `list` operation returns a shallow copy with just those fields, and that for more details you may have to do a `get` operation.  It's also worth playing with the `fields` property :)

**Comment by jeromeSH26** [comment]
` it's also worth playing with the fields property 
`
there is no fields property in drvies.list() ;-)

**Comment by JustinBeckwith** [comment]
Sure it does!  I just modified the `samples/drive/list.js` sample to include a filter like this:

```js
const params = {
  pageSize: 3,
  fields: 'kind,nextPageToken,files(name,id,thumbnailLink,modifiedTime)'
};
params.q = query;
const res = await drive.files.list(params);
console.log(res.data);
```

You can choose from any of the fields available here:
https://developers.google.com/drive/api/v3/reference/files#resource

Hope this helps!
