### ISSUE TITLE
Sheets api call fails referring to unknown project.

### ISSUE THREAD

**Issue by rovrevik** [googleapis/google-api-nodejs-client#1733]
The error output is as follows:
```
(node:5042) UnhandledPromiseRejectionWarning: Error: Google Sheets API has not been used in project 146510208931 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sheets.googleapis.com/overview?project=146510208931 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
    at Gaxios.request (/.../node_modules/gaxios/build/src/gaxios.js:70:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```
The referenced project 146510208931 is not even one of our projects and is not referenced in the offending code.

We are using a service account to authenticate and call the sheets api. The credentials and api work fine using the edit-google-spreadsheet npm nodule but we are updating to use the sheets v4 api directly.

The code that fails is below. GOOGLE_SERVICE_ACCOUNT is the service account email. GOOGLE_KEY is the key contents SPREADSHEET_ID is valid and shared with the service account.

```
const { google } = require("googleapis");

const auth = new google.auth.JWT({
    email: process.env.GOOGLE_SERVICE_ACCOUNT,
    key: process.env.GOOGLE_KEY,
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});
await auth.authorize();

const sheets = await google.sheets({ version: "v4", auth });

// this throw an exception
const res = await sheets.spreadsheets.values.get({
    spreadsheetId: process.env.SPREADSHEET_ID,
    range: "Sheet!A1:E",
});
```

**Comment by JustinBeckwith** [comment]
At a glance - it doesn't look like you're telling google auth which Project Id to use :) You can do this a few ways:
- Setting the `GCLOUD_PROJECT` env var
- Using the `auth.getClient()` method with a keyfile that includes the projectId\
- Directly setting the `projectId` on the `JWT` object

If you don't do any of these, it's going to use some fuzzy application default logic to try and figure out the project Id for you.

A few side notes looking at the code:
- You don't need to call `await auth.authorize()`, that will just happen for you
- You don't need to `await` the result of `google.sheets()` - that method is synchronous!

I would recommend setting the `GCLOUD_PROJECT` env var 😎 Please do let us know how it goes!

**Comment by rovrevik** [comment]
Thank you for the response and recommendations. FWIW the JWTOptions interface doesn't declare a projectId property.

I am still getting the same error. I have tried using the` GCLOUD_PROJECT` and `auth.projectId = 'mb-sheets';` as seen below.

```
const auth = new google.auth.JWT({
    email: process.env.GOOGLE_SERVICE_ACCOUNT,
    key: process.env.GOOGLE_KEY,
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});
auth.projectId = 'mb-sheets';

const sheets = google.sheets({ version: "v4", auth });

// this throw an exception
const res = await sheets.spreadsheets.values.get({
    spreadsheetId: process.env.SPREADSHEET_ID,
    range: "Sheet!A1:E",
});
```

**Comment by rovrevik** [comment]
@JustinBeckwith sorry to bug you. Did you have any other ideas?

**Comment by bcoe** [comment]
@rovrevik out of curiosity, what value do  you get when you:

```
const projectId = await auth.getProjectId();
```

I wonder if something is failing to be set in the underlying auth instance.
