### ISSUE TITLE
Schema$SubscriptionPurchase missing "acknowledgementState" field 

### ISSUE THREAD

**Issue by philippeauriach** [googleapis/google-api-nodejs-client#1744]
#### Environment details

  - OS: macOS 10.14.5
  - Node.js version: 10.16
  - npm version: 5.7.1
  - `googleapis` version: 40.0.0

Types of `Schema$SubscriptionPurchase` is missing the `acknowledgementState` field
as per the doc : https://developers.google.com/android-publisher/api-ref/purchases/subscriptions
the class missing the field : https://apis-nodejs.firebaseapp.com/androidpublisher/interfaces/Schema$SubscriptionPurchase-3.html

#### Steps to reproduce

```javascript
  const res = await androidPublisher.purchases.subscriptions.get({
    packageName,
    subscriptionId,
    token,
  })
  const subscription = res.data
  console.log(subscription) // displays the 'acknowledgementState' field 
  subscription.acknowledgementState // property does not exist
```

The property exists in the object returned by the api.

Thanks !

**Comment by BH4EHN** [comment]
same issue

**Comment by BH4EHN** [comment]
I override type definition to make it work for now
```TypeScript
enum SubscriptionPurchaseAcknowledgementState {
    YetTobeAcknowledged,
    Acknowledged
}

declare module 'googleapis' {
    namespace androidpublisher_v3 {
        interface Schema$SubscriptionPurchase {
            acknowledgementState: SubscriptionPurchaseAcknowledgementState
        }
    }
}
```

**Comment by bcoe** [comment]
@BH4EHN any interest in submitting a patch with this fix?

**Comment by BH4EHN** [comment]
@bcoe Yep, you are right, this kind of code are all generated, or I submitted the patch already hahahaha.

**Comment by BH4EHN** [comment]
This issue is solved by commit https://github.com/googleapis/google-api-nodejs-client/commit/c726608ec6444d512a6af068679f0a2b3fb5bafc

**Comment by JustinBeckwith** [comment]
Awesome!  @philippeauriach does it look like this is solved with the latest version for you too?

**Comment by philippeauriach** [comment]
Yep, looks good from here ! Thanks !
