### ISSUE TITLE
Fit API - Require at least one aggregateby

### ISSUE THREAD

**Issue by mtang8264** [googleapis/google-api-nodejs-client#1746]
I am trying to get a user's step count on a given day. I am working in Unity and therefore I am using its built-in UnityWebRequest functionality to send the request.
I am using SimpleJSON to parse the request into the following JSON string:
```JSON
{"aggregateBy":[ {"dataTypeName":"com.google.step_count.delta", "dataSourceId":"derived:com.google.step_count.delta:com.google.android.gms:estimated_steps"} ], "startTimeMillis":"1561348800000", "endTimeMillis":"1561435200000"}
```
Then I'm setting the headers of the request for both Authorization and Content-Type:
```C#
var request = UnityWebRequest.Post("https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate", temp);

request.SetRequestHeader("Authorization", "Bearer " + accessToken);
request.SetRequestHeader("Content-Type", "application/json");

yield return request.SendWebRequest();
```
When I send this request I receive a 400 Bad Request error along with the following response:
```JSON
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalidArgument",
    "message": "Require at least one aggregateby"
   }
  ],
  "code": 400,
  "message": "Require at least one aggregateby"
 }
}
```

**Comment by JustinBeckwith** [comment]
Greetings!  It looks like you're trying to directly use the API with a different request library.  We generally use this repository for issues directly related to the library, which actually does have a nice wrapper for accessing the Fitness API :)  

I'm going to close this out for now.  If you want to try using the `googleapis` module, and run into problems there - please feel free to open a new issue!
