### ISSUE TITLE
Add a Google Hire Client

### ISSUE THREAD

**Issue by IngBombita** [googleapis/google-api-nodejs-client#1750]
I have looked for a Google Hire Client in node.js and i haven't found nothing yet. What do you think? Is it a good feature?

[There are some examples in Google Hire API Docs](https://developers.google.com/hire/tenants/libraries)

**Comment by bcoe** [comment]
@IngBombita :wave: did you find the sample Node.js code that the hire API links to:

https://developers.google.com/hire/tenants/libs/20190313-tenants-v1beta1-nodejs-sample.txt

The API wrappers in this library, e.g., `drive`, `firestore`, `file`, are auto-generated, and use the same discovery docs; so you should find the example linked to above has close to the same behavior.
