### ISSUE TITLE
https://oauth2.googleapis.com/token connect ETIMEDOUT

### ISSUE THREAD

**Issue by Sandural** [googleapis/google-api-nodejs-client#1752]
## Environment details

  - OS:
  - Node.js version: v10.15.0
  - npm version:  npm@6.4.1 
  - `googleapis` version: 40.0.0

#### Steps to reproduce

![image](https://user-images.githubusercontent.com/16163090/60490943-28091c00-9cda-11e9-8d14-868ff0c0c67d.png)

**Comment by Sandural** [comment]
I fix this problem by set proxy

**Comment by 1c7** [comment]
@Sandural do you mind provide a simple code snippet?

**Comment by VisonM** [comment]
@Sandural how to set proxy ? do you mind provide a simple code snippet?
