### ISSUE TITLE
How to get modified content from sheets API

### ISSUE THREAD

**Issue by TheeranMahadev** [googleapis/google-api-nodejs-client#1753]
I have tried to get the modified changes from Google sheets no where I can see the api to get the modified content. If i use drive api got modified time and fileId. Please suggest me the solution

**Comment by TheeranMahadev** [comment]
Please Look at this issue.

**Comment by JustinBeckwith** [comment]
I'm not sure if there's an API specifically for that.  Another one for @erickoledadevrel and @sqrrrl :)

**Comment by erickoledadevrel** [comment]
Unfortunately this isn't possible today; you can only reliably fetch the current state of the spreadsheet.
