### ISSUE TITLE
Getting "Error: null at createError" during purchase validation

### ISSUE THREAD

**Issue by mikelibg** [googleapis/google-api-nodejs-client#1758]
#### Environment details

  - OS: AWS hosted Linux version 4.15.0-1032-aws (buildd@lcy01-amd64-025) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #34-Ubuntu SMP Thu Jan 17 15:18:09 UTC 2019
  - Node.js version: v10.16.0
  - npm version: 6.9.0
  - `googleapis` version: "^32.0.0",

#### Steps to reproduce

Started getting this error at 2019-07-10T19:01:06.497Z and then after about two hours the error stopped and everything got back to normal again, receiving proper response with subscription data.

During a call:

```
var { google } = require('googleapis');
var pub = google.androidpublisher('v3')

authClient.authorize()
        .then(function (tokens) {
            return pub.purchases.subscriptions.get({
                auth: authClient,
                packageName: "my.app.package",
                subscriptionId: subscription_id,
                token: purchase_token
            })
        })
        .then(function (resp) {
            return Promise.resolve(resp)
        })
```

Getting error:

> Error: null\n    at createError (/app_dir/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app_dir/node_modules/axios/lib/core/settle.js:18:12)\n    at Unzip.handleStreamEnd (/app_dir/node_modules/axios/lib/adapters/http.js:202:11)\n    at Unzip.emit (events.js:203:15)\n    at Unzip.EventEmitter.emit (domain.js:448:20)\n    at endReadableNT (_stream_readable.js:1129:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by JustinBeckwith** [comment]
Greetings!  A few things to note:
- if this started happening randomly, and then started working again, it's most likely a problem with the back end service.  We try to keep issues in this repo limited to problems with this code base.  If you think this was a problem with the service, I'd suggest [reaching out to that team for help](https://support.google.com/googleplay/android-developer/answer/7218994).
- It looks like you're using an older version of the library (a lot has changed).  If you could upgrade to the latest version, that would probably do wonders :)

Hope this helps!

**Comment by mikelibg** [comment]
It is probably a service error. I expected to get a more informative error to understand how to handle it, but from the error I see that axios is used for the request so I will try to check their code as well. Thanks!
