### ISSUE TITLE
Does google.storage support gzip files for cloud storage?

### ISSUE THREAD

**Issue by AnthonyWC** [googleapis/google-api-nodejs-client#1764]
I am using NodeJS `googleapi` to download files from gcp storage, e.g.
  
```
google.storage('v1').objects.get({
  auth: jwtClient,
  bucket: bucketName,
  object: object,
  alt: 'media'
}, (err, resp) => {
  if (err) {
    console.log(err)
  } else {
    fs.writeFile(filename, resp.data, (err) => {
      if (err) throw err;
  })
})
```
For non gz files the downloaded files are fine but gz files are not downloaded properly.  Original file would show `gzip compressed data` from file whereas downloaded file show just `data`

The resp.data looks to be encoded in utf8 as it displayed text data in the data object.  Does the get method supports other type of encoding?

writeFile itself can support gzip file as I was able to readFile from a gz then write back to a gz file.

#### Environment

  - OS: OSX
  - Node.js version: 8.10
  - npm version: 6.8.0
  - `googleapis` version: 41.0.0

**Comment by JustinBeckwith** [comment]
While we're happy to take a look at this, I would really urge you to use [@google-cloud/storage](https://github.com/googleapis/nodejs-storage/) instead :)

**Comment by AnthonyWC** [comment]
I would preferred to use @google-cloud/storage as well but I need to use JWT with service account where I only have email & privatekey as authentication.  I am not sure if  @google-cloud/storage support that and I can't seem to find an example to show that it does.

**Comment by JustinBeckwith** [comment]
It uses the same google-auth-library under the hood, so you should be able to! Can you try something like this?

```js
const {Storage} = require('@google-cloud/storage');
const storage = new Storage({
  clientOptions: {
    email: 'yer email',
    key: 'yer private key'
  }
});
```

**Comment by AnthonyWC** [comment]
Hi @JustinBeckwith thanks for you suggestion, so I did manage to test with @google-cloud/storage to download gzip files properly.

BUT somehow it only worked for my own test service account, when I switch over the other account (which I have no control over) with the authentication method it didn't work for even listing the files.  It is weird because the same authentication method worked w/ googleapis.

So basically I had something like this for list files (which didn't even work, as I first list then download):

```
async function listFiles(bucketName) {
  const {Storage} = require('@google-cloud/storage');

  const storage = new Storage({
    clientOptions: {
      email: email,
      key: privatekey,
      prefix: prefix
    }
  });

...
```

And I had different key/email/prefix for the different account, and the authentication method only worked for my testing account which I control but not for the actual account (which I don't control).  And the same authentication info worked /w JWT method for both accounts:

```
 const jwtClient = new google.auth.JWT(
   email,
   null,
   privatekey,
   scopes
 );
```

What can possible cause this behavior?  Is there some way for me to enable debug/verbosity?

**Comment by JustinBeckwith** [comment]
Greetings! And apologies for the delay.  Are you still running into issues?  One thing that could cause this to happen is possibly overriding the key settings via environment variable.  Is it possible a `GOOGLE_APPLICATION_CREDENTIALS` env var is set?

**Comment by bcoe** [comment]
going ahead and closing this, @AnthonyWC please feel free to reopen if you continue to run into issues, and can provide some more context.
