### ISSUE TITLE
trying to unzip gzip response from adsense.accounts.reports.generate throw "incorrect header check"

### ISSUE THREAD

**Issue by thewizarodofoz** [googleapis/google-api-nodejs-client#1777]
#### Environment details

  - OS: mac OS Mojave
  - Node.js version: 12.4.0
  - npm version: 6.9.0
  - `googleapis` version: 41.0.1

#### Steps to reproduce
```js
// create auth client, get token, instantiate adsense bla bla...
const reportResponse = await adsense.accounts.reports.generate({
    accountId: ACCOUNT_ID,
    dimension: DIMENSIONS,
    metric: METRICS,
    startDate: START_DATE,
    endDate: END_DATE,
    useTimezoneReporting: false,
    currency: "USD",
    alt: "media",
});

const unzipped = zlib.unzipSync(reportResponse.data); // throws: "incorrect header check"
```

**Comment by bcoe** [comment]
@thewizarodofoz I believe `adsense.accounts.reports.generate` returns a promise, perhaps you need to do something like:

```js
async function run () {
  // create auth client, get token, instantiate adsense bla bla...
  const reportResponse = await adsense.accounts.reports.generate({
      accountId: ACCOUNT_ID,
      dimension: DIMENSIONS,
      metric: METRICS,
      startDate: START_DATE,
      endDate: END_DATE,
      useTimezoneReporting: false,
      currency: "USD",
      alt: "media",
  });

  const unzipped = zlib.unzipSync(reportResponse.data); // throws: "incorrect header check"
}

run()
```

**Comment by thewizarodofoz** [comment]
@bcoe nice catch, I omitted the await when I reducted the code for this issue. This is not the problem.

**Comment by bcoe** [comment]
@thewizarodofoz mind providing the full stack trace? Is the code you provided sufficient to produce the error?

**Comment by thewizarodofoz** [comment]
Here is the minimal code I could write to reproduce (and assert) the behaviour:
```js
const {strictEqual, throws} = require("assert");
const {gunzipSync} = require("zlib");
const {adsense_v1_4, google} = require("googleapis");
const {Adsense} = adsense_v1_4;

const ACCOUNT_ID = "...";
const CLIENT_ID = "...";
const CLIENT_SECRET = "...";
const REFRESH_TOKEN = "...";

async function run() {
    const authClient = new google.auth.OAuth2({
        clientId: CLIENT_ID,
        clientSecret: CLIENT_SECRET,
    });

    authClient.setCredentials({
        refresh_token: REFRESH_TOKEN,
    });

    const adsense = new Adsense({
        auth: authClient,
    });

    const reportResponse = await adsense.accounts.reports.generate({
        accountId: ACCOUNT_ID,
        dimension: ["APP_NAME"],
        metric: ["EARNINGS"],
        startDate: "2019-07-20",
        endDate: "2019-07-27",
        useTimezoneReporting: false,
        currency: "USD",
        alt: "media",
    });

    strictEqual(reportResponse.headers["content-type"], "application/gzip", "content type is not gzip");

    throws(() => gunzipSync(reportResponse.data), /incorrect header check/, "unzipped successfully");

    console.log(reportResponse.data);
}

run();
```

Full stack trace:
```
Error: incorrect header check
    at Gunzip.zlibOnError (zlib.js:153:15)
    at Gunzip._processChunk (zlib.js:411:30)
    at zlibBufferSync (zlib.js:144:38)
    at zlib.js:590:14
    at run (/Users/ozwiess/vidazoo/adSenseGzipIssue.js:37:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by bcoe** [comment]
thanks you :+1: not sure how quickly we'll be able to investigate, but this gives us a great foundation to do so.

**Comment by thewizarodofoz** [comment]
If it helps, I also requested the same data using axios directly (instead of using this library) and the result was the same.

**Comment by maseratidreamz** [comment]
Can you fix this problem for me

**Comment by bcoe** [comment]
@thewizarodofoz if you `console.log` `reportResponse.data`, what is the value? The documents suggest that the response should be in JSON format (not zipped):

https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/adsense/v1.4.ts#L2026

My expectation would be that it uses a gzip HTTP request, but that the client would return data that isn't zipped.

**Comment by thewizarodofoz** [comment]
@bcoe I am sorry, I am unable to run the code because I am not working in the organisation i used to work for, and I don't have AdSense credentials to play with right now. But the reason I expected the response to be gzipped is [this](https://developers.google.com/adsense/management/reporting/large_reports#limit):

> You can add the alt parameter to your request, setting it to "media"... The results will come back as a gzipped CSV which, after decompression, is identical to the one in the previous section.

And if I remember correctly when I debugged this I did output `reportResponse.data` and it looked like gzipped data (gibberish).

On the other hand I see this library internally uses `node-fetch` which according to the [docs](https://github.com/node-fetch/node-fetch#features) opens compressed responses automatically:
> Decode content encoding (gzip/deflate) properly and convert string output (such as res.text() and res.json()) to UTF-8 automatically.

Sorry I can't help more right now.

**Comment by bcoe** [comment]
@thewizarodofoz no this is a big help, thanks for taking the time to answer even though this isn't a major issue for you anymore.

**Comment by JustinBeckwith** [comment]
I think we have this one figured out.  The issue was the return type of `res.data`.  By default, `gaxios` will try to parse return data as JSON.  When we use `alt=media`, it's a signal to the server to return a blob, but gaxios is asking for JSON.  We need to be specific about asking for an `arraybuffer`:

```
  const res = await adsense.accounts.reports.generate({
    accountId,
    metric: ["EARNINGS"],
    useTimezoneReporting: false,
    currency: "USD",
    startDate: "2020-01-01",
    endDate: "2020-01-30",
    alt: "media"
  }, {
    responseType: 'arraybuffer'
  });  
```

This ensures `res.data` isn't going to be parsed, and can be directly ungzipped.

Note - this uses the sample client available here: 
https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/sampleclient.js

```js
const zlib = require("zlib");
const { google } = require("googleapis");
const client = require('./sampleclient');

async function run() {
  const accountId = 'pub-xxxxxxxxxx';

  await client.authenticate([
    'https://www.googleapis.com/auth/adsense'
  ]);

  const adsense = google.adsense({
    version: 'v1.4',
    auth: client.oAuth2Client,
  });

  const res = await adsense.accounts.reports.generate({
    accountId,
    metric: ["EARNINGS"],
    useTimezoneReporting: false,
    currency: "USD",
    startDate: "2020-01-01",
    endDate: "2020-01-30",
    alt: "media"
  }, {
    responseType: 'arraybuffer'
  });  
  
  const data = zlib.gunzipSync(res.data).toString('utf8');
  console.log(data);
}

run();
```

It's possible we need to take a closer look here at how `gaxios` treats response data, but at the very least this snippet should unblock folks :)

**Comment by JustinBeckwith** [comment]
For now, calling this one done.  If you're still having trouble - please do let us know!
