### ISSUE TITLE
Service to service example code not working

### ISSUE THREAD

**Issue by q42jaap** [googleapis/google-api-nodejs-client#1782]
The example code in the readme:
```
const auth = new google.auth.GoogleAuth({
    // Scopes can be specified either as an array or as a single, space-delimited string.
    scopes: ['https://www.googleapis.com/auth/compute']
  });
```
Is not working, the runtime error is:
```
TypeError: google.auth.GoogleAuth is not a constructor
```
It's not clear how to solve this.

**Comment by bcoe** [comment]
@q42jaap we hadn't yet published version `42.0.0` of the library, which introduces the `GoogleAuth` constructor.

Could you please `npm i googleapis@latest`, and let me know if this solves your problem?

**Comment by jlippold** [comment]
Im using 42.0.0 and getting the same error, I have no idea why

**Comment by bcoe** [comment]
@jlippold @q42jaap I have just confirmed that the following code works:

```js
const {google} = require('googleapis');
const auth = new google.auth.GoogleAuth({
  // Scopes can be specified either as an array or as a single, space-delimited string.
  scopes: ['https://www.googleapis.com/auth/compute']
});
```

On `googleapis@42.0.0`.

@jlippold try `rm -rf node_modules; rm package-lock.json; npm i`, and give the example code a shot.

If you're continuing to have issues, mind sharing a snippet of the code you're running?

**Comment by ryanpoh** [comment]
It doesnt work for me too
