### ISSUE TITLE
Intermittent errors on drive.files.create

### ISSUE THREAD

**Issue by jayjanssen** [googleapis/google-api-nodejs-client#1784]
#### Summary

I am using v3 drive files.create to upload files to a shared folder.  I am using request.get to get a stream of an existing internet file (see code below).  

Intermittently the file either uploads correctly, or else I get an exception, see Trace below

#### Environment details

  - OS: Linux (Docker) and Mac (Reproducible both places)
  - Node.js version: reproduced on 12.6.0 and 10.16.0
  - npm version: 6.10.2
  - `googleapis` version: 42.0.0
  - `request` version: 2.88.0

#### Steps to reproduce

  1.  Have auth credentials and a folder those credentials have permission to create files in.
  2. Populate script below and run 5-10 times and watch for errors

#### Code
I use access tokens for my authentication. I'm not sharing my access credentials here for obvious reasons.  I presume this will work with any other authentication type with the proper privs.  I'm also not sharing the folder id.  

```js
  var auth, clientId, clientSecret, credentials, drive, file_url, filename, folder, google, mime, redirectUri, request, util;

  util = require('util');
  request = require("request");
  ({google} = require('googleapis'));

  auth = new google.auth.OAuth2(clientId, clientSecret, redirectUri);
  auth.credentials = credentials;

  drive = google.drive({
    version: 'v3',
    auth
  });

  filename = 'fatboy.png';
  mime = 'image/png';
  file_url = "http://findicons.com/files/icons/1267/futurama_vol_4_the_robots/256/fat_bot.png";

  (async function() {
    var resp;
    resp = (await drive.files.create({
      resource: {
        name: filename,
        mimeType: mime,
        parents: [folder]
      },
      media: {
        body: request.get(file_url)
      }
    }));
    return console.log(util.inspect(resp));
  })();
```

#### Trace

The above code intermittently emits this:

```
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_PUSH_AFTER_EOF] [ERR_STREAM_PUSH_AFTER_EOF]: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:263:32)
    at PassThrough.Readable.push (_stream_readable.js:210:10)
    at PassThrough.Transform.push (_stream_transform.js:150:32)
    at PassThrough.afterTransform (_stream_transform.js:94:10)
    at PassThrough._transform (_stream_passthrough.js:44:3)
    at PassThrough.Transform._read (_stream_transform.js:189:10)
    at PassThrough.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
    at PassThrough.Writable.write (_stream_writable.js:301:11)
    at ProgressStream.ondata (_stream_readable.js:713:22)
    at ProgressStream.emit (events.js:203:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at ProgressStream.Readable.push (_stream_readable.js:210:10)
    at ProgressStream.Transform.push (_stream_transform.js:150:32)
    at ProgressStream._transform (/Users/jayjanssen/Src/google_drive_bug/node_modules/googleapis-common/build/src/apirequest.js:259:14)
    at ProgressStream.Transform._read (_stream_transform.js:189:10)
    at ProgressStream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
    at ProgressStream.Writable.write (_stream_writable.js:301:11)
    at Request.ondata (internal/streams/legacy.js:17:31)
    at Request.emit (events.js:203:13)
    at IncomingMessage.<anonymous> (/Users/jayjanssen/Src/google_drive_bug/node_modules/request/request.js:1080:12)
    at IncomingMessage.emit (events.js:203:13)
    at IncomingMessage.Readable.read (_stream_readable.js:508:10)
    at flow (_stream_readable.js:977:34)
    at resume_ (_stream_readable.js:958:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at PassThrough.onerror (_stream_readable.js:737:7)
    at PassThrough.emit (events.js:203:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at readableAddChunk (_stream_readable.js:263:9)
    at PassThrough.Readable.push (_stream_readable.js:210:10)
    [... lines matching original stack trace ...]
```

**Comment by bcoe** [comment]
@jayjanssen does the problem occur if you `await request.get(file_url)` outside of the create call, so instead passing the full body to create, rather than a stream.

**Comment by jayjanssen** [comment]
Adding `await` to my request doesn't do anything because the request library does not support promises natively.   If I use the request-promise library and await as you suggest, this does indeed prevent the error, but it is counter to what I'm trying to accomplish:  I want to stream the download into the file upload without having to download the entire source file first.  

I was considering my download link and realized it does a 302 to https.  If I put the https target into file_url like this:
```
file_url = "https://findicons.com/files/icons/1267/futurama_vol_4_the_robots/256/fat_bot.png"
```
I am getting the error now EVERY time.  I thought maybe request was broken for https, but using this code:
```
request(file_url).pipe(fs.createWriteStream(filename))
```
I can download https and write to a local file just fine, so the request library is working to download https just fine.    For reference, here is my updated test script:

```js

var auth, clientId, clientSecret, credentials, drive, file_url, filename, folder, fs, google, mime, redirectUri, request, util;

fs = require('fs');

util = require('util');

request = require("request");

({google} = require('googleapis'));

auth = new google.auth.OAuth2(clientId, clientSecret, redirectUri);

auth.credentials = credentials;

drive = google.drive({
  version: 'v3',
  auth
});

filename = 'test.png';

mime = 'image/png';

file_url = "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png";

(async function() {
  var resp;
  // Works fine
  request(file_url).pipe(fs.createWriteStream(filename));

  // Throws exception
  resp = (await drive.files.create({
    resource: {
      name: filename,
      mimeType: mime,
      parents: [folder]
    },
    media: {
      body: request.get(file_url)
    }
  }));
  return console.log(resp.status);
})();
```

**Comment by bcoe** [comment]
@jayjanssen streams can be a bit finicky, what I'm curious to see is whether bushing the bytes to `google.drive` rather than the stream still exhibits the rror

What you could perhaps do would be:

```js
function getFile (fileUrl) {
  return new Promise((resolve, reject) {
    request.get(fileUrl, (err, res, body) {
      if (err) return reject(err)
      return resolve(body)
    })
  }
}

const body = await getFile(fileUrl)

  resp = (await drive.files.create({
    resource: {
      name: filename,
      mimeType: mime,
      parents: [folder]
    },
    media: {
      body: body
    }
  }));
```

I'm curious to see if the problem happens when you're sending the full body rather than a stream.

**Comment by jayjanssen** [comment]
Sorry if I wasn’t clear before - using request-promise with await it works fine.  I agree the problem is with the stream.

Jay Janssen

________________________________

**Comment by bcoe** [comment]
@jayjanssen let's eliminate request from the equation and try https://www.npmjs.com/package/node-fetch or `got`'s streaming API, see if it happens consistently across HTTP libraries.

**Comment by jayjanssen** [comment]
Ok, fair enough.  node-fetch and got both seem to be working fine _and_ are definitely streaming for me.  

I'm probably fine with migrating away from request since it in maintenance mode.  IDK if you'd want to open a bug with them since technically if this is request misbehaving AFA streams, it may be worth them patching.

**Comment by bcoe** [comment]
@jayjanssen I opened an issue on request:

https://github.com/request/request/issues/3192

I'm glad to hear that you've found a couple work arounds however :+1:

**Comment by jayjanssen** [comment]
The only other thing that I neglected to mention was that this worked fine on `googleapis` 22.2.0, so I think it's a regression.  That said, I'll let you decide if it's worth trying to hunt down what changed.

**Comment by adamthesax** [comment]
I was running into similar issues when using `progress-stream` with `googleapis` `drive.files.create`. After a bit of debugging I found that if you pipe a [`stream.PassThrough`](https://nodejs.org/api/stream.html#stream_class_stream_passthrough) as the final stream in your chain, the `ERR_STREAM_PUSH_AFTER_EOF` error goes away. Didn't figure out what is different about the `progress-stream` stream and a normal `stream.Readable` but you may want to see if  `request.get(file_url).pipe(new stream.PassThrough())` fixes it for you.
