### ISSUE TITLE
auth from Params$Resource$Commentthreads$List cannot be assigned by type OAuth2Client 

### ISSUE THREAD

**Issue by jamfly** [googleapis/google-api-nodejs-client#1785]
#### Environment details

  - OS: MacOS 10.14.6
  - Node.js version: 10.16.0
  - npm version: 6.9.0
  - `googleapis` version: 42.0.0

#### Steps to reproduce

I'm following the steps from [Node.js Quickstart](https://developers.google.com/youtube/v3/quickstart/nodejs). 

After authorize successfully, program will execute the following function
```
const getComments = (auth: OAuth2Client): void => {
  const service = google.youtube('v3');

  service.commentThreads.list(
    {
      allThreadsRelatedToChannelId: 'my code',
      part: 'snippet, replies',
      maxResults: 100,
      auth: auth
    },
    (err: Error | null, response: any) => {
      if (err) {
        console.log('The API returned an error: ' + err);
        return;
      }
      console.log(response);
    }
  );
};
```

My issue is that if I declare the auth with type `OAuth2Client` then there's an error came up 
```
Auth client or API Key for the request

Type 'OAuth2Client' is not assignable to type 'string | OAuth2Client | JWT | Compute | UserRefreshClient | undefined'.
  Type 'OAuth2Client' is missing the following properties from type 'UserRefreshClient': fromJSON, fromStream, fromStreamAsyncts(2322)
```

But turns out that I could run this code just declare auth as  type `any`. 

I'm a bit confused about the difference between the `OAuth2Client` from `v3.d.ts` and `google-auth-library`, they seem to be the same. 

Thanks!

**Comment by bcoe** [comment]
@jamfly I'm curious, does this same issue happen with version `41.0.0` of the client?

**Comment by jamfly** [comment]
Hi @bcoe, 

It does happen.

**Comment by JustinBeckwith** [comment]
Greetings!  This can happen if you have two different versions of `google-auth-library` installed.  Can you share your `package.json`?  It may be worth removing any explicit dependencies on `google-auth-library`, and using the version that comes packaged with the `googleapis` npm module instead.  After doing that:
```
rm -rf node_modules package-lock.json
npm install
```

... and try again :) Could I trouble you to give this a shot and see if it solves the problem?

**Comment by jamfly** [comment]
HI @JustinBeckwith,

thanks for your respond, but, I've removed these code and change another approach.

and the way you mentioned above I've already tried them it doesn't work. But still thanks for your help.

Best,
jamfly

**Comment by JustinBeckwith** [comment]
Sorry we couldn't get you on your way with the other approach - but glad you're set up :) Let us know if there's anything else we can do!
