### ISSUE TITLE
Wrong type of secret parameter in OAuth constructor?

### ISSUE THREAD

**Issue by germansokolov13** [googleapis/google-api-nodejs-client#1787]
#### Environment details

  - OS: Linux
  - Node.js version: 12.7
  - npm version: 6.10
  - `googleapis` version: 42.0.0
  - `typescript`: 3.5.3

#### Steps to reproduce

Create `oAuthClient` and try to `getToken` using Typescript compiler
```javascript
import { google } from 'googleapis';
const oauth2Client = new google.auth.OAuth2( CLIENT_ID, SECRET, URL);
const { tokens } = await oauth2Client.getToken(code);
```
If the secret is a plain js object it will work. However if Typescript can derive that's it's an object and not a String then it will throw compile time errors. My PhpStorm IDE also notices that the parameter is of a wrong type and references a file
`node_modules/google-auth-library/build/src/auth/oauth2client.d.ts`:
```
constructor(clientId?: string, clientSecret?: string, redirectUri?: string);
```

If secret is passed as a string that contains a json then it doesn't work. Google will return an `invalid_client` error.

**Comment by JustinBeckwith** [comment]
Greetings!  The `SECRET` in this case is (as far as I know ...) always a string :) We're expecting you to get a keyfile from the developers console that looks something like this:

```
{
  "web": {
    "client_id": "---",
    "project_id": "---",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://accounts.google.com/o/oauth2/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "---",
    "redirect_uris": [
      "http://localhost:3000/oauth2callback"
    ]
  }
}
```

The `client_secret` in this case is always a string ... so that should work out :)

**Comment by germansokolov13** [comment]
It's a json. I can either pass a string that contains unparsed json. Or I can parse it into an object and pass an object. The latter works but breaks type defenitions. The former is fine with compiler but it doesn't work. In the former case I get 401 invalid_client Unauthorized from Google as a response.

Also my secret has "installed" instead of a "web" as its root key.

**Comment by JustinBeckwith** [comment]
The entire blob of JSON isn't the secret :) We're expecting you to pass `theWholeConfig.installed.client_secret` as the value for `secret` there!

**Comment by germansokolov13** [comment]
Thank you for your quick reply! Now this gets really odd. My json is just like the one in your previous comment. But it has "installed" instead of a "web" and it also has no "client_secret" key! But it has all other keys. It's a `client_secret_<somecode>.json` that I was given by my superior.

And it does work for `getToken` method as a plain object but not as as a string. I even managed to get userinfo that token. How is it possible?

**Comment by germansokolov13** [comment]
OK, I figured if there is no `client_secret` key in config then I could go with an empty string. And that worked. So it was not the issue with a type definition. Just I didn't realize my secret was empty. Sorry for false report.

But why don't I have any actual secret? I spent two day reading many guides and looking for a secret. Some guides mention a secret being a json file of some kind.
