### ISSUE TITLE
Drive API V3: cannot update drive's background image

### ISSUE THREAD

**Issue by adshrc** [googleapis/google-api-nodejs-client#1789]
### Environment details

  - OS: MacOS 10.14.6 with Docker 19.03.1
  - Node.js version: 8.14.0
  - npm version: 6.4.1
  - `googleapis` version: 42

#### Steps to reproduce

  1. Try to update a Shared Drive's background image:
```
drive.drives.update({
    driveId: '0AB4qWMNRDLqOUk9PVA',
    requestBody: {
      colorRgb: '#AC725e',
      backgroundImageFile: {
        id: '1XP-9a8dW0ivmXUTlTI0YEp4rmAqWC_WI',
        xCoordinate: 1,
        yCoordinate: 1,
        width: 1
      }
    },
  })
```
  2. Error 400 with no reason what is wrong
```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid Value"
   }
  ],
  "code": 400,
  "message": "Invalid Value"
 }
}
```

Doesn't work in JS SDK nor in API Explorer. But can set the same image and same color by Drive UI in Browser. Is anything wrong with xCoordinate/yCoordinate/width parameters?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  If this isn't working with the API explorer, there's a good chance this isn't an issue with the library itself.  To get in touch with the Google Drive folks ... probably best to file an issue over here:
https://issuetracker.google.com/issues/new?component=191650&template=823909

**Comment by adshrc** [comment]
I reported the issue here: https://issuetracker.google.com/issues/139490293
