### ISSUE TITLE
getToken(): res.text is not a function

### ISSUE THREAD

**Issue by cressidave** [googleapis/google-api-nodejs-client#1792]
I am getting the following error when calling getToken().

Has anyone else experienced this?

Code:

auth.getToken(code, function(err, token){
  if(err){
	console.log("GET TOKEN ERROR: ", err)
  }
});

**Comment by bcoe** [comment]
@cressidave could you provide a bit more of a code sample, where is `auth` initialized, and which library are you using?

**Comment by cressidave** [comment]
Thanks for the reply @bcoe 

I have tried using the example code @ https://developers.google.com/drive/api/v3/quickstart/nodejs

I have been looking at both the gaxios and node-fetch modules to see if I can see where the problem lies. What I see so far is that the result object in gaxios does not have the text() function.

**Comment by cressidave** [comment]
This can be closed.

Tt was a conflict my side with a poor Box2D implementation. Apologies.
