### ISSUE TITLE
What will be the flow to create gdocs on behalf of client users (in their own gdrive) via Node.js

### ISSUE THREAD

**Issue by smkrn110** [googleapis/google-api-nodejs-client#1799]
Our required flow is, we have two applications where, from first app (php) a user will be providing authorization to our application,
and then from another app (background nodeJs app) to create/store file in their g-drive account.

So far the solution I found not fit the above scenario/flow and in NodeJS SDK I did not found any such api/method to create a file/store
file in the other user g-drive.

Looking forward if any one out there could assist me in this regard. Thanks

**Comment by JustinBeckwith** [comment]
Greetings!  For the application where the user provides authorization/authorization, I am going to assume you'll have access to:
- An `access_token`
- A `refresh_token`
- An `expiry_date`

You can construct a new OAuth2 client that uses these to get started:
```js
const auth = new google.auth.OAuth2({
  clientId:  keys.client_id,
  clientSecret: keys.client_secret,
  redirectUri: redirectUri,
});
auth.credentials = {
  access_token,
  refresh_token,
  expiry_date
};
google.options({auth});

// now you can do stuff with `google`!
```

On the particulars of using the google docs API to create stuff ... we have samples for that!
https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/docs/create.js

There are also a few samples in there specific to Google Drive if that helps:
https://github.com/googleapis/google-api-nodejs-client/tree/master/samples/drive

Give this all a shot - and do let me know if you have any questions!  If you're running into problems, please make sure to include a code sample of what you're trying, and any errors you're getting as well.
