### ISSUE TITLE
Where can if find oauth2.key.json?

### ISSUE THREAD

**Issue by smkrn110** [googleapis/google-api-nodejs-client#1800]
where to find or retrieve the file mentioned!

**Comment by JustinBeckwith** [comment]
Greetings!  You need to create an OAuth2 account key on the Google Developer's Console, and download that file.  We cover this a little here:
https://github.com/googleapis/google-api-nodejs-client#oauth2-client

The TL;DR for the steps are:
- Go here: https://console.cloud.google.com/apis/credentials/oauthclient
- Use `web` for the type, and fill in any names, and the callback url
- Download the JSON key file
- Rename it to `oauth2.key.json` if that's what you want to use
- Make sure the file is in the CWD where you're running your app

That should do it!  If you're still running into problems, please do let us know!
