### ISSUE TITLE
How to set an user-agent?

### ISSUE THREAD

**Issue by oliverjessner** [googleapis/google-api-nodejs-client#1802]
As far as I understand, there is a way implemented to set the user-agent.
But I didn't found any documentation/comment which explains how I add the user-agent. 

https://github.com/googleapis/google-api-nodejs-client/issues/1468

**Comment by oliverjessner** [comment]
friendly pump

**Comment by bcoe** [comment]
@oliverjessner I believe you should be able to do something along the lines of:

```
const {google} = require('googleapis');
google.options({
  userAgentDirectives: [{product: 'frog', version: '1.0', comment: 'jumps'}]
});
const blogger = google.blogger({
  version: 'v3',
  // All requests made with this service client will contain the
  // blogId query parameter unless overridden in individual API calls.
  params: {
    blogId: 3213900
  }
});
```

:point_up: global configuration options should be applied to each client.

**Comment by crwilcox** [comment]
Since we haven't heard anything I am going to close this and assume @bcoe sample above will work for your use case.
