### ISSUE TITLE
Limited Documentation

### ISSUE THREAD

**Issue by mfigurski80** [googleapis/google-api-nodejs-client#1805]
Having trouble finding the documentation for the object generated by `new google.auth.OAuth2()`, and, more specifically, it's method `oAuth2Client.generateCodeVerifierAsync`.

Trying to exchange one-time verification code (sent from frontend to server) with the actual access token, per step seven in the server side flow explanation [here](https://developers.google.com/identity/sign-in/web/server-side-flow), and this method seems necessary. Cannot find a good explanation or sample doing that with this node object either.

**Comment by JustinBeckwith** [comment]
Greetings!  There's a full sample of this available here:
https://github.com/googleapis/google-auth-library-nodejs/blob/master/samples/oauth2-codeVerifier.js

The ref docs for this actually look busted ... so I'm going to look at that in the meantime :)
