### ISSUE TITLE
generate binding for the homegraph api

### ISSUE THREAD

**Issue by proppy** [googleapis/google-api-nodejs-client#1806]
The `homegraph` API is now listed under the discovery directory:
https://www.googleapis.com/discovery/v1/apis/

It would be nice to have generated bindings for it so that the smarthome library (https://github.com/actions-on-google/actions-on-google-nodejs/blob/master/src/service/smarthome/smarthome.ts) can depends on it rather than handcrafting a client.

**Comment by bcoe** [comment]
👍 @proppy thanks for the heads up, the `homegraph` API should be pulled in next time we generate the client.

We don't generate the client very frequently these days, if you'd like to get a head start playing with the API, checking out this repo and running `npm run generate` should give you something to play with.

**Comment by JustinBeckwith** [comment]
This has been available for a few releases :)
