### ISSUE TITLE
createScopedRequired is still referenced on the Readme even though it has been removed from the code example

### ISSUE THREAD

**Issue by AyabongaQwabi** [googleapis/google-api-nodejs-client#1811]
The **createScopedRequired** referenced in the below text does not exist in the given code sample

> The code below shows how to retrieve a default credential type, depending upon the runtime environment. The createScopedRequired must be called to determine when you need to pass in the scopes manually, and when they have been set for you automatically based on the configured runtime environment.

See commit [https://github.com/googleapis/google-auth-library-nodejs/pull/255/commits/ca1fdd6be5d0c](https://github.com/googleapis/google-auth-library-nodejs/pull/255/commits/ca1fdd6be5d0c)

#### Environment details

  - OS: Linux Pop
  - Node.js version: v8.16.1
  - npm version: 6.10.3
  - `googleapis` version: 42.0.0

#### Steps to reproduce

  1. Visit [https://github.com/googleapis/google-api-nodejs-client#authentication-and-authorization](https://github.com/googleapis/google-api-nodejs-client#authentication-and-authorization)
  2. Read Service to Service Authentication

**Comment by bcoe** [comment]
@AyabongaQwabi good catch 👍 we will make an effort to update this soon.
