### ISSUE TITLE
part.body.pipe is not a function

### ISSUE THREAD

**Issue by Fazendaaa** [googleapis/google-api-nodejs-client#1833]
#### Environment details

  - OS: Linux
  - Node.js version: 12.9.0
  - npm version: 6.11.2
  - `googleapis` version: 43.0.0

#### Steps to reproduce

I have the following piece of code:

```typescript
    const drive = google.drive({
        version: 'v3',
        auth: 'MYAPIKEYHERE'
    });
    const folderId = 'MYFOLDERIDHERE';
    const fileMetadata = {
        name: filename,
        parents: [ folderId ]
    };
    const media = {
        body: file
    };

    return new Promise((resolve, reject) => {
        drive.files.create({
            // @ts-ignore
            resource: fileMetadata,
            media: media,
            fields: 'id'
            // @ts-ignore
        }, (err, result) => {
            if (null !== err) {
                reject(err);
            } else {
                resolve(result.id);
            }
        });
    });
```

`filename` is a string and `file` a Buffer... I tried many combinations from StackOverflow, Github, and Google Docs but all of them gave me the following error:

```shell
TypeError: part.body.pipe is not a function
    at createAPIRequestAsync (/home/farm/Documents/InventorySystemAPI/node_modules/googleapis-common/build/src/apirequest.js:182:31)
    at Object.createAPIRequest (/home/farm/Documents/InventorySystemAPI/node_modules/googleapis-common/build/src/apirequest.js:41:9)
    at Resource$Files.create (/home/farm/Documents/InventorySystemAPI/node_modules/googleapis/build/src/apis/drive/v3.js:660:37)
    at /home/farm/Documents/InventorySystemAPI/dist/google/drive.js:39:21
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/farm/Documents/InventorySystemAPI/dist/google/drive.js:38:12)
    at Generator.next (<anonymous>)
    at /home/farm/Documents/InventorySystemAPI/dist/google/drive.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/farm/Documents/InventorySystemAPI/dist/google/drive.js:3:12)
    at Object.exports.addToGDrive (/home/farm/Documents/InventorySystemAPI/dist/google/drive.js:13:43)
    at Object.<anonymous> (/home/farm/Documents/InventorySystemAPI/dist/controllers/invoice.js:21:44)
    at Generator.next (<anonymous>)
    at /home/farm/Documents/InventorySystemAPI/dist/controllers/invoice.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/farm/Documents/InventorySystemAPI/dist/controllers/invoice.js:3:12)
```

The funny part is that following the Google Docs tutorial when I tried to create a 'credntials.json' file, it was given to me an API key.

**Comment by bcoe** [comment]
@Fazendaaa can you share the logic you're using to load the `file`? are you using `fs.createReadStream` like in the sample?

**Comment by rashikbhasin** [comment]
@Fazendaaa how did you resolve it? I have been stuck with the same issue.

**Comment by bcoe** [comment]
@Fazendaaa @rashikbhasin rather than using a `Buffer`, could you try passing:

```
body: fs.createReadStream('./path/to/file')
```

:point_up: I believe this is the API surface that it expects currently (I understand wanting to pass a buffer, this might be a feature request or gap in documentation).

**Comment by JustinBeckwith** [comment]
Greetings folks!  Haven't heard anything back in a while, so I'm closing this out.  Please do let us know if you're still running into issues!

**Comment by Alfred-Onuada** [comment]
Hi, [Fazendaaa](https://github.com/Fazendaaa) seems the body key only accepts a readable stream so.

`
const { Readable } =  require('stream')
...
body: Readable.from(file)
`

Hope this helps someone

**Comment by NachoRondan** [comment]
Hi, @Fazendaaa did the comments work for you? I have the same issue, I want to create a readStream from a slack file (https get to the file's url_private) and pass it to the body on the media attribute for a google drive upload but this solutions didn't work for me...

**Comment by keshavageekyants** [comment]
@Fazendaaa I'm facing the same issue, can you provide the solution if you found any.

**Comment by crlsmtzprds** [comment]
> 

You can also do:
`body: Readable.from(Buffer.from( base64_str, 'base64'))`

**Comment by MichFont** [comment]
@Alfred-Onuada that ended up being the key for me. 
If anyone is trying to parse the form data using the Remix framework I just put out a short post on my findings in the Discord: https://discord.com/channels/770287896669978684/1064931829624352768/1064931829624352768

**Comment by borisboskovic** [comment]
@Alfred-Onuada Yeah, that did the trick, thanks.

**Comment by FerEnoch** [comment]
The solution that worked for me in a Next.js 13 form submit project to upload a file to google drive:
`
import { Readable } from 'node:stream'
...
const fileBuffer = file.stream()
...
body: Readable.from(fileBuffer)
`

**Comment by yousuf123456** [comment]
@FerEnoch Yup! It worked for me

**Comment by Youtmax654** [comment]
> The solution that worked for me in a Next.js 13 form submit project to upload a file to google drive: `import { Readable } from 'node:stream'` ... `const fileBuffer = file.stream() ` ... `body: Readable.from(fileBuffer) `

Thank you ! It worked for me too :)
