### ISSUE TITLE
Possible naming issue

### ISSUE THREAD

**Issue by Maxim-Mazurok** [googleapis/google-api-nodejs-client#1836]
Shouldn't `Resource$Commentthreads` be called `Resource$CommentThreads` instead?

https://github.com/googleapis/google-api-nodejs-client/blob/948fd05b1f65ff87fb4856cfb887df04d7bda8cf/src/apis/youtube/v3.ts#L6581

My IDE can't handle `Commentthreads`, because it doesn't use [CamelCase](https://en.wikipedia.org/wiki/Camel_case).

It also seems to affect `Params$Resource$Commentthreads$List` and other params and I want to use these types in my code.

Not a critical issue, but if it's OK to rename it (the class name is not generated from API Discovery, etc.) - I will be happy to do that to keep code clean :)

**Comment by bcoe** [comment]
@Maxim-Mazurok these resource names are generated from API discovery. Are API calls actually failing? or is this purely an IDE issue I wonder.

**Comment by Maxim-Mazurok** [comment]
Yes, it's purely an IDE issue, API calls work as expected.
I believe that it's not unique for my IDE, because most spell checkers for code will fail to recognize two separate words when they are written like `Commentthreads`. So it just would be nice to name it in CamelCase.
But since you're getting it from the API discovery - this repo seems like a wrong place to ask for that. Should I create a topic in [Google API Discovery Forums](https://developers.google.com/discovery/forum) or there's more appropriate place to ask for that? Thanks!

**Comment by bcoe** [comment]
@Maxim-Mazurok opening a discussion on _Google API Discovery Forums_ seems like a good place to start, if you can find a forum specific to the Youtube API, this might also be a good place to start a conversation 👍
