### ISSUE TITLE
Lists remain on document after content has been deleted

### ISSUE THREAD

**Issue by Karasuni** [googleapis/google-api-nodejs-client#1842]
#### Environment details

  - OS: Ubuntu 18.04 on WSL on Windows 10
  - Node.js version: 12.10.0
  - npm version: 6.10.3
  - `googleapis` version: 43

#### Steps to reproduce

  0. ( Create a brand new document )
  1. Create content including lists
  2. Delete all this content
  3. Observe how the document still contains lists definitions
 99. Repeat and observe how new unused list references pile up

#### Expected behavior

  - List definitions should, just like named references, be removed if all content linked to it is removed

I've created a [github repository](https://github.com/Karasuni/googleapis-docs-lists/) to show this issue in action. Originally I asked a [stackoverflow question](https://stackoverflow.com/questions/58183725/) to address this issue and look for a request method to remove these unused list definitions.

**Comment by bcoe** [comment]
@Karasuni :wave: this is the client library for various Google APIs, it might also be worth contacting Google Drive support.

**Comment by JustinBeckwith** [comment]
Greetings folks!  It looks like this is a bug with the underlying API.  In this repository, we can only really address issues with the npm module itself.  For the API, you're going to have the best luck going here:
https://issuetracker.google.com/issues/new?component=555502&template=1211163

Hope this helps!
