### ISSUE TITLE
Authorization for accessing ALL user's Google Calendar from Firebase Cloud Functions 

### ISSUE THREAD

**Issue by nealdyrkacz** [googleapis/google-api-nodejs-client#1843]
Users have signed in to Flutter app with Google Sign In, which has 'https://www.googleapis.com/auth/calendar.events.readonly' as a scope.  In the sign in flow the accessToken and idToken are returned from the google_sign_in package.  User is created / updated in Firebase.

Now I want to be able to run a cloud function every so often that will access each user's Google Calendar and get an event that is due to start with in a certain period of time.  

I have looked through a lot of documentation and only confused myself even more.
I'm certain I need to use a service account, but I am having a hard time grasping the steps to take with google-api-nodejs-client to actually access a users calendar in a cloud function ( that no longer needs to ask a user for permission with redirects, etc... )

**Comment by bcoe** [comment]
@nealdyrkacz is your goal to have users, other than yourself, authenticate with your application, at which point you will perform operations on their behalf sever-side?

To do this, you will need to register an application, and use the OAuth 2.0 flow (described in the README). The user need only go through the authentication flow once, at which point you will store an access-token and refresh-token which can be used to interact with Google APIs on the user's behalf.

To get started, visit [here](https://console.developers.google.com/) and register a client.

**Comment by nealdyrkacz** [comment]
@bcoe Maybe I have a disconnect in my thinking.
Yes, the objective is to have a **scheduled task** in a firebase cloud function.  The cloud function will be reading events in google calendars, from all the users'  in the the firebase db.  The mobile app written in Flutter/dart.  We us the dart package for the Google Sign In.  I have added the calendar scope added to this Google Sign In.  In a test users google account I can see that the confirmation screen asks for permission to access the users calendar. 
Back in the code the calls with Google Sign In , an **access token** and a **id token** are returned for the user who was just authenticated.

At this point,  I guess my confusion is... if the user is now authenticated, but with no refresh token.  And all the work to be done will be in an async cloud function at some point .... I need to run through the OAuth flow again in the scheduled task?  But there will be no user to return a redirect/confrim screen to as its all in the background.

**Comment by bcoe** [comment]
@nealdyrkacz I found this thread:

https://github.com/flutter/flutter/issues/14245

I think there's an option to fetch a refresh_token, you can then create this to avoid needing to refresh server-side.

**Comment by nealdyrkacz** [comment]
@bcoe Hmmm looking at that **getIdToken()** of FireBaseUser in firebase_auth, it seems that is just renewing the access token and sending it back, instead of giving a refreshToken.

**Comment by bcoe** [comment]
@nealdyrkacz I think it might be worth opening an issue on flutter, referencing this issue. You are going to need to find a way to retrieve and store the refresh token, at which point you can use it indefinitely for renewing tokens, in applications using `google-api-nodejs-client`.

**Comment by nealdyrkacz** [comment]
@bcoe Agreed.  Thanks for all the help though!

**Comment by jerryheir** [comment]
Hi @bcoe please are you saying we can't access google calendar with getIdToken() of FireBaseUser in firebase_auth

**Comment by kjonnalagadda** [comment]
hi i am creating webiste , while i am login or signin with google i have to ask the permission from the user to give me the calendar event permission, how to do in my react application.
Right now i am able to do the login option only i am not able ask the permission , once i click on continute with google check the user's gmail account and after that user click on continute it is not asking the calendar permission, directly going into the application,
Right now i need this feature to ask user permission for calendar event
