### ISSUE TITLE
store discovery docs in fixtures for tests

### ISSUE THREAD

**Issue by bcoe** [googleapis/google-api-nodejs-client#1847]
It would be good to store the discovery docs we use to exercise libraries in unit tests (they're currently integration tests). See:

https://github.com/googleapis/google-api-nodejs-client/pull/1846

It would also potentially be good to look at adding back some of the tests we removed when urlshortner was retired.

**Comment by JustinBeckwith** [comment]
Pretty sure we landed this :)
