### ISSUE TITLE
logging_v2.entries.write  api with service account : "The caller does not have permission"

### ISSUE THREAD

**Issue by jeromeSH26** [googleapis/google-api-nodejs-client#1849]
Hi,

I'm struggling in using the stackdriver logging api to log errors and information in the GCP project.
I'm using a service account (used also for more than 20 APIs without issue).

The scope `https://www.googleapis.com/auth/logging.admin` has been set to the service account, as well as the role `"logging admin"` in the GCP IAM console.

MoreOver, I have added a superadmin user in the impersonate mode ("`subject`" in the JWT options)

However, I still have the error **"The caller does not have permission"** while calling the logging API, although the oAuthClient has been well set.

What additionnal role or scope or permission to add to make this running ?

Please note that there is a lack of example and documentation to use the logging api, which makes things confusing, especially where to set the auth, since it appears in 2 different places. It should be set in the `logging({})` options, and/or in the `entries.write({})` options ? I tried all combinations, all of them failed with the same authorization error.

Thks for your help
```

const t = await google.logging({ version: "v2", auth }).entries.write({
                auth,
		requestBody: {
			logName: "projects/THEPROJECT/logs/THELOGS",
			resource: {
				type: "project",
				labels: {
					projectId: "THEPROJECT",
				},
			},
			entries: [
				{
					severity: "INFO",
					jsonPayload: {
						source: "code",
						value: "test",
						details: "this is INFO log test",
					},
				},
			],
		},
	});
	console.log(t.status);
```

**Comment by bcoe** [comment]
@jeromeSH26 have you seen this library:

https://github.com/googleapis/nodejs-logging

This is the client we recommend for interfacing with stackdriver logging.

**Comment by jeromeSH26** [comment]
Yes and finally I used that one.

Le mar. 8 oct. 2019 à 00:21, Benjamin E. Coe <notifications@github.com> a
écrit :

**Comment by bcoe** [comment]
@jeromeSH26 sounds like you're good to go :+1: let me know if you bump in to any issues with `@google-cloud/logging`.
