### ISSUE TITLE
how to download partial file with 'Range' request header using drive nodejs sdk

### ISSUE THREAD

**Issue by Tilak999** [googleapis/google-api-nodejs-client#1850]
I tried to pass the range header to underlying `gaxios` config but it is not working.

```js
drive.files.get(
    {fileId: fileId, alt: 'media'}, 
    {responseType: 'stream', headers: {'Range': 'bytes=0-1023'}},
    function(err, res){
        //handle file content..
    }
```

Can anyone provide any feedback?

**Comment by JustinBeckwith** [comment]
Greetings!  I was able to get this working as expected with very similar code.  When you say "it is not working" - can you share details?  What exactly are you seeing?  How are you handling the response?

**Comment by YouriT** [comment]
Personally doing:

```ts
this.api.files.get(
  {
    fileId: fileId,
    supportsTeamDrives: true,
    alt: 'media'
  },
  {
    responseType: 'stream',
    headers: { Range: `bytes=0-10` }
  },
  (err, res) => {
    if (err) {
      return reject(new Error('The API returned an error: ' + err));
    }

    const stream = res.data as Readable;

    stream.on('data', chunk => {
      console.log('Chunk', chunk);
    });
  }
);
```

Returns me way more than 10 bytes. Looks more like hundreds of:
```
Chunk <Buffer 00 00 00 1c 66 74 79 70 6d 70 34 32 00 00 00 01 69 73 6f 6d 6d 70 34 31 6d 70 34 32 00 00 00 01 6d 64 61 74 00 00 00 00 00 85 e9 32 de 02 00 4c 61 76 ... 691 more bytes>
```

Which doesn't seem to respect the range given as options.

**Comment by YouriT** [comment]
Upgrading to `47.0.0` solved the issue. The thing is documentation is proposing to install `v39` in [here](https://developers.google.com/drive/api/v3/quickstart/nodejs#step_2_install_the_client_library). Reason of the issue.
