### ISSUE TITLE
Cloud run only supports v1alpha1 not v1

### ISSUE THREAD

**Issue by jayp** [googleapis/google-api-nodejs-client#1857]
https://cloud.google.com/run/docs/reference/rest/#discovery-document states the only valid version is 'v1'. This library only generates method for `v1alpha1` (`v1` exists but has no generated methods). 

Is this expected?

**Comment by bcoe** [comment]
:wave: @jayp thanks for pointing this out, it sounds like we potentially need to run the generator (we do so periodically).

**Comment by JustinBeckwith** [comment]
Greetings!  I just confirmed that version `45.0.0` has the `v1` version of the API available :) Thanks!
