### ISSUE TITLE
broken link to stackdriver logging docs

### ISSUE THREAD

**Issue by simonz130** [googleapis/google-api-nodejs-client#1859]
Here: https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/logging/README.md

the link to Stackdriver Logging documentation leads to this:
https://github.com/googleapis/google-api-nodejs-client/blob/master/logging/docs
and this is broken link.

**Comment by JustinBeckwith** [comment]
We're pulling the description on the README directly from the discovery doc, which uses a relative link in markdown format:
https://www.googleapis.com/discovery/v1/apis/

**Comment by JustinBeckwith** [comment]
Looks like at some point this was fixed :)
