### ISSUE TITLE
Firebase/GCP Service Account Auth Call with Domain Wide Delegation

### ISSUE THREAD

**Issue by JaredLGarcia** [googleapis/google-api-nodejs-client#1861]
My team and I are trying to put together a tool that allows users in our domain to discover/modify Shared Drives in our G Suite environment. We have structured the call properly and testing it with just the auth object works great, but as soon as we add another parameter besides auth (in our use case we pass "useDomainAdminAccess: true") it says the "q" parameter is incorrect even though we don't define the q parameter. If we got a different error, we could work with that. Nothing we try has worked so far.  Partial Code Example below:

const SCOPES = ['https://www.googleapis.com/auth/drive']
class DriveApi {
  async authorize() {
    const client = await google.auth.getClient({ scopes: SCOPES })
    return client
  }
  async list() {
    try {
      const auth = await this.authorize()
      const drive = google.drive('v3')
      const list = await drive.drives.list({ useDomainAdminAccess: true, auth })
      console.log('---------------------drive')
      console.log(drive)
      console.log('---------------------list')
      console.log(list)
    } catch (error) {
      console.log('---------------------error2!!!!')
      console.log(error)
    }
  }
}
export default new DriveApi()

We are using React in Firebase. When we don't pass a ClientID/Email, Firebase automatically assumes the default service account is to be used. It works when we pass just auth to 

await drive.drives.list({ auth })

The error we get in the response is `q parameter invalid value`

**Comment by bcoe** [comment]
@JaredLGarcia is your example working when you use it in isolation, rather than in a React application?

We've made an effort to make it possible to webpack `googleapis`, and require it within the context of a react application, but it can take a little bit of fiddling. I would start by getting a working example running as a script, and then trying to work backwards into webpacking it.
