### ISSUE TITLE
Google Sheets spreadsheets.values.get() Slow to update

### ISSUE THREAD

**Issue by quesurifn** [googleapis/google-api-nodejs-client#1865]
Hello,

I have a sheet of 34000 rows. I update it and then call `spreadsheets.values.get()`to look for the row to remove later with `batchUpdate` and `deleteDemension`. 

I usually call these 40 seconds apart for google to update fully, however, I'm finding with the larger spreadsheet that isn't enough. 

Based on these observations I have a few questions:

Why is the API so slow? 
What can I do on my end to speed things up OR get better accuracy?

Thanks,

Kyle Fahey

**Comment by bcoe** [comment]
Hey @quesurifn :wave: I work on the client libraries team, `google-api-nodejs-client` is an abstraction layer on top of dozens of Google APIs, and I don't work directly with the folks developing Google Sheets.

All this is to say, it might also be worth giving feedback here:

https://developers.google.com/sheets/api

And you might find there's some sheets specific documentation about how to best interact with fairly large spread sheets.
