### ISSUE TITLE
HTTPS certificate pinning / prevent DNS poisoning / prevent man-in-the-middle

### ISSUE THREAD

**Issue by matthiasfeist** [googleapis/google-api-nodejs-client#1866]
Hi.

We're currently working with the Node.js client to develop towards Gmail. To protect the integrity of our users as good as we can, I was wondering if there is an option to prevent DNS poisoning attacks/man-in-the-middle attacks somehow while doing requests with this lib.

I was thinking something around HTTPS cert pinning in the client or some extended cert validation.
Is that possible and is this a good idea? Are there maybe other ways this could be approached?

Thanks!
Matthias

**Comment by JustinBeckwith** [comment]
Greetings!  This isn't something that I've personally seen done in an API client, separate from being sure to use HTTPS for the endpoint.  Can you point to an example of somewhere this was done well?
