### ISSUE TITLE
Does the Sheets API support API key auth.

### ISSUE THREAD

**Issue by MarcARoberge** [googleapis/google-api-nodejs-client#1868]
I need add to a nodejs cloud functions the api but I can't login with OAuth2 since it needs browser assistance. I was wondering how to use an API key to authenticate server-server.

**Comment by bcoe** [comment]
@MarcARoberge your best bet would likely be to create a service account in the developer console, see:

https://github.com/googleapis/google-api-nodejs-client#service-to-service-authentication

and

https://cloud.google.com/docs/authentication/getting-started
