### ISSUE TITLE
sample code for calendar api batch request

### ISSUE THREAD

**Issue by blacknell** [googleapis/google-api-nodejs-client#1870]
**Is your feature request related to a problem? Please describe.**
I'm struggling to make a large number of API calls and want to batch these up. I can't find any sample code anywhere for how to do this. I've had no problems with the other methods such as `calendar.events.insert`

 **Describe the solution you'd like**
Sample code to show how to batch up a number of `events.insert` with a `.then` for each individual sub-request

 **Describe alternatives you've considered**
I'm hitting calendar usage errors (not to be confused with api usage errors). I've struggled to get any response or help via [stackoverflow](https://stackoverflow.com/questions/58325909/google-calendar-api-when-do-calendar-usage-limits-reset/58344268#58344268)

 **Additional context**

**Comment by 0xdevalias** [comment]
Related: https://github.com/googleapis/google-api-nodejs-client/issues/2375

**Comment by jrmdayn** [comment]
Having hit the issue of batching Google apis requests using Node.js myself, I decided to develop [a solution](https://github.com/jrmdayn/googleapis-batcher) that follows the guidelines provided in Google's batching [documentation](https://developers.google.com/calendar/api/guides/batch), implementing the `multipart/mixed` HTTP request/response protocol.

Please have a look and do not hesitate to raise an issue if you find a bug or would like to discuss improvements.

**Comment by sofisl** [comment]
This [answer](https://github.com/googleapis/google-api-nodejs-client/issues/2375#issuecomment-717470917) does a great job of explaining the current state of the world, but TL;DR: calendar does not support batch requests.
