### ISSUE TITLE
sample for Google my business api

### ISSUE THREAD

**Issue by KinyuaNgugi** [googleapis/google-api-nodejs-client#1871]
Hi. Could you please provide a sample for Google my business api

**Comment by chrisdavis112** [comment]
I'm looking for this as well, are there any plans for this?

**Comment by bcoe** [comment]
@chrisdavis112 no immediate plans to add a sample, would happily take a community contribution in case anyone stumbles across this thread :smile:

**Comment by oliverjessner** [comment]
@bcoe so basically there is currently no docu, howto use GMB with the SDK? 
I would love to write this example, but how would I be able without any docu in the first place?

**Comment by chrisdavis112** [comment]
@bcoe I second that.  I've used the the calendar api with success before, but I cannot find anything inside the module.  Is this something that needs built, and then a sample can be created, or can you point me in the direction of where the code for this resides?

**Comment by bcoe** [comment]
:wave: I reached out to a couple folks on the GMB team and put this issue on their radar.

**Comment by balazsorban44** [comment]
Also interested. I would like to show the reviews on my business's website.

**Comment by ImmanuelKannan** [comment]
Hi @balazsorban44, I'm wondering if you managed to display reviews on your website? I'm currently in the same boat you were and can't figure out how to get the reviews using this library.

**Comment by SymShivam** [comment]
Hi, is there any update on this? Also if there is a sample available then is it updated with new business profile performance api?

**Comment by sofisl** [comment]
Hello! Not sure which API is best suited for your needs, but there are a few APIs with mybusiness* [here](https://github.com/googleapis/google-api-nodejs-client/tree/main/src/apis). Examples on how to use each method live in the v*.ts file, for example, [here](https://github.com/googleapis/google-api-nodejs-client/blob/31defea1dca2e32d2cfcea1649087a206e7254d1/src/apis/mybusinessaccountmanagement/v1.ts#L107). Feel free to open up another issue for any specific question relating to this APIs.

**Comment by nKtistakis** [comment]
You answer @sofisl is really not helpfull and pretty dismissive. It is clear that if someone needs mybusiness API then manual implementation is most likely needed. You only support the `mybusiness*` APIs, while missing all the `mybusiness.` ones.

Anyways to whoever that might stumble upon this, check this answer that might be helpful:
https://stackoverflow.com/questions/73695043/get-google-business-reviews-server-side
