### ISSUE TITLE
"Invitation pending" on User Permissions: create

### ISSUE THREAD

**Issue by konradstrek** [googleapis/google-api-nodejs-client#1874]
I'm using `user_permissions.create` to add new admin to the Google Tag Manager account. The problem is that even If we have `"permission": "admin"` in code, we still have yellow Invitation pending badge. How to make it directly green (Has access)?

Note: User making `create` request allowed our app to make this request.

![ice_screenshot_20191106-134400](https://user-images.githubusercontent.com/37452287/68299605-5342b400-009c-11ea-8b1d-97826d9bfa54.png)

```
return gapi.client.tagmanager.accounts.user_permissions.create({
  "parent": "accounts/0123456789",
  "resource": {
    "path": "accounts/1111111111",
    "accountId": "1111111111",
    "emailAddress": "myemail@gmail.com",
    "accountAccess": {
      "permission": "admin"
    },
    "containerAccess": [
      {
        "containerId": "123456789",
        "permission": "publish"
      }
    ]
  }
})
.then(function(response) {
  console.log("Response", response);
},
function(err) {
  console.error("Execute error", err);
});
```

**Comment by bcoe** [comment]
@konradstrek if I'm following, the API works as expected but there's the incorrect badge in the UI?

It might also be worth opening a help issue with the tag manager project itself, if I'm following your problem correctly:

https://support.google.com/tagmanager/community

**Comment by konradstrek** [comment]
Issue closed but still no solution.

**Comment by bcoe** [comment]
@konradstrek the client library is unlikely to be causing a display bug in the upstream display in the UI. Did you get a response from support?

**Comment by konradstrek** [comment]
@bcoe Yes, google support but still no response. It isn't bug, but part of code that wasn't previously included on google documentation [https://developers.google.com/tag-manager/api/v2/reference/accounts/user_permissions/create](Link)

**Comment by konradstrek** [comment]
@bcoe Yes, google support but still no response. It isn't bug, but part of code that wasn't previously included on google documentation https://developers.google.com/tag-manager/api/v2/reference/accounts/user_permissions/create

**Comment by konradstrek** [comment]
I hope someone will include this `status` on documentation https://developers.google.com/tag-manager/api/v2/reference/accounts/user_permissions

**Comment by bcoe** [comment]
👍 I'm glad you worked things out, sorry that this was frustrating.
