### ISSUE TITLE
Search console is not showing newly added (via API call) sites

### ISSUE THREAD

**Issue by mustafabutt** [googleapis/google-api-nodejs-client#1877]
I am trying to automate the site registration (as a property) and sitemap submission process at google search console. 
For this purpose I am building it in Nodjes which is integrated with Google search console via a **service account**. Here are the API docs. https://developers.google.com/webmaster-tools/search-console-api-original/v3/sites/add
So now, when I manually register a site at search console then it gets added successfully and I submit the sitemap via api call(using same service account) to that property it gets added and shows up in search console. **BUT**, when I try to add site via api call using the same service account the call complete successfully with status 204 but that newly added site does not show in search console. 
So, why sitemap submission using same service account submits show up in search console but not **Sites** ?
Thanks

**Comment by fhinkel** [comment]
Hi @mustafabutt , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.
