### ISSUE TITLE
v4 sheets.spreadsheets.values.update missing resource parameter in type definition

### ISSUE THREAD

**Issue by Hebilicious** [googleapis/google-api-nodejs-client#1883]
The resource parameter is documented in v4.d.ts, but it's missing from the interface.
![image](https://user-images.githubusercontent.com/13395944/68994890-be03a480-087f-11ea-88f6-814f8c5209f1.png)

Example code : 
![image](https://user-images.githubusercontent.com/13395944/68994915-f60ae780-087f-11ea-9736-fdb1b36918e7.png)
![image](https://user-images.githubusercontent.com/13395944/68994919-04590380-0880-11ea-8c82-b268944f07c8.png)

**Comment by JustinBeckwith** [comment]
Greetings!  The field name you're looking for here is called `requestBody`.  If you use `requestBody` instead of `resource` this should work :)
