### ISSUE TITLE
400 Bad request - Gmail API - GSuite account

### ISSUE THREAD

**Issue by bitliner** [googleapis/google-api-nodejs-client#1886]
I'm trying to access the emails of a GSuite account.

I've followed the correct procedure, specifically:
- I've enabled Gmail API on Google Cloud Console
- I've created a service account
- I've enabled G Suite Domain-wide Delegation
- I've added the service account to the page of API access permission (https://admin.google.com/<domain>/pagelet/ManageOauthClients), with scope `https://www.googleapis.com/auth/gmail.readonly` and `https://www.googleapis.com/auth/gmail.labels`

However, when I run the following code:

```js
// index.js

const { google } = require('googleapis')

const scopes = [
  'https://www.googleapis.com/auth/gmail.labels'
  'https://www.googleapis.com/auth/gmail.readonly'
]

async function main () {
  const googleAuth = new google.auth.GoogleAuth({ scopes })
  const auth = await googleAuth.getClient()

  const gmail = google.gmail({ version: 'v1' })
  gmail.users.labels.list({
    userId: 'XXX-YYY@domain.com',
    auth
  }, (err, res) => {
    console.log('>', JSON.stringify(err, null, 4))
    if (err) return console.log('The API returned an error: ' + err)
    console.log(JSON.stringify(res))
  })
}

main()

```

if fails by throwing the following error:

```
The API returned an error: Error: Bad Request
```

I run that code as follow:

```
GOOGLE_APPLICATION_CREDENTIALS=path-to-key.json node index.js
```

I've followed the correct setup process, everything should work fine.

However the program fails without giving me any relevant information that can help me to fix the problem

**Comment by JustinBeckwith** [comment]
Greetings!  I was able to get this to work with a few small edits to your code:

```js
const { google } = require('googleapis');

const scopes = [
  'https://www.googleapis.com/auth/gmail.labels',
  'https://www.googleapis.com/auth/gmail.readonly'
];

async function main () {
  const googleAuth = new google.auth.GoogleAuth({ scopes })
  const auth = await googleAuth.getClient()
  const gmail = google.gmail({ 
    version: 'v1',
    auth,
  });
  const res = await gmail.users.labels.list({
    userId: 'me',
  });
  console.log(res.data);
}

main().catch(console.error);
```

Could you give this a shot?  I suspect there may be some kind of permissions problem unrelated to the library, but having something to do with delegation.
