### ISSUE TITLE
HOW to use the fitness API on NodeJS

### ISSUE THREAD

**Issue by codemodify** [googleapis/google-api-nodejs-client#1887]
The OAuth 2.0 playground is useless and never returns anything, `gapi` package seems from 8 years ago, google-api-nodejs-client has no documentation at all.

Is there a simple 1-2-3 steps example that shows how to query number of steps that was ever recorded ?

The scenario is:
- user logs in with Firebase auth providers
- get that magic tokens to and pass them to the Firebase function to read his fitness data

The next frustrating part is the fitness data sources/datasets and all that, complete nightmare, no way to understand how it is organized. Feels like a low level SQL database than an actual API

Then there are next steps:
From here: https://github.com/googleapis/google-api-nodejs-client#oauth2-client

Is this expected to be asked on the client side like a web page then the token to be send to the backend where it will be used to query the fitness data ?

dear god

**Comment by bcoe** [comment]
@codemodify there is not an example of the fitness API at this time, having said this, I think you should be able to potentially use some of the other samples as a starting point, in the samples folders (all of the REST APIs are interacted with in similar manner).

You will find the methods supported by the API wrapper documented [here](https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/fitness/v1.ts#L623), and there will be a close corollary to the methods outlined in the REST API [here](https://developers.google.com/fit/rest/v1/get-started).

As for authentication, you will likely be creating an OAuth 2.0 [Web Server Application](https://developers.google.com/identity/protocols/OAuth2), you will initially send the user through an authentication flow, at which point you store a refresh token for the user, which can be used by your application to update their credentials over time.
