### ISSUE TITLE
List all projects without OAuth2

### ISSUE THREAD

**Issue by francesco-clementi-bip** [googleapis/google-api-nodejs-client#1898]
Is it possible to use the resource manager to list all projects with a service account?
How con I use the resource manager api with this package?

**Comment by bcoe** [comment]
@francesco-clementi-bip :wave: it should be possible to use a service account:

1. create and download the service account credentials, as a JSON file.
2. set the variable `GOOGLE_APPLICATION_CREDENTIALS`, which should be the absolute path to the JSON file created in step 1.

There is documentation on this topic [here](https://cloud.google.com/docs/authentication/getting-started).

Let me know if this does the trick for you.

**Comment by francesco-clementi-bip** [comment]
Actually I'm using and express nodejs server on google app engine. I managed to get the list of all projects with my local env (with my google account credential).
When I deploy it on GAE, the api respond with only the project of the App Engine.
The service account of the App Engine has also the role of "Browser".
Am I using a right pattern? Should I set different roles on the Gae service account?

**Comment by francesco-clementi-bip** [comment]
Hi, thanks for your response.
I managed to use a service account with permissions of owner and browser, but the resource manager api return only one project (the one of the service account), but I need all the projects. 
Any idea?

**Comment by francesco-clementi-bip** [comment]
Here the code that I'm trying and that return only the project with service account, even if I set the role of browser. 
`
const {Resource} = require('@google-cloud/resource');
const keyFilename = 'path_to_json_service_account';
const resource = new Resource({keyFilename});
const [projects] = await resource.getProjects();
console.log("PROJECTS",projects)
`
