### ISSUE TITLE
How to use proxy

### ISSUE THREAD

**Issue by minato961102** [googleapis/google-api-nodejs-client#1899]
Please tell me. how to add proxy when getting an email with googleapis

**Comment by JustinBeckwith** [comment]
Greetings!  There's a section in the README that has instructions here:
https://github.com/googleapis/google-api-nodejs-client#using-a-proxy

If you try it out and run into trouble, please do let us know!

**Comment by glebmlk** [comment]
Hi @minato961102, documentation says `but then override it for a specific request, using the proxy configuration option.` What is this option? Where can I pass it?
e.g. in my case I want every googleapi request to pass through a proxy, but I don't want to use environment variable. Is this possible?
