### ISSUE TITLE
Can I pass custom headers (like Referer) when calling the youtube API?

### ISSUE THREAD

**Issue by iamgoodbytes** [googleapis/google-api-nodejs-client#1906]
Recent youtube API changes have triggered the following in my code: `Error: The request did not specify any referer. Please ensure that the client is sending referer or use the API Console to remove the referer restrictions.`

I tried setting the referrer domain to my own domain without success. I also tried to create a new key for my app and remove all restrictions on that key, but that gives me another error: `Error: Access Not Configured. YouTube Data API has not been used in project`

How are you all handling this? 

Thanks for helping out!

**Comment by bcoe** [comment]
You should be able to do this:

google.options({
  headers: {referer: 'value'}
});

Please let me know if this gives you issues.

**Comment by iamgoodbytes** [comment]
@bcoe Thanks so much, that solved the issue for me. I didn't think of adding that to the options.

**Comment by bcoe** [comment]
@iamgoodbytes awesome, I'm glad you're unblocked.
