### ISSUE TITLE
Missing documentation for "compute"

### ISSUE THREAD

**Issue by garyo** [googleapis/google-api-nodejs-client#1915]
What's not working: there is no documentation for the `compute` API in the API docs, although this repo's README says "This library has a full set of API Reference Documentation". 

To repro: go to https://googleapis.dev/nodejs/googleapis/latest and look for `compute` or anything like that. Notice that there's nothing there.

(It was suggested in https://github.com/googleapis/google-cloud-node/issues/952 that I check out this lib for accessing the compute API from Typescript because `@google-cloud/compute` will not be getting Typescript type decls.)

**Comment by bcoe** [comment]
@garyo thanks for the bug report, I'm not sure why that's missing.

**Comment by Fryuni** [comment]
The IDEs and TS type checking recognize all the methods and their documentations from the Discovery API if I import `compute_v1` directly. Maybe there is a broken export somewhere above that.

**Comment by JustinBeckwith** [comment]
@bcoe this is on purpose.  The Compute API is large and in charge.  The only way I could get the docs to generate in a reasonable amount of time was to disable this specific API.  I tried it locally with an updated toolchain, and it's taking ~5 minutes on my macbook just to generate compute.  Not sure if that's something we should try, given the memory consumption issues I've had here before 🤷

**Comment by bcoe** [comment]
@garyo @JustinBeckwith I'll leave this open as something to dig into, perhaps something will jump out at me if I profile.

**Comment by Splaktar** [comment]
It looks like the docs are now available [here](https://googleapis.dev/nodejs/googleapis/latest/compute/index.html) thanks to PR https://github.com/googleapis/google-api-nodejs-client/pull/2244.
