### ISSUE TITLE
Add `compute.zoneOperations.wait` as beta

### ISSUE THREAD

**Issue by garyo** [googleapis/google-api-nodejs-client#1916]
Using `googleapis@46.0.0`, I can only get to `compute.zoneOperations.wait()` if I use `google.compute('alpha')`, but then I can't access it anyway because alpha APIs require special permissions. If I try to use 'beta' the `wait` function doesn't exist. 
But I believe `compute.zoneOperations.wait()` is now in beta, see: https://cloud.google.com/compute/docs/reference/rest/beta/zoneOperations/wait

So can this be moved into the beta API?

My code is something like this:
```typescript
import { google } from 'googleapis'
// ...
  const compute = google.compute('beta') // or try "alpha"
  const authClient = await google.auth.getClient({
    scopes: [...]
  })
  const projectId = await google.auth.getProjectId()
  const request = {
    project: projectId,
    zone: zone,
    resource: vmConfig,
    auth: authClient,
  };
  const response = await compute.instances.insert(request)
  const operationId = response.data.id
  if (!operationId)
    throw new Error(`createInstance: Error creating instance ${vmName}`)

  // Wait for the instance to be created: this is where it fails
  const status = await compute.zoneOperations.wait({operation: operationId})
```
The error I get with the above above in 'beta' is `TypeError: compute.zoneOperations.wait is not a function`. In 'alpha' I get the error `Error: Required 'Alpha Access' permission for 'Compute API'`

**Comment by JustinBeckwith** [comment]
Greetings!  There must have been some drift between when the API docs were released and the updated library went out.  Regardless - this should be solved!  In the latest release, I'm seeing a `compute.zoneOperations.wait` on the `beta` channel of the API.  Let us know how it goes!
