### ISSUE TITLE
The service-to-service section is not actually about service-to-service auth

### ISSUE THREAD

**Issue by bennlich** [googleapis/google-api-nodejs-client#1923]
The authentication section describes service-to-service auth:

> Service <--> Service - In this model, your application talks directly to Google APIs using a Service Account. It's useful when you have a backend application that will talk directly to Google APIs from the backend.

The "Learn more" link goes to https://github.com/googleapis/google-api-nodejs-client#service-to-service-authentication

But this section does not seem to be about authenticating service accounts. Instead it is about auto-detecting what kind of auth credential you need for your runtime environment.

**Comment by bcoe** [comment]
@bshaffer any thoughts on this documentation, I know you've been doing some work specifically related to service to service authentication; could we update this part of the documentation as part of it.
