### ISSUE TITLE
Use Node.js to call Google API and put it into a cloud function. client method cannot return data

### ISSUE THREAD

**Issue by radianceltd** [googleapis/google-api-nodejs-client#1929]
```js
exports.devicegetway = async (req,res) => {
  const cloudRegion = 'us-central1';
  const gatewayId = 'my-region-001';
  const projectId = 'riltmw025tool-2019';
  const registryId = 'my-registry-006s';
  
  const client = getClient('riltmw025tool-2019-21396a54b9be.json');
  listDevicesForGateway(client, projectId, cloudRegion, registryId, gatewayId);
}

const getClient = async (serviceAccountJson,res) => {
  const authClient = await google.auth.getClient({
    keyFilename: serviceAccountJson,
    scopes: ['https://www.googleapis.com/auth/cloud-platform'],
  });
  const discoveryUrl = 'https://cloudiot.googleapis.com/v1/projects/riltmw025tool-2019/locations/us-central1/registries/my-registry/devices';
  google.options({
    auth: authClient,
  });
  try {
    return google.discoverAPI(discoveryUrl);
  } catch (err) {
    console.error('Error during API discovery.', err);
  }
};

const listDevicesForGateway = async (client,projectId,cloudRegion,registryId,gatewayId) => {
  const parentName = projects/${projectId}/locations/${cloudRegion}/registries/${registryId};
  const request = {
    parent: parentName,
    'gatewayListOptions.associationsGatewayId': gatewayId,
  };
  let devices;
  try {
    const {data} = await client.projects.locations.registries.devices.list(
      request
    );
    devices = data.devices;
  } catch (err) {
    console.error('Could not list devices', err);
    return;
  }
  console.log('Current devices bound to gateway: ', gatewayId);
  
  if (devices && devices.length > 0) {
    devices.forEach(device => {
      console.log(\tDevice: ${device.numId} : ${device.id});
    });
  } else {
    console.log('No devices bound to this gateway.');
  }
};
```
`const {data} = await client.projects.locations.registries.devices.lis` cannot return data

I try to use `const client = new iot.v1.DeviceManagerClient` to get only part of the API function data

IAM and service account / valid keys are stored in the project file, but the client data can not return data

**Comment by radianceltd** [comment]
@dazuma @blowmage @lukesneeringer @proppy @hongalex

**Comment by bcoe** [comment]
@radianceltd :wave: sorry that you're bumping into issues, just a thought it might also be worth trying out our standalone iot library:

**Comment by hongalex** [comment]
@bcoe Apologies. This is partially due to an in-progress migration of our current IoT Core samples from the discovery client to the standalone library that you mentioned.

@radianceltd As mentioned above, we recommend [installing the nodejs-iot package](https://www.npmjs.com/package/@google-cloud/iot). This won't require a separate `getClient` call, and can be instantiated by doing
```
const iotClient = new iot.v1.DeviceManagerClient({});
```

For reference, the `listDevices` sample can be [found here](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/iot/manager/manager.js#L455-L486).

**Comment by radianceltd** [comment]
thank u for response @hongalex @bcoe

**Comment by radianceltd** [comment]
@hongalex 我这边用你建议的Nodejs-iot软件包是可以访问到某些谷歌API的功能，但nodejs软件包缺少很大重要的API调用数据，因此，我目前想使用，如:const {data} = await client.projects.locations.registries.devices.list(request);，来实现列出注册表中的所有设备.

**Comment by radianceltd** [comment]
@bcoe The independent Internet of Things you described, iot.v1.DeviceManagerClient ({}); can access the data, but this nodejs package cannot implement other more IOT API data. Is it because Google has restricted the VPN method for Chinese computers? To access Google IOT data?

**Comment by radianceltd** [comment]
![image](https://user-images.githubusercontent.com/58924597/72118275-8ef34600-338b-11ea-8c07-92c094041446.png)
@hongalex @bcoe @jmdobry @ace-n @fhinkel

**Comment by hongalex** [comment]
What specific API is missing from nodejs-iot that is available in the other method you are trying to use? Most of the standard features are available, including creating, listing, updating, and deleting devices

**Comment by radianceltd** [comment]
@hongalex If I use mqtt to read device data, I can't

**Comment by radianceltd** [comment]
@hongalex Thank you for your response. For example: I get the device list in the registry under the nodejs-iot package. It will display a list of all devices and gateways in the registry. It will not only display the list of devices, but also create a gateway and bind the device to the gateway On the nodejs-iot I have not seen this API available

**Comment by hongalex** [comment]
Ah, gotcha. None of the Google Cloud IoT packages support connecting to the MQTT broker. You would have to use a separate package like the [npm mqtt library](https://www.npmjs.com/package/mqtt). For more info, see [our docs page on connecting via MQTT](https://cloud.google.com/iot/docs/how-tos/mqtt-bridge) and [this sample for the connection arguments for connecting the mqtt client](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/iot/mqtt_example/cloudiot_mqtt_example_nodejs.js#L425-L466)

**Comment by radianceltd** [comment]
@hongalex Thank you for your response. For example: I get the device list in the registry under the nodejs-iot package, and it will display a list of all devices and gateways in the registry. I just want it to display a list of devices. Also create a gateway and bind the device to the gateway. These are not provided on nodejs-iot

**Comment by radianceltd** [comment]
![image](https://user-images.githubusercontent.com/58924597/72121806-16928200-3397-11ea-8822-64e5d237f478.png)
我引入的这个密钥文件有不对吗？为什么它说找不到这个.pem文件？因此，我也尝试了利用官方的MQTT去建立连接设备，但还未成功.
@hongalex

**Comment by radianceltd** [comment]
![image](https://user-images.githubusercontent.com/58924597/72122019-a0424f80-3397-11ea-9247-1640bba3de80.png)
Is this key file I imported wrong? Why does it say that it cannot find this .pem file? Therefore, I also tried to use the official MQTT to establish a connected device, but it has not been successful.

@hongalex

**Comment by radianceltd** [comment]
![image](https://user-images.githubusercontent.com/58924597/72138275-7acd3a00-33c7-11ea-96ee-7e2de4e09d0a.png)
我按照官方Nodejs-MQTT文档进行了尝试，但遇到无法进入客户端连接，客户端的信息和所需的参数，我都仔细的填写检查了，但测试依然无法把设备连接到Google IOT Core，感谢您能帮我看看，希望再次得到您的解答！谢谢
@hongalex @bcoe

**Comment by radianceltd** [comment]
![image](https://user-images.githubusercontent.com/58924597/72139135-29be4580-33c9-11ea-9aa7-1d0e90348af3.png)
I tried according to the official Nodejs-MQTT document, but I couldn't enter the client connection. The client information and required parameters were carefully filled in and checked, but the test still couldn't connect the device to Google IOT Core. Can you help me see, hope
Get your answer again! Thank you

**Comment by hongalex** [comment]
You might be looking in the wrong directory for the `rsa_private.pem` file. Relative to `index.js`, it's actually in `./resources/rsa_private.pem`

**Comment by JustinBeckwith** [comment]
@radianceltd  while we are happy to help - please stop specifically @-ing people who have contributed to the repository.

**Comment by radianceltd** [comment]
OK, I want to ask the above one. I tried MQTT to connect to the device, but couldn't read the connection data. Thank you for your help!

**Comment by hongalex** [comment]
A couple things to note here:
> I get the device list in the registry under the nodejs-iot package, and it will display a list of all devices and gateways in the registry. I just want it to display a list of devices.

In both packages, list devices will list both devices and gateways (since a gateway is just a type of device). In `nodejs-iot`, you would need to construct the request slightly differently but it is possible to filter by devices only.

> Also create a gateway and bind the device to the gateway. These are not provided on nodejs-iot

Similarly, these are available. The former is done by making a `createDevice` call. Binding a device to a gateway is also [included in this library](https://github.com/googleapis/nodejs-iot/blob/c2150452cf0613a96b2c35f13f5d703a5e46d6fd/src/v1/device_manager_client.ts#L217).

If you would like specific code related to making the above calls (or help with configuring MQTT), please post the question on StackOverflow and members of our community (including myself) would be glad to help you further there.

**Comment by bcoe** [comment]
@radianceltd hopefully this has gotten you pointed in the right direction :smile:, as @hongalex suggests, let's move this conversation to StackOverflow, since it sounds like this doesn't relate to the client library.

**Comment by yeuuaeh** [comment]
@hangler Yes, if the former uses the createDevice method to obtain the device and gateway, it also takes into account the use of filtering to achieve. I can try to filter it out. (Because IOT Core has too many APIs that cannot be used like "createDevice to make a call"), but the latter, completing the steps such as client.probjects.locations.registries.list, etc., makes me unable to continue.

**Comment by radianceltd** [comment]
@bcoe  @hongalex Yes, if the former uses the createDevice method to obtain the device and gateway, it also takes into account the use of filtering to achieve. I can try to filter it out. (Because IOT Core has too many APIs that cannot be used like "createDevice to make a call"), but the latter, completing the steps such as client.probjects.locations.registries.list, etc., makes me unable to continue.

**Comment by radianceltd** [comment]
@bcoe  @hongalex  Yes, if the former uses the createDevice method to obtain the device and gateway, it also takes into account the use of filtering to achieve. I can try to filter it out. (Because there are too many IOT Core APIs that cannot be completed using "createDevice call"), but the latter cannot implement such steps as client.probjects.locations.registries.list.

**Comment by radianceltd** [comment]
@bcoe So these issues prevent me from using Google IOT Core, and publishing on StackOverflow didn't solve the problem.

**Comment by radianceltd** [comment]
Analyzed from https://github.com/googleapis/nodejs-iot, there is a direct call method (client.registryPath) on the described source code, but there are also many APIs that I see also use client.projects.locations.registries .bindDeviceToGateway method, the former method can be implemented as long as the Node.js official package provides, but the latter client has been unable to return data. Hope to get your answers again.
