### ISSUE TITLE
[Question] What is the CLIENT_SECRET in OAuth2?

### ISSUE THREAD

**Issue by baruchiro** [googleapis/google-api-nodejs-client#1930]
I created an auth key here:
![image](https://user-images.githubusercontent.com/17686879/72134043-9d416200-338b-11ea-828e-8981d706ff89.png)

Then I have a `json` file with the following fields:

```json
{
  "type": "service_account",
  "project_id": "myProject",
  "private_key_id": "12345",
  "private_key": "-----BEGIN PRIVATE KEY-----\nFooBar\n-----END PRIVATE KEY-----\n",
  "client_email": "name@project.iam.gserviceaccount.com",
  "client_id": "54321",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/name%40project.iam.gserviceaccount.com"
}
```

So what is the `CLIENT_SECRET` you mention here:
https://github.com/googleapis/google-api-nodejs-client/blob/715db840356a82724a5c5f264044bb22ff51de44/README.md#L125

**Comment by JustinBeckwith** [comment]
Greetings!  When you create an OAuth client Id, you will get a keyfile that includes a `client_id` and a `client_secret` that you would use for these samples.  It looks like you're creating a service account credential, which wouldn't have these fields.

When you're authenticating as the user on behalf of their account, as in those samples referenced above, you need to use an OAuth2 workflow.  

You want to create one of these :) 
![image](https://user-images.githubusercontent.com/534619/72215161-4c815480-34c4-11ea-92ed-65dc1370e2fa.png)

**Comment by baruchiro** [comment]
Yes, I had a "Service account key" and not "OAuth".
