### ISSUE TITLE
google.sqladmin marked as Readonly

### ISSUE THREAD

**Issue by ebower12** [googleapis/google-api-nodejs-client#1932]
#### Environment details

  - OS: MacOS Catalina
  - Node.js version: 11.8.0
  - npm version: 6.13.4
  - `googleapis` version: 46.0.0

#### Steps to reproduce

  1. `npm i googleapis`
  2. 
```
import { google } from "googleapis";
const sqladmin = google.sqladmin("v1beta4");
```
This is exactly how the documentation [here](https://googleapis.dev/nodejs/googleapis/latest/sqladmin/classes/Sqladmin.html) says to use this library, but when I try to bundle my code with webpack it throws the following error.
```
TS2349: This expression is not not callable.
Type 'Readonly<any>' has no call signatures.
```

This is preventing me from building my code. Is the documentation I found out of date, or is this actually a bug?

Thanks!

**Comment by ebower12** [comment]
Reverting to `googleapis` version 45.0.0 seems to have fixed the issue. This appears to be a bug that was introduced in the latest version.

**Comment by bcoe** [comment]
@ebower12 could you try using `sql` rather than `sqladmin`:

https://googleapis.dev/nodejs/googleapis/latest/sql/index.html

```
import { google } from "googleapis";
const sqladmin = google.sql("v1beta4");
```

Looks like they're potentially aliases of each other, and the discovery docs for `sqladmin` might have been unpublished (is my guess).

**Comment by ebower12** [comment]
@bcoe that worked and allowed me to build with v46.0.0. Thanks for the help!

**Comment by bcoe** [comment]
@ebower12 where did you find `sqladmin` linked to, I wonder if there are some docs we need to update; I don't believe it's linked to from the main index page any longer (those `sqladmin` docs would have actually been from `45.0.0`.

**Comment by JustinBeckwith** [comment]
For now, it feels like you're on the right path :) We're tracking the docs bug over in https://github.com/googleapis/docuploader/issues/25 to try and figure out why this doc still exists.
