### ISSUE TITLE
BatchUpdate copyPaste "PASTE_FORMULA" not working properly

### ISSUE THREAD

**Issue by ferrandr83** [googleapis/google-api-nodejs-client#1939]
#### Environment details

  - OS: Ubuntu 19.10
  - Node.js version: 12.14.1
  - npm version: 6.13.6
  - `googleapis` version: 46

#### Steps to reproduce

  1. Do a sheets batchupdate with a request like this:

```
sheets.spreadsheets.batchUpdate({
        spreadsheetId: spreadsheetId,
        resource: {
            requests: [
                {
                    appendDimension: {
                        sheetId: sheetId,
                        dimension: "ROWS",
                        length: 1
                    }
                },
                {
                    copyPaste: {
                        source: {
                            sheetId: sheetId,
                            startRowIndex: lastRow - 1,
                            endRowIndex: lastRow,
                        },
                        destination: {
                            sheetId: sheetId,
                            startRowIndex: lastRow,
                        },
                        pasteType: "PASTE_FORMULA",
                        pasteOrientation: "NORMAL"
                    }
                },
            ],
            includeSpreadsheetInResponse: true,
        }
    });
```

And the new row is copied with formulas and values in it.

**Comment by sofisl** [comment]
Hi @ferrandr83, I tried to reproduce your functionality but couldn't find any issues. For reference, this is the code I used:

```
const {google} = require('googleapis');

const credentials = //credentials file
const sheets = google.sheets({version: 'v4'});


async function updateSheets() {
  // Obtain user credentials to use for the request
  const auth = new google.auth.GoogleAuth({
    keyFilename: credentials,
    scopes: 'https://www.googleapis.com/auth/drive'
  });
  
  const authClient = await auth.getClient();

  const project = await auth.getProjectId();

    await sheets.spreadsheets.batchUpdate({
        auth: authClient,
        spreadsheetId: //spreadsheetId,
        resource: {
            requests: [
                {
                    appendDimension: {
                        sheetId: //sheetId,
                        dimension: "ROWS",
                        length: 1
                    }
                },
                {
                    copyPaste: {
                        source: {
                            sheetId: //sheetId,
                            startRowIndex: //startRowIndex,
                            endRowIndex: //endRowIndex,
                        },
                        destination: {
                            sheetId: //sheetId,
                            startRowIndex: //startRowIndex,
                        },
                        pasteType: "PASTE_FORMULA",
                        pasteOrientation: "NORMAL"
                    }
                },
            ],
            includeSpreadsheetInResponse: true,
        }
    });
  }

  updateSheets();
```

Would you mind trying this code, or commenting to see if there's a more specific issue you're facing?

**Comment by ferrandr83** [comment]
Hi @sofisl ,
When I execute the code above, it paste the formulas and also the values of the copied row. I think it should be paste only the formulas
Thanks

**Comment by sofisl** [comment]
Hi @ferrandr83, thanks for the quick response!

So, I have a couple of thoughts here. First, I would say that you should make sure that you are selecting only the area that you want to copy - i.e., values and formulas, or just formulas only. You can specify these ranges in the [Grid Range](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/other#GridRange) Object as much as you'd like! Second, I'd say that if your concern is that the copy-paste formula is copying over values and formulas for a specified range, even though you want it to only copy formulas without changing the range, then I think that is most likely intended functionality, given that this is how it works in the UI (i.e., if you copy and paste a selection of sheets using the "formulas only" method, it will copy over values and formulas in the selected range. The difference between this method of copying and the regular method of copying is that it specifically copies over formulas in the cells where there are formulas, vs. just copying over values in those cells). 

However, I think it would still be valuable to give your feedback to the product team if you think it should be different, or just to confirm that this is the intended functionality. To do so, simply go to [this page](https://developers.google.com/sheets/api/reference/rest) and click on the "Send Feedback" button on the bottom of the page. Then, click on "Sheets API/Product Feedback". 

Feel free to also add in what you're looking to do specifically into this comment chain - perhaps I can help you find another way to achieve what you're looking to do in the sheets API.
