### ISSUE TITLE
Are play store APIs supported by this node module?

### ISSUE THREAD

**Issue by hemantreddy** [googleapis/google-api-nodejs-client#1945]

**Comment by JustinBeckwith** [comment]
Greetings!  You can find a list of all supported APIs here:
https://googleapis.dev/nodejs/googleapis/latest/

There is an "Android Publisher API" that may get you where you want to go.  I guess it depends on what you're specifically trying to do :)  Can you include a link to the specific API you're trying to use?

**Comment by hemantreddy** [comment]
@JustinBeckwith Hey Justin, thank you so much for your time. 
This is the API I am interested in: 
https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get

**Comment by bcoe** [comment]
@hemantreddy that method should be supported [see](https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/androidpublisher/v3.ts#L6068).

Your code would look something like this:

```js
  const {google} = require('googleapis');
  const androidPublisher = google.
  const res = await google.androidpublisher('v3').purchases.subscriptions.get({
    packageName,
    subscriptionId,
    token,
  })
  const subscription = res.data
  console.log(subscription) // displays the 'acknowledgementState' field 
  subscription.acknowledgementState // property does not exist
```

:ok_hand: please let us know if this doesn't do the trick for you.
