### ISSUE TITLE
Adding attendees request parameter not working!

### ISSUE THREAD

**Issue by jawwadturabi** [googleapis/google-api-nodejs-client#1948]
I am using a service account with google calendar API to share events with friends as mentioned in the documentation. Bypassing the attendee's list as an array will add an event in all the members of the attendee's list. but when I tried to do such using the code below:

       calendar.events.insert({
        auth: serviceAccountAuth,
        calendarId: calendarId,
        resource: {
            summary: "booking",
            start: { dateTime: "2020-01-25T12:00:00+05:00" },
            end: { dateTime: "2020-01-25T13:00:00+05:00" },
            attendees: [{
                email: "jawwad***@gmail.com"
            }]
        }
    }, (err, event) => {
        err ? console.log(err) : console.log(event);
    }
    ); 

I get the following error:

`
           code: 403,
              errors: [
                {
                  domain: 'usageLimits',
                  reason: 'quotaExceeded',
                  message: 'Calendar usage limits exceeded.'
                 }
             ] 
`

I don't know why it is giving this error. When we are using direct expose APIs using access token this method is working fine but with a service account, it is not.

I'll appreciate all the feedback and updates on this issue. Thanks

**Comment by JustinBeckwith** [comment]
Adding @sqrrrl in case he has thoughts here :)

**Comment by sqrrrl** [comment]
The restriction on service accounts is relatively new (and unfortunately not well advertised) and related to abuse/spam prevention.

@jawwadturabi If you're a G Suite customer and are using this for internal use, contact support and they can whitelist your project. Or you can use the service account to impersonate users on your domain with no whitelisting required.

In other words, calendars and events are meant to be owned by users, not service accounts.

**Comment by jawwadturabi** [comment]
Oh, I get it. Can you please share any document on how to use the service account to impersonate users on the domain in my scenario. I encourage your answer. Thanks a lot for your help

**Comment by sqrrrl** [comment]
For general info, see https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority

Not sure if there are docs for the NodeJS client on this -- @JustinBeckwith might know.

Just be careful if going this route. Domain-wide delegation is very powerful and is intended for administrator/organizational use cases -- things you're automating on behalf of an organization and getting user-opt isn't an option (automating things to standardize practices, ensure compliance, etc.) Most uses of the G Suite APIs are better with the standard OAuth2 flows to get a per-user access/refresh token.

**Comment by jawwadturabi** [comment]
Thanks a lot, @sqrrrl, As I have no G suite account so that I was also thinking to use these APIs with standard OAuth2 flow by making HTTP/Rest API call. I will share the method after obtaining a successful response for this task later.

**Comment by bcoe** [comment]
@sqrrrl thanks for chiming in :smile: would it be worth adding a blurb in our README about this do you think, does this apply to a variety of products in G Suite?

**Comment by farminf** [comment]
I want to call the API from AWS Lambda and I need to use service account for that... is there any way I can add the attendees?
Thanks

**Comment by jawwadturabi** [comment]
@farminf, In general, You can't use the service account. You have to use exposed Google calendar API's along with oauth2.0 token to add attendees

**Comment by farminf** [comment]
@jawwadturabi ok. so how can I do that service-to-service? cause I want to do that from AWS lambda.

**Comment by jawwadturabi** [comment]
It is just like calling a normal API using an HTTP request or any module. Refer to this document:
https://developers.google.com/calendar/v3/reference
Select the API which one you want to use and generate oauth2.0 token. Send the bearer token in your request and get your work done.

**Comment by farminf** [comment]
@jawwadturabi but for generating the oAuth2 token I need a callback url and ... so basically a real user. right?
Lambda function is just a service. because of that, I want service-to-service

**Comment by RusseII** [comment]
I have the same quests and issues as @farminf

**Comment by jawwadturabi** [comment]
@farminf  you can use OAuth [playground](https://developers.google.com/oauthplayground/) for generating OAuth2.0 token. There is no need to generate new auth for each user.

**Comment by RusseII** [comment]
@jawwadturabi doesn't the OAuth2.0 token expire though?

**Comment by jawwadturabi** [comment]
Yes, you're right! the token will expire but you can revoke it using refresh token which you get when request with your client id and secret.

**Comment by jawwadturabi** [comment]
I think there is enough information provided about how this issue will resolve, so I am closing it.

**Comment by nizhrgorodtsev** [comment]
@jawwadturabi Could you give a code example how to use refresh token if the token is expired, please
