### ISSUE TITLE
OAuth2client calling `generateAuthUrl` with different `redirect_uri` throws an error

### ISSUE THREAD

**Issue by kuldarim** [googleapis/google-api-nodejs-client#1955]
#### Issue description

There is a need for my project to have support for different redirect urls. To be able to set cookies with auth tokens on different domains. Reading from documentation I see that when I am creating google auth client I need to pass `redirect_url` which will be used to redirect back to my service after user gives his consent.  When calling `generateAuthUrl` method I can either not pass redirect_url so then default one from constructor will be used or I can pass a different url so that instead of redirecting to one used in constructor it will redirect to the one passed in generateAuthUrl params. Which is awesome, and solves my need, but unfortunately in that case it throws an `redirect_uri_mismatch` error. 

Reading the source code it should work fine:

```
generateAuthUrl(opts = {}) {
...
  opts.redirect_uri = opts.redirect_uri || this.redirectUri;        
...
    }
```

As a workaround now I'm creating two google client instances with different redirect urls. So I think there is a bug somewhere in the client implementation, that you cannot pass a different redirect_url to `generateAuthUrl`.

#### Environment details

  - OS:
      ProductName:	Mac OS X
      ProductVersion:	10.15.2
      BuildVersion:	19C57
  - Node.js version: v10.16.3
  - npm version: 6.13.2
  - `googleapis` version: 46.0.0

#### Steps to reproduce

  1. Create a client using following code:
```
import { google } from 'googleapis';
const client = new google.auth.OAuth2(config.google.clientId, config.google.clientSecret, config.google.redirectUrl);
```
  2. Call a method to get auth url using following code:
```
const scope = ['https://www.googleapis.com/auth/userinfo.email'];
const url = client.generateAuthUrl({
      access_type: 'offline',
      prompt: 'consent',
      scope,
      redirect_uri: 'Some different url',
    });
```

3. Use the url and give google consent
4. After completing google login it throws following error:

```
Error: redirect_uri_mismatch
    at Gaxios._request (/projects/account/node_modules/gaxios/build/src/gaxios.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by bcoe** [comment]
@kuldarim thanks for the bug report, I'm glad you have a workaround for the time being.

Quick question, have you added both redirect URIs in the configuration for your OAuth application? The OAuth client ID you've created must have both redirect URIs.

**Comment by kuldarim** [comment]
@bcoe Yes I have configuration for both urls in google console. Besides it would throw a different error if I wouldn't have configured the urls.

**Comment by JustinBeckwith** [comment]
Greetings @kuldarim!  Are you still having trouble here?  I am trying to figure out what you're seeing.  The url that gets generated from `generateAuthUrl`, is it encoding the `redirect_uri` you expect?  I am guessing that function works properly, and redirects you to the Google login.  I am guessing the login works, and that you get redirected back to the correct redirect Uri.  What's not clear to me is exactly what code is running when you get this error:

```js
Error: redirect_uri_mismatch
    at Gaxios._request (/projects/account/node_modules/gaxios/build/src/gaxios.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Where is that callstack coming from?  Are you calling the `oauth2client.getToken` method?  If so, are you passing the `redirect_uri` you expect to use in the get token options?
