### ISSUE TITLE
Does it supports the querying options as it does in version 3

### ISSUE THREAD

**Issue by vinodhreddygs** [googleapis/google-api-nodejs-client#1960]
Hi,

I'am trying to get row/record on Querying with conditions.
i.e. I have number of records in a google sheet with header names Emp Name, Emp ID, Emp Place etc.
I'am trying to get the employee record and then, update who's Emp ID is 6258. But its fails.

Thanks in advance.

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share:
- What code you tried
- Any error messages you got?

**Comment by vinodhreddygs** [comment]
@JustinBeckwith Querying options not supporting in the Google API version 4.
