### ISSUE TITLE
google my bussines  api support

### ISSUE THREAD

**Issue by Zimovets** [googleapis/google-api-nodejs-client#1961]
Does the api support google my bussines api? can't find examples or docs

**Comment by bcoe** [comment]
@Zimovets it doesn't look like we are currently able to generate a client for the business API. We automatically generate clients for any libraries listed in the discovery index (the full list is [here](https://github.com/googleapis/google-api-nodejs-client/tree/master/src/apis)). My hunch is that My Business is not indexed here.

**Comment by JustinBeckwith** [comment]
Greetings!  This is a duplicate of https://github.com/googleapis/google-api-nodejs-client/issues/1303, so closing this one out.  Please follow along over there!
