### ISSUE TITLE
Strange ACL behaviour

### ISSUE THREAD

**Issue by t5unamie** [googleapis/google-api-nodejs-client#1965]
I don't know if this is a feature request or a bug.

 

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: -  Docker image node:13.8.0 - debian
  - Node.js version: 13.8.0
  - "googleapis": "^47.0.0",

#### Steps to reproduce

Use the online API tester
 https://developers.google.com/calendar/v3/reference/acl/insert
I enter the correct calendar ID and the correct user/scope.

The following JSON is put in
```
{
  "role": "writer",
  "scope": {
    "type": "user",
    "value": "ABCDEFG@example.com"
  }
}
```

The API responds with 200 everything is okay. However, when I go into the calendar it's blank. The email has not been added.

When I use the NodeJS call, it does the same thing. Google does register the ACL update however does not show it in the console on the calendar. When I add the email address in manually via the console. It asks me in a pop up if I am sure I want to add the user. As the user does not have a google calendar. When I click yes, it then shows the email address on the list.

I suspect the following.

Unless the email address has an active google account it doesn't show the email in the list. Until they click on the link sent to the email?

What's strange is I click on the email in the account that did not have a calendar and nothing happens. Is there no way to force the showing of the listing in the API?

**Comment by bcoe** [comment]
:wave: thanks for opening the bug report @t5unamie. This sounds like it's most likely related to the upstream API, and not to the client library itself, it might be worth also opening a customer support issue: https://support.google.com/calendar.

**Comment by t5unamie** [comment]
created the following - https://support.google.com/calendar/thread/29269652?hl=en

**Comment by JustinBeckwith** [comment]
Looks like you made it to the right place :) Closing this out!
