### ISSUE TITLE
'resource' does not exist in type 'Params$Resource$Spreadsheets$Batchupdate'.

### ISSUE THREAD

**Issue by francoisromain** [googleapis/google-api-nodejs-client#1966]
#### Environment details

  - OS: Mac Os 10.13.6
  - Node.js version: v13.8.0
  - npm version: 6.13.7
  - `googleapis` version: 47.0.0

#### Steps to reproduce

I try to convert this code (from the official docs: https://developers.google.com/sheets/api/guides/batchupdate) to typescript: 
```js
gapi.client.sheets.spreadsheets.batchUpdate({
  spreadsheetId: spreadsheetId,
  resource: batchUpdateRequest
})
```
It makes the following error: 
```
Argument of type '{ spreadsheetId: string; resource: { requests: any; }; }' is not assignable to parameter of type 'Params$Resource$Spreadsheets$Batchupdate'.

Object literal may only specify known properties, and 'resource' does not exist in type 'Params$Resource$Spreadsheets$Batchupdate'.
```

(Actually here is the file I am trying to convert to ts, where I have this error: https://github.com/MTES-MCT/camino-api/blob/89a8a764177c5efda57a7154b6ffd936f63afee9/src/tools/api-google-spreadsheets/index.js#L22)

what should I do to avoid the error? 

Thank you

**Comment by JustinBeckwith** [comment]
Greetings!  It looks like this may be coming from an old tutorial.  Instead of `resource`, can you try `requestBody`?
https://github.com/googleapis/google-api-nodejs-client#specifying-request-body

Let us know if this helps!

**Comment by francoisromain** [comment]
thank you

**Comment by nachocab** [comment]
> Greetings! It looks like this may be coming from an old tutorial. Instead of `resource`, can you try `requestBody`?
> https://github.com/googleapis/google-api-nodejs-client#specifying-request-body
> 
> Let us know if this helps!

I can still see `resource` being used in the [official documentation](https://developers.google.com/drive/api/v3/manage-uploads#node.js). Is it just a synonym for `requestBody`? And, just curious, how does this work? I don't see the synonym specified anywhere.

**Comment by nachocab** [comment]
@JustinBeckwith Also, same thing for `uploadType` ([official sample](https://developers.google.com/drive/api/v3/manage-uploads#multipart)) when creating a new file. Is this parameter no longer required? You provided [this sample](https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/drive/upload.js#L35). Is providing `requestBody` enough for multipart? If I want a simple upload, do I need to specify `uploadType`?

**Comment by cuginoAle** [comment]
thanks @francoisromain.
just wanted to let you know that the official docs are still not up to date (12/12/22) and this causes confusion to people familiarising with the APIs: https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/update

thanks!

**Comment by cuginoAle** [comment]
thanks @JustinBeckwith and @francoisromain ,
Just wonted to let you know that the official docs are still not up to date, causing confusion to people familiarising with the APIs:
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/update


cheers

**Comment by albertosanmartin** [comment]
The official [doc](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#resource:-spreadsheet) accept this [type](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#spreadsheetproperties) that contains "title" attribute but I still receiving the following error:

    16.53 src/controllers/campaign/campaign-session.controller.ts(396,32): error TS2769: No overload matches this call.
    16.53   Overload 1 of 6, '(params: Params$Resource$Spreadsheets$Create, options: StreamMethodOptions): GaxiosPromise<Readable>', gave the following error.
    16.53     Type '{ properties: { title: string; }; }' has no properties in common with type 'Params$Resource$Spreadsheets$Create'.
