### ISSUE TITLE
Unable to download file using drive APIs TypeError: drive.files.get(...).pipe is not a function

### ISSUE THREAD

**Issue by 839998664** [googleapis/google-api-nodejs-client#1971]
I am trying to download a pdf document from drive. Update it locally and then upload the updated document back into the drive. The api documentation shows that I can pipe the get request to a writeable stream. But I am getting an error that pipe is not a function. Tried looking around for a solution finally came across this and thought of asking for help here.

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share a small example of the code you're using?

**Comment by 839998664** [comment]
Greetings!
I am using below snippet from the documentation...
```javascript
let drive = google.drive({ version: 'v3', auth });
let dest = fs.createWriteStream(path.join(__dirname, '../temp/', filename));
 drive.files.get({
         fileId: fileId,
         alt: 'media'
 })
.on('end', function () {
      console.log('Done');
})
.on('error', function (err) {
      console.log('Error during download', err);
 })
.pipe(dest);
```

**Comment by JustinBeckwith** [comment]
Got it - can you share the doc where you're finding this?  This is a far better example:
https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/drive/download.js

**Comment by 839998664** [comment]
I found this at
[https://developers.google.com/drive/api/v3/manage-downloads](https://developers.google.com/drive/api/v3/manage-downloads) 
Thanks for pointing me to another example...Will take a look at it...

**Comment by 839998664** [comment]
Ok, the example at the new Url provided works for me...Thanks a lot...

**Comment by Hermogenes00** [comment]
Sei que faz tempo, mas talvez ajude alguma outra pessoa....
` drive.files.get({
            fileId: fileId,
            alt: 'media'
        }).then(result => {
            console.log(result);
        }).catch(err=>{
            console.log(err);
        })`

Como pode ver, está retornando uma promisse.

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.

**Comment by fachryansyah** [comment]
write new issue to update this article may help other developer
https://developers.google.com/drive/api/v3/manage-downloads#node.js
