### ISSUE TITLE
How to call drive.files.list synchronously? 

### ISSUE THREAD

**Issue by JoeCodeswell** [googleapis/google-api-nodejs-client#1980]
Currently the [Node.js Quickstart](https://developers.google.com/drive/api/v3/quickstart/nodejs)
has [Sample Code](https://developers.google.com/drive/api/v3/quickstart/nodejs#step_3_set_up_the_sample) that makes a call to `drive.files.list` with *Fat Arrow Function* callbacks.

Please post similar code so that I can call the function synchronously, i.e. in a blocking manner. Preferably using `async` and `await`. 
Thanks.

Love and peace,
Joe Dorocak
aka JoeCodeswell@gmail.com

**Comment by JustinBeckwith** [comment]
Greetings!  You likely don't truly want to make a call like this synchronously... and you can't!  That would block the entire node.js event loop, and cause a lot of problems on any web server.  Using `async/await` is still very much asynchronous, it's just using a non-callback approach to managing the asynchronicity.

If it's `async/await` you're looking for .... I got you:
https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/drive/list.js

Hope this helps!

**Comment by JoeCodeswell** [comment]
Thanks so much, Justin.
Love and peace,
Joe
