### ISSUE TITLE
Cannot set JSON Patch on FHIR resource with Content-Type set

### ISSUE THREAD

**Issue by bcoe** [googleapis/google-api-nodejs-client#1987]
This results in the inability to use some methods in the healthcare API.

**Comment by vaiol** [comment]
Have the same issue.
Unable to set `'Content-Type': 'application/json-patch+json'` header and `healthcare.projects.locations.datasets.fhirStores.fhir.patch` method give next error:
```
{
  "issue": [
    {
      "code": "structure",
      "details": {
        "text": "invalid_headers"
      },
      "diagnostics": "patching a FHIR resource requires the content type to be: application/json-patch+json",
      "severity": "error"
    }
  ],
  "resourceType": "OperationOutcome"
}
```

**Comment by cmanzi-microdrop** [comment]
This doesn't seem like a very good solution. Having to set the headers in the SDK globally every time we make do a PATCH operation is very cumbersome. Shouldn't the FHIR client handle setting this header for us? Is there a better way to handle this issue on a per-request basis right now?
