### ISSUE TITLE
google calendar api - check if a calendar is being watched

### ISSUE THREAD

**Issue by zachi** [googleapis/google-api-nodejs-client#1992]
is there an api for checking if a calendar is being watched? or getting s list of all watched calendars for my Google API project?

**Comment by grant** [comment]
Hi Zachi, good question.
Unfortunately, there is no API method that checks if a calendar is being watched. A consumer must manually track that information. It could also be a privacy issue to be able to see all information about various users watching a common calendar.

Only users with the right permission can create watch channels in the first place, so it shouldn't be an issue. When creating a channel, you specify a TTL, which defaults to 3600 seconds. You may also see a `X-Goog-Channel-Expiration` header, or you can manually stop the watch channel as ways to understand if a channel watch status has changed.

There is more information here:
https://developers.google.com/calendar/v3/push

Hope that helps!
