### ISSUE TITLE
Question: Why does certain fhir functions don't require a parent in the params object

### ISSUE THREAD

**Issue by JoelV** [googleapis/google-api-nodejs-client#1997]
I'm working with the healthcare.projects.locations.datasets.fhirStores.fhir functions.

Why does healthcare.projects.locations.datasets.fhirStores.fhir.create require a parent key to build the rul (https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/healthcare/v1beta1.ts#L9497), 
while 
healthcare.projects.locations.datasets.fhirStores.fhir.update(https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/healthcare/v1beta1.ts#L10700) only require a name key in which we will have to include the url 

Let me know if you need me to show some examples

**Comment by bcoe** [comment]
@JoelV 👋 this API is auto-generated from the upstream healthcare API, it might be giving some feedback to the team [here](https://cloud.google.com/healthcare/docs/getting-support), my hunch is there are actually some discrepancies in the parameters the API accepts.

**Comment by JoelV** [comment]
Got it thanks!!!
