### ISSUE TITLE
Question: Is is possible to partially load the library?

### ISSUE THREAD

**Issue by oltreseba** [googleapis/google-api-nodejs-client#2000]
I'm using googleapis in my project, but i'm using only a couple of services from it. (I guess this is quite a common use case).

Importing googleapis, require (on my machine) between 500ms and 1000ms.

I'm building an electron app with several webworkers that are requiring google apis. Currently the main thread require google APIs after the startup, but still the main thread is going to be blocked for 500-1000ms.

I'm wondering if there is a simple way to:
a) only require the necessary services
or
b) rebuild the library only with the necessary services (possibly without forking and rebuilding from scratch).

Thank you

**Comment by bcoe** [comment]
👋 @oltreseba it's not currently possible to do so, but we'd like to move towards publishing each library individually.

There's a tracking issue [here](https://github.com/googleapis/google-api-nodejs-client/issues/806) It's just a matter of prioritizing the work.

Please feel free to add your +1 on the issue I linked.
