### ISSUE TITLE
Get youtube stream key

### ISSUE THREAD

**Issue by abhishek0196** [googleapis/google-api-nodejs-client#2001]
Hey, I was trying to get the youtube live stream key using node js, but I do not see any updates on any portal regarding this, or any clear navigation on how to get the key, please help me out.

**Comment by JustinBeckwith** [comment]
Greetings!  I took a quick look, but it doesn't look like the stream key is exposed via the YouTube API here:
https://developers.google.com/youtube/v3/live/docs/liveStreams/list

This npm module can only really return what's available in the underlying API :/

It may be worth asking how to do this with the underlying API here!
https://stackoverflow.com/questions/tagged/youtube-api

Best of luck!
