### ISSUE TITLE
Bug in apirequest for JS files.

### ISSUE THREAD

**Issue by giorod3** [googleapis/google-api-nodejs-client#2002]
- OS: Mac OS
  - Node.js version: 10
  - npm version: 6.4.1
  - `googleapis-common` version: 2.0.4

#### Steps to reproduce

  1. Running the logging api and entries:list call in JS

```js
let authClient =
    params.auth ||
    parameters.context._options.auth ||
    (parameters.context.google
      ? parameters.context.google._options.auth
      : null);
```

if parameters.context._options is null the operation breaks. I have created a fix for it and will create a Pull Request ASAP.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by JustinBeckwith** [comment]
Thanks!  Looking closer at that code ... that's a bit of a strange way to interact with the API.  Could I trouble you to follow a method more similar to what's in the README?:
https://github.com/googleapis/google-api-nodejs-client#service-to-service-authentication

Specifically, a few things to call out:
- You don't need to use `[ ]` to access properties.  You can just use `google.logging` for example!
- The list of parameters you're passing into the `logging.entries.list` method do not look right.  It looks like you're trying to pass auth metadata.  

The guide I linked to above goes into detail on how to manage authentication for a service to service scenario like this one.  Please let us know if you have any other questions!
