### ISSUE TITLE
get sample for google fit API

### ISSUE THREAD

**Issue by rahulj3716** [googleapis/google-api-nodejs-client#2007]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

**Comment by JustinBeckwith** [comment]
Greetings!  You can find all methods available, along with samples for how to use them here:
https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/fitness/v1.ts#L1816

If you run into specific problems, please let us know:
- What code you tried
- What errors you're getting

Thanks!
