### ISSUE TITLE
Google Drive api v3 gives untitled as file name after uploading to drive

### ISSUE THREAD

**Issue by fazilsk619** [googleapis/google-api-nodejs-client#2008]
Angular 8 - Node.js

let exportfile = "/Users/Documents/Testzipcheck.zip";
let readfile = this.service.FS.createReadStream(exportfile);
var self = this; 
var fileMetadata = {
      name: 'Test123'
    };

    var media = {
      mimeType: 'application/zip',
      body: readfile
    };
let drive = google.drive({
      version: 'v3',
      auth: self.Service.oauth2Client
    });

    drive.files.create({
      request: fileMetadata,
      media: media,
      fields: '*'
    }, function (err, file) {
      if (err) {
        // Handle error
        console.error(err);
      } else {
        console.log('File : ', file);
      }
    });

#### Environment details

  - OS: OS X 10.11.6 
  - Node.js version:v10.16.0
  - npm version:6.9.0
  - `googleapis` version:^48.0.0

Steps to reproduce
1)uploading a zip file to drive , create's a untitled zip file in drive ,Tried with even a simple json file with mimeType: 'application/json', but still it gives untitled Name for the uploaded file

it will be really helpful  if there is a way to update the title of the uploading file ,or if it's a bug,please update it at the earliest.

Thank you

**Comment by JustinBeckwith** [comment]
Greetings!  The callback from that method is going to be a `Response` object :) Could you try:

```js
drive.files.create({
  request: fileMetadata,
  media: media,
  fields: '*'
}, function (err, res) {
  if (err) {
    // Handle error
    console.error(err);
  } else {
    console.log(res.data);
  }
});
```

**Comment by fazilsk619** [comment]
> Greetings! The callback from that method is going to be a `Response` object :) Could you try:
> 
> ```js
> drive.files.create({
>   request: fileMetadata,
>   media: media,
>   fields: '*'
> }, function (err, res) {
>   if (err) {
>     // Handle error
>     console.error(err);
>   } else {
>     console.log(res.data);
>   }
> });
> ```

Thanks for your suggestion, But i am getting proper response from Both either it may be  File or res as parameter, the actual issue is After finishing upload when i check in the google Drive opened in the browser ,the file shows as untitled, even though i have given proper name in the fileMetadata while uploading.

**Comment by cvjude** [comment]
I have a similar issue, I don't know if I'm doing anything wrong
```
async function upload(file) {
    const fileSize = file.size;

    const response = await gapi.client.drive.files.create(
      {
        request: {
          name: file.name,
          mimeType: file.type,
          // parents: ['1RExy32fq9fIAx--lKTlOcEVrTjyHm5WJ'],
        },
        media: {
          body: file,
          mimeType: 'application/octet-stream',
        },
      },
      {
        // Use the `onUploadProgress` event from Axios to track the
        // number of bytes uploaded to this point.
        onUploadProgress: (evt) => {
          const progress = (evt.bytesRead / fileSize) * 100;
          console.log(progress);
        },
      }
    );
    // log the result
    console.log(response.data);
    console.log(
      `\nstatus: ${response.status}, text status: ${response.statusText}`
    );
  }
```

I get the file from an input form and call like this
```
upload(files[0])
```

**Comment by fhinkel** [comment]
Hi @fazilsk619 , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google Drive API tag](https://stackoverflow.com/questions/tagged/google-drive-api?tab=Newest) is most appropriate for general troubleshooting.
* [Google Drive API's public issue tracker](https://developers.google.com/drive/api/v3/support)

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!
