### ISSUE TITLE
Node

### ISSUE THREAD

**Issue by joaocastro125** [googleapis/google-api-nodejs-client#2009]
Estou tentando execultar no node mais esta dando erro no servidor da certo mais no postman esta dando errdado 
O codigo esse 

duvida no node
0
João emanoel de Souza Araújo · Aula 142 · há 19 horas
professor nao estou  conseguindo execultar no get da certo ja no post nao da esse essa aki 

no get da certo agora no post esta dando esse erro pode me ajudar  
key              value 
nome             notebook 
preco             1259.99
 
 
<!DOCTYPE html>
<html lang="en">
 
<head>
    <meta charset="utf-8">
    <title>Error</title>
</head>
 
<body>
    <pre>TypeError: Converting circular structure to JSON<br> &nbsp; &nbsp;--&gt; starting at object with constructor &#39;Object&#39;<br> &nbsp; &nbsp;--- property &#39;1&#39; closes the circle<br> &nbsp; &nbsp;at JSON.stringify (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at stringify (C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\response.js:1119:12)<br> &nbsp; &nbsp;at ServerResponse.json (C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\response.js:260:14)<br> &nbsp; &nbsp;at ServerResponse.send (C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\response.js:158:21)<br> &nbsp; &nbsp;at C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\src\servidor.js:25:9<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\router\route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\router\route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at C:\Users\joaoc\Desktop\curso moderno da 
 
 
no visual code esse  
 
 
no servidor da certo so no postman que esta dando erro   
 
 
 
onst porta = 3003
 
 
const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const bancoDeDados = require('./bancoDeDados')
 
app.use(bodyParser.urlencoded({ extended: true }))
 
app.get('/produtos', (req, res, next) => {
    res.send(bancoDeDados.getProdutos()) //vai converter para json 
 
})
app.get('/produtos/:id', (req, res, next) => {
    res.send(bancoDeDados.getProduto(req.params.id))
})
 
app.post('/produtos', (req, res, next) => {
    const produto = bancoDeDados.salvarProduto({
        nome: req.body.name,
        preco: req.body.preco
 
    })
    res.send(produto) // converter em json 
})
 
app.listen(porta, () => {
    console.log(`servidor excultando na porta ${porta}`)
})
 
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `node src/servidor.js`
servidor excultando na porta 3003
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property '1' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\response.js:1119:12)  
    at ServerResponse.json (C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\response.js:260:14)
    at ServerResponse.send (C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\response.js:158:21)
    at C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\src\servidor.js:25:9
    at Layer.handle [as handle_request] (C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\router\route.js:137:13)    
    at Route.dispatch (C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\joaoc\Desktop\curso moderno da web\node\projeto\node_modules\express\lib\router\index.js:281:22

**Comment by bcoe** [comment]
@joaocastro125 👋 looking at this stack trace, it looks like the issue you're bumping into is being thrown by the library [express](https://github.com/expressjs/express).

At a glance, this error is usually caused by trying to serialize a complex object that has references to itself, e.g.,

```js
const a = {
  a: b  
}
const b = {
  b: a
}
```

When sending responses with express, I recommend you create a new object and send it, rather than serializing the response from a library.
