### ISSUE TITLE
google-api-nodejs-client/samples/drive/copy

### ISSUE THREAD

**Issue by gianpieromarcacci** [googleapis/google-api-nodejs-client#2014]
Is it possible to upload a sample of google-api-nodejs-client/samples/drive/copy API with the async/await mode ? 

Thanks very much!!!

**Comment by JustinBeckwith** [comment]
Greetings!  Of course it is :) What did you try?  Did you run into any issues?  I suggest starting with this sample:
https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/drive/quickstart.js

And then using this guide for the specific fields you need:
https://developers.google.com/drive/api/v3/reference/files/copy
