### ISSUE TITLE
Google group api

### ISSUE THREAD

**Issue by cmplayMC** [googleapis/google-api-nodejs-client#2024]
I have been trying to make a script in nodejs to take a email and add it to google groups by the api and delleting it after a time i couldn't get it working i have tried everything but could not get it to work any help would be good

thanks in advainc.

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share the code you've tried, and any errors you're getting?  For inserting members, please read:
- https://developers.google.com/admin-sdk/directory/v1/reference/members/insert
- https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/admin/directory_v1.ts#L7158

For deleting members:
- https://developers.google.com/admin-sdk/directory/v1/reference/members/delete
- https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/admin/directory_v1.ts#L6796

Let us know how it goes!
