### ISSUE TITLE
pathParams in Service-client options don't persist

### ISSUE THREAD

**Issue by JacobDorman** [googleapis/google-api-nodejs-client#2029]
#### Environment details

  - Node.js version: `v12.11.1`
  - npm version: `6.14.4`
  - `googleapis` version: `48.0.0`

#### Steps to reproduce
https://github.com/googleapis/google-api-nodejs-client#service-client-options
```js
const gmail = google.gmail({
  version: 'v1',
  auth,

  params: {
    userId: 'me',
  },
})

await gmail.gmail.users.labels.list()
await gmail.gmail.users.labels.list()
```

userId is used in the url `pathParams: ['userId']`, so it is deleted from `Gmail.context` by [googleapis-common](https://github.com/googleapis/nodejs-googleapis-common)

https://github.com/googleapis/nodejs-googleapis-common/blob/0e6d3cfcc89712e2a75ed33ce8ba476b53275016/src/apirequest.ts#L210-L221
```js
  // delete path parameters from the params object so they do not end up in
  // query
  parameters.pathParams.forEach(param => {
    delete params[param];
    if (
      parameters.context &&
      parameters.context._options &&
      parameters.context._options.params
    ) {
      delete parameters.context._options.params[param];
    }
  });
```

related: https://github.com/googleapis/nodejs-googleapis-common/pull/147

**Comment by bcoe** [comment]
@JacobDorman sounds like a bug. Can you workaround by providing the parameter in each list operation?
