### ISSUE TITLE
How to pass multiple parent ids in a File list query

### ISSUE THREAD

**Issue by anjali89r** [googleapis/google-api-nodejs-client#2060]
Currently, I'm getting the file names of a folder in nodejs API using below code,
```js
service.files.list(
    {
      auth: auth,
      pageSize: 1000,

      q: "'folderid' in parents",
 fields: 'nextPageToken, files(id, name,parents)'})
```

Now I have requirement to do the check for multiple folder ids and is not able to figure out what is the right syntax to pass multiple folderids in the same query.
Something like this is not working,
```js
service.files.list(
    {
      auth: auth,
      pageSize: 1000,

      q: "['folderid',folderid2'] in parents",
 fields: 'nextPageToken, files(id, name,parents)'})`
```

**Comment by JustinBeckwith** [comment]
Greetings!  I don't have any inside knowledge, but looking at this page:
https://developers.google.com/drive/api/v3/search-files

It looks like you can use `or` in the q field.  Have you tried something like:

```
q: "'folderid in parents or 'filderid2' in parents"
```

**Comment by anjali89r** [comment]
works thanks!

**Comment by aykxt** [comment]
> Greetings! I don't have any inside knowledge, but looking at this page: https://developers.google.com/drive/api/v3/search-files
> 
> It looks like you can use `or` in the q field. Have you tried something like:
> 
> ```
> q: "'folderid' in parents or 'filderid2' in parents"
> ```

Seems like this doesn't work anymore, I'm getting an empty error as response.
