### ISSUE TITLE
Update & Delete API in Google Sheet

### ISSUE THREAD

**Issue by mddanishyusuf** [googleapis/google-api-nodejs-client#2083]
**Is your feature request related to a problem? Please describe.**
I'm using nodejs library for sheet API and there is no documentation about Update a row or delete a row.

 **Describe the solution you'd like**
I just need API documentation for Update & delete.

 **Describe alternatives you've considered**
this project supports update & delete https://www.npmjs.com/package/google-spreadsheet 

 **Additional context**
:)

**Comment by sofisl** [comment]
Hi @mddanishyusuf, have you looked at the documentation for the sheet API? Here's some info on [updating a row](https://developers.google.com/sheets/api/guides/values) and [deleting ](https://developers.google.com/sheets/api/samples/rowcolumn
) rows. Please feel free to send along your specific use-case or specific documentation request that you cannot find. 

Thanks in advance!

**Comment by mddanishyusuf** [comment]
```
requests.push({
  findReplace: {
    find,
    replacement,
    allSheets: true,
  },
});
// Add additional requests (operations) ...
const batchUpdateRequest = {requests};
this.sheetsService.spreadsheets.batchUpdate({
  spreadsheetId,
  resource: batchUpdateRequest,
}, (err, response) => {
  if (err) {
    // Handle error
    console.log(err);
  } else {
    const findReplaceResponse = response.replies[1].findReplace;
    console.log(`${findReplaceResponse.occurrencesChanged} replacements made.`);
  }
});
```

Finding into any direction and updating. In my use case, I wanna update one-row values in time.

**Comment by mddanishyusuf** [comment]
Note: Finally, I'm able to do the update and deletion hack according to my use-case.

Thanks
