### ISSUE TITLE
TypeScript interface Schema$Channel field 'expiration' type mismatch.

### ISSUE THREAD

**Issue by Kyeong-min** [googleapis/google-api-nodejs-client#2089]
#### Environment details

  - OS: Ubuntu 18.04 LTS
  - Node.js version: 6.14.4
  - npm version: 12.16.3
  - `googleapis` version: 50.0.0

#### Steps to reproduce

Same as the title.

In TypeScript, the type of "expiration" of the interface field in response to a push notification request is different from the document.

For example
https://developers.google.com/calendar/v3/reference/events/watch

The expiration value type described in the Response section of the above document is long.

However, in the actual v3.d.ts file interface definition, the expiration declared in the Schema $ Channel interface is of type string | null.

thanks.

**Comment by JustinBeckwith** [comment]
Taking a closer look at this one - the type in the discovery document that dictates the data type is typically the `type` field.  As far as I can tell, the `format` field calls out how the field will be converted into protobuf fields in the API backend.  

The `type` fields are generally simple types like:
- `string`
- `array`
- `boolean`
- `object`
- `integer`
- `any`

The `format` field includes fields such as:
- `google-datetime`
- `google-duration`
- `google-fieldmask`
- `date-time`
- `int32`
- `uint32`
- `int64`
- `uint64`
- `double`
- `byte`
- `float`

At the end of the day, these formatted fields need to be represented as JSON when it goes over the wire.  It may be possible to accept values with the `format` types, and go through some sort of translation to the JSON types needed for transport.

**Comment by mpsijm** [comment]
How does this issue relate to #2405? Based on the response there, I'd say this issue could be closed as well, right?

**Comment by sofisl** [comment]
I agree. I think this is a duplicate, [this is the correct answer](https://github.com/googleapis/google-api-nodejs-client/issues/2405#issuecomment-721512809). Apologies that this appears to be confusing documentation. It seems that the Unix timestamp should be passed as a string given the JS MAX_SAFE_INTEGER constraints.
