### ISSUE TITLE
Classroom API access to comments of students in courseWorks

### ISSUE THREAD

**Issue by xavis** [googleapis/google-api-nodejs-client#2091]
I'm developing a NodeJS app that wants to retrieve information from Google Classroom. After checking the API and making some tests I found that it's not possible to access students' and teachers' private or public comments of the courseworks... 

Is there any way to access this messages from NodeJS SDK or REST API? 
I think that professors should be able to recover this comments in a custom software, it would not be a problem if teachers should identify theirselves through the app.

Thank you.

**Comment by AncestorHunter06** [comment]
**PSA: I am a beginner/newbie to coding and the like***

Although I am still new to this, I figured I would share some resources that I've been perusing, that may be able to provide you with an answer. 
I have read within the Google api and App Scripts that there is a prior auth that has to be implemented for any app wanting access to google accounts/ apps. I don't know if that helps or not.

[REST Resources | Google Classroom](https://developers.google.com/classroom/reference/rest/v1/courses) 

[Authorizing Requests | Google Classroom API](https://www.google.com/url?sa=t&source=web&rct=j&url=https://developers.google.com/classroom/guides/auth&ved=2ahUKEwjs7sS90qfpAhV0mHIEHSOfDSgQFjACegQICBAB&usg=AOvVaw0D_0We8TTQM7dMZ16wB2Qy&cshid=1589056988045) 

Happy coding!

**Comment by xavis** [comment]
@AncestorHunter06 thank you for the information. But it was after checking those link that I found that there is no function or endpoint retrieve the students comments :/

**Comment by JustinBeckwith** [comment]
Greetings folks!  This library exposes 100% of the underlying APIs that are available.  At the end of the day, we can really only help out with issues specific to the nodejs wrapper, not the API itself.  If you'd like to request additional endpoints, I'd suggest filing an issue in the classroom API feedback tracker here:
https://code.google.com/a/google.com/p/apps-api-issues/issues/list?can=2&q=label%3AAPI-Classroom

Hope this helps!
