### ISSUE TITLE
Don't require auth to pull sheet data when using public access link

### ISSUE THREAD

**Issue by SephReed** [googleapis/google-api-nodejs-client#2103]
Not sure if this a feature yet or not.  

 **Is your feature request related to a problem? Please describe.**
The following instructions imply the only way to pull a sheet is to get authenticated first:

https://developers.google.com/sheets/api/quickstart/nodejs

For reading public sheets, this is more work than is necessary.  Doubly so to only grant access to a short list of sheets.

 **Describe the solution you'd like**
I'd rather just create a public access link and pass that in.  

 **Describe alternatives you've considered**
Creating a separate user, giving that user access to certain sheets, using them for auth.  Spending a day figuring out why it's not working.

 **Additional context**
If you want users to play with the apis you make, make sure there are fun things that can be done without tedius setup requirement.  ie:
```
import { readSheet} from "google-api";

const rawCsvText = await readSheet("https://docs.google.com/spreadsheets/d/1324publiclinktosheet1234/edit#gid=0");

// immediately start having fun
```

For over a year now I've just been downloading sheets manually because I don't want to deal with whatever insane Auth system exists to protect Google security.  I'm not sure, but I have strong reason to suspect it's not going to be just a simple bearer token or something else easy.

**Comment by JustinBeckwith** [comment]
Greetings!  And thanks for the request :) This library can really only expose features that the server supports.  For feature requests against the Google Sheets API itself, this is the best place to start:
https://developers.google.com/sheets/api/support#missing_features

The good news is, this could possibly be much easier.  This doc outlines the auth methods supported by the API:
https://developers.google.com/sheets/api/guides/authorizing

It looks like the API supports API keys, which are _a lot_ easier to deal with.  Hope this helps!
