### ISSUE TITLE
Chunk upload large file with multiple requests

### ISSUE THREAD

**Issue by taducquang** [googleapis/google-api-nodejs-client#2114]
**Is your feature request related to a problem? Please describe.**
Im having a trouble with uploading large files, the upload speed is too slow due to only 1 upload request being used and result in slow upload speed. 

 **Describe the solution you'd like**
I would love to upload large file using multiple requests to upload chunks files in resumable like in this guide to achieve maximum upload speed.
https://developers.google.com/drive/api/v3/manage-uploads#http---multiple-requests
But im not sure how to make multiple requests in nodejs.

Hope if anyone can help me with this.

**Comment by JustinBeckwith** [comment]
Greetings!  To support this, we would need to add the resumable upload protocol.  We're tracking that over here:
https://github.com/googleapis/google-api-nodejs-client/issues/276

I'm going to close this out for now - please follow that other issue for updates!
