### ISSUE TITLE
discovery-artifact-manager failing

### ISSUE THREAD

**Issue by broady** [googleapis/google-api-nodejs-client#2120]
![image](https://user-images.githubusercontent.com/24982/82377262-45b99f80-99d8-11ea-9556-71632cb69b01.png)

**Comment by broady** [comment]
Cron job dashboard:
https://pantheon.corp.google.com/appengine/cronjobs?project=discovery-artifact-manager&organizationId=433637338589

**Comment by JustinBeckwith** [comment]
I have no idea how these are related.  Context?

**Comment by JustinBeckwith** [comment]
Chatted with @broady - we do not rely on these jobs at all in nodejs for generating libraries or releasing them.  All of that today is handled with synth tool and release-please.
