### ISSUE TITLE
Samples don't work

### ISSUE THREAD

**Issue by bbourn** [googleapis/google-api-nodejs-client#2125]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-nodejs-client/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `googleapis` version:

#### Steps to reproduce

  1. ?
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  If you're having issues, please answer the questions in the issue template above :)

**Comment by bbourn** [comment]
Following directions for samples gives me "Error: Unable to detect a Project Id in the current environment."

Can't find any documentation to get past this error.

**Comment by bbourn** [comment]
I just want to be able to manipulate as spreadsheet.  I fully expected an npm that I can drop into node like   
import sheet from 'fullOfSheet'

const mySheet = sheet()

And have the module deal with EVERYTHING!  Like browsing local files, google drives, sheet url shares, etc.   A full component like auth0 that handles EVERYTHING.

**Comment by bbourn** [comment]
Why did you close my issue?  It persists.

B-(
