### ISSUE TITLE
Google APIs Node.js Client: Node.js Samples - default auth Project ID missing

### ISSUE THREAD

**Issue by bbourn** [googleapis/google-api-nodejs-client#2126]
#### Environment details

  - OS: Google Cloud Shell
  - Node.js version: Google Cloud Shell
  - npm version: Google Cloud Shell
  - `googleapis` version: Google Cloud Shell

#### Steps to reproduce

  1. Goto samples page: https://github.com/googleapis/google-api-nodejs-client/tree/master/samples
  2. Click "open in cloud shell" for default auth.
  3. cd samples
  4. npm install
  5. cd ..
  6. node samples/defaultauth.js

ERROR:
Error: Unable to detect a Project Id in the current environment.

**Comment by bbourn** [comment]
It also says
```
Before running the samples, make sure you've followed the steps outlined in
[Using the client library](https://github.com/googleapis/google-api-nodejs-client#using-the-client-library).
```

And there is no such section...

**Comment by bbourn** [comment]
This article: https://support.google.com/googleapi/answer/7014113?hl=en
Says
```
To locate your project ID:

Go to the API Console.
From the projects list, select Manage all projects. The names and IDs for all the projects you're a member of are displayed.
```

And I click the link to go to https://console.developers.google.com/apis/dashboard?project=quickstart-

And there is no "Projects List" that I can see, or that looks like it...  Are they meaning the Quckstart dropdown next to GoogleAPI's in the upper left???

**Comment by bcoe** [comment]
@bbourn if you run:

`gcloud config set project [YOUR-PROJECT-NAME]` it should set the project name for your default credentials, and I believe unblock you.

Let us know if you continue bumping into any issues.
