### ISSUE TITLE
[Question] How to set inAppUpdatePriority?

### ISSUE THREAD

**Issue by 6pm** [googleapis/google-api-nodejs-client#2186]
I want to deploy new app and change 'inAppUpdatePriority '. I looked through source code and ts interfaces and looks 'inAppUpdatePriority' exists only in returned values - Androidpublisher -> edits -> releases. 
Is it possible to define it during upload?

**Comment by JustinBeckwith** [comment]
👋 Looks like this is supported through the following two methods:
- `androidpublisher.edits.tracks.patch`
- `androidpublisher.edits.tracks.update`

You can find the HTTP reference that describes all of the fields here:
https://developers.google.com/android-publisher/api-ref/edits/tracks/patch

And some lightweight samples here:
https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/androidpublisher/v3.ts#L6078

Hope this helps!
