### ISSUE TITLE
How do you write Comments on a YouTube video?

### ISSUE THREAD

**Issue by Axerty** [googleapis/google-api-nodejs-client#2195]
Hey ! So i was wondering if a sample for comments would be possible.
Like, how do we write comments with nodejs ? 
Thanks !

**Comment by JustinBeckwith** [comment]
Greetings - which specific API are you trying to use?  What did you try?

**Comment by Axerty** [comment]
I am trying to use the youtube api, and i tried nothing because i do not know how to well, write youtube comments

**Comment by JustinBeckwith** [comment]
For a basic example of interacting with the youtube API, auth, and all that stuff - check out this sample:
https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/youtube/search.js

For an example of using the `youtube.comments.insert` method, check this out:
https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/youtube/v3.ts#L7340

And for a reference of the fields that are used in the requests and responses, see the HTTP reference:
https://developers.google.com/youtube/v3/docs/comments/insert

Best of luck!
