### ISSUE TITLE
Where is sample oauth2.keys.json

### ISSUE THREAD

**Issue by InfoSecRavindra** [googleapis/google-api-nodejs-client#2196]
Where is sample oauth2.keys.json, I want to follow examples but you didn't provide oauth2.keys.json sample anywhere in the code.

**Comment by cpeker** [comment]
same here

**Comment by JustinBeckwith** [comment]
Greetings!  The instructions to get this file are now in #2199.  Please try:
- Navigate to the Cloud Console and [Create a new OAuth2 Client Id](https://console.cloud.google.com/apis/credentials/oauthclient)
- Select `Web Application` for the application type
- Add an authorized redirect URI with the value `http://localhost:3000/oauth2callback` (or applicable value for your scenario)
- Click `Create`, and `Ok` on the following screen
- Click the `Download` icon next to your newly created OAuth2 Client Id

Make sure to store this file in safe place, and *do not check this file into source control!*

Mind giving this a shot and letting me know how it goes?

**Comment by ninjasort** [comment]
How should I handle the `keys.json` in production? Is there a way to limit the access to only access it from my server?
