### ISSUE TITLE
Unable to resolve module `fs`

### ISSUE THREAD

**Issue by idoor88** [googleapis/google-api-nodejs-client#2211]
Hi, I installed both googleapis and googleapis-common module for my react-native project, but when I run my project, I got this error:

Error: Unable to resolve module `fs` from `MyProject/node_modules/googleapis-common/build/src/discovery.js`: Module `fs` does not exist in the Haste module map

I know fs is a part of node.js, I do not need to install anything for fs since I already have nodejs installed, but how can this be fixed?

#### Environment details

  -info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 19.28 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.4.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: ^0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-asset: 2.0.0
    react-native-cli: 2.0.1
    react-native-cn-richtext-editor: 1.0.33
    react-native-git-upgrade: 0.2.7

   "googleapis": "^44.0.0",
    "googleapis-common": "^3.1.1",

also I tried the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

#### Steps to reproduce
  1. create a sample react-native project
  2.  npm install googleapis
  3.  npm install googleapis-common
  4. run react-native android

Thanks!

**Comment by HazyFish** [comment]
Is there any plan to officially support web-based environments? 
There isn't a nice way to call Google APIs in an Angular project as of today.

**Comment by ddelgrosso1** [comment]
Supporting web is something we are looking into but at this time there are no concrete plans for support. I am going to close this issue as it appears it should be fixed by the above suggestion to polyfill fs as necessary.
