### ISSUE TITLE
Recurrent event: redundant instance event when start date points to a day not in the pattern

### ISSUE THREAD

**Issue by arthabus** [googleapis/google-api-nodejs-client#2214]
#### Environment details

- API simulator from the docs website (link below)

#### Steps to reproduce

  1. Go to calendar.event.inser api explorer: https://developers.google.com/calendar/v3/reference/events/insert
  2. Set calendar to "primary"
  3. Paste the following json as body:
```
{
  "description": "Location:  bla",
  "end": {
    "dateTime": "2020-06-08T14:00:00.000Z",
    "timeZone": "UTC"
  },
  "location": {
    "locationType": "default",
    "displayName": " bla",
    "locationUri": "null"
  },
  "recurrence": [
    "RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=TU,TH,SA;COUNT=5"
  ],
  "reminders": {
    "useDefault": true
  },
  "start": {
    "dateTime": "2020-06-08T13:00:00.000Z",
    "timeZone": "UTC"
  },
  "summary": "Mark Green: 16 weeks -  session"
}
```
4. Grant access and execute the request
5. Go to the calendar view (https://calendar.google.com/calendar)

**Actual result**: Calendar view shows 6 events: Mon 8th (redundant one), Tue 9th, Thu 11th, Sat 13th, Tue 16th, Thu 18th. 

**Expected result**: calendar view shows 5 events as per the provided recurrence rule: Tue 9th, Thu 11th, Sat 13th, Tue 16th, Thu 18th; (no Mon 8th)

![Screen Shot 2020-06-03 at 13 01 23](https://user-images.githubusercontent.com/8145834/83629442-623e0600-a59a-11ea-93e0-32a4d298a5e9.png)

How do I ensure Mon 8th is not showing having the start date set to Mon 8th and recurring rules that excludes Mondays?

**Comment by JustinBeckwith** [comment]
Greetings!  This repository is specifically for reporting issues related to the node.js module itself.  For issues on the underlying API, please check out:
https://developers.google.com/calendar/support

Specifically, you would need to file a bug here:
https://issuetracker.google.com/issues/new?component=191627&template=824103

Just trying to make sure this gets into the right hands!
