### ISSUE TITLE
 Google Analytics Reporting API V4

### ISSUE THREAD

**Issue by b-dabrowski** [googleapis/google-api-nodejs-client#2217]
Will `google.analytics` support v4 of google analytics API eventually? 

As I now the newest version that I can use is v3 with is mentioned as a legacy on the Google Analytics website:

https://developers.google.com/analytics/devguides/reporting/core/v3

**Comment by JustinBeckwith** [comment]
Greetings! It looks to support v4 in the latest version: https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/analyticsreporting/v4.ts

Are you running into any issues with it?

**Comment by b-dabrowski** [comment]
@JustinBeckwith thx for the quick reply sorry for bothering you :( 

I didn't saw `analyticsreporting` property...

Thank you one more time :)
