### ISSUE TITLE
Google Analytics Reporting v4 Data Response Empty

### ISSUE THREAD

**Issue by jlpetracca** [googleapis/google-api-nodejs-client#2225]
Hi! i am getting an empty data response,

I am doing this and dont know where is the mistake

```
  let repReq = [
    {
      "viewId": req.session.GA_Selected.view_id,
      "metrics": [ { "expression": "ga:hits" } ],
    }
  ]


  const oauth2Client = new google.auth.OAuth2(
    process.env.GOOGLE_CLIENT_ID,
    process.env.GOOGLE_CLIENT_SECRET,
    "http://localhost:3000/account/google/callback"
  );
  google.options({
    auth: oauth2Client,
    headers: {
      'Content-Type': 'application/json'
    },
    resource: {
      "reportRequests": repReq
    } 
  });
  oauth2Client.setCredentials(req.session.guser);

  response = await google.analyticsreporting('v4').reports.batchGet();
  console.log(response.data);
```

Here is the response

```

{
  config: {
    resource: { reportRequests: [Array] },
    url: 'https://analyticsreporting.googleapis.com/v4/reports:batchGet',
    method: 'POST',
    userAgentDirectives: [ [Object] ],
    paramsSerializer: [Function],
    headers: {
      'x-goog-api-client': 'gdcl/4.3.0 gl-node/12.16.1 auth/6.0.1',
      'Accept-Encoding': 'gzip',
      'User-Agent': 'google-api-nodejs-client/4.3.0 (gzip)',
      Authorization: 'Bearer XXXXXXXXX',
      Accept: 'application/json'
    },
    params: [Object: null prototype] {},
    validateStatus: [Function],
    retry: true,
    responseType: 'json'
  },
  data: {},
  headers: {
    'alt-svc': 'h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
    'cache-control': 'private',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-type': 'application/json; charset=UTF-8',
    date: 'Sun, 07 Jun 2020 22:30:04 GMT',
    server: 'ESF',
    'transfer-encoding': 'chunked',
    vary: 'Origin, X-Origin, Referer',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'SAMEORIGIN',
    'x-xss-protection': '0'
  },
  status: 200,
  statusText: 'OK',
  request: {
    responseURL: 'https://analyticsreporting.googleapis.com/v4/reports:batchGet'
  }
}

```

Anyone can help me?
regards!

**Comment by JustinBeckwith** [comment]
Greetings!  Usually digging around the generated source is a good way to figure these ones out :) Check this out:
https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/analyticsreporting/v4.ts#L1111

That has a little example which should be mostly right.  A few things I noticed:
- You do not need to set the  `'Content-Type': 'application/json'` header like that, we do it for you
- I would avoid putting `resource` in `google.options`
- Instead of `resource`, please use `requestBody`

For the exact fields in a report request fields, see:
https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/analyticsreporting/v4.ts#L731

Hopefully this helps!  Let us know how it goes?

**Comment by jlpetracca** [comment]
@JustinBeckwith  Thank you! Thank you! Thank you! Very much!!!

I am newbie, it is my first time
- I develop fullstack
- I use JS
- I never used a framework before
- Developing object based

I try, try, try, and keep trying but It is really difficult to me to read this https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/analyticsreporting/v4.ts#L731 because...
- I do understand how objects works
- But I don't understand the handeling of objects, when is a class, how to export an object, and that kinds of things...

For example, 

I would love to simplify code by make this part of the code a function or require or something else
  ```
const oauth2Client = new google.auth.OAuth2(
    process.env.GOOGLE_CLIENT_ID,
    process.env.GOOGLE_CLIENT_SECRET
  );
  google.options({
    auth: oauth2Client
  });
  oauth2Client.setCredentials(req.session.guser);
```
I tried, but then, when I call it from an controller in express js, there is always a problem...

If you know how to do it, dont give me the solution, but explain me how to start researching learning how to do it..

I would love to be able to read a library and understand whats going on...

**Comment by JustinBeckwith** [comment]
@jlpetracca I'd suggest trying to get one small piece of code working at a time.  Start off with just focusing on the parts that use this library, and make sure you can get data through.  Without more specific data on what errors you're getting, it's very difficult to help.  

I'm going to close this out for now.  If you're still having trouble - please let us know and we'll re-open!  Just be super sure to include what specific code you're using, and which errors you're getting.
