### ISSUE TITLE
Changelog does not indicate what the breaking changes are

### ISSUE THREAD

**Issue by alphashuro-br** [googleapis/google-api-nodejs-client#2226]
It seems that many of the major version releases on this project are only accompanied with the message "⚠️ Breaking changes" but no indication of what the breaking changes are. This makes it extremely difficult to know whether there is any action required before upgrading the package, and is even more-so important when you consider how often there seems to be major-version releases/breaking changes on this repo.

**Comment by JustinBeckwith** [comment]
👋  thanks for the feedback.  Agreed, the prior releases here were lacking here. For context - most of this library is auto-generated, and we have very little information on the backend of what actually changed.  It makes building changelogs ... hard.  

Regardless - would you mind checking something out for me?  Here's the next release we have queued up:
https://github.com/googleapis/google-api-nodejs-client/pull/2223

That at least tells you specifically which APIs have breaking changes.  If you look at the specific commits for those APIs linked in the PR:
https://www.github.com/googleapis/google-api-nodejs-client/commit/979ad5a70bbe40627190ef91df2da7c1b667f886

You should a specific list of fields that have been removed:
![image](https://user-images.githubusercontent.com/534619/84059215-0ba44380-a96f-11ea-8b32-e794e66848e1.png)

Note - this is all very, very new.  What do y'all think?  Is this an improvement?  Ways we can make it better?
