### ISSUE TITLE
Better document and/or make more consistent authentication through api endpoints

### ISSUE THREAD

**Issue by sofisl** [googleapis/google-api-nodejs-client#2248]
This issue is related to our work with extensible client options.

Currently, in order to authenticate with an api endpoint, we need to authenticate through the request itself in a separate object with the property titled 'rootURL':

```
async function runSample() {
  // Obtain user credentials to use for the request
  const auth = new google.auth.GoogleAuth({
    keyFilename: //keyfile,
    scopes: //scopes
  });
  
  const authClient = await auth.getClient();

  const project = await auth.getProjectId();

  const createResponse = await docs.documents.create({
    auth: authClient,
    requestBody: {
      title: 'Your new document!',
    }
  },
//here is where we authenticate with the api endpoint
    {rootUrl: 'https://helloworld.com'});
```

It would be nice if we either (a) created better documentation for authenticating with this endpoint, and/or (b), changed this authentication to be less different/confusing (i.e., perhaps making the property title to apiEndpoint vs. rootUrl, and moving it to the same object in the request as the authClient).

**Comment by JustinBeckwith** [comment]
We chatted through this yesterday, and I think we're in good shape.  If it turns out that overriding the `rootUrl` is in fact broken, please do let me know!
