### ISSUE TITLE
provide sample of how to use google fit API to get data like steps,distance.

### ISSUE THREAD

**Issue by rahulj3716** [googleapis/google-api-nodejs-client#2252]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

**Comment by rahulj3716** [comment]
Right now there is no sample of how to use fit API. plz provide one sample so I can use it to get data like steps, heart rate, distance, etc. otherwise there is no use.

**Comment by JustinBeckwith** [comment]
Greetings!  We already have an issue tracking this here:
https://github.com/googleapis/google-api-nodejs-client/issues/1308

Feel free to follow and subscribe to that issue for updates!
