### ISSUE TITLE
Strategy for resolving shortcut and downloading linked content, in Google Drive

### ISSUE THREAD

**Issue by ajmas** [googleapis/google-api-nodejs-client#2258]
Google drive has added a new file type, having an associated mime-type of 'application/vnd.google-apps.shortcut'. Displaying the file object, I get something like:

```
{
  "id": "1TBGha4guewbMXMJrhYaH403hnuWT5LRO",
  "name": "My map",
  "mimeType": "application/vnd.google-apps.shortcut",
  "parents": [
    "1zLoGsLYASFMuEdkn0A0Kpr0xpCX21HcZ"
  ],
  "createdTime": "2020-07-02T18:03:18.769Z",
  "modifiedTime": "2020-07-02T18:03:18.769Z"
}
```

Here I see the 'parents' entry is the id of the folder in the local drive and the id appears to be the actual id of the resource. The issue is using this information it is not clear how to resolve the mime-type, to be able to establish the right export mime type.

In my case the file that is linked is a custom map in Google Maps, which we would like to download, when it changes, as a KML or KMZ.

**Comment by sofisl** [comment]
Hi @ajmas, can you clarify what you're looking to do, and any code samples that can be used to reproduce the issue? I'm not exactly sure I understand the issue. Thanks in advance!

**Comment by ajmas** [comment]
@sofisl I am wring a tool to be able to do a one way sync of a Google drive folder and then download or export the contents as appropriate. What is not clear is how to handle content represented by a shortcut.

<img width="455" alt="Screenshot 2020-07-06 at 15 49 48" src="https://user-images.githubusercontent.com/682269/86634866-66e24980-bfa0-11ea-9144-bccead953153.png">

In the screenshot I have a folder with a shortcut (the new way Google adds content to a drive, when shared with someone). My code uses the following operation to list the entries in the folder:

```js
        const response = await drive.files.list({
            pageToken: nextPageToken,
            includeRemoved: false,
            spaces: 'drive',
            fileId: fileId,
            fields: 'nextPageToken, files(id, name, parents, mimeType, createdTime, modifiedTime)',
            q: `'${fileId}' in parents`,
            pageSize: 200
        });
```

I then iterate over the contents:

```js
        for (let i = 0; i < files.length; i++) {
            const file = files[i];
            if (file.mimeType === 'application/vnd.google-apps.folder') {
              // list contents of folder
            } else if (file.mimeType === 'application/vnd.google-apps.shortcut') {
               // TODO process shortcut
            } else {
               await downloadContent(drive, file, folderPath, options)
           }
        }
```

Here I am not sure how to resolve a shortcut to the actual content node, so that it can be downloaded. I could not see anything in the documentation on this.

In the example above it was a Google Sheet that was shared with my test user and when trying to list the contents I get an entry that is a 'shortcut'. Are there extra fields I need to be requesting to be able to resolve the shortcut to the actual document node or is there something else I might be missing to do this?

**Comment by ajmas** [comment]
Further digging shows I need to pass 'shortcutDetails' to the fields parameter, such that:

```js
fields: 'nextPageToken, files(id, name, parents, mimeType, createdTime, modifiedTime, shortcutDetails)',
```

This provides an extra field, of the form:

```js
  "shortcutDetails": {
    "targetId": "1a007-BwgXY8mGGEk5Vs3Yx4nBOKEB-3poNUmdVi2GFA",
    "targetMimeType": "application/vnd.google-apps.spreadsheet"
  }
```

This works, though now I need to deal with what appears to be access permissions not passing down to the resources.

**Comment by sofisl** [comment]
Hi @ajmas, sorry for the delay in responding. It looks like you've figured out a way to resolve, and thanks for posting the solution. I'll go ahead and close for now, feel free to post the permissions question on a separate issue.
