### ISSUE TITLE
#2197 broke YouTube API typings

### ISSUE THREAD

**Issue by cpboyd** [googleapis/google-api-nodejs-client#2262]
#### Environment details

  - OS: macOS 10.15.5
  - Node.js version: v14.5.0
  - npm version: 6.14.5
  - `googleapis` version: 52.1.0

#### Steps to reproduce

  1. See https://developers.google.com/youtube/v3/docs/channels/list
  2. `part` and `id` are type `string`
  3.  See https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/youtube/v3.ts#L6380-L6418
  4. The generator changed these parameters to type `string[]` in #2197

At the very least (assuming the generator is correct), these should be `string | string[]` since the API publicly states that a single string is required.

Downgrading to v51.0.0 works fine with the existing code.

**Comment by JustinBeckwith** [comment]
@sofisl Youtube recently rolled out a new discovery doc.  Chances are high we're doing exactly what the discovery doc tells us.  Could I trouble you to take a look, make sure the generator is doing the right thing, and then open an issue internally if needed?

**Comment by cpboyd** [comment]
As an update, this is still broken in v66

**Comment by sofisl** [comment]
Hi @cpboyd,

Sorry for the delay in responding!

It looks like the discovery doc actually corresponds to the generated code, as indicated by the [`repeated` property ](https://github.com/googleapis/google-api-nodejs-client/blob/26770978627ba14471a5c7b5606f961f1937740a/discovery/youtube-v3.json#L733). 

It's also indicated in the API explorer
<img width="373" alt="Screen Shot 2021-11-04 at 12 31 10 PM" src="https://user-images.githubusercontent.com/55454395/140407458-1f9f828a-78fe-4054-a6db-935afdfa3f61.png">


So it looks like this is actually right. Feel free to open a new issue with any code that isn't working as you'd expect!

**Comment by cpboyd** [comment]
@sofisl Ah, I see.

Could the docs at https://developers.google.com/youtube/v3/docs/channels/list maybe indicate the `repeated` property by using something like `list<string>` instead of just `string`?

<img width="1277" alt="Screen Shot 2021-11-05 at 4 54 22 PM" src="https://user-images.githubusercontent.com/6323077/140577254-1163b581-0a7e-4689-b8f1-fcc23762e9bf.png">
