### ISSUE TITLE
Have exceeded your quota

### ISSUE THREAD

**Issue by mddanishyusuf** [googleapis/google-api-nodejs-client#2263]
#### Environment details

  - OS: macOS 10.15.5
  - Node.js version: v12.13.0
  - npm version: 6.12.0
  - `googleapis` version:  49.0.0

#### Steps to reproduce

  1. Enabled 3rd API(YouTube Data API v3) into my project and using same `OAuth 2.0 Client IDs` as I'm using for other two.
  2. I'm able to get `access_token` without any problem. but when using APIs then giving this error.

```
{
  "error": {
    "code": 403,
    "message": "The request cannot be completed because you have exceeded your <a href=\"/youtube/v3/getting-started#quota\">quota</a>.",
    "errors": [
      {
        "message": "The request cannot be completed because you have exceeded your <a href=\"/youtube/v3/getting-started#quota\">quota</a>.",
        "domain": "youtube.quota",
        "reason": "quotaExceeded"
      }
    ]
  }
}
```
4. I also try to use direct `API_KEY` way and giving same problem.
3. When I use the new project `OAuth 2.0 Client IDs` then everything working great.

Can you please explain to me what is the issue.

Thanks!

**Comment by JustinBeckwith** [comment]
👋  I mean I know this may be an obvious question... but is it possible you're over your API request quota?  You can check your usage on the developer console by:
- Go to http://console.developers.google.com/
- Search in the library for the Youtube Data v3 API
- You should end up at a url that looks something like https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=***your-project-id***

That should give you an idea of how much you're using the API.  

If that's *not* it - can you share how you're acquiring your access tokens?  A snippet of example code here would be super helpful.

**Comment by mddanishyusuf** [comment]
Thanks, @JustinBeckwith for quick reply.

Here is the usage

<img width="1095" alt="Screenshot 2020-07-09 at 7 56 00 AM" src="https://user-images.githubusercontent.com/9165019/86990187-a46def00-c1b9-11ea-8ef2-e193ab532251.png">

That was my first call.

Here is the code snippet:

```
const oauth2Client = new google.auth.OAuth2(
           '***.apps.googleusercontent.com',
             '***',
             'http://localhost:3001/dashboard/api/yt'
);
scopes = ['https://www.googleapis.com/auth/youtube'];

const url = oauth2Client.generateAuthUrl({
                // 'online' (default) or 'offline' (gets refresh_token)
                access_type: 'offline',

                // If you only need one scope you can pass it as a string
                scope: scopes,
        });
```

And then exchanging code for token

```
oauth2Client.getToken(req.body.code, (err, tokens) => {
})
```

The same code working fine with my different projects.

**Comment by JustinBeckwith** [comment]
Got it.  Sadly when this stuff happens, it's a little bit of guess work.  Next things to look at!  Can you double check:
- The code that attaches the auth client to the request - is the auth client you're getting added to the service client?
- Scopes, scopes scopes - are you double checking the scopes you're asking for, against the specific API call?
- I've heard rumblings about the callback for `getToken` not workin as folks expect - can you double check you're getting the right tokens back?

Thanks for sticking with us here.

**Comment by mddanishyusuf** [comment]
@JustinBeckwith Everything is great.

I have one project name `nocodeapi` and I already using two APIs `google sheet` & `google analytics` and they are working great.

When I enable `YouTube Data API` on the account `nocodeapi` it's not working and returning quota error.

So, I create new account called `nocodeapi v2` and enable only `YouTube Data API` and everything works smooth.

No problem.

IDK is there any code problem.

I hope you got my point now. Thanks

**Comment by atif089** [comment]
I'm facing the same problem. It looks like my quota goes to 0 after a few hours. I read it somewhere else that I need to request to raise limits (or get my app verified) in order to get it fixed although I was well within my limits. They just set my limit to 0 now.

**Comment by llazzaro** [comment]
Same issue here.

**Comment by manh-nguyen-irep** [comment]
same issue here

**Comment by fensterhebel** [comment]
I had the same issue, no usage at all but "quota exceeded" response. My solution was to create a new project. I guess it's because something changed internally over time and wasn't applied correctly to (at least my) already existing project...

**Comment by dirablue** [comment]
@fensterhebel 
> My solution was to create a new project.
I'd struggled by same issue, and fixed with your solution.
thanks!

**Comment by AirtonBorges** [comment]
same problem

**Comment by gdunghi** [comment]
same problem and my project have only YouTube Data API

**Comment by tioguil** [comment]
From what I saw, it looks like your account must be linked to a billing account
