### ISSUE TITLE
Unable to install this library in my react-native app

### ISSUE THREAD

**Issue by developershanker** [googleapis/google-api-nodejs-client#2296]
I have tried "npm install googleapis" and "yarn add googleapis" still I am getting this error **Error: Unable to resolve module `stream` from `node_modules\googleapis-common\build\src\apirequest.js`: stream could not be found within the project.**
Please help me out with this. Thanks in advance

**Comment by sofisl** [comment]
Hi @developershanker:

For running this library in a browser or react native context, you'll want to use a tool like webpack to shim Node.js globals. We currently are [tracking this request](https://github.com/googleapis/google-cloud-node/issues/2933) with plans to implement it in the future.
