### ISSUE TITLE
Watch() sends message to PubSub regardless of label on added email

### ISSUE THREAD

**Issue by MaxMaeder** [googleapis/google-api-nodejs-client#2301]
#### Environment details

  - OS: Firebase Cloud Functions
  - Node.js version: 10
  - npm version: 6.14.5
  - `googleapis` version: `^54.1.0`

#### Steps to reproduce

I am trying to watch a users' inbox so that my Google Cloud Pub/Sub subscription receives a message every time a new message is received. To achieve this, I closely followed the [Push Notifications guide](https://developers.google.com/gmail/api/guides/push). 

However, in testing the subscription receives a message seemingly any time a new email is added to the users' inbox, even when they sent it or just saved a draft of it. 

I've granted the client access to the `https://mail.google.com/` scope, as [an issue](https://github.com/googleapis/google-api-nodejs-client/issues/469#issuecomment-140328898) mentioned lesser scopes caused a similar issue for them. Below is my code responsible for watching a users' inbox. I have tried it with and without the commented code near the bottom.
```js
  await gmailClient.users.watch({
    userId: "me",
    requestBody: {
      topicName: "projects/*****/topics/newMail",
      labelIds: ["INBOX"]/*,
      labelFilterAction: "include"*/
    },
  });
```

Any ideas as to why this isn't working would be greatly appreciated.

**Comment by MaxMaeder** [comment]
More of my code, if it helps:
#### Watching a Gmail account:
```js
// Add a new Gmail account to the list of triggering accounts
app.get("/oauthRedirect", async function(req, res) {

  // Get authorization code
  const authorizationCode = req.query.code;

  // Get refresh token using authorization code 
  const responseBody = await googleOauth.getToken(authorizationCode)
  const refreshToken = responseBody.tokens.refresh_token;

  // Get the list of the refresh tokens of the already added Gmail accounts
  let gmailAccountRefreshTokens = await firebaseAdmin.database().ref("gmailAccounts").once("value");
  gmailAccountRefreshTokens = gmailAccountRefreshTokens.val() || [];

  // Append the refresh token to the list
  if (!gmailAccountRefreshTokens.includes(refreshToken)) {
    gmailAccountRefreshTokens.push(refreshToken);
  }

  // Update the list of the refresh tokens of the added Gmail accounts
  await firebaseAdmin.database().ref("gmailAccounts").set(gmailAccountRefreshTokens);

  // Log in to the account assosiated with the refresh token
  googleOauth.setCredentials({
    refresh_token: refreshToken
  });

  // Request the newMail topic watch the account's gmail inbox for the next ~24 hours
  await gmailClient.users.watch({
    userId: "me",
    requestBody: {
      topicName: "projects/myproj/topics/test",
      labelIds: ["INBOX"]/*,
      labelFilterAction: "include"*/
    },
  });

  // Redirect user to dashboard homepage
  res.redirect("/");
});
```
#### Getting whether new mail in a Gmail inbox:
```js
// Get whether any new mail has been received by any of the triggering accounts since it was last checked
app.get("/getNewMail", async function(req, res) {
  // Get new mail subscription
  const subscription = pubSubClient.subscriptionPath(
    "myproj",
    "test"
  );

  // Get new messages to the subscription
  const [response] = await pubSubClient.pull({
    subscription,
    returnImmediately: true,
    maxMessages: 10
  });
  const {receivedMessages} = response;

  // Acknowledge the received messages 
  const ackIds = [];
  for (const receivedMessage of receivedMessages) {
    ackIds.push(receivedMessage.ackId);
  }
  if (ackIds.length > 0) {
    await pubSubClient.acknowledge({
      subscription,
      ackIds
    });
  }

  // Respond with whether new mail was received by any of the watched accounts
  res.send({
    newMail: response.receivedMessages.length > 0
  });
});
```

**Comment by MaxMaeder** [comment]
What's weird is that I'm trying to debug the issue by plugging an older `historyId` returned by Pub/Sub into the *Users.history: list* method using the API Explorer, but I can't seem to locate any newer returned `historyId`s in the resulting response.

I'm not specifying the `historyTypes` and the two `historyId`s are close enough together that `maxResults` shouldn't have any effect. I know both `historyId`s are valid because I don't receive a `404` response when I use them as the `startHistoryId`.

**Comment by sofisl** [comment]
Hi @MaxMaeder, I think the issue here is that you'll want to specify the filter in your `watch()` request,  like so:

```
      labelIds: ['DRAFT', 'SENT'],
      labelFilterAction: 'exclude',
```

You can learn more about labels and filtering syntax[ here](https://developers.google.com/gmail/api/guides/labels) and [here](https://developers.google.com/gmail/api/reference/rest/v1/users/watch#LabelFilterAction).

Let me know if this doesn't work for you!
