### ISSUE TITLE
People API: listDirectoryPeople function not defined

### ISSUE THREAD

**Issue by pereirfe** [googleapis/google-api-nodejs-client#2318]
**Goal**
Assert that the listDirectoryPeople function [(link)](https://developers.google.com/people/api/rest/v1/people/listDirectoryPeople) is, in fact, a function.

**Steps to reproduce**
I am using the [quickstart](https://developers.google.com/people/v1/getting-started) guide for the people's API as a base and then tweaking to use [listDirectoryPeople](https://developers.google.com/people/api/rest/v1/people/listDirectoryPeople). 

My scopes are:
```js
const SCOPES = [
  'https://www.googleapis.com/auth/calendar.readonly',
  'https://www.googleapis.com/auth/directory.readonly', // <- Required by listDirectoryPeople
  'https://www.googleapis.com/auth/contacts.readonly'
]
```

The function called by `authorize` is:
```js
function listConnectionNames (auth) {
  const service = google.people({ version: 'v1', auth })

  console.log('Get:', service.people.get)  // [Function: get]
  console.log('ListDirectoryPeople:', service.people.listDirectoryPeople)  // undefined
  console.log('searchDirectoryPeople:', service.people.searchDirectoryPeople) // undefined
  console.log('GetBatchGet:', service.people.getBatchGet) // [Function: getBatchGet]
  console.log('UpdateContact:', service.people.getBatchGet) // [Function: updateContact]
}
```
The rest of the authorization process is let as it is in the guide. 

**Issue** 
The `console.log` for the listDirectoryPeople logs undefined instead of a function.

**Attempts to solve**
  * Delete tokens and re-authorize
  * Check if the app has authorization to access people's api (it does, since other functions from the same api exist)
  * Tweaking the scope and removing the ".readonly" 
    (Interestingly, when I curl GET `https://www.googleapis.com/auth/directory` I get a 404. It works when I do it for `https://www.googleapis.com/auth/contacts` or `https://www.googleapis.com/auth/directory.readonly`. IMHO it doesn't look like an expected behavior, but I am not sure it is linked to the problem)
  * Testing the api using API explorer: It works fine, and the javascript code it uses does use the scope as instructed. Still, I couldn't make it work 

**Using**
`node v12.18.2`
`googleapis@39`

**Comment by JustinBeckwith** [comment]
Greetings!  On `googleapis@58.0.0`, this seems to work:
```
const {google} = require('googleapis');
const people = google.people({version: 'v1'});
console.log(people.people.listDirectoryPeople);
```

Can you update to the latest version and give this another try?  Any chance you're trying to use create-react-app, webpack, angular, electron, or anything like that?

**Comment by pereirfe** [comment]
Greetings!

Ok. I feel stupid right now. It indeed works on googleapis@58
I just used v39 due the tutorial. 

Thanks!
