### ISSUE TITLE
( quickstart ) can't get oAuth token

### ISSUE THREAD

**Issue by artem-rekunov** [googleapis/google-api-nodejs-client#2329]
**executing code from**  [quickstart](https://developers.google.com/gmail/api/quickstart/nodejs) returns error:
Error retrieving access token GaxiosError: invalid_grant
status: 400,
statusText: 'Bad Request'

but if you use [urldecoder](https://www.urldecoder.org/) to decode manually (which is not said and which was't before...) you can get a token.

**the problem** is that this way I can't get the refresh token... (which was't there before, about 28 days ago),
I'm looking for a refresh token because of this output:
Something went wrong4: Error: listMessagesInitial: The API returned an error: Error: No access or refresh token is set.
I would like to assume that the problem is not the lack of access, since I received the token.

code:

      gmailApiSync.authorizeWithToken(accessToken, function (err, oauth) {
        if (err) { console.log('Something went wrong3: ' + err); rej(); }
        else { gmailApiSync.queryMessages(oauth, options, function (err, response) {
          if (err) { console.log('Something went wrong4: ' + err); rej(); }

please tell me how to get the refresh token.

gmail-api-sync is just a wrapper over: googleapis (**what returns an error, looked at the wrapper code**), gmail-api-parse-message (which is not used in this request), google-auth-library and etc.

**Comment by KapitalEarth** [comment]
﻿

**Comment by KapitalEarth** [comment]
Go for Blue is the warmest color device.
R.
Now.

**Comment by artem-rekunov** [comment]
Answer please

**Comment by artem-rekunov** [comment]
Please give me answer.
