### ISSUE TITLE
listByBlog of Blogger API v3 keeps returning 404 error.

### ISSUE THREAD

**Issue by leestrument** [googleapis/google-api-nodejs-client#2332]
Hi, I'm trying to get all comments by listByBlog in node.js
I'm even still getting 404 error  ""Try This API" menu" here. https://developers.google.com/blogger/docs/3.0/reference/comments/listByBlog

Please fix this issue.....

**Comment by sofisl** [comment]
Hi there! Can you share your code snippet and/or values you are using in the API explorer?
