### ISSUE TITLE
Always getting error 401 Login required

### ISSUE THREAD

**Issue by snitin315** [googleapis/google-api-nodejs-client#2334]
#### Current behavior
I'm trying to use the google drive API key to upload files.

Getting an error with code 401 saying login required 😞 

#### Steps to reproduce
Run the following module.

```js
const {google} = require('googleapis');

async function main() {
    const drive = google.drive({
        version: 'v3',
        auth: 'MY_API_KEY'
      });
       
      const res = await drive.files.create({
        requestBody: {
          name: 'Test',
          mimeType: 'text/plain'
        },
        media: {
          mimeType: 'text/plain',
          body: 'Hello World'
        }
      });
}

main().catch(console.error);
```

**Comment by JustinBeckwith** [comment]
Greetings!  Google Drive does not support API key based authentication.  It needs to authenticate on behalf of a user, so it only really supports OAuth2:
https://developers.google.com/drive/api/v3/about-auth

You can read a whole bunch about that here:
https://github.com/googleapis/google-api-nodejs-client#oauth2-client

Hope this helps!

**Comment by babyrusa** [comment]
Hey @JustinBeckwith ,
How do I find out if a library supports certain type of authentication. I'm using Service account json for Android Publisher https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions/get but it's not working and I'm thinking perhaps it only accepts OAuth2?
