### ISSUE TITLE
How to include only modules for the APIs we want to use

### ISSUE THREAD

**Issue by SteveALee** [googleapis/google-api-nodejs-client#2340]
This is is one massive monolithic package!

How do we include only the parts we want (and dependencies)? For example see lodash

**Comment by bcoe** [comment]
@SteveALee we do not currently publish individual packages for each API, but to improve application start times, you can:

```
require('./build/src/apis/some-api')
```

☝️ and use an API directly.

**Comment by SteveALee** [comment]
Thanks. In the end i used the auth component with REST. Eg https://opendirective.net/2020/09/11/sending-mail-with-g-suite/
