### ISSUE TITLE
Error trying to get authenticated user email with googleapis and node.js

### ISSUE THREAD

**Issue by alenieto97** [googleapis/google-api-nodejs-client#2341]
I'm implementing auth on my website using googleapis. The function plus.people.get doesn't work. I have seen it is deprecated on some forums but it's still documented at google which has me confused. The error I get is "Legacy People API has not been used in project 328985958128 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/legacypeople.googleapis.com then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry." The webpage doesn't even load. My code is

```js
if (!req.body.token) {
  return res.status(500).json({ type: 'error', message: 'No access token provided.' });
}
const oauth2Client = new google.auth.OAuth2(keys.client_id, keys.client_secret);
google.options({ auth: oauth2Client });

const plus = google.plus('v1')
oauth2Client.setCredentials({
  access_token: req.body.token
});
plus.people.get({
  userId: 'me',
  auth: oauth2Client
}, (error, response) => {
  if (error) {
    console.log(error);
    return res.status(500).json({ type: 'error',error });
  }
  const emails = (response.data || {}).emails;
});
```

**Comment by JustinBeckwith** [comment]
Greetings!  You want to use the Google People API, not the Google+ API (which has been deprecated):
https://developers.google.com/people

You can find examples of it's usage here:
https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/people/v1.ts#L3420

Hope this helps!
