### ISSUE TITLE
Add a proxy option for using vpn

### ISSUE THREAD

**Issue by qiulang** [googleapis/google-api-nodejs-client#2345]
Like [request](https://github.com/request/request) has proxy option https://github.com/request/request#proxies, it is extremely useful for Chinese developers who use vpn to access google api

I actually opened a related issue https://github.com/googleapis/google-api-nodejs-client/issues/1471 but it was closed.

I raised a question at stackoverflow https://stackoverflow.com/questions/53593182/client-network-socket-disconnected-before-secure-tls-connection-was-established

But I think if api can support proxy option, it will be easiest solution.

**Comment by JustinBeckwith** [comment]
Greetings!  Have you followed the instructions here?
https://github.com/googleapis/google-api-nodejs-client#using-a-proxy

**Comment by qiulang** [comment]
I didn't know that and now I finally made it work with `http_proxy='http://myvpn' node index.js` Thanks!

Can you add more information about this setting ?  For example can you add some sample code for proxy configuration option?

> It is valid to define a proxy in one of the environment variables, but then override it for a specific request, using the proxy configuration option.

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.

**Comment by atubo2012** [comment]
> I didn't know that and now I finally made it work with `http_proxy='http://myvpn' node index.js` Thanks!
> 
> Can you add more information about this setting ? For example can you add some sample code for proxy configuration option?
> 
> > It is valid to define a proxy in one of the environment variables, but then override it for a specific request, using the proxy configuration option.

Could you share how to confirm the 'myvpn'  in your environment ?
I've encountered same issue, many thanks. :)

**Comment by atubo2012** [comment]
> > I didn't know that and now I finally made it work with `http_proxy='http://myvpn' node index.js` Thanks!
> > Can you add more information about this setting ? For example can you add some sample code for proxy configuration option?
> > > It is valid to define a proxy in one of the environment variables, but then override it for a specific request, using the proxy configuration option.
> 
> Could you share how to confirm the 'myvpn' in your environment ?
> I've encountered same issue, many thanks. :)

I've found it:
Press the Windows Key
Search For Internet Options
Click on "Internet Options"
Click On "Connection"
Go to LAN Settings
Uncheck "Use Proxy Server for LAN ...."

**Comment by atubo2012** [comment]
> I didn't know that and now I finally made it work with `http_proxy='http://myvpn' node index.js` Thanks!
> 
> Can you add more information about this setting ? For example can you add some sample code for proxy configuration option?
> 
> > It is valid to define a proxy in one of the environment variables, but then override it for a specific request, using the proxy configuration option.

Solved after removing EV https_proxy='https://127.0.0.1:1003' and Only keep http_proxy='http://127.0.0.1:1003'
