### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by Rich-Harris** [googleapis/google-api-nodejs-client#2346]
## 1) Is this a client library issue or a product issue?

It takes a very long time for `require('googleapis')` to run, because it eagerly requires every API submodule. Notwithstanding the fact that the source code uses static `import` rather than `require`, this package could most likely be built in such a way that submodules were required lazily, so that in code like this, for example...

```js
const { google } = require('googleapis');

const auth = google.auth.fromJSON(credentials);
auth.scopes = ['https://www.googleapis.com/auth/drive.readonly'];

const client = google.drive('v3');
const { data } = await client.files.export(file);
```

...only the submodules for `google.auth` and `google.drive` would be `require`d.

Alternatively, or additionally, exposing submodules directly could solve the problem:

```js
const { fromJSON } = require('googleapis/auth');
const auth = fromJSON(credentials);

const client = require('googleapis/drive/v3');
const { data } = await client.files.export(file);
```

## 2) Did someone already solve this?

Couldn't find any prior discussion

## 3) Do you have a support contract?

No

#### Environment details

  - OS: MacOS
  - Node.js version: 12.18.3
  - npm version: 6.14.6
  - `googleapis` version: 59

#### Steps to reproduce

```js
function timed_require(x) {
  const start = Date.now();
  const mod = require(x);
  console.log(`required ${x} in ${Date.now() - start}ms`);
  return mod;
}

timed_require('googleapis');
```

**Comment by schmod** [comment]
I've noticed this as well – requiring `googleapis` is _by_ far the slowest part of my application's startup process, and can add over a second to the time it takes to launch the application.

**Comment by haohaolee** [comment]
Agree. Especially when require is running in a serverless environment like AWS lambda, it hurts the cold start performance much

**Comment by alexblack** [comment]
I think we're experiencing a related but different issue - our typescript compile times shot up by about 20-30s when we added `googleapis` to our project

**Comment by bcoe** [comment]
@alexblack wow, this is a blast from the past 😆, _so I work on client libraries at Google now._

---

@alexblack @Rich-Harris @haohaolee, we just started publishing [individual libraries from googleapis](https://www.npmjs.com/package/@googleapis/drive), which should significantly speed up startup/compile time:

You can find them under the [`@googleapis` namespace on npm](https://www.npmjs.com/search?q=%40googleapis). Once install a dependency, it should work almost identically to using the top level module, e.g.,


```bash
npm i @googleapis/drive
```

```js
const drive = require('@googleapis/drive')
const auth = new drive.auth.GoogleAuth({
  // Scopes can be specified either as an array or as a single, space-delimited string.
  scopes: ['https://www.googleapis.com/auth/drive.readonly']
});
const authClient = await auth.getClient();
const client = drive.drive({
  version: 'v3',
  auth: authClient
});
const { data } = await client.files.export({fileId: 'abc123', mimeType: 'application/text'});
```

**Comment by alexblack** [comment]
Hey @bcoe great to bump into you here! That's awesome you're at google.

Individual libraries sounds amazing, I will check them out.

**Comment by bcoe** [comment]
Closing this issue, now that we have the ability to install individual APIs. Let us know if you continue to have any issues.

**Comment by jasonpolites** [comment]
@bcoe 

Having individual APIs is perfect, but the the main one that we (presumably) all need, "oauth2" is listed as deprecated here: https://www.npmjs.com/package/@googleapis/oauth2

If there a newer API for the `google.oauth2` namespace?

**Comment by uvais-srv** [comment]
I was researching the same and found this [https://github.com/googleapis/google-api-nodejs-client/issues/3375#issuecomment-1779376385](link).

**Comment by davidthornton** [comment]
Hi Team, if you're here it appears that we need to use this now https://github.com/googleapis/google-auth-library-nodejs and before you thank me... ChatpGPT told me so 😳 I didn't work it out myself! In my case it appears to be (unverifiable of course) due to es6 `"type": "module"` versus the existing auth packages perhaps being CommonJS modules!

For Google keyword catches, previously we were using: `import { google } from 'googleapis';` and `const oauth2Client = new google.auth.OAuth2(`

We now use:

```
import { OAuth2Client } from 'google-auth-library';

const oauth2Client = new OAuth2Client(
...
```
