### ISSUE TITLE
Add APIs for containerregistry.googleapis.com

### ISSUE THREAD

**Issue by pskrbasu** [googleapis/google-api-nodejs-client#2349]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
I use these methods in gcloud https://cloud.google.com/sdk/gcloud/reference/container/images. But I'm always frustrated knowing that these are not available in API. These features would be great to use in a REST API.
 **Describe the solution you'd like**
The same methods as in gcloud https://cloud.google.com/sdk/gcloud/reference/container/images, in Container Registry API.
 **Additional context**
The methods in gcloud container images can be created in an API.

**Comment by JustinBeckwith** [comment]
So sadly this isn't really possible.  The Container Registry API technically doesn't really exist 👻   Container Registry maps completely to the Docker Registry API as called out here:
https://cloud.google.com/container-registry/docs/reference/docker-api

The spec for the docker registry API is defined outside of Google here:
https://docs.docker.com/registry/spec/api/

For context - this library is entirely auto-generated, using https://www.googleapis.com/discovery/v1/apis/ as the source of truth.  With no Google driven discovery file there, there's nothing we can do directly in the library to support it.  

There look to be a few interesting options here:
https://www.npmjs.com/search?q=docker%20registry

Best of luck!
