### ISSUE TITLE
Invalid export in /googleapis/build/src/index.d.ts

### ISSUE THREAD

**Issue by salitha-pathi** [googleapis/google-api-nodejs-client#2357]
Following error raises when the library is used with [Loopback 4](https://loopback.io/doc/en/lb4/#overview)

`node_modules/googleapis/build/src/index.d.ts:5:10 - error TS1005: 'from' expected.

5 export * as Common from 'googleapis-common';
           ~~

node_modules/googleapis/build/src/index.d.ts:5:13 - error TS1005: ';' expected.

5 export * as Common from 'googleapis-common';
              ~~~~~~

node_modules/googleapis/build/src/index.d.ts:5:20 - error TS1005: ';' expected.

5 export * as Common from 'googleapis-common';
                     ~~~~

node_modules/googleapis/build/src/index.d.ts:5:25 - error TS1005: ';' expected.

5 export * as Common from 'googleapis-common';
`


#### Environment details
##### 1.
  - OS: Windows 10 x64
  - Node.js version: 12.13.1
  - npm version: 6.12.1
  - `googleapis` version: 59.0.0
  - `typescript` version: 3.7.5

##### 2.
  - OS: Ubuntu 18.04 LTS
  - Node.js version: 12.10.0
  - npm version: 6.14.4
  - `googleapis` version: 59.0.0
  - `typescript` version: 3.7.5

Thanks!

**Comment by ocket8888** [comment]
I get the same problem - not using loopback, though, just a typescript server being webpack-ed by angular 8 for server-side-rendering.

**Comment by salitha-pathi** [comment]
> I get the same problem - not using loopback, though, just a typescript server being webpack-ed by angular 8 for server-side-rendering.
> 
> Edit: actually I noticed that my problem is merely similar. I get these problems trying to import `Auth`:
> 
> ```
> ERROR in /home/ocket8888/src/myapp/server.ts
> ./server.ts
> [tsl] ERROR in /home/ocket8888/src/myapp/server.ts(30,18)
>       TS2305: Module '"./node_modules/googleapis/build/src"' has no exported member 'Auth'.
> 
> ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts
> [tsl] ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts(5,10)
>       TS1005: 'from' expected.
> 
> ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts
> [tsl] ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts(5,13)
>       TS1005: ';' expected.
> 
> ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts
> [tsl] ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts(5,20)
>       TS1005: ';' expected.
> 
> ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts
> [tsl] ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts(5,25)
>       TS1005: ';' expected.
> 
> ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts
> [tsl] ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts(6,10)
>       TS1005: 'from' expected.
> 
> ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts
> [tsl] ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts(6,13)
>       TS1005: ';' expected.
> 
> ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts
> [tsl] ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts(6,18)
>       TS1005: ';' expected.
> 
> ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts
> [tsl] ERROR in /home/ocket8888/src/myapp/node_modules/googleapis/build/src/index.d.ts(6,23)
>       TS1005: ';' expected.
> ```
> 
> I'm not actually sure if it's the same problem, but they look related at a glance

Yes, this is same issue

**Comment by bcoe** [comment]
@HachimanHiki  @salitha-pathi if you run `typescript@3.9`, do you run into this issue? This seems like it might be a regression in TypeScript itself, as we're not seeing it in our own compilation.

**Comment by ocket8888** [comment]
I'm using an Angular 8 project which doesn't work with Typescript > 3.6. Is there an older version of googleapis that would support Angular 8?

**Comment by bcoe** [comment]
@ocket8888 yes, please try installing `npm i googleapis@legacy-8`.

**Comment by HachimanHiki** [comment]
It works for me with `typescript@3.9.7`. My original version is `typescript@3.7.5`

**Comment by HachimanHiki** [comment]
microsoft/TypeScript#34903 adds support for the new export * as ns from 'specifier' syntax, which is after `typescript@3.8`

**Comment by JustinBeckwith** [comment]
Looks like this one is solved - to use this lib, you need to be using at least TypeScript 3.8.x.  Sadly - there's no way we can figure out how to express which version of TypeScript we require in a programmatic sense (peer dependencies, optional dependencies, strict engine checks, etc).  

I know this answer isn't super fulfilling, but our plan is to start gating TypeScript tooling version on semver major releases of the library (which for this library ... is often.).
