### ISSUE TITLE
send gmail emails with jwt-google api

### ISSUE THREAD

**Issue by eladnm** [googleapis/google-api-nodejs-client#2361]
I am trying to send email using nodejs and google api auth and jwt. i get the following error:

```
  code: 400,
  errors: [
    {
      message: 'Precondition check failed.',
      domain: 'global',
      reason: 'failedPrecondition'
    }
```
and this is my code:

```
   const jwtClient = new google.auth.JWT(
  googleKey.client_email,
  null,
  googleKey.private_key,
  ['https://www.googleapis.com/auth/gmail.send'],
  'email@xxx-cloud.iam.gserviceaccount.com',
)

function sendMessage(auth, from, to, subject, content) {
  // The Gmail API requires url safe Base64
  // (replace '+' with '-', and '/' with '_')
  var encodedEmail = new Buffer(
    'From: ' + from + '\r\n' + 'To: ' + to + '\r\n' + 'Subject: ' + subject + '\r\n\r\n' + content,
  )
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')

  var gmail = google.gmail('v1')
  var request = gmail.users.messages.send(
    {
      auth: auth,
      userId: 'email@xxx-cloud.iam.gserviceaccount.com',
      resource: {
        raw: encodedEmail,
      },
    },
  )
}
```

**Comment by sqrrrl** [comment]
The Gmail API isn't intended to be used with service accounts (other than domain-wide delegation use cases.) You need to be acting as a real user -- either using oauth credentials obtained with user consent, or in the case of a Gsuite domain, using a service account delegating/impersonating a real user.

I'll file a bug to make the error message clearer, but it's likely that the failed precondition is that the service account isn't a valid gmail user.

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
