### ISSUE TITLE
Auth: Invalid_grant after a few days of usage

### ISSUE THREAD

**Issue by jlippold** [googleapis/google-api-nodejs-client#2363]
I'm looking for general help and guidance here, because I'm totally stumped. I use the `passport-google-oauth` library to perform the original oauth process and I get and store an access and refresh token, and use those credentials with this `googleapis` library.

More Info
  - OS: Ubuntu LTS, and MacOs
  - Node.js version: 8.9.4
  - npm version: 5.6.0
  - `googleapis` version: 42.0.0

After I authenitcate with passportjs, I store the access/refresh token in my database, then I create a googleClient like so to talk with the api endpoints:

```js
const oauth2Client = new google.auth.OAuth2(clientId, secret);

// This is to store updated accessTokens in my DB. I assume the lib 
// emits the tokens event when a accessToken is near expiration
oauth2Client.on('tokens', (tokens) => {
    var record = { 
        googleAccountId: item.googleAccountId,
        accessToken: tokens.access_token,
        idToken: tokens.id_token,
        accessTokenExpiration: tokens.expiry_date
    };
    db.google_accounts.update(record, function () { });
});

// define config here
oauth2Client.setCredentials({
    "access_token": item.accessToken,
    "refresh_token": item.refreshToken,
    "scope": scopes.join(" "),
    "token_type": "Bearer",
    "expiry_date": item.accessTokenExpiration,
});

// finally use the client to talk with google
const classroom = google.classroom({ version: 'v1', auth: oauth2Client });
classroom.courses.list(options, function (err, googleResponse) { ... }
```

All of that above works great initially, then after a few days it stops working and the google api begins returning an `invalid_grant` error. I know there are a ton of reasons why invalid_grant happens as listed in this [blog post](https://blog.timekit.io/google-oauth-invalid-grant-nightmare-and-how-to-fix-it-9f4efaf1da35) but I can't find the reason why it's happening so frequently. It even happens with google accounts I own, so I know it's not an issue of revoking access. 

Once I start getting that `invalid_grant` error there's nothing I can do. I have tried multiple methods to manually refresh the tokens, but it's too late.. it's dead. For example: 

```js
//method 1
oauth2Client.refreshAccessToken(function(err) {
    if (err) return callback(err);
    return callback(err, oauth2Client);
});

//method 2
async function (req, res, callback) {
    const oAuth2Client = new google.auth.OAuth2(...);
    const refreshResponse = await oAuth2Client.refreshToken(req.body.refresh_token).catch(err => {
        return callback(err);
    });
    callback(null, refreshResponse);
}
```

How do I refresh the access_token? Am I requesting it incorrectly to begin with in passportjs? 

Here's my passport strategy for reference:
```js
    passport.use(new GoogleStrategy({
        clientID: process.env.GOOGLE_CLIENT_ID,
        clientSecret: process.env.GOOGLE_CLIENT_SECRET,
        scope: ['profile', 'email', 'openid'].concat(scopes),
        callbackURL: server[process.env.NODE_ENV].url + "/auth/google/callback",
    }, function (accessToken, refreshToken, tokens, profile, done) {
            // tokens.refreshToken is in here
            google.getOrCreateUser(tokens, profile, done);
    }
    ));
```

And my initial redirect is like:
```js
function redirect(req, res, callback) {
    var opts = {
        scope: ['profile', 'email', 'openid'].concat(scopes),
        accessType: 'offline',
        prompt: 'consent',
    };
    passport.authenticate('google', opts)(req, res, callback);
}
```

Any and all suggestions welcome, I'm banging my head on the wall over here. Thanks

**Comment by sofisl** [comment]
@bcoe, tagging this one for our work this week

**Comment by bcoe** [comment]
@jlippold  if the publishing status of your OAuth Application is "Testing", refresh tokens only last for 7 days, see: [refresh token expiration](https://developers.google.com/identity/protocols/oauth2).

Is there a chance you have your application set to testing?

**Comment by sofisl** [comment]
@jlippold just wondering if this suggestion worked for you!

**Comment by sofisl** [comment]
Will close this for now, although we did update documentation in #2553
