### ISSUE TITLE
Compute examples with error handling would be useful

### ISSUE THREAD

**Issue by garyo** [googleapis/google-api-nodejs-client#2364]
**Is your feature request related to a problem? Please describe.**
I'm trying to start and stop VM instances using the compute API, and it's not at all clear how to handle the API return value; what kinds of errors can happen, when should I retry vs. give up, etc.
For instance, `compute.instances.start` returns a `compute_beta$SchemaOperation` which has an `error` field, a couple of `httpError` fields, and warnings. How do I use those to know if the `start` call failed and needs to be retried, or the resource is exhausted, etc.?

I know that the operation is long-running, so I don't expect to get the final status of the `start` operation from this, but what kinds of errors are reported in the `error` field, vs. other errors that get sent later as the operation is progressing? And do I need to care about the `httpErrorMessage` at all?

 **Describe the solution you'd like**
Would love to have a fully worked example of `compute.instances.start` and `compute.instances.stop` and other API calls, with proper error handling, so we can see how it should be done. Alternatively, a document describing proper API calling procedures for `compute` including best-practice error handling.

 **Describe alternatives you've considered**
I look at the intellisense docs and try to figure out what likely failure modes are, and/or just try stuff.

**Comment by fhinkel** [comment]
Hi @garyo . We recommend that you use the [nodejs-compute SDK](https://github.com/googleapis/nodejs-compute). That library should also have the samples you're looking for.

**Comment by garyo** [comment]
@fhinkel thanks for the recommendation. Unfortunately that SDK has no typescript typings, and according to @JustinBeckwith in https://github.com/googleapis/google-cloud-node/issues/952 it'll never get them. 
In that, I asked: Any news on type decls for googleapis/nodejs-compute (aka @google-cloud/compute)?
He replied:
> Greetings @garyo! That is the one module that likely won't be getting types 😬 I would highly recommend using https://github.com/googleapis/google-api-nodejs-client instead.
...
> Yeah, it's not deprecated as of now, but there's so much code it would take a very, very long time to support types.

If that has changed, I would be more than happy to switch over. But as I'm fully typescript, I can't really use @google-cloud/compute.

**Comment by sofisl** [comment]
Hi @garyo, please refer to [these samples](https://github.com/googleapis/nodejs-compute/tree/main/samples), and feel free to reopen if this doesn't fit your needs.

**Comment by garyo** [comment]
Hi @sofisl; as I mentioned above, those samples are for the nodejs-compute SDK (@google-cloud/compute), not the googleapis/google-api-nodejs-client one I need. Only the latter one has typescript support, as far as I know. If that has changed, I'll close this ticket. (I can't reopen this myself but I think it should be reopened.)
