### ISSUE TITLE
Compute doc page is huge; consider splitting it up

### ISSUE THREAD

**Issue by garyo** [googleapis/google-api-nodejs-client#2365]
The autogenerated compute doc at https://googleapis.dev/nodejs/googleapis/latest/compute/classes/Resource$Instances-1.html is huge; even on my fast 32GB machine it takes several minutes for the page to render in Chrome. (It's not the download as far as I can tell, it's just the sheer page complexity.)

An easy thing to help would be to separate out alpha, beta, and v1 into separate pages. That would also reduce the visual duplication:
![image](https://user-images.githubusercontent.com/139975/93722706-c6470300-fb66-11ea-9523-0e0609a2a8c2.png)

**Comment by sofisl** [comment]
Hi @garyo, please refer to documentation [here](https://cloud.google.com/nodejs/docs/reference/compute/latest).
