### ISSUE TITLE
Docs artifacts on sample code not usable

### ISSUE THREAD

**Issue by lalilaloe** [googleapis/google-api-nodejs-client#2373]
See https://googleapis.dev/nodejs/googleapis/latest/drive/classes/Resource$Files-1.html#watch

The examples contain raw html code such as: `<p>,<a>` and unicodes `&#39; &quot`;. As far as i can see all docs on https://googleapis.dev/nodejs/googleapis/latest/index.html are affected which are many.

I think it has to do with the document parser that adds these artifacts and replaces urls with <a> tags. You can't use the copy function now because the code is invalid due to the artifacts.

![afbeelding](https://user-images.githubusercontent.com/9057622/94249065-a5443080-ff1f-11ea-9866-386bb6a39eed.png)

**Comment by fhinkel** [comment]
Thanks for reporting the issue @lalilaloe ! 

Duplicate https://github.com/googleapis/google-api-nodejs-client/issues/2194
