### ISSUE TITLE
Local Services API - Request contains an invalid argument.

### ISSUE THREAD

**Issue by mayrop** [googleapis/google-api-nodejs-client#2374]
#### Environment details
  - OS: MacOS
  - Node.js version: v12.16.3
  - npm version: 6.14.4
  - `googleapis` version: 60.0.1

#### Background
Not sure if this is a product issue or not, and I'm sorry if issue should not be here, but client library is still missing code to make it work (scopes are missing). There is no documentation available, but I found that the support was added to the clients for different languages (Node, [Ruby](https://github.com/googleapis/google-api-ruby-client/tree/master/generated/google/apis/localservices_v1), [PHP](https://github.com/googleapis/google-api-php-client-services/tree/master/src/Google/Service/Localservices), [Go](https://github.com/googleapis/google-api-go-client/tree/master/localservices/v1), etc.), so I assume it should be working. Also, the API is available in Google Developer Console. If the Local Services API is not ready yet to be used, I guess this issue can be closed.

People asking about the Local Services API:
  - https://support.google.com/google-ads/thread/63308856?hl=en
  - https://groups.google.com/g/adwords-api/c/_ApYeJ8o-Zc

#### Steps to reproduce
I took the code in [here](https://github.com/googleapis/google-api-nodejs-client/blob/d7a77a5b7e4945db4931158b57311dc8fcc73186/src/apis/localservices/v1.ts#L367). First, the scopes, there are no scopes [here](https://developers.google.com/identity/protocols/oauth2/scopes) for local services yet, but the code stopped complaining about permissions when using:
```javascript
scopes: [
      'https://www.googleapis.com/auth/adwords',
      'https://adwords.google.com/api/adwords',
      'https://adwords.google.com/api/adwords/',
      'https://adwords.google.com/api/adwords/cm'
]
```

But then no matter what parameters I add in the search consult, I always get:
```javascript
...
code: 400,
errors: [
    {
      message: 'Request contains an invalid argument.',
      domain: 'global',
      reason: 'badRequest'
    }
]
```

If I add a different parameter, for example `endDate.day.test` instead of `endDate.day`,  I can confirm that the error makes sense:
```javascript
  code: 400,
  errors: [
    {
      message: `Invalid JSON payload received. Unknown name "endDate.day.test": Cannot bind query parameter. Field 'day' could not be found in request message.`,
      reason: 'invalid'
    }
  ]
```

#### Related questions
- https://stackoverflow.com/questions/64049430/google-local-services-ads-api

**Comment by mayrop** [comment]
FYI, if I change query to: `query: "manager_customer_id:XXX-YYY-ZZZZ",`

I get the following error:

```txt
  code: 500,
  errors: [
    {
      message: 'Internal error encountered.',
      domain: 'global',
      reason: 'backendError'
    }
  ]
```

If I change the ID, let's say to 123, I get:

```
  code: 403,
  errors: [
    {
      message: 'The caller does not have permission',
      domain: 'global',
      reason: 'forbidden'
    }
  ]
```

Which means that I do get the correct permissions in place.

**Comment by Korvath85** [comment]
Can confirm, following the above steps through setting the scopes does get rid of permissions herrors.

I'm using a Typescript app, so my results may be different, but what I'm experiencing is that after building the client and sending the requirest, I receive an 'Internal Error encountered.'  Continuing to step through.

**Comment by mayrop** [comment]
Hi,

I got access to internal documentation from google and figured this out. This is a [gist](https://gist.github.com/mayrop/236e7ff55a7fb16b9b30437f00a52978) with the complete code that makes it work:

```javascript
  const url = oauth2Client.generateAuthUrl({
    // 'online' (default) or 'offline' (gets refresh_token)
    access_type: 'offline',
    // If you only need one scope you can pass it as a string
    // https://developers.google.com/identity/protocols/oauth2/scopes
    scope: ['https://www.googleapis.com/auth/adwords'],
  })
```

Then, the query will be:
```
query: 'manager_customer_id:XXXX'
```

Where XXX is the numeric number of the manager customer ID for the MCC account (without any dashes). See logic to get it [here](https://support.google.com/google-ads/thread/1467498?hl=en).

For detailed reports, also this can be used:
```
manager_customer_id:XXXX;customer_id:YYYY
```

**Comment by mayrop** [comment]
This is a [gist](https://gist.github.com/mayrop/236e7ff55a7fb16b9b30437f00a52978) with the complete code that makes it work:

```javascript
  const url = oauth2Client.generateAuthUrl({
    // 'online' (default) or 'offline' (gets refresh_token)
    access_type: 'offline',
    // If you only need one scope you can pass it as a string
    // https://developers.google.com/identity/protocols/oauth2/scopes
    scope: ['https://www.googleapis.com/auth/adwords'],
  })
```

Then, the query will be:
```
query: 'manager_customer_id:XXXX'
```

Where XXX is the numeric number of the manager customer ID for the MCC account (without any dashes). See logic to get it [here](https://support.google.com/google-ads/thread/1467498?hl=en).

For detailed reports, also this can be used:
```
manager_customer_id:XXXX;customer_id:YYYY
```

**Comment by sofisl** [comment]
Hi @mayrop, sounds like you've been able to find a solution to get the sample working!

Our source code contains inline samples in the comments, and it looks like [this one](https://github.com/googleapis/google-api-nodejs-client/blob/19bfebf7da7ada39b12b37ed0ed0b46113f521a7/src/apis/localservices/v1.ts#L358) contains the correct parameters and mentions customer ID as well. Are there any problems you're still encountering that we could add for the inline code samples?
