### ISSUE TITLE
Following Contributing docs fails locally

### ISSUE THREAD

**Issue by elierotenberg** [googleapis/google-api-nodejs-client#2377]
#### Environment details

  - OS: Windows 10
  - Node.js version: 13.10.1
  - npm version: 6.13.7
  - `googleapis` version: 60.0.1

#### Steps to reproduce

  1. Checkout repository
  2. `npm run samples-test`, `npm run system-test` (without prior `npm run fix`).

Working on a PR, I checkout out the repo and followed the [CONTRIBUTING](https://github.com/googleapis/google-api-nodejs-client/blob/master/CONTRIBUTING.md) instructions.

I ran across several issues, similar to those encountered in [`nodejs-googleapis-common`](https://github.com/googleapis/nodejs-googleapis-common/issues/327).

### Not Windows-related

The following dependencies were already in the [samples `package.json`](https://github.com/googleapis/google-api-nodejs-client/tree/master/samples) but caused `npm run samples test` to fail:
- `@google-cloud/local-auth`,
- `nconf`,
- `express`.

This is because the samples subpackage isn't installed. It is installed as a side effect of `npm run prelint` which may hide the problem, e.g. if `prelint` has run at least once.

Running `npm install` from the `samples` subdir solved it.

### Windows related

The following error is raised when running `npm run samples-test` on Windows:
```
  1) Auth samples
       should support JWT:
     Error: EPERM: operation not permitted, symlink
         'XXXXXX\google-api-nodejs-client\test\fixtures\service.json' ->
         'XXXXXX\google-api-nodejs-client\samples\jwt.keys.json'
```

This is likely because [`fs.symlinkSync`](https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/test/test.samples.auth.js#L44) doesn't work properly on Windows on files (altough it works with directories using `junction` type) or requires privilege elevation.

As a workaround, copying the file instead of symlinking it solved it.

### Authentication related

The problems described in [this issue](https://github.com/googleapis/nodejs-googleapis-common/issues/327) also apply.

**Comment by bcoe** [comment]
@elierotenberg this answers my question 😄 

Is there a tracking issue on Node.js (or is this a known limitation of Windows?). I'm on the Node.js tooling team, and would love  to fix odd things like this.

**Comment by elierotenberg** [comment]
I couldn't find an issue on Node.js, because I believe it "works as intented" on Windows: symlinks in "dir" or "file" mode require elevated privileges, "junction" doesn't but only works on directories.
See also:
* [a minimal reprod example](https://github.com/elierotenberg/workbench/commit/8df3052ce80fd0cf2455ae6bb08e71da5904b0ee)
* [Official Windows Doc on links](https://docs.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions#junctions)
* [related issue on nodejs repo](https://github.com/nodejs/node/issues/18518)

Another option would be to symlink (using junction on Windows, `type` being ignored on non-Windows hosts) the parent folder and use the original filename, would that be better?
