### ISSUE TITLE
Split into smaller libraries, 72mb is too much if you need just one service's api.

### ISSUE THREAD

**Issue by truestep** [googleapis/google-api-nodejs-client#2381]
Current size of the google-api-nodejs-client lib is 72mb. My whole nodejs app is 15mb with already installed npm_modules, I choose them carefully. I don't need the whole google-api-nodejs-client I just need androidPublisher v3. Please make it possible to install every "google-api" separately. 

Also it's just ts files there https://github.com/googleapis/google-api-nodejs-client/tree/master/src/apis/androidpublisher .Currently I have to take the v3.ts, compile the file and include in my project as js file. I'm not using ts, I'm using latest nodejs with pure javascript and trying to avoid unnecessary steps and libraries. In my case it's not convenient at all.

**Comment by JustinBeckwith** [comment]
👋 we hear ya, this is something we've wanted to do for a while.  We're tracking this over in #806

**Comment by NoelAbrahams** [comment]
Yes, please. I simply hit the roof after installing googleapis and checking `node_modules`. This has a significant detrimental impact on cloud deployments.
