### ISSUE TITLE

Прошу вашего содействия в решении вопроса о посещении запретного контента

### ISSUE THREAD

**Issue by Dimasik0** [googleapis/google-api-nodejs-client#2383]
kizya0010@GSuite.com

**Comment by JustinBeckwith** [comment]
Greetings @Dimasik0!  Apologies, but we can only really offer help in English on this tracker.  A quick Google translate tells me you're asking: "I ask for your assistance in resolving the issue of visiting prohibited content".  If this is related to the google apis npm module here, please add more details!
