### ISSUE TITLE
Passing “region” to AI Platform (ML V1) endpoint 

### ISSUE THREAD

**Issue by aditya-malte** [googleapis/google-api-nodejs-client#2389]
Hi,
I’d like to pass the “region” through the Nodejs client library while using the ML endpoint(AI Platform). 
My deployed model exists on the us-central1-ml endpoint and hence cannot be found with just ml.googleapis.com endpoint.
Any help would be appreciated 
Thanks

Aditya Malte

**Comment by aditya-malte** [comment]
cc @shah-sid

**Comment by JustinBeckwith** [comment]
Good news!  You can absolutely override the API endpoint :) It looks something like this:
```js
const {google} = require('googleapis');
const compute = google.compute({
  version: 'v1',
  rootUrl: 'https://www.googleapis.com/compute',
});
```

The `rootUrl` option will override the default rootUrl that the service is configured to use.  Give that a shot, and let us know how it goes!
