### ISSUE TITLE
Using googleapi node client with Google Civic API

### ISSUE THREAD

**Issue by ooledezma** [googleapis/google-api-nodejs-client#2391]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hi, is it possible to provide an example of how to use the this node package with google civic info. I am looking for an example to call different properties such as elections and voterinfoquery.

Thank you

**Comment by JustinBeckwith** [comment]
Greetings!  We try to generate some basic examples of how to use every API along with the code itself.  I'd try giving those a look, and searching specifically for `@example`:
https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/civicinfo/v2.ts

For more conceptual documentation on the API itself, or to experiment with the REST API and such, check out these docs:
https://developers.google.com/civic-information

If you run into specific problems using the library let us know!
