### ISSUE TITLE
Create,Update,Delete operations for Google Chat API

### ISSUE THREAD

**Issue by RidhwaanDev** [googleapis/google-api-nodejs-client#2398]
Currently there is no support to programmatically create spaces or add/remove members to spaces. There is only option to get/list the members in space. In order to create powerful apps/plug-ins that interact with Google Chat API, I highly suggest adding these features.

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the suggestion!  In this repository, we really only manage the JavaScript bindings to these APIs.  For feature requests specific to the Chat API, please file an issue over here:
https://issuetracker.google.com/issues/new?component=350158&template=1047215

And for general support links and such for that API, check this out:
https://developers.google.com/hangouts/chat/support

Hope this helps!
