### ISSUE TITLE
Issues finding ./docs

### ISSUE THREAD

**Issue by NikhilPunwaney** [googleapis/google-api-nodejs-client#2416]
*UNCAUGHT EXCEPTION*
Error: Cannot find module './docs'
Require stack:
/XXX/node_modules/googleapis/build/src/apis/index.js
/XXX/node_modules/googleapis/build/src/googleapis.js
/XXXh/node_modules/googleapis/build/src/index.js
/XXX/server-common/common/gmailLogic.js
/XXX/server-api/routes/users.js
/XXX/server-api/app.js
/XXX/bin/www
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/XXX/node_modules/googleapis/build/src/apis/index.js',
    '/XXX/node_modules/googleapis/build/src/googleapis.js',
    '/XXX/node_modules/googleapis/build/src/index.js',
    '/XXX/server-common/common/gmailLogic.js',
    '/XXX/server-api/routes/users.js',
    '/XXX/server-api/app.js',
    '/XXX/bin/www'
  ]
}

**Comment by JustinBeckwith** [comment]
Greetings!  A call stack with no steps on how to reproduce the issue, or any details on your environment is not going to help us very much here :) Could I trouble you to add some of the details we ask for in the [issue template](https://github.com/googleapis/google-api-nodejs-client/issues/new?template=bug_report.md)?

**Comment by NikhilPunwaney** [comment]
Hi Justin,

This was on importing googleapis; 

Node version: v14.10.1
npm version: 6.14.8
googleapis: 62.0.0

**Comment by bcoe** [comment]
@NikhilPunwaney mind providing an example of the JavaScript you're running to perform the import, and how you're running the code?

**Comment by NikhilPunwaney** [comment]
@bcoe 

the error comes up on launching the server: 
forever -w bin/www

In www:
const server = require('server-common/server');
const app = require('../app');
server.run(app, 8081);

In server:
module.exports.run = (app, defaultPort) => {
    port = normalizePort(process.env.PORT || defaultPort);
    app.set('port', port);
    let server;
    const httpsOptions = {
            key: fs.readFileSync(__dirname + '/cert.key'),
            cert: fs.readFileSync(__dirname + '/cert.pem'),
            requestCert: false,
            rejectUnauthorized: false,
    };
    server = https.createServer(httpsOptions, app);
    server.on('error', onError);
    server.listen(port, function () {
        console.log(
            'Express server listening on port ' + server.address().port
        );
    });
};

In app:
app.use('/users', users);

How I'm importing it: const { google } = require('googleapis');

**Comment by bcoe** [comment]
@NikhilPunwaney please try the following, inside your project directory:

* `rm -rf node_modules`.
* `rm package-lock.json`.
* `npm i`.

If you continue to run into issues, could you publish your example to an example repository on GitHub, so that we can attempt to reproduce.

**Comment by NikhilPunwaney** [comment]
I was able to get it working by switching v3 to v1 in google.gmail({ version: 'v1', auth });

Thank you

@bcoe

**Comment by plash** [comment]
> @NikhilPunwaney please try the following, inside your project directory:
> 
> * `rm -rf node_modules`.
> * `rm package-lock.json`.
> * `npm i`.
> 
> If you continue to run into issues, could you publish your example to an example repository on GitHub, so that we can attempt to reproduce.

I am facing the same issue and tried this approach, but it did not work. 
Also, instead of gmail, I am using the `youtube_v3` from `googleapis` module.

Please suggest if you have the possible working solution.
