### ISSUE TITLE
All files include sourceMappingURL linking to nonexistent map file

### ISSUE THREAD

**Issue by DormouseSays** [googleapis/google-api-nodejs-client#2422]
When installing the current version (63.0.0) through npm, every file ends with a link to a source map that's no longer shipped with the library and shows errors in debugger output. 

For example, `googleapis/build/src/index.js` ends with the line `//# sourceMappingURL=index.js.map` but there is no index.js.map file.

This causes a huge list of errors when attempting to debug any application that uses `googleapis`, one for each file in the library. This example is from debugging through VS Code but it should be the same in any debugger that loads source maps.

```
Could not read source map for file:///[PATH]/node_modules/googleapis/build/src/index.js: ENOENT: no such file or directory, open '[PATH]/node_modules/googleapis/build/src/index.js.map'
...
Could not read source map for file:///[PATH]/node_modules/googleapis/build/src/apis/youtubereporting/v1.js: ENOENT: no such file or directory, open '[PATH]/node_modules/googleapis/build/src/apis/youtubereporting/v1.js.map'
```

#### Environment details

  - OS: OSX 10.13
  - Node.js version: v12.14.1
  - npm version: 6.14.8
  - `googleapis` version: 63.0.0

#### Steps to reproduce

1. `npm install googleapis`
2. Create a new nodejs file that includes `const {google} = require('googleapis');`
3. Debug the nodejs file. In VS Code I used the following launch configuration:
```
{
      "type": "node",
      "request": "launch",
      "name": "run test",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/test.js"
    }
````
4. check the debugger output

**Comment by JustinBeckwith** [comment]
@bcoe I kinda want to start shipping source maps again with our packages.  What do you think of doing this broadly?

**Comment by bcoe** [comment]
> @bcoe I kinda want to start shipping source maps again with our packages. What do you think of doing this broadly?

@JustinBeckwith the tradeoff is that it does significantly increase the size of a module... I'm on the fence.

What I've done in yargs is have a separate tsconfig for testing, which turns off source map generation. This would be an alternate way to prevent the errors that @primedb  and @DormouseSays are seeing.
