### ISSUE TITLE
Admob Api

### ISSUE THREAD

**Issue by baffonero** [googleapis/google-api-nodejs-client#2427]
Could you provide an admob example?
I can't figure out how methods in admob reference are implemented in google-api-nodejs-client:

https://developers.google.com/admob/api/v1/reference/rest/

Thanks

**Comment by sofisl** [comment]
Hi @baffonero,

We have examples of using every method inside of the library you can browse through [here](https://github.com/googleapis/google-api-nodejs-client/blob/b706742847c0c0103cf5f7b0b52d5d34a800b358/src/apis/admob/v1.ts#L498). We also rely on the reference docs that you have encountered above. However, if you have any specific questions on usage, feel free to post them here!
