### ISSUE TITLE
No Push Notification HTTP headers in typescript definiton files

### ISSUE THREAD

**Issue by coldner** [googleapis/google-api-nodejs-client#2446]
Google Api's Push Notifications emit HTTP headers that can be used to identify channels https://developers.google.com/calendar/v3/push#headers

We need someting like:

```
import * as http from 'http';

export interface PushNotificationHeaders extends http.IncomingHttpHeaders {
  'x-goog-channel-id': string,
  'x-goog-channel-token'?: string,
  'x-goog-channel-expiration'?: string,
  'x-goog-resource-id': string,
  'x-goog-resource-uri': string,
  'x-goog-resource-state': 'sync' | 'exists' | 'not_exists',
  'x-goog-message-number': string,
}
```

**Comment by JustinBeckwith** [comment]
Greetings!  I'm having a little trouble figuring out what you're asking for :) The headers in a request should be available via `res.headers`:

```js
const res = await calendar.events.lilst({ ... });
console.log(res.headers);
```

`headers` in this case should be of type `{ [index: string]: any };`, since we can't reasonably predict which headers will come back with any response.  

Are you running into a particular problem?  Or just looking for super strict TypeScript types on `Headers`?

**Comment by coldner** [comment]
Hi!
That's not what I'm looking for ;)
I used:
```
await calendar.events.watch({
  requestBody: {
    type: 'web_hook',
    address: `${MY_SERVER_URL}/api/notifications/google`,
  },
});
```
and then my server is listening for Push Notifications from Google Api:
```
app.post('/api/notifications/google', (req, res) => {
  console.log(req.headers['x-goog-channel-id']);
  res.send();
});
```
It would be nice to type request headers from Google instead of using magic strings ;)
```
app.post('/api/notifications/google', (req, res) => {
  const headers = req.headers as PushNotificationHeaders;
  console.log(headers['x-goog-channel-id']);
  res.send();
});
```

**Comment by JustinBeckwith** [comment]
Ahhh, I get it now.  Sadly, 100% of the code in this repository is auto-generated from service definitions.  That definition for calendar is here:
https://calendar-json.googleapis.com/$discovery/rest?version=v3

We're trying to support hundreds of APIs with this package, so we can't really add customizations like this that are outside of the structured API definition.  While I agree it would be nice, this is something that would have to come from outside of this library :/
