### ISSUE TITLE
Samples for Android Publisher API

### ISSUE THREAD

**Issue by risalfajar** [googleapis/google-api-nodejs-client#2447]
**Is your feature request related to a problem? Please describe.**
I find it kind of hard to understand how to use the API, please provide samples.

**Comment by sofisl** [comment]
Hi @risalfajar, 

We have examples of using every method inside of the library you can browse through [here](https://github.com/googleapis/google-api-nodejs-client/blob/90db68e517294d0e398e78a01361606d8406db9d/src/apis/androidpublisher/v3.ts#L1301) (you can also look through the other versions as well). We also rely on these r[eference docs](https://developers.google.com/android-publisher
). However, if you have any specific questions on usage, feel free to post them here!
