### ISSUE TITLE
Add  typescript samples

### ISSUE THREAD

**Issue by steveja42** [googleapis/google-api-nodejs-client#2453]
There don't seem to be any samples in typescript, only javascript.  It would be helpful if some typescript samples were added that illustrate how to use the type def files and  get things correctly typed.

**Comment by increos** [comment]
It will be also very helpful to add samples for using Server-to-Server, 2 legged authentication between Cloud Functions and Calendar API's

**Comment by dalepo** [comment]
I mean, documentation is terrible enough (as usual with google) to not have a basic example
