### ISSUE TITLE
updateShapeProperties complaining about missing fields property

### ISSUE THREAD

**Issue by trjoshjimenez** [googleapis/google-api-nodejs-client#2455]
Details

  - OS: Manjaro Linux
  - Node.js version: 10
  - npm version: 6
  - `googleapis` version: 51.0.0

#### Steps to reproduce

  1. We are sending a google slide API request with updateShapeProperties:
```json
        "updateShapeProperties": {
            "objectId": objectId,
            "shapeProperties": {
                "shapeBackgroundFill": {
                    "solidFill": {
                        "color": {
                            "rgbColor": {
                                "red": r,
                                "green": g,
                                "blue": b
                            }
                        },
                        "alpha": 1
                    }
                },
                "outline": {
                    "outlineFill": {
                        "solidFill": {
                            "color": {
                                "rgbColor": {
                                    "red": 0,
                                    "green": 0,
                                    "blue": 0
                                }
                            },
                            "alpha": 0.1
                        }
                    },
                },
                "contentAlignment": "MIDDLE"
            },
            "fields": "*"
        }
```
where `objectId` comes from one of any `pageElement` we get from `slide.pageElements`

  2. We get a 400 response that states:
```
message: ""Invalid requests[2].updateShapeProperties: At least one field must be listed in 'fields'. (Use '*' to indicate all fields.)
```

This somehow used to work the past few months, and was wondering why it suddenly doesn't work right now. Did we have any changes or updates on the `updateShapeProperties` API?

**Comment by JustinBeckwith** [comment]
Greetings!  At a glance, what you're doing seems to be right.  In this repository, we really only handle issues related to the npm module itself.  Could I trouble you to give the request a try in the API explorer?
https://developers.google.com/slides/reference/rest/v1/presentations/batchUpdate

If the issue happens there, it means this is an underlying API issue and I can get you pointed in the right direction :)
