### ISSUE TITLE
Error: Google Local Services API - 403 Forbidden 

### ISSUE THREAD

**Issue by pyeldi** [googleapis/google-api-nodejs-client#2477]
We’re currently pulling the Google Local Services reports data down through the UI on a weekly basis. These reports can be accessed using the [MCC Reports](https://adwords.google.com/localservices/mccreports) We would like to automate this process and download this data using the Google Local Services API. We're sending the HTTP Get request to “https://localservices.googleapis.com/v1/accountReports:search” and “https://localservices.googleapis.com/v1/detailedLeadReports:search”. But when we send the get request to the Google Local Services API, we’re getting the following errors. 

{
"error": {
"code": 403,
"message": "Request had insufficient authentication scopes.",
"status": "PERMISSION_DENIED"
}
}

403 Forbidden 

Thanks,
Pavan

**Comment by dhbarker** [comment]
Any updates on this Permission Denied error and what we maybe doing wrong?

**Comment by JustinBeckwith** [comment]
Greetings!  This issue tracker is for the `googleapis` npm module - are you using this module to try making the requests?  If so, can you share the code you're using?  

Taking a look at the underlying discovery docs we use to generate this API, it seems like they don't define a set of required scopes... which I agree would probably make this difficult.  I would suggest posting this question where there are exports on the Ads API itself, over here:
https://groups.google.com/g/adwords-api

Hope this helps!

**Comment by pyeldi** [comment]
@JustinBeckwith This is not AdWords API related issue, this is related to Google Local Services API. Is the URL that you shared is the right place to post the questions related to Google Local Services? We're using PowerShell to make the requests. Here is the code.

`$requestUri = "https://www.googleapis.com/oauth2/v4/token"

$body = @{
  code="XXXXXXXXXXX";
  client_id="XXXXXXXXXXX.apps.googleusercontent.com";
  client_secret="XXXXXXXXXXX";
  redirect_uri="http://localhost/Google/";
  scope = "https://www.googleapis.com/auth/adwords";
  grant_type="authorization_code"; # Fixed value
};

$tokens = Invoke-RestMethod -Uri $requestUri -Method POST -Body $body;

# Store refreshToken
Set-Content $PSScriptRoot"\refreshToken.txt" $tokens.refresh_token

# Store accessToken
Set-Content $PSScriptRoot"\accessToken.txt" $tokens.access_token

$accessToken = $tokens.access_token;
$refreshToken = $tokens.refresh_token;

$refreshTokenParams = @{
  client_id="XXXXXXXXXXX.apps.googleusercontent.com";
  client_secret="XXXXXXXXXXX";
  refresh_token=$refreshToken;
  grant_type="refresh_token"; # Fixed value
}
$tokens = Invoke-RestMethod -Uri $requestUri -Method POST -Body $refreshTokenParams;
$accessToken = $tokens.access_token;

$requestUri = "https://localservices.googleapis.com/v1/accountReports:search?query=manager_customer_id:XXX-XXX-XXXX"
Invoke-RestMethod -Headers @{Authorization = "Bearer $accessToken"} -Uri $requestUri -Method GET -ContentType 'application/json'
`

**Comment by JustinBeckwith** [comment]
It doesn't look like you're using this library - are you using nodejs and the `googleapis` package?  Is this PHP code?

**Comment by pyeldi** [comment]
It's a PowerShell

**Comment by dhbarker** [comment]
@pyeldi can you confirm if the PowerShell code is using nodejs and the googleapis package?

**Comment by sofisl** [comment]
As an update, I think the correct scope is: https://www.googleapis.com/auth/adwords.
