### ISSUE TITLE
Google voice example

### ISSUE THREAD

**Issue by omarcostahamido** [googleapis/google-api-nodejs-client#2481]
Following what you wrote [here](https://github.com/googleapis/google-api-nodejs-client#samples) I am asking for a google voice example.

thank you,

**Comment by sofisl** [comment]
Hi @omarcostahamido! I don't believe we a library for that API yet! Do you have a specific API name in mind [here](https://github.com/googleapis/google-api-nodejs-client/tree/master/src/apis)?

**Comment by omarcostahamido** [comment]
Hi @sofisl 
Hum, I'm not sure.
What I want to be able to do is programmatically send me and my family an sms.
I thought google voice, which I use, would be nice for this.
Do you have any solution in mind?

**Comment by sofisl** [comment]
Hi @omarcostahamido,

I think you can do this many ways, but at the end of the day you'll want to use a third-party service like one listed [here](https://cloud.google.com/appengine/docs/standard/php/mail/sending-messages).

For your use case, I might recommend just starting with a [Cloud Function](https://cloud.google.com/functions/?utm_source=google&utm_medium=cpc&utm_campaign=na-US-all-en-dr-bkws-all-all-trial-e-dr-1009135&utm_content=text-ad-none-any-DEV_c-CRE_338004603063-ADGP_Hybrid+%7C+AW+SEM+%7C+BKWS+%7C+RLSA+%7C+US+%7C+en+%7C+EXA+~+Compute+~+Functions+~+gcp+cloud+functions-KWID_43700042023475590-aud-664745643345:kwd-289154591473&utm_term=KW_gcp%20cloud%20functions-ST_gcp+cloud+functions&gclid=CjwKCAiAiML-BRAAEiwAuWVggtDhPKeNc07CjMBlh3LzLUpp-D9kXhLU6gkF0uOwmpdHHbgjHpOJFBoCj7AQAvD_BwE), as it might be the most lightweight solution for this goal.

Hope this helps!
