### ISSUE TITLE
which proxies do you use?

### ISSUE THREAD

**Issue by gadget2recycle** [googleapis/google-api-nodejs-client#2484]
It's not proxies? Kevin it's the bot which has stopped working. Please fix it if you can ASAP. Thanks for all your efforts 

which proxies do you use?

__Originally posted by @KevinLage in https://github.com/KevinLage/YouTube-Livestream-Botter/issues/199#issuecomment-743280278__

**Comment by Raz92** [comment]
Hattps proxy I am using
