### ISSUE TITLE
Please guide how to perform EMAIL_LOG_SEARCH using api

### ISSUE THREAD

**Issue by amadeus-x1** [googleapis/google-api-nodejs-client#2487]
Gsuite admin console has a report called email log search which details all the emails sent, receivers and their senders, but I am not able to find a corresponding api in this package.

**Comment by JustinBeckwith** [comment]
Greetings!  Unfortunately, I don't think that's something this npm module is going to provide.  Everything we have here is generated from the documents that are provided here:
https://www.googleapis.com/discovery/v1/apis/

Poking about, it looks like this is the API you want to use:
https://developers.google.com/admin-sdk/email-audit

However ...  it looks to support a really old version of Google's APIs - one so old, I don't think we can support it with this library (sorry).  What I would recommend - I would follow the links in this doc here, and submit a request to the team to provide a modern version of email search through the Admin SDK Reports API:
https://developers.google.com/admin-sdk/email-audit/support

Sorry this feels like I'm shuffling you off to another issue tracker - but there's really nothing we can do with this particular API :/  Adding in @sqrrrl in case he has anything else to add here.
