### ISSUE TITLE
Login required: SDM

### ISSUE THREAD

**Issue by mddanishyusuf** [googleapis/google-api-nodejs-client#2489]
Hello there,

I'm setting up automation for google nest camera & using OAuth flow in my code.

This code is giving the Error.

```
const oauth2Client = new google.auth.OAuth2(
      "https://www.googleapis.com/auth/sdm.service"
    );

    oauth2Client.setCredentials({
      access_token: "",
      refresh_token: "",
      scope: "",
      token_type: "Bearer",
      expiry_date: 1608477748018,
    });

    const devicesList = google
      .smartdevicemanagement("v1")
      .enterprises.devices.list({ parent: "enterprises/my-enterprise" });

```

Error:

<img width="591" alt="Screenshot 2020-12-20 at 8 27 11 PM" src="https://user-images.githubusercontent.com/9165019/102716409-bffd2a00-4301-11eb-8b6c-7499d40df758.png">

Please let me know where I'm doing wrong.

**Comment by JustinBeckwith** [comment]
Greetings!  To use the OAuth2 client this way, you would need to include a refresh token, and / or access token.  What's your intended usage here?  We include a lot of info on how to use the OAuth2 client here:
https://github.com/googleapis/google-api-nodejs-client#oauth2-client
