### ISSUE TITLE
Google Local Services API 403 insufficient authentication scopes error

### ISSUE THREAD

**Issue by dhbarker** [googleapis/google-api-nodejs-client#2491]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
Hello, we are having a permissions issue with the Google Local Service API we cannot figure out.  Can you help?  

Here is the error:
{
    "error": {
        "code": 403,
        "message": "Request had insufficient authentication scopes.",
        "status": "PERMISSION_DENIED"
    }
}

We are successfully querying the API, but it’s telling us that we don’t have the proper permissions.  We don't understand why we are getting this error.  We have tried using PowerShell and Postman and we get the same error.  Based on the documentation it looks like a 2-step process.  First, you retrieve an access token via OAuth, then you use that token to make a request to the reporting API to get the data.  The request get the token is working fine, but the subsequent request to retrieve data using that token is failing with error.  In a previous ticket there was discussion around scope.  Its our understanding the scope is part of what you pass in to get the access token, and we are using the scope that the documentation says to use. It’s not that we can’t access the API.  We are successfully querying the API, but it’s telling us that we don’t have the proper permissions to retrieve the data.

Questions:
1 - The documentation itself shows examples using Curl, which is a command line web client.  Can we use any valid web client to access the API or does it work best with a specific client?
2 - Can you provide an example / direction for how to use PowerShell or Postmate to successfully retrieve data from the LSA API?
3 - How can we grant the proper permissions to our token to retrieve the data?

Thanks
David

**Comment by sofisl** [comment]
@dhbarker, I'm reaching out to the documentation team to see what's going on. I'm hoping it's a documentation issue but it might be more.

Connected to #2477

**Comment by dhbarker** [comment]
Thank you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dhbarker** [comment]
Hello, just checking to see if there have been any updates from the documentation team.

**Comment by dhbarker** [comment]
Hi @sofisl .  I wanted to see if the documentation team has any feedback on the LSA API issue we are having.

**Comment by dhbarker** [comment]
Hi @sofisl . Just checking to see if the docmentation team has given you any feedback on the LSA API issue we are having.

**Comment by sofisl** [comment]
Hi @dhbarker, I apologize we do not have any updates yet. 

Internal reference bug: #176252216

**Comment by dhbarker** [comment]
Hi @sofisl , any updates yet on the internal bug #176252216?

**Comment by sofisl** [comment]
@dhbarker, it seems that you can use it with any web client. Can you try again with this scope? https://www.googleapis.com/auth/adwords.

**Comment by dhbarker** [comment]
Hi @sofisl thanks we were able to pull data from the API.  But now we can only seem to pull Month to Date data from the Account report.  Do you know how to pull just a specific date using the API.  We have tried several things and we keep getting month to date data.

**Comment by dhbarker** [comment]
I also wanted you to know we have looked at several posts here in GitHub and didn't see any related to how to pull a specific date range of data from the API.  We are even exploring subtracting one day from the next in our data base to see if we can calculate a specific days worth of data from the API.  Any tips or assistance you can provide would be greatly appreciated.

**Comment by sofisl** [comment]
@dhbarker, Would you mind opening up a new issue for these questions just to help other people in their search? Thanks in advance!
