### ISSUE TITLE
Investigate OOM while compiling TypeScript on Node.js 10.x

### ISSUE THREAD

**Issue by sofisl** [googleapis/google-api-nodejs-client#2492]
We are not able to continue merging generator PRs because our tests run out of memory. See https://github.com/googleapis/google-api-nodejs-client/pull/2476.

We'll need to figure out some way of breaking up our test suites so we don't run out of memory.
cc @bcoe

**Comment by JustinBeckwith** [comment]
Interesting! Taking a closer look at the failure, it appears to only happen on node 10, and it looks like *TypeScript* is what's causing the OOM, not our tests:

```
> googleapis@66.0.0 compile /home/runner/work/google-api-nodejs-client/google-api-nodejs-client
> tsc -p .

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

<--- Last few GCs --->
```

I would be tempted to look at any recent TypeScript releases, and possibly see if something happened there.

**Comment by sofisl** [comment]
@bcoe added a fix for this
