### ISSUE TITLE
Refresh token and invalid_grant error confusion

### ISSUE THREAD

**Issue by boberbober** [googleapis/google-api-nodejs-client#2494]
I have successfully implement the whole OAuth process using googleapis in my app and it works but I still get the `invalid_grant` error every now and then. I searched for a solution to this and it seems there is a lot of confusion as to how the tokens should work.

When I want to make a call to one of the APIs I set the credentials like so:

```javascript
oauth2Client.setCredentials({
    access_token: "ACCESSTOKEN",
    refresh_token: "REFRESHTOKEN"
})
```

and set an event listener for `.on('tokens')` to get the new set of tokens in case the current ones are expired and when that happens I save them to the db but the `invalid_grant` error is still thrown on that call. Only the next call with updated tokens eventually works (or sometimes doesn't and the whole integration needs to be reauthenticated).

Should I send the `refresh_token` with _every_ API call in case the tokens are expired and new ones will be issued? Some people suggested this issues a new token on every call and eventually exceeds the token quota for the user.

How do I get a new working token before making the API call so that there's no `invalid_grant` error?

There seems to be a widespread confusion about how those tokens work. It would be nice if it was explained in the documentation.

**Comment by bcoe** [comment]
@boberbober the access token you should need to save is the `refresh_token`, when setting credentials likewise this is what I would provide:

```js
oauth2Client.setCredentials({
  refresh_token: `STORED_REFRESH_TOKEN`
});
```

On the first request the `refresh_token` is then exchanged for an `access_token`.

If this is not working, could you provide an example of the error message you're seeing (ensuring there's no secrets in it, e.g., the token).

**Comment by bl4ckck** [comment]
> @boberbober the access token you should need to save is the `refresh_token`, when setting credentials likewise this is what I would provide:
> 
> ```js
> oauth2Client.setCredentials({
>   refresh_token: `STORED_REFRESH_TOKEN`
> });
> ```
> 
> On the first request the `refresh_token` is then exchanged for an `access_token`.
> 
> If this is not working, could you provide an example of the error message you're seeing (ensuring there's no secrets in it, e.g., the token).

how to exchange the refresh token to access token?

**Comment by bcoe** [comment]
@bl4ckck on the first request, it should automatically do so for you, is this not working?

**Comment by bl4ckck** [comment]
I'm doing like this to get the first access token.

```js
const oAuth2Client = new google.auth.OAuth2(
  process.env.GOOGLE_CLIENT_ID,
  process.env.GOOGLE_CLIENT_SECRET,
  process.env.CALLBACK_URL
);

app.post("/auth/google/redirect", (req, res) => {
  setToken(req.body.code)
    .then((result) => {

      res.json({
        token: result,
      });
    })
    .catch((err) => {
      res.status(500).send({ error: "There was an error signing in" });
      console.log(err);
    });
});

async function setToken(code) {
  const {tokens} = await oAuth2Client.getToken(code);

  return JSON.stringify(tokens.access_token);
}
```

And call the Google Drive API.
```js
async function getListDrive(tokens, authuser) {
  oAuth2Client.setCredentials({ access_token: tokens });

  return listFiles(oAuth2Client, authuser);
} 
```

**Comment by bl4ckck** [comment]
@bcoe I'm doing like this to get the first access token.

```js
const oAuth2Client = new google.auth.OAuth2(
  process.env.GOOGLE_CLIENT_ID,
  process.env.GOOGLE_CLIENT_SECRET,
  process.env.CALLBACK_URL
);

app.post("/auth/google/redirect", (req, res) => {
  setToken(req.body.code)
    .then((result) => {

      res.json({
        token: result,
      });
    })
    .catch((err) => {
      res.status(500).send({ error: "There was an error signing in" });
      console.log(err);
    });
});

async function setToken(code) {
  const {tokens} = await oAuth2Client.getToken(code);

  return JSON.stringify(tokens.access_token);
}
```

And call the Google Drive API.
```js
async function getListDrive(tokens, authuser) {
  oAuth2Client.setCredentials({ access_token: tokens });

  return listFiles(oAuth2Client, authuser);
} 
```

**Comment by bcoe** [comment]
@bl4ckck @boberbober the first time you're authenticating the client, try following this example to get the `refresh_token` and `access_token`:

https://github.com/googleapis/google-auth-library-nodejs#a-complete-oauth2-example

Then, simply store the `refresh_token`, and instantiate the client like this:

```js
const oAuth2Client = new OAuth2Client(
  keys.web.client_id,
  keys.web.client_secret,
  keys.web.redirect_uris[0]
);

oauth2Client.setCredentials({
  refresh_token: `STORED_REFRESH_TOKEN`
});
```

The `access_token` is short lived, and will not work for an extended period of time, whereas the `refresh_token` can be used to fetch an `access_token`, and is long lived.

**Comment by bl4ckck** [comment]
@bcoe thanks, I think I've resolved my problem here.

When I put access_token and refresh_token to setCredentials, it works and automatically replaces the previous access token.
```js
oAuth2Client.setCredentials(tokens); //access_token, refresh_token, expiry
```

And I can obtain new access token after refreshing with this function
```js
oAuth2Client.getAccessToken((err, token) => {
        console.log("new access_token: "+token)
})
```

**Comment by bcoe** [comment]
@boberbober are you able to get the approach discussed in @bl4ckck and my last posts working for yourself?

**Comment by parkerproject** [comment]
I seem to have this error intermittently ``No access, refresh token or API key is set`` even though I set my ``refresh_token`` on every call;
`` oauth2Client.setCredentials({ refresh_token, access_token, forceRefreshOnFailure: true })``
also tried this `` oauth2Client.setCredentials({ refresh_token, access_token })`` still getting that error

**Comment by alexander-fenster** [comment]
@parkerproject Is this still a problem? If it is, please open a new issue describing the environment you're in, the specific API you're calling, and providing as much details as possible. Also, we updated the documentation for refresh tokens [here](https://github.com/googleapis/google-api-nodejs-client#handling-refresh-tokens).

Since this issue is originally about a different problem, I'll close it now.
