### ISSUE TITLE
How to Switch Account Google Drive?

### ISSUE THREAD

**Issue by bl4ckck** [googleapis/google-api-nodejs-client#2502]
I managed to get the drive file download URL from a user who has logged in through the server. And when I try to log in again with my second account and get the file download URL, it says "403 That's an error. Sorry, but you don't have access to this page", But when I switched my account from Google Drive, it worked.

**CODES**
```js
const SCOPES = [
  "https://www.googleapis.com/auth/drive.readonly",
  "https://www.googleapis.com/auth/userinfo.email",
  "https://www.googleapis.com/auth/userinfo.profile",
];

const oAuth2Client = new google.auth.OAuth2(
  process.env.GOOGLE_CLIENT_ID,
  process.env.GOOGLE_CLIENT_SECRET,
  process.env.CALLBACK_URL
);

app.get("/auth/google", (req, res) => {
  res.redirect(301, generateLoginUrl());
});

app.get("/mysongs", (req, res) => {
  const getToken = req.headers.authorization || "";

  getListDrive(getToken)
  .then((result) => {
    console.log(result)
    res.json(result);
  })
  .catch((err) => {
    res.json({
      songs: err,
    });  
  })
});




/* 
   GENERATE LOGIN URL
   ================
*/
function generateLoginUrl() {
    return oAuth2Client.generateAuthUrl({
        access_type: 'offline',
        scope: SCOPES
    });
}

/* 
    GET FILES GOOGLE DRIVE 
    ================
*/
async function getListDrive(tokens) {
  oAuth2Client.setCredentials({access_token: tokens});

  return listFiles(oAuth2Client);
} 
function listFiles(auth) {
  const drive = google.drive({ version: "v3", auth });
  const driveFileList = drive.files.list({
    q: "mimeType contains 'audio/'",
    pageSize: 5,
    fields: "nextPageToken, files(webContentLink, name)",
  });

  return driveFileList 
}
```

**Comment by sofisl** [comment]
Hi @bl4ckck, would you mind clarifying the steps to reproduce and the expected outcome so I can further investigate? Thank you!

**Comment by bl4ckck** [comment]
Sorry for unclear information.

1. Client redirect to server to login(server generated authentication url) [http://server/auth/google]
2. After logging in, it redirects back to the client and the client gets some unique code to be tokenized by the server [http://client/redirect?code=XXX_XXX]
3. Client gets access token from server by sending the unique code from step 2 [http://server/generate-token]
4. Client saves the token to cookie with react-cookie [http://client/redirect?code=XXX_XXX]
5. Client redirects to home page [http://client/home]
6. Client calls GET [http://server/mysongs] and returns file download URL Google Drive based on their access token
7. Client do sign out, and token has been revoked and cookies have been deleted
8. Client tries to sign in again with another account
9. After logging in, user calls GET [http://server/mysongs] again
10. And it returns "403 That's an error. Sorry, but you don't have access to this page"
11. But when I switched my account from Google Drive to the current account that has logged into my app, it worked.

**Comment by bl4ckck** [comment]
I have resolved this by adding an authuser param (I got this from a redirect callback which includes code, authuser, etc) to download URL google drive like this https://drive.google.com/uc?id=MY_ID&export=download&authuser=2

```js
return driveFiles.map((obj) => ({
      ...obj,
      webContentLink: obj.webContentLink + "&authuser=" + authuser
    }))
```
