### ISSUE TITLE
How can I determine if the hangoutsMeet URL can be generated automatically?

### ISSUE THREAD

**Issue by seito2** [googleapis/google-api-nodejs-client#2506]
Hi,

I am trying to create an event using google calendar api and automatically generate the Google Meet URL when creating it.
To do so, I understand that I can add the following value to createRequest.conferenceSolutionKey and execute the insert function.
> The possible values are:
"eventHangout" for Hangouts for consumers (http://hangouts.google.com)
"eventNamedHangout" for classic Hangouts for Google Workspace users (http://hangouts.google.com)
"hangoutsMeet" for Google Meet (http://meet.google.com)
"addOn" for 3P conference providers
(https://developers.google.com/calendar/v3/reference/events)

But how do I determine if Google Meet is an account I can use?
Maybe that can be restricted by scope during authentication?

**Comment by sofisl** [comment]
Hi @seito2, 

Thanks for your question. Would you mind clarifying your current outcome and your expected outcome, as well as any steps to reproduce? Thanks in advance!

**Comment by seito2** [comment]
@sofisl Thanks for the reply.

My application flow is as follows.
1. Google Calendar authentication by user from client side.
2. Send the retrieved code to the API server and save it.
3. User creates a meeting using my application.
4. Then, use the code we got in step 1 to add the event to google calendar and automatically create the GoogleMeet URL.

In the step 4, I send conferenceData as follows.
```json
{
   "createRequest":{
      "conferenceSolutionKey":{
         "type":"hangoutsMeet"
      },
      "requestId": "randamId"
   }
}
```
--- 
### Case1. Normal GoogleAccount
The event has been successfully created and the GoogleMeet URL has been created.

### Case2. G Suite Account
Failed to create the event and the following error is output.
```
invalid conference type value.
```
I'm aware that this is an error that occurs because the G Suite account requires the eventNamedHangout in the conferenceSolutionKey.type, is that correct?

--- 
From the above, I decided that we needed to determine if the account the user authenticated to was G Suite or not.
Therefore, we would like to know how I can determine if a user is a G Suite account or not, is it possible?

**Comment by sofisl** [comment]
Hi @seito2, thanks for the further information. Is there a reason why you want to generate exclusively a GoogleMeetURL (vs., for example, Hangouts for a consumer account, etc.)? Regardless, I think what you'll have to do is first check the `conferenceProperties.allowedConferenceSolutionTypes` of a given user's calendar to see what conference solutions are available to them:


```
You can learn which conference type is supported for any given calendar of a user 
by looking at the conferenceProperties.allowedConferenceSolutionTypes in the 
calendars and calendarList collections. You can also learn whether the user prefers 
to have Hangouts created for all their newly created events by checking the 
autoAddHangouts setting in the settings collection.

```
More info [here.](https://developers.google.com/calendar/create-events)

From there, you can decide whether you want to add a Hangouts, Classic Hangouts, or Google Meet event. If you're just looking to generate Google Meet events, then you can skip creating events for those users who don't have Meet in their `allowedConferenceSolutionTypes`.

Feel free to further clarify if this doesn't answer your question!

**Comment by seito2** [comment]
Hi @sofisl, Thanks for the reply!

The reason why we want to generate only the GoogleMeet URL is because we show "Google Meet Integration" in the app.

Thanks for the solution!
I solved the problem by using it!

Thank you!!
