### ISSUE TITLE
Why oAuth2Client.on('tokens') function never trigger ?

### ISSUE THREAD

**Issue by shinichimg** [googleapis/google-api-nodejs-client#2509]
Hi everyone, I'm facing to this issue. I used these below codes to refresh access_token. But I realize that it never triggers, although the access_token expired already:

```js
oauth2client.on('tokens', (tokens) => {
  // But it never triggers
  // store the refresh_token in my database!
}
```

Do anyone have a workaround for this ? Additional:

```js
oAuth2Client.refreshAccessToken((error, tokens) => {
  // return (Tokens is undefined) 
})
```

**Comment by bcoe** [comment]
@shinichimg an access token is short lived. Once you have a `refresh_token`, try setting your credentials like this:

https://github.com/googleapis/google-auth-library-nodejs#retrieve-access-token

At which point, the next request to an API will request a new access token.

**Comment by shinichimg** [comment]
> @shinichimg an access token is short lived. Once you have a `refresh_token`, try setting your credentials like this:
> 
> https://github.com/googleapis/google-auth-library-nodejs#retrieve-access-token
> 
> At which point, the next request to an API will request a new access token.

Thanks for your reply.
 I configured my credentials like the document ( on the first time, when I get tokens come from first authorization ). 
 But after 1 hour, the access_token  is still expired, then I call some event listeners function but It doesn't work. 
 What do I need to do now ? many thanks.

**Comment by bcoe** [comment]
@shinichimg this sounds like a bug that someone will need to investigate.

**Comment by bcoe** [comment]
> But after 1 hour, the access_token is still expired, then I call some event listener functions to get a new refresh_token but It doesn't work.

The next API call you make after the access token has expired will automatically use the refresh token to get a new access token -- there should be no need to ever manually call a method such as `oAuth2Client.refreshAccessToken`.

Could you please share the code that you are running that is failing to refresh the token?

**Comment by SurferJeffAtGoogle** [comment]
This issue will fall OoSLO soon.

**Comment by bcoe** [comment]
@rubek-joshi could I bother you to open a new issue with your specific questions?

@shinichimg I'm closing this issue since I haven't heard back from you (_and I'm hoping that the automatic refreshing did the trick for you_). Please let me know if you're continuing to bump into issues.

**Comment by rubek-joshi** [comment]
> @rubek-joshi could I bother you to open a new issue with your specific questions?

I've created one [here](https://github.com/googleapis/google-api-nodejs-client/issues/2637).
