### ISSUE TITLE
Delegation denied for user email

### ISSUE THREAD

**Issue by gauravkrp** [googleapis/google-api-nodejs-client#2510]
I am trying to read emails metadata for my org gsuite users to create a email analytics tool for internal use at my organization.

I am using node.js to implenet google admin apis.
Created a service account and then delegated domain wide access to this service account id.

But whenever, I try to access email data for any user other than the subject line, it gives me this error.
And seems like I've been stuck for 2 days for this just one issue.

errors: [
    {
      message: 'Delegation denied for user email',
      domain: 'global',
      reason: 'forbidden'
    }
  ]

**Comment by JustinBeckwith** [comment]
Greetings!  Could I trouble you to give the steps here a shot?
https://github.com/googleapis/google-api-nodejs-client/issues/2418#issuecomment-783494711

The relevant bit here that seems to trip folks up is the creation of the auth object, and passing the subject:
```js
const auth = new google.auth.JWT({
  keyFile: 'path/to/keyFile.json',
  scopes: ['https://mail.google.com/'],
  subject: 'email-address-to-impersonate@your-domain.com'
});
const gmail = google.gmail({ 
  auth: auth,
  version: 'v1'
});
```

Could you share the code you're using as well?

**Comment by gauravkrp** [comment]
> Greetings! Could I trouble you to give the steps here a shot?
> [#2418 (comment)](https://github.com/googleapis/google-api-nodejs-client/issues/2418#issuecomment-783494711)
> 
> The relevant bit here that seems to trip folks up is the creation of the auth object, and passing the subject:
> 
> ```js
> const auth = new google.auth.JWT({
>   keyFile: 'path/to/keyFile.json',
>   scopes: ['https://mail.google.com/'],
>   subject: 'email-address-to-impersonate@your-domain.com'
> });
> const gmail = google.gmail({ 
>   auth: auth,
>   version: 'v1'
> });
> ```
> 
> Could you share the code you're using as well?

yeah man! exactly this way had worked for me!

**Comment by JustinBeckwith** [comment]
@sofisl I think we can prevent a significant amount of pain by writing a few words on this in the README :)
