### ISSUE TITLE
Invalid Credentials on Server-to-server app  

### ISSUE THREAD

**Issue by brunapcs** [googleapis/google-api-nodejs-client#2511]
Hi, I'm trying to list users on my gsuit domain and I'm getting this "invalid credentials" error. I'm authenticating my request using google.auth.GoogleAuth() then auth.getClient() and the keyfile parameter with my service-account credentials. 

I've alredy set domain-wide authority to this service account and the correct scopes to perform the operation... 

Full code bellow: 
`
    const {google} = require('googleapis');
    
    async function main () {
      const auth = new google.auth.GoogleAuth({
        scopes: 'https://www.googleapis.com/auth/compute, https://www.googleapis.com/auth/admin.directory.user, https://www.googleapis.com/auth/admin.directory.group, https://www.googleapis.com/auth/admin.directory.user.readonly,https://www.googleapis.com/auth/cloud-platform', 
        keyFile: './key.json'
      });
      const authClient = await auth.getClient();
      google.options({auth: authClient});
    
      const admin_client = google.admin({ version: 'directory_v1' , auth});
      admin_client.users.list(
      {
           domain: 'my_domain',
           maxResults: '10',
           orderBy: 'email',
           sortOrder: 'ascending',
        },
      (err, res) => {
        if (err) return console.log('The API returned an error:', err.message);
  
        const { users } = res.data;
        if (users.length) {
          console.log('Users:');
          users.forEach((user) => {
            console.log(`${user.primaryEmail} (${user.name.fullName})`);
          });
        } else {
          console.log('No users found.');
        }
      }
    );
  }
  
  main().catch(console.error);

`

**Error: The API returned an error: Invalid Credentials**

**Comment by CodeSchwert** [comment]
Having the same issue ... looks like the Directory API only accepts OAuth2 authentication. Unless there's another way to setup the auth correctly without OAuth consent??

**Comment by CodeSchwert** [comment]
> Having the same issue ... looks like the Directory API only accepts OAuth2 authentication. Unless there's another way to setup the auth correctly without OAuth consent??

Figured it out in the end, all the instructions were here: https://developers.google.com/identity/protocols/oauth2/service-account

tl:dr;

- Create a project and service account in GCP
- Grant [Domain Wide delegation](https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority) to the service account
- Go into the G-Suite admin console and [delegate access to the service account](https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority)
- Then use the `googleapis` `JWT` auth client to connect to the API (like the example below):

```js
const {google} = require('googleapis');
const path = require('path');

async function runSample() {
  // acquire an authentication client using a service account
  const auth = new google.auth.JWT({
    keyFile: path.join(__dirname, './key.json'),
    scopes: [
      // ensure these scopes are correct!
      'https://www.googleapis.com/auth/admin.directory.user', 
      'https://www.googleapis.com/auth/admin.directory.group'
    ],
    // need to specify the impersonated/delegated user
    // that has access to the API
    // the request will not work if this is missing!!
    subject: 'gsuite.user@your-domain.co.nz'
  });

  // obtain the admin client
  const admin = google.admin({
    version: 'directory_v1',
    auth
  });

  // List all users in your directory
  const res = await admin.users.list({
    // list options
  });

  console.log(res.data);
}

runSample().catch(console.error);
```

**Comment by brunapcs** [comment]
@CodeSchwert thanks! I guess the
