### ISSUE TITLE
Using this library with angular 11

### ISSUE THREAD

**Issue by skarensmoll** [googleapis/google-api-nodejs-client#2526]
I'm trying to use this library on my angular project to get an access tokens by using a service account however, after installing it and trying to use it with a node version of 10, I'm getting this error

`Warning: /...../stage.service.ts depends on 'googleapis'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Error: ./node_modules/google-auth-library/build/src/auth/googleauth.js
Module not found: Error: Can't resolve 'child_process' in '/....../node_modules/google-auth-library/build/src/auth'
`
Could you please help me to understand this issue, or if you know of any library I could use for angular I'd really appreciate it !

Thanks

**Comment by sofisl** [comment]
Hi @skarensmoll,

Currently we're using webpack 5 to bundle the library, which no longer auto-polyfills these dependencies. You can use something like [this](https://sanchit3b.medium.com/how-to-polyfill-node-core-modules-in-webpack-5-905c1f5504a0
) to inject the polyfills.

**Comment by skarensmoll** [comment]
> Hi @skarensmoll,
> 
> Currently we're using webpack 5 to bundle the library, which no longer auto-polyfills these dependencies. You can use something like [this](https://sanchit3b.medium.com/how-to-polyfill-node-core-modules-in-webpack-5-905c1f5504a0) to inject the polyfills.

Thanks @sofisl for your reply!
