### ISSUE TITLE
See BCC on incoming email.

### ISSUE THREAD

**Issue by gmwill934** [googleapis/google-api-nodejs-client#2527]
How do I actually see the BCC recipient(s)? I'm using Node JS and I cannot see it, I only see "`to`", "`from`" and "`cc`".
In case someone sends an email like this. I'd like the BCC recipient header/property.

Take the following example

```
from: team@google.com
to: cloud@google.com
cc: hr@google.com
bcc: myOwnPersonalEmail@gmail.com
```
How would I get access to `Bcc` so I can manipulate it later? (myOwnPersonalEmail is actually my own email, since its bcc, its the only recipient that I'm expected to see)

Thanks

**Comment by sofisl** [comment]
Hi @gmwill934,

You need to add the BCC section to the headers, in addition to raw encoding the whole message in base 64. For example:


```
{
  "raw": "RnJvbTogSm9obiBEb2UgPGpkb2VAbWFjaGluZS5leGFtcGxlPiAKVG86IE1hcnkgU21pdGggPG1hcnlAZXhhbXBsZS5uZXQ+IApTdWJqZWN0OiBTYXlpbmcgSGVsbG8gCkRhdGU6IEZyaSwgMjEgTm92IDE5OTcgMDk6NTU6MDYgLTA2MDAgCk1lc3NhZ2UtSUQ6IDwxMjM0QGxvY2FsLm1hY2hpbmUuZXhhbXBsZT4KClRoaXMgaXMgYSBtZXNzYWdlIGp1c3QgdG8gc2F5IGhlbGxvLiBTbywgIkhlbGxvIi4=",
  "payload": {
    "headers": [
      {
        "name": "bcc",
        "value": "value@value.com"
      },
      {
        "name": "to",
        "value": "value@value.com"
      }
    ],
    "body": {
      "data": ""
    }
  }
}

``` 


where the raw message property is just something like this encoded in base 64:

```
From: John Doe <jdoe@machine.example> 
To: Mary Smith <mary@example.net> 
Subject: Saying Hello 
Date: Fri, 21 Nov 1997 09:55:06 -0600 
Message-ID: <1234@local.machine.example>

This is a message just to say hello. So, "Hello".
```

You can learn more about this method and try it [here](https://developers.google.com/gmail/api/reference/rest/v1/users.messages/send).

Hope this answers your question! Feel free to reopen if not.

**Comment by sofisl** [comment]
Oh sorry, just to clarify your specific question. Once you are sure you've sent an email with BCC, you can use the [`get`](https://developers.google.com/gmail/api/reference/rest/v1/users.messages/get) method with the message ID to see details about the message, including what is in the headers.
