### ISSUE TITLE
Calendar API with Firebase FUNCTIONS

### ISSUE THREAD

**Issue by AirtonLucianoAragao** [googleapis/google-api-nodejs-client#2529]
Hi.

As FIREBASE FUNCTIONS uses NODE to emulate and (am not sure) to deploy the index.js file it would very good if you could show how to implement Calendar API at this scenario.

I searched a lot but didn't find an example.

Thanks a lot.

**Comment by sofisl** [comment]
Hi @AirtonLucianoAragao, you can find inline examples in this file (I've linked [one](https://github.com/googleapis/google-api-nodejs-client/blob/5b2f6697acd10851a49bb2fdf2040043dc15b039/src/apis/calendar/v3.ts#L2346), but you can scroll in that file for more). You should be able to put this in the index file of a firebase function to get it started. Hope this helps!
