### ISSUE TITLE
Is there a way to batch requests?

### ISSUE THREAD

**Issue by tiwalayo** [googleapis/google-api-nodejs-client#2530]
The way I have been using the client thus far has been like

```javascript
      client = new OAuth2Client(
        process.env.GOOGLE_CLIENT_ID,
        process.env.GOOGLE_CLIENT_SECRET,
        "http://localhost:5000/oauth2callback"
      );

      client.setCredentials({refresh_token: getRefreshToken(user)});
      let url = 'https://www.googleapis.com/gmail/v1/users/me/messages?q=myquery';
      client.request({url}).then((response) => {
        doSomethingWith(response);
      });
```
Since `response` holds a list of message ids, I will have to use [`users.messages.get`](https://developers.google.com/gmail/api/reference/rest/v1/users.messages/get) to get the actual data for each message. I would prefer not to do hundreds of separate requests just for one query. Is there a way to batch the `users.messages.get` requests?

**Comment by JustinBeckwith** [comment]
Greetings!  There is no native support batch, but there *is* native HTTP/2 support, which kind of gives you the same thing.  I cover this here:
https://github.com/googleapis/google-api-nodejs-client/#http2

Take a look and let me know if you have any questions!

**Comment by jrmdayn** [comment]
Having hit the issue of batching Google apis requests using Node.js myself, I decided to develop [a solution](https://github.com/jrmdayn/googleapis-batcher) that follows the guidelines provided in Google's batching [documentation](https://developers.google.com/calendar/api/guides/batch), implementing the `multipart/mixed` HTTP request/response protocol.

Please have a look and do not hesitate to raise an issue if you find a bug or would like to discuss improvements.
