### ISSUE TITLE
It would be very useful at least one "working" example using this guide

### ISSUE THREAD

**Issue by AirtonLucianoAragao** [googleapis/google-api-nodejs-client#2531]
As a newby I am having dificultie interpreting the examples... It would be very helpful to have at least one "working" example in JavaScript. I suggest something as Calendar Quickstart demo... 

Thanks a lot

**Comment by JustinBeckwith** [comment]
Greetings @AirtonLucianoAragao, and welcome to the repo!  As it would turn out the README is full of information to help you learn:
https://github.com/googleapis/google-api-nodejs-client

And it includes a rather large list of well maintained, tested samples:
https://github.com/googleapis/google-api-nodejs-client/tree/master/samples

Now we don't have something specific to calendar, but the patterns used in the other gsuite APIs are going to be very similar.  I can appreciate that getting started is frustrating, and we're here to help!  Next time you open a bug though, please include:
- What did you, including the code you're trying
- What happened when you ran the code, including any console output or error messages you're getting
- Which guides/tutorials were you trying to follow

Best of luck!
