### ISSUE TITLE
Google Local Services API for Account Report

### ISSUE THREAD

**Issue by dhbarker** [googleapis/google-api-nodejs-client#2534]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
Hello @sofisl , we her at American Residential Services (ARS)
[External Developer's Guide for Local Services API - Google Docs (1).pdf](https://github.com/googleapis/google-api-nodejs-client/files/6085444/External.Developer.s.Guide.for.Local.Services.API.-.Google.Docs.1.pdf)
 are using the Google Local Service API to pull data for the Account Report.  We see in the documentation that you should be able to pull metrics in a specified timer period.  

"Account Reports show the performance and metrics associated with linked LocalServices
accounts of a Manager account in the specified time period. Data has up to a 30 minute
staleness period.
To acquire the report, please send a HTTP GET request to
“ https://localservices.googleapis.com/v1/accountReports:search ” with the
following configurable url parameters."

However the Account Report does not return a "date" value.  

We are trying to use the optional startDate.year, startDate.month, startDate.day and endDate.year, endDate.month, endDate.day URL parameters to pull just one days worth of Month to Date data.  However, we cannot get it to work.

Can  you provide a URL example using the Start & End Date optional parameters that works or give some guidance on what else we can try to get just one day's worth of account report data?

**Comment by dhbarker** [comment]
Hello @bcoe @sofisl , could either of you help with the support question above?  Or could you point us to some documentation that can help us?

**Comment by dhbarker** [comment]
Hello, @bcoe & @sofisl  will either one of you be able to help or comment on this issue?  Could you point us to someone who can help?

**Comment by dhbarker** [comment]
Hello, is there someone else who can help answer our question or point us in a different direction?

**Comment by JustinBeckwith** [comment]
@dhbarker this is a best-effort issue tracker, and we're not going to be able to answer every question.  Please stop spamming the issue.  This question doesn't appear to be related to the npm module we ship here, rather the API itself.  I'd suggest checking out some of the resources here for help:
https://support.google.com/google-ads/

Best of luck!
