### ISSUE TITLE
Support for contacts API?

### ISSUE THREAD

**Issue by bradvogel** [googleapis/google-api-nodejs-client#254]
I noticed that the contact api (https://developers.google.com/google-apps/contacts/v3) isn't supported here. Is that on the roadmap? Or is there an alternative here?

**Comment by koreanilkumar** [comment]
https://myaccount.google.com/contacts

Save contact info when you interact with people

Is there any API to get the contacts for this in NodeJS?

Actually while we create an calendar event and while we add guests it is showing auto list when I start typing, From where I'm getting these contacts?
