### ISSUE TITLE
"No overload matches this call" error from ts

### ISSUE THREAD

**Issue by fedyk** [googleapis/google-api-nodejs-client#2542]
Hey,

I was trying to use calendar API with Nodejs/TS, but faced with following problem:

```
No overload matches this call.
  Overload 2 of 6, '(callback: BodyResponseCallback<Schema$Event>): void', gave the following error.
    Argument of type '{ calendarId: string; conferenceDataVersion: string; maxAttendees: string; sendNotifications: string; sendUpdates: string; supportsAttachments: string; requestBody: { anyoneCanAddSelf: boolean; ... 36 more ...; visibility: string; }; }' is not assignable to parameter of type 'BodyResponseCallback<Schema$Event>'.
      Object literal may only specify known properties, and 'calendarId' does not exist in type 'BodyResponseCallback<Schema$Event>'.
```

To demonstrate the problem I have created a simple [repo](https://github.com/fedyk/googleapis-test-repo) and put the code from [here](https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/calendar/v3.ts#L5192-L5268):

```
git clone git@github.com:fedyk/googleapis-test-repo.git
cd googleapis-test-repo
npm install
npm run build
```

During the build you should see the error from TS.

**Comment by sofisl** [comment]
Hi there, 

I think this is not the most descriptive error, but I think it's actually complaining about the other fields not being the right types Try replacing the values with the correct types, and you should see the error go away. For example:

```
    calendarId: 'calendarId',
    maxAttendees: 2,
    sendUpdates: "all",
    supportsAttachments: false,
    conferenceDataVersion: 0,
```

Alternatively, you can omit the optional parameters, everything except for `calendarId`.

Feel free to read more about the error [here](https://developers.google.com/calendar/v3/reference/events/insert?apix_params=%7B%22calendarId%22%3A%22r0cl5t411o1iv5d54pqec96ktk%40group.calendar.google.com%22%2C%22resource%22%3A%7B%22end%22%3A%7B%7D%2C%22start%22%3A%7B%7D%7D%7D). And, you can reopen if this doesn't solve your question!
