### ISSUE TITLE
Is there any way to get events for a single day?

### ISSUE THREAD

**Issue by evenstensberg** [googleapis/google-api-nodejs-client#2550]
Hi! Is there a way to get all events for a single day with an api call? In advance, thx!

**Comment by JustinBeckwith** [comment]
Greetings!  Guessing you want to use the `calendar.events.list` call described here:
https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/calendar/v3.ts#L5579

You likely want to set the `timeMin` and `timeMax` fields to the range you want to search for.  All of the fields are described here:
https://developers.google.com/calendar/v3/reference/events/list

Best of luck!
