### ISSUE TITLE
Schema$GcsData.path is missing

### ISSUE THREAD

**Issue by nilsreichardt** [googleapis/google-api-nodejs-client#2554]
# Description
Hi! In the StorageTransfer API `Schema$GcsData.path` is missing. There is only `Schema$GcsData.name` but as you can see in the documentation `path` is missing in the Dart library:

## Documentation
![image](https://user-images.githubusercontent.com/24459435/105491363-74e68600-5cb6-11eb-8055-30ffc0e79f65.png)
https://cloud.google.com/storage-transfer/docs/reference/rest/v1/TransferSpec#gcsdata

# TypeScript code
![image](https://user-images.githubusercontent.com/24459435/111672463-48fd0200-881a-11eb-953d-087a7d37534b.png)

`googleapis/build/src/apis/storagetransfer/v1.d.ts`

**Comment by sofisl** [comment]
This should be updated now :) Thanks for the report!

**Comment by nilsreichardt** [comment]
Oh, so fast? :o
