### ISSUE TITLE
Document how to install individual APIs

### ISSUE THREAD

**Issue by bcoe** [googleapis/google-api-nodejs-client#2567]
We should document how to install an individual API, such as `@google-apis/youtube`.

Refs: #2557
Refs: #2346 
Refs: #2187

**Comment by proppy** [comment]
Do you also plan to link to the reference documentation from each package README.md?

**Comment by bcoe** [comment]
@proppy hadn't planned on doing so, perhaps open an issue requesting this?

**Comment by proppy** [comment]
Sure filed #2577
