### ISSUE TITLE
Youtube PlaylistItemSnippet doesn't have ts definition for 'videoOwnerChannelId' and 'videoOwnerChannelTitle'.

### ISSUE THREAD

**Issue by metamon123** [googleapis/google-api-nodejs-client#2574]
#### Pre-check
1) Is this a client library issue or a product issue?
It's client library issue.

2) Did someone already solve this?
I couldn't find related issues about missing definition of 'videoOwner*' in both StackOverflow and issue list for this repository.

3) Do you have a support contract?
No. This is just an personal report.
-----
#### Statement
Below fields
* `videoOwnerChannelId`
* `videoOwnerChannelTitle`

are not defined in [Schema$PlaylistItemSnippet interface (ts)](https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/youtube/v3.ts#L3041) although
* [Official api docs for Youtube PlaylistItems API](https://developers.google.com/youtube/v3/docs/playlistItems) specifies them
* Actual api call returns result containing them
-----
#### Environment details

  - OS: `Windows 10`
  - Node.js version:  `v12.13.1`
  - npm version: `6.12.1`
  - `googleapis` version: `59.0.0`
-----
#### Steps to reproduce

  1. Send PlaylistItems.list API request
  ```typescript
import * as google from 'googleapis';
const youtube = new google.youtube_v3.Youtube({ auth: client /* Your OAuth2Client client */ });
const res = await youtube.playlistItems.list({
    '<any-playlist-id>',
    part: ['snippet'],
});

console.log(res.data.items[0].snippet['videoOwnerChannelId'], res.data.items[0].snippet['videoOwnerChannelTitle']);
  ```
  2. Check response. It contains `videoOwnerChannelTitle` and `videoOwnerChannelId` as [official youtube playlistItems api docs](https://developers.google.com/youtube/v3/docs/playlistItems) specifies.
-----
p.s. Since this is my first issue raising in open source environment, I'm not sure I have followed reporting procedure correctly.
Please feel free to tell me if I made any mistake!

**Comment by JustinBeckwith** [comment]
👋  thanks for reporting this!  This is a real bug.  We have a fix coming, but it's probably going to be monday until it gets out.  Apologies!
