### ISSUE TITLE
How to upload two deobfuscationfiles for one APK using androidpublisher?

### ISSUE THREAD

**Issue by max-zaytsev** [googleapis/google-api-nodejs-client#2587]
Is it possible to upload "ReTrace mapping file" and "Native debug symbols" simultaneously for a single APK?

We use "androidpublisher_v3" from [googleapis][1] npm package ("googleapis": "^70.0.0") in our application and we manage to publish a new APK with one deobfuscation file (mapping.txt OR native-debug-symbols.zip) to the Google Play Console.

#### Environment details

  - OS: Windows 10
  - Node.js version: v10.23.0
  - npm version: 6.14.8
  - `googleapis` version: ^70.0.0

#### Steps to reproduce

Our current flow is:

 1. Initializing Google Play publisher API.
 2. Creating a new edit transaction in Google Play.
 3. Uploading APK
 4. Uploading mapping.txt file
 5. Committing the edit transaction in Google Play.

We have a function for uploading mapping.txt file (which uses [Method: edits.deobfuscationfiles.upload][2]):

```typescript

/**
 * Uploads a deobfuscation file (mapping.txt) for a given package
 * Assumes authorized
 * @param {string} mappingFilePath the path to the file to upload
 * @param {string} packageName unique android package name (com.android.etc)
 * @param apkVersionCode version code of uploaded APK
 * @returns {Promise} deobfuscationFiles A promise that will return result from uploading a deobfuscation file
 *                          { deobfuscationFile: { symbolType: string } }
 */
export async function uploadDeobfuscation(edits: any, mappingFilePath: string, packageName: string, apkVersionCode: number): Promise<void> {
    const requestParameters = {
        deobfuscationFileType: 'proguard',
        packageName: packageName,
        apkVersionCode: apkVersionCode,
        media: {
            body: fs.createReadStream(mappingFilePath),
            mimeType: ''
        }
    };

    try {
        const res = (await edits.deobfuscationfiles.upload(requestParameters)).data;
    } catch (e) {
        throw new Error(tl.loc('CannotUploadDeobfuscationFile', mappingFilePath, e));
    }
}

```

And also we have almost the same function to upload native-debug-symbols.zip (the only difference is another deobfuscationFileType: nativeCode)

So if we call *edits.deobfuscationfiles.upload* once to upload one of the deobfuscation files it works fine, but if we want to upload mapping.txt and native-debug-symbols with a single *edits* transaction, we can only see the last file uploaded to the Google Play Console (App bundle explorer -> Downloads -> Assets)
![Case 1](https://user-images.githubusercontent.com/16704239/114187802-44010f00-98fd-11eb-8107-c47f87457a01.PNG)
![Case 2](https://user-images.githubusercontent.com/16704239/114187812-46fbff80-98fd-11eb-8714-4de1107637a5.PNG)

Is it expected behavior? 

  [1]: https://github.com/googleapis/google-api-nodejs-client
  [2]: https://developers.google.com/android-publisher/api-ref/rest/v3/edits.deobfuscationfiles/upload
  [3]: https://i.stack.imgur.com/MN2y9.png
  [4]: https://i.stack.imgur.com/TNVVD.png
  [5]: https://www.nuget.org/packages/Google.Apis.AndroidPublisher.v3/1.51.0.2239?_src=template

**Comment by max-zaytsev** [comment]
Hi Folks. Could someone please take a look at this?

**Comment by JustinBeckwith** [comment]
@max-zaytsev we can generally answer questions about the npm module itself, but most of the code here is auto-generated from API definitions we're provided by service teams.  When it comes to the specifics of a given service ... we're not likely to be much help.  I suspect with something like this, you're going to have a lot better luck with a product specific forum like https://stackoverflow.com/questions/tagged/google-play-developer-api.  Wish I had a better answer :/

**Comment by max-zaytsev** [comment]
@JustinBeckwith thank you for your reply. Actually, I asked the same question on stackoverflow a month ago, but also haven't received any answer yet.
https://stackoverflow.com/questions/67022152/how-to-upload-two-deobfuscationfiles-for-one-apk-using-androidpublisher

**Comment by sofisl** [comment]
Hi @max-zaytsev, following up on stale issues, and I'm sorry you haven't gotten any answers on stackoverflow. I think, if you click on the 'we're here to help' link here: https://developers.google.com/android-publisher, you might get a better answer for the product specifically.
