### ISSUE TITLE
calendar.events.insert returns "notFound" while executing in firebase cloud functions, working fine locally

### ISSUE THREAD

**Issue by rawatnaresh** [googleapis/google-api-nodejs-client#2589]
I'm trying to insert events in my google calendar and I'm using [serviceAccount](https://googleapis.dev/nodejs/googleapis/latest/calendar/index.html#service-account-credentials) for the authentication

Running the functions locally adds the events to my calendar but when I deploy it to the firebase-functions it gives me `notFound` error

![Screen Shot 2021-04-14 at 13 11 37](https://user-images.githubusercontent.com/29520305/114670752-119f4980-9d23-11eb-8d38-3667c244cea9.png)
![Screen Shot 2021-04-14 at 13 19 46](https://user-images.githubusercontent.com/29520305/114671715-1ca6a980-9d24-11eb-8338-a41acb75a4e0.png)

Here's the sample code
```ts
import { Auth, google } from 'googleapis';

const scopes = [
  'https://www.googleapis.com/auth/calendar',
  'https://www.googleapis.com/auth/calendar.events',
];
const client: Auth.GoogleAuth = new google.auth.GoogleAuth({
  scopes: scopes,
});

const calendar = google.calendar({ version: 'v3', auth: client });

calendar.events
  .insert({
    calendarId: 'myemail@gmail.com',
    requestBody: {
      summary: `My title`,
      start: {
        date: '2021-04-14',
      },
      end: {
        date: '2021-04-17',
      },
    },
  })
  .then((result) => {})
  .catch((err) => {});
```
I'm not sure what causing the issue, also the authorization headers are being added properly

![Screen Shot 2021-04-14 at 13 27 45](https://user-images.githubusercontent.com/29520305/114672756-372d5280-9d25-11eb-8a66-f6e858e3c040.png)

**Comment by tmatsuo** [comment]
I think you're using the cloud function's default service account on Cloud Function environment.
Here is some documentation:
https://cloud.google.com/functions/docs/concepts/iam

The email of the default service account looks like:
PROJECT_ID@appspot.gserviceaccount.com

Can you add your Cloud Function default service account to your calendar's permission list?

**Comment by rawatnaresh** [comment]
wow, thanks it worked. 👍
