### ISSUE TITLE
Introduce browser support

### ISSUE THREAD

**Issue by rakyll** [googleapis/google-api-nodejs-client#26]
- Remove util.inherits
- Create a build target for browsify
- DefaultTransporter should be able to detect env and change behavior accordingly.
- Discovery cache should be auto switched off.

**Comment by slorber** [comment]
@rakyll as of today there's no way to add google apis in a Webpack/Browserify bundle? didn't find anything yet

**Comment by jmdobry** [comment]
This library will remain Node.js-only. To access Google APIs from the browser, use the [Google API Client Library for JavaScript](https://developers.google.com/api-client-library/javascript/)

**Comment by slorber** [comment]
that's what I thought @jmdobry , unfortunatly it's not really clear how to integrate this library inside a webpack bundle as it seems the methods are somehow loaded lazily by discoveryUrls.

**Comment by jmdobry** [comment]
I don't think you can integrate it into a webpack bundle
