### ISSUE TITLE
Bad request: invalid_grant

### ISSUE THREAD

**Issue by shablenko-sednor** [googleapis/google-api-nodejs-client#2611]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?

Issue is with this library

2) Did someone already solve this?

There were lots of similar issues, none of solutions helped or worked

3) Do you have a support contract?

No

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Mac OS BigSur 11.3.1
  - Node.js version: 12.21.0
  - npm version: 6.14.11
  - `googleapis` version: ^73.0.0

#### Steps to reproduce

This is what I have on client side

```js
// gapi is fetched from https://apis.google.com/js/api:client.js?onload=onGoogleScriptLoad

gapi.load("client:auth2", {
            callback: async () => {
                await gapi.client.init({
                    clientId: B24Config.googleApi,
                    fetchBasicProfile: false,
                    scope: "https://www.googleapis.com/auth/spreadsheets",
                });
                const res = await gapi.auth2.getAuthInstance().grantOfflineAccess({
                    accessType: "offline",
                    prompt: "consent",
                    scope: "https://www.googleapis.com/auth/spreadsheets",
                });
                onConnect({ type: "google", code: res.code });
            },
        });
```

```js

class GoogleService {
    constructor() {
        this.client = new google.auth.OAuth2(config.google.clientId, config.google.clientSecret);
    }

    async login(code) {
        const tokens = await this.client.getToken(code); // this always throws invalid_grant

        this.client.setCredentials(tokens);
    }
    ...
}
```

I have tried changing scopes, tried adding redirect urls, verified domains, web urls, nothing helped.
I'm trying to exchange code for refresh_token and access token, doing this on localhost in nodejs

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by bcoe** [comment]
@shablenko-sednor it looks like you are using a different library than `googleapis`, which my team is not too familiar with (_it's a library for interacting with the Google REST APIs that predates this repository_).

We have a few examples of using Google sheets with this repository:

https://github.com/googleapis/google-api-nodejs-client/tree/master/samples/sheets

Some of these include examples of the OAuth flow.

**Comment by shablenko-sednor** [comment]
Resolved issue
If somebody encounters the same, solution is to set `redirect_uri` as `postmessage`
In my case I was using google client sdk on web to obtain `code`, had no redirects set up
