### ISSUE TITLE
How to create a redirect_uri?

### ISSUE THREAD

**Issue by Prottoy2938** [googleapis/google-api-nodejs-client#2612]
I'm trying to use the Youtube API v3 to automatically upload videos to youtube. Its a nodejs serverside app.

I have no idea what should I put in the `redirect_uri` field. What is a `redirect_uri` and how do I create a `redirect_uri`?

**Comment by Hrushi20** [comment]
A redirect_uri is required for oauth service provider to redirect the client back to the website after authorization.
https://www.oauth.com/oauth2-servers/redirect-uris/#:~:text=Redirect%20URLs%20are%20a%20critical,access%20token%20in%20the%20URL.


If you are on localhost, try adding your developement url in the authorized redirect uri section (i.e http://localhost: + port_number)
in the https://console.developers.google.com/ (google developer console) website. 
https://i.ibb.co/LkgF1wQ/Screenshot-134.png

**Comment by Prottoy2938** [comment]
The issue has been resolved. The problem was I didn't publish the project.
