### ISSUE TITLE
How can we update cloud scheduler job httpTarget?

### ISSUE THREAD

**Issue by askdhyan** [googleapis/google-api-nodejs-client#2630]
I'm using a cloud scheduler client.

My code:

` job: {
            name: client.jobPath(process.env.GCP_PROJECT, process.env.FUNCTION_REGION, req.body.name),
            description: 'dhyan edited',
            schedule: req.body.schedule,
            retryConfig: {
                retryCount: Number(process.env.JOB_RETRY_MAX)
            },
            httpTarget: {
                uri: req.body.httpTarget.uri,
                httpMethod: req.body.httpTarget.httpMethod || 'POST',
                headers: req.body.httpTarget.headers ? { ...req.body.httpTarget.headers } : undefined,
                body: req.body.httpTarget.body ? Buffer.from(JSON.stringify(req.body.httpTarget.body)).toString('base64') : undefined
            },
            updateMask: {
                paths: ['description', 'retryConfig', 'httpTarget']
            }
        }`
   
I'm getting below error.
Error: 3 INVALID_ARGUMENT: Invalid mask for Job: httpTarget at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26) at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:179:52) at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141) at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181) at /workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78 at processTicksAndRejections (internal/process/task_queues.js:79:11)

I feel there is no support for the "httpTARGET" update mask.  😔

**Comment by SurferJeffAtGoogle** [comment]
Could you craft a minimal code sample complete with project.json, etc., post it on github and link to it here?
