### ISSUE TITLE
Error: Usage: node samples/drive/download.js $FILE_ID

### ISSUE THREAD

**Issue by Saketsuraj** [googleapis/google-api-nodejs-client#2636]
In samples/drive/download.js, When I run `node download.js`. I get the error as Error: `Usage: node samples/drive/download.js $FILE_ID`

**Comment by fhinkel** [comment]
@Saketsuraj you need to call the program with a `file_id`, it looks something like this `1GjjoOB8X4wVuID0Df4ptFcAxhDsXJ8U`. You can get the `file_id` by getting a sharable link in Drive or by using the Drive API and using functions like `getFiles()` and `getId()`.
