### ISSUE TITLE
oAuth2Client.on('tokens') function not triggering

### ISSUE THREAD

**Issue by rubek-joshi** [googleapis/google-api-nodejs-client#2637]
#### Environment details

  - OS: Windows
  - Node.js version: 14.15.4
  - npm version: 6.14.10
  - `googleapis` version: 67.1.1

#### Steps to reproduce

```ts
import { google } from "googleapis";
import { CLIENT_ID, CLIENT_SECRET, REDIRECT_URI } from "someFile";

const oAuth2Client = new google.auth.OAuth2(
  CLIENT_ID,
  CLIENT_SECRET,
  REDIRECT_URI
);

oAuth2Client.on("tokens", async (tokens) => {
  console.log("New Tokens!", tokens); // This is never called
  if (tokens.refresh_token) {
    try {
      oAuth2Client.setCredentials({
        refresh_token: tokens.refresh_token,
        access_token: tokens.access_token, // is this necessary?
      });

      await storeInDatabase();
      logger.info("New refresh token stored successfully.");
    } catch (err) {
      // TODO: critical error, report to sentry
      logger.error(err);
    }
  }
});
```

A couple of lingering doubts: is it necessary to keep the above code snippet in my root `index.ts` file and does it not work if the publishing status is set to **Testing**?

Thanks!

**Comment by sofisl** [comment]
Hi @rubek-joshi,

Can you confirm you've followed the steps [here](https://github.com/googleapis/google-api-nodejs-client#handling-refresh-tokens)? This tokens event will only occur during the first authorization.

Feel free to reply back if this doesn't work for you.

**Comment by rubek-joshi** [comment]
@sofisl Yes, I have followed the steps.

> This tokens event will only occur during the first authorization.

If that's the case, how am I supposed to get a new refresh token when it expires?

> As a developer, you should write your code to handle the case where a refresh token is no longer working.

This has been mentioned in the README. How am I suppose to ensure the refresh token is working and has not expired?

**Comment by sofisl** [comment]
Hi @rubek-joshi, the refresh token should automatically refresh once you get it: 

> Once the client has a refresh token, access tokens will be acquired and refreshed automatically in the next call to the API.

You can confirm details about the expiration, etc, like this:

```
const tokenInfo = await oAuth2Client.getTokenInfo(oAuth2Client.credentials.access_token);
console.log(tokenInfo);
```

See a full sample [here](https://github.com/googleapis/google-auth-library-nodejs/blob/master/samples/oauth2.js).

Feel free to ask further questions on this channel if this doesn't fully answer your questions!

**Comment by rubek-joshi** [comment]
Thanks for getting back and I understand the part about how the refresh token refreshes the access token. What I am asking is how do I handle the case where the refresh token **itself** has expired. The confusion stems from [this document](https://developers.google.com/identity/protocols/oauth2#expiration) where it says the following:

> You must write your code to anticipate the possibility that a granted refresh token might no longer work.

So my question is, say in the case of the refresh token being unused for more than six months, how am I suppose to "anticipate" programmatically? Is this something that has to be done manually?

**Comment by sofisl** [comment]
Hi @rubek-joshi,

Unfortunately we don't have a readily available sample to share, but I believe you will want to do something like this:

1. Confirm the status of the token (i.e., expired, etc.) using the `getTokenInfo` method
2. You can set `prompt` to `consent` and `access_type` to offline when using `generateUrl` to re-prompt the user to give their consent, giving a new access token. See more info on those parameters [here](https://developers.google.com/identity/protocols/oauth2/web-server#python_1).

Let me know if you need more guidance on this if you give it a try.

**Comment by sofisl** [comment]
I'm going to close this for now, feel free to reopen or start a new issue if you still need a sample!
