### ISSUE TITLE
Inconsistent videoID when running youtube.videos.list

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [googleapis/google-api-nodejs-client#2650]
I am currently writing some tests that contain YouTube API requests using this library. I have a predefined videoID that I have been using to test the ` youtube.videos.list` method "FSxW--qwUhA". 

If I run this method with this ID, half the time I get a success and half the time I get an error on the request claiming that the ID does not exist. This is the real ID of a video as I can use the web query tool to get the video information. The following is the error:

![image](https://user-images.githubusercontent.com/12765521/121936231-42d5cf00-ccfe-11eb-8060-637c95aa63e3.png)

Is this behavior expected?

**Comment by chingor13** [comment]
Can you post a snippet of the code you're using to make this request? Then we can verify that the client is making the appropriate backend request.

**Comment by Nathan-Nesbitt** [comment]
Absolutely! The following is the core of the function that is being tested. 

```js
youtube.videos.list({
  maxResults: 1,
  part: ['statistics', 'snippet'],
  id: videoID      
}).then(response => {            
  var videos = response.data.items;    
  // ... the rest of my code that just returns the values //
})
```

Where videoID is "FSxW--qwUhA" for the test.
