### ISSUE TITLE
Gmail api's are intermittently failing with 401

### ISSUE THREAD

**Issue by aniltallam** [googleapis/google-api-nodejs-client#2665]
#### Environment details

  - OS: Ubuntu
  - Node.js version: 12.16 
  - npm version: v12.13.0
  - `googleapis` version: 34.0.0

#### Steps to reproduce

  1.  Gmail Apis like "users.messages.list" sometimes intermittently failing with below 401 error. And is working fine after retrying the request again after some time.
`{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","errors":[{"message":"Invalid Credentials","domain":"global","reason":"authError","location":"Authorization","locationType":"header"}],"status":"UNAUTHENTICATED"}`

Note: 
Is this due to an issue in gmail servers or any issue in the google nodejs client or we miss configuring anything at our side?

Thanks!

**Comment by SurferJeffAtGoogle** [comment]
Could you point me to a sample that reproduces this issue?
