### ISSUE TITLE
Missing types definitions 'purchaseState' and 'purchaseState' and others

### ISSUE THREAD

**Issue by rusakovic** [googleapis/google-api-nodejs-client#2666]
Environment details

Node.js version: 16.0.0
npm version: 7.11.0
googleapis version: 78.0.0

Issue
Property 'purchaseState' does not exist on type 'Schema$ProductPurchase | Schema$SubscriptionPurchase'.:

Property 'purchaseState' does not exist on type 'Schema$ProductPurchase | Schema$SubscriptionPurchase'.

As per docs: 
https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.products
https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions

Steps to reproduce
 ```js
         const googlePurchasesRef = google.androidpublisher({
            version: "v3",
         }).purchases;
  
         const purchaseResponse = isProduct
            ? await googlePurchasesRef.products.get({
                 packageName: PackageNames.android,
                 productId: productId,
                 token: transactionReceipt,
              })
            : await googlePurchasesRef.subscriptions.get({
                 packageName: PackageNames.android,
                 subscriptionId: productId,
                 token: transactionReceipt,
              });

         const { orderId, paymentState, purchaseState } = purchaseResponse.data; // <= paymentState, purchaseState  are missed in types
```

The property exists in the object returned by the API.

Maybe all possible response types should be added here
![image](https://user-images.githubusercontent.com/17801144/123928294-1375c200-d98e-11eb-9155-41aac430d16f.png)

**Comment by SurferJeffAtGoogle** [comment]
@tjohns, this bug is for you.
