### ISSUE TITLE
Getting Google Reviews for my business?

### ISSUE THREAD

**Issue by ImmanuelKannan** [googleapis/google-api-nodejs-client#2677]
Hey everyone, I'm wondering if anyone can point me to the right direction in order to get google reviews for our business to be displayed on our website? My plan is for our backend to periodically make an API call to the GMB API (once a week) to get all the reviews for our business, cache them, and display on our website. What would be the best way for our server to authenticate? From what I've read so far, the only kind of authentication I've seen involves an OAuth flow with redirects.

**Comment by bcoe** [comment]
Hello @ImmanuelKannan 👋 

I poked around a little bit, and to me it didn't seem like the GMP API exposed in this library supports fetching reviews for a business.

I think your best bet would be opening an issue [here](https://github.com/google/google-my-business-samples/issues), and starting a conversation with the My Business team.
