### ISSUE TITLE
Youtube upload, processing abandoned, the video could not be processed.

### ISSUE THREAD

**Issue by rzfzr** [googleapis/google-api-nodejs-client#2687]
Working with nodejs (electron) on windows 10.
There is no errors from the request, the response is as follows:
![image](https://user-images.githubusercontent.com/13456224/125791638-ad387ccc-7df9-4933-b34f-b5a8971850e5.png)
Thing is the code worked before I was granted a quota extension, I've tried different channels, different video files but nothing changed.

**Comment by tmatsuo** [comment]
@rzfzr Can you add reproducible code or step?

**Comment by rzfzr** [comment]
Sure thing, here is the auth code:
```
      let auth = await authorize(channel);

      async function authorize(channel) {
        let credentials = JSON.parse(fs.readFileSync("./src/client_id.json"));
        console.log(`trying with ${JSON.stringify(credentials)}`);

        const clientSecret = credentials.web.client_secret;
        const clientId = credentials.web.client_id;
        const redirectUrl = credentials.web.redirect_uris[0];

        console.log(clientSecret, clientId, redirectUrl);
        const oauth2Client = new OAuth2(clientId, clientSecret, redirectUrl);
        let token = JSON.parse(fs.readFileSync(TOKEN_PATH + channel.code + ".json"));
        token = token.tokens || token;
        await oauth2Client.setCredentials(token);
        return oauth2Client;
      }

```
and here is the upload:
```

      service.videos.insert(
        {
          auth: auth,
          part: "snippet,status",
          requestBody: {
            snippet: {
              title,
              description,
              tags,
              defaultLanguage: "en",
              defaultAudioLanguage: "en",
            },
            status: {
              privacyStatus: "private",
            },
          },
          media: {
            body: fs.createReadStream(videoPath),
          },
        },
        function (err, response) {
          if (err) {
            console.log("The API returned an error: " + err);
            return;
          }
          console.log(response.data);

          console.log("Video uploaded. Uploading the thumbnail now.");
          service.thumbnails.set(
            {
              auth: auth,
              videoId: response.data.id,
              media: {
                mimeType: "image/jpeg",
                body: fs.createReadStream(thumbPath),
              },
            },
            function (err, response) {
              if (err) {
                console.log("The API returned an error: " + err);
                return;
              }
              console.log(response.data);
            }
          );
        }
      );

```
modules as follows

```
const { google } = require("googleapis");
const OAuth2 = google.auth.OAuth2;
const SCOPES = ["https://www.googleapis.com/auth/youtube.upload"];
 const service = google.youtube("v3");
```
let me know if you need anything else.
Thanks

**Comment by rzfzr** [comment]
Is it still lacking information? I rolled back my code, testing things out, no luck still
![image](https://user-images.githubusercontent.com/13456224/126841354-dcc01c58-0ff1-4efc-b154-42cd6004e59a.png)

**Comment by rzfzr** [comment]
Don't know if it helps or not, but trying to upload a thumbnail fails with this message.
![image](https://user-images.githubusercontent.com/13456224/126841785-c7018686-db7a-4e8e-81c7-3f27b156524a.png)
![image](https://user-images.githubusercontent.com/13456224/126841808-e898adb1-92cb-4804-93da-1b75d3f27dca.png)

**Comment by rzfzr** [comment]
Something changed for requests in electron, I'm having to do my calls in the main process, although I have the old version which worked in the renderer.

**Comment by quocvu** [comment]
@rzfzr how did you get the quota extension?  My quota is enough to upload just 6 videos per day.  My app is for my own use and very crude thus I can't thru the approval requirements.

**Comment by rzfzr** [comment]
I just filled out the form asking for more.... From what I remember of it you just had to prove that the app had a legit use case. I remember attaching an YouTube video of a tool walkthrough, using the app, I believe they didn't ask for it, but it might have helped.

I was already using the same auth for doing the same requests for months though, that might have helped too. I imagine that if you ask for an extension describing some use that doesn't match your current one being denied, otherwise it would be easy to deploy comment bots and such.
