### ISSUE TITLE
Support managing reviews in MyBusinessAccountManagement

### ISSUE THREAD

**Issue by zavan** [googleapis/google-api-nodejs-client#2700]
Because the [MyBusinessAccountManagement discovery document](https://github.com/googleapis/google-api-nodejs-client/blob/11bc6787b419772f8f1eb9e62f9ed44ab45146a9/discovery/mybusinessaccountmanagement-v1.json) is incomplete (it doesn't describe the review management endpoints), this library doesn't support [location review management](https://developers.google.com/my-business/content/review-data).

I don't really know how that document works, or I'd create a PR myself.

[Reference](https://developers.google.com/my-business/reference/rest/v4/accounts.locations.reviews).

Right now I'm just using the `auth` part of the library:

```js
import { google } from 'googleapis';

const client = new google.auth.OAuth2(
  config.googleClientId,
  config.googleClientSecret,
  config.googleRedirectUrl
);

client.setCredentials({
  access_token: tokens.accessToken,
  refresh_token: tokens.refreshToken,
  expiry_date: tokens.expiryDate,
  token_type: tokens.tokenType,
});

const url = `https://mybusiness.googleapis.com/v4/accounts/${accountId}/locations/${locationId}/reviews`;
const res = await client.request({ url });
```

**Comment by zavan** [comment]
Related: #2677 and #1871

**Comment by SurferJeffAtGoogle** [comment]
Thank you for reporting this issue.  Unfortunately, the fix requires adding a feature to the API.  Please open a feature request here:
https://cloud.google.com/support/docs/issue-trackers

**Comment by zavan** [comment]
@SurferJeffAtGoogle Thanks for the response, but I don't understand what you mean.
The Google My Business API itself already supports this, it's not a new Google Cloud feature, it's just this library that doesn't support those endpoints/resources.

**Comment by SurferJeffAtGoogle** [comment]
@zavan Sorry for the late reply.  Is this still an issue?

**Comment by cpellet** [comment]
This is still not done yea?
