### ISSUE TITLE
Fetch traffic stats by date for a domain through gmailpostmastertools : Request contains an invalid argument.

### ISSUE THREAD

**Issue by nonacc** [googleapis/google-api-nodejs-client#2702]
#### Environment details

  - OS: Windows 10 Pro
  - Node.js version: v12.18.4
  - npm version: 6.14.13
  - `googleapis` version: 83.0.0

#### Error

I'm trying to fetch traffic stats by date for a domain through gmailpostmastertools over OAuth2,
I'm able to retrieve postmaster.domains.list and traffic stats for a domain without any date parameters,
when any of the endDate or startDate parameters included in the request, it throws the following,

```
Error: Request contains an invalid argument.
    at Gaxios._request (C:\projects\postmaster-api\node_modules\gaxios\src\gaxios.ts:158:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at OAuth2Client.requestAsync (C:\projects\postmaster-api\node_modules\google-auth-library\build\src\auth\oauth2client.js:345:18)
```

#### Code

```javascript
oauth2Client = new google.auth.OAuth2(
  'client_placeholder',
  'secret_placeholder', 
  '/oauth2callback'
);

postmaster = google.gmailpostmastertools({
  version: 'v1',
  auth: oauth2Client
});

await this.postmaster.domains.trafficStats.list({ 
  'startDate.day'   : 1,
  'startDate.month' : 7,
  'startDate.year'  : 2021,
  parent : `domains/${domain_name}`
});
```

#### Steps to reproduce

  1. Create a new Google API Project
  2. Create the Authentication Credentials-> OAuth 2.0 Client
  3. Redirect to consent -> Approve
  4. Callback with code -> oauth2Client.setCredentials
  5. Get exact domain name from postmaster.domains.list();
  6. Try to retrieve traffic stats by date for the domain from postmaster.domains.trafficStats.list

It works fine to fetch the data directly with access_token, I get back a valid response as expected,

```javascript

let access_token = 'my_access_token';
let domain_name = 'mydomain.com';
let date = '20210701';
await fetch(`https://gmailpostmastertools.googleapis.com/v1/domains/${domain_name}/trafficStats/${date}?access_token=${access_token}`, {
    method: 'GET'
});

```

**Comment by SurferJeffAtGoogle** [comment]
Is this issue still happening?

**Comment by nonacc** [comment]
Hey @SurferJeffAtGoogle ,
Yes, unfortunately the issue is still happening.

#### Environment details
- node version: 17.1.0
- npm version: 8.1.4
- googleapis version: **92.0.0**

#### Error
```
GaxiosError: Request contains an invalid argument.
    at Gaxios._request (C:\projects\postmaster-api\node_modules\gaxios\src\gaxios.ts:158:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at OAuth2Client.requestAsync (C:\projects\postmaster-api\node_modules\google-auth-library\build\src\auth\oauth2client.js:368:18)
```

#### Full response
```
{
  response: {
    config: {
      url: 'https://gmailpostmastertools.googleapis.com/v1/domains/XXX.com/trafficStats?endDate.day=1&endDate.month=10&endDate.year=2021&startDate.day=1&startDate.month=8&startDate.year=2021',
      method: 'GET',
      userAgentDirectives: [Array],
      paramsSerializer: [Function (anonymous)],
      headers: [Object],
      params: [Object],
      validateStatus: [Function (anonymous)],
      retry: true,
      responseType: 'json',
      retryConfig: [Object]
    },
    data: { error: [Object] },
    headers: {
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      'cache-control': 'private',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Tue, 25 Jan 2022 09:18:13 GMT',
      server: 'ESF',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    status: 400,
    statusText: 'Bad Request',
    request: {
      responseURL: 'https://gmailpostmastertools.googleapis.com/v1/domains/XXX.com/trafficStats?endDate.day=1&endDate.month=10&endDate.year=2021&startDate.day=1&startDate.month=8&startDate.year=2021'
    }
  },
  config: {
    url: 'https://gmailpostmastertools.googleapis.com/v1/domains/XXX.com/trafficStats?endDate.day=1&endDate.month=10&endDate.year=2021&startDate.day=1&startDate.month=8&startDate.year=2021',
    method: 'GET',
    userAgentDirectives: [ [Object] ],
    paramsSerializer: [Function (anonymous)],
    headers: {
      'x-goog-api-client': 'gdcl/5.0.5 gl-node/17.1.0 auth/7.11.0',
      'Accept-Encoding': 'gzip',
      'User-Agent': 'google-api-nodejs-client/5.0.5 (gzip)',
      Authorization: 'Bearer XXX',
      Accept: 'application/json'
    },
    params: {
      'endDate.day': 1,
      'endDate.month': 10,
      'endDate.year': 2021,
      'startDate.day': 1,
      'startDate.month': 8,
      'startDate.year': 2021
    },
    validateStatus: [Function (anonymous)],
    retry: true,
    responseType: 'json',
    retryConfig: {
      currentRetryAttempt: 0,
      retry: 3,
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      statusCodesToRetry: [Array]
    }
  },
  code: 400,
  errors: [
    {
      message: 'Request contains an invalid argument.',
      domain: 'global',
      reason: 'badRequest'
    }
  ]
}
```
_*Obviously the XXX for privacy reasons._
The auth configured correctly, the error thrown only when the date range fields are added.

**Comment by SurferJeffAtGoogle** [comment]
Do you have a sample with a project.json file available on github to reproduce this issue?  I haven't called the postmaster API.

**Comment by SurferJeffAtGoogle** [comment]
Without a sample, I can't begin to debug this issue.  Feel free to re-open with a sample.

**Comment by Santiago-Eid-Jala** [comment]
Good day! Has this been looked at any further? I'm experiencing the same issue including another one that seems very related.

**Environment details**

node version: 12.22.1
npm version: 7.11.2
googleapis/gmailpostmastertools version: 0.2.1

**Error**
I'm also trying to fetch traffic stats by date for a domain through gmailpostmastertools over OAuth2. Whenever I try to fetch stats without date parameters, results are fetched fine. Whenever I add `endDate` (day, month and year) and `startDate` (day, month and year), I get the following error:

```
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}
```
But, another issue I'm facing is, according to the documentation for `googleapis` [here](https://googleapis.dev/nodejs/googleapis/latest/gmailpostmastertools/classes/Gmailpostmastertools.html#source), I can replace any of the date parameters with a 0 if I don't want to include it. For example if I want to filter by month and year but not day, I can put a 0 on both startDate and endDate day. Whenever i try to do this i get the following error:

```

**Comment by Santiago-Eid-Jala** [comment]
Good day @SurferJeffAtGoogle! Has this been looked at any further by any chance? I'm experiencing the same issue including another one that seems related.

**Environment details**

node version: 12.22.1
npm version: 7.11.2
googleapis/gmailpostmastertools version: 0.2.1

**Error**
I'm also trying to fetch traffic stats by date for a domain through gmailpostmastertools over OAuth2. Whenever I try to fetch traffic stats without date parameters, results are fetched fine. However when I add `endDate` (day, month and year) and `startDate` (day, month and year), I get the following error:

```
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}
```
But, another issue I'm facing is, according to the documentation for `googleapis` [here](https://googleapis.dev/nodejs/googleapis/latest/gmailpostmastertools/classes/Gmailpostmastertools.html#source), I can replace any of the date parameters with a 0 if I don't want to include it. For example if I want to filter by month and year but not day, I can put a 0 on both `startDate` and `endDate` day parameters. Whenever I try to do this I get the following error:

```
{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
```
My code and responses are similar to the ones posted above. A way of reproducing these errors is using the [Google Postmaster Tools API Sandbox](https://developers.google.com/gmail/postmaster/reference/rest/v1/domains.trafficStats/list). The GUI already comes with `cURL`, `HTTP` and `JavaScript` code samples.

**Steps to reproduce**
 - Go to [Google Postmaster Tools API Sandbox](https://developers.google.com/gmail/postmaster/reference/rest/v1/domains.trafficStats/list).
 - Go to `Try Method`. 
 - Add `parent`, `endDate` and `startDate` parameters (with 0's and/or wanted values).
 - Click `execute`.
 - Log in with a Google account used in Postmaster Tools.
 - One of the errors mentioned should pop up.
 
**Expected Errors**
![Screenshot from 2022-10-19 19-00-22](https://user-images.githubusercontent.com/85369785/196820332-f923e2f2-30e4-4f6a-8792-e93f60361273.png)
![Screenshot from 2022-10-19 18-59-51](https://user-images.githubusercontent.com/85369785/196820339-5f9308cc-55db-4f23-9245-3e2c028b05b3.png)

**Comment by gconway345** [comment]
I had this problem but i was able to work around it, instead of passing the start date and end date as objects you have to provide them individually as arguments as reflected here - https://googleapis.github.io/google-api-python-client/docs/dyn/gmailpostmastertools_v1beta1.domains.trafficStats.html
