### ISSUE TITLE
typo spelling grammar

### ISSUE THREAD

**Issue by slowy07** [googleapis/google-api-nodejs-client#2711]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
This is the client library for . We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [ Support page]() to reach the most relevant engineers.

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/google-api-nodejs-client/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.
#### description
typo spelling grammar on ``google-api-nodejs-client``

#### Environment details

  - OS: ``linux``
  - Node.js version:
  - npm version:
  - `googleapis` version:

#### Steps to reproduce

  1. replace typo spelling grammar to correct words with reference from [merriam webster](merriam-webster.com)

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by bcoe** [comment]
See comment on PR 👏 

Thank you for bringing these typos to our attention.
