### ISSUE TITLE
Duplicate identifiers in most recent Artifact Regsitry discovery doc

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-api-nodejs-client#2723]
This is blocking generation, so I am disabling it for now.  Please make sure to remove this from ignored.json when fixed!

**Comment by sofisl** [comment]
I think we can undo this once AR fixes the last duplicate identifier (I have an email thread open with them). SHould be good when we can close #2898

**Comment by SurferJeffAtGoogle** [comment]
@sofisl #2898 is assigned to no one and this issue is out of SLO.  What next?

**Comment by sofisl** [comment]
I'm going to close this for now, in lieu of #2906
