### ISSUE TITLE
Revoke and Remove all Google tokens/permissions in Electron App

### ISSUE THREAD

**Issue by talentedandrew** [googleapis/google-api-nodejs-client#2729]
Building an electron app where we need to clear the google session after some action is performed. Using the below code to clearing the google session.

```
const { google, GoogleApis } = require('googleapis')

const oauth2Client = new google.auth.OAuth2(
      GOOGLE_AUTH_CONFIG: XXXXXXX,
      GOOGLE_AUTH_CONFIG: XXXXXXX,
      GOOGLE_AUTH_CONFIG: XXXXXXX
    );

async function logout() {
    console.log('Logging out....')

    await oAuth2Client.revokeCredentials()
}
```

However, when the user opens the app again, and they get the login screen, their Google Account is still there where all they have to do is click on it. They don't have to login again, they don't have to enter a password, and they don't have to use 2FA again.

What I am looking for is, when a user logs out of my Desktop Application, they are completely Logged out with no Google remnants left behind, such that, when they open the Application the next time, they have to re-enter a user name and a password and use their 2FA.

**Comment by sofisl** [comment]
Hi @talentedandrew, 

Throwing some links your way before we get time to work on your question. Hope this helps in the meantime!

[Using auth with electron](https://github.com/googleapis/release-please/issues/1028)

[Sample test for revoking credentials](https://github.com/googleapis/google-auth-library-nodejs/blob/2fcab77a1fae85489829f22ec95cc66b0b284342/test/test.oauth2.ts#L1270)

**Comment by talentedandrew** [comment]
I think this question doesn't belong here. The issue was that I was not able to clear the users session on the renderer process of the electron app. Still I'm posting my solution here for anyone who might face this exact issue. I didn't find any solution to my problem online, but I found a way to clear the session on my renderer in the electron app using the below code

```

// Auth window
const AuthWindow = new BrowserWindow({
      width: 600,
      height: 600,
      alwaysOnTop: true,
      fullscreen: false,
      fullscreenable: false
 });

.
.
.
// Before quitting the window, clear the storage so all the cookies related to google are cleared 
AuthWindow.webContents.session.clearStorageData().then(function (data) {
        AuthWindow.destroy();
});
```

What it does is that it clears the cookies related to the users google account, so next time the user will be shown the login screen.
