### ISSUE TITLE
No document and example is provided for calling Google Fit (Fitness) APIs

### ISSUE THREAD

**Issue by divyanshrws** [googleapis/google-api-nodejs-client#2739]
The module does not have any elaborated document or example on how to call the Fitness APIs using this module in NodeJS.

**Comment by bcoe** [comment]
Hello @divyanshrws, you will find inline examples of how to call the fitness API as JSDoc comments:

https://github.com/googleapis/google-api-nodejs-client/blob/main/src/apis/fitness/v1.ts#L740

These examples are also available in reference documents [here](https://googleapis.dev/nodejs/googleapis/latest/fitness/index.html).

If these don't do the trick, you may also find some additional documentation for the REST API [here](https://developers.google.com/fit/rest/v1/get-started) which should correlate closely to this library.

Let me know if this helps get you on your feet.
