### ISSUE TITLE
A link to google meet is not created 

### ISSUE THREAD

**Issue by NooBiToo** [googleapis/google-api-nodejs-client#2751]
My code 
`
import { google } from "googleapis";

const CALENDAR_ID = process.env.CALENDAR_ID;
const SCOPE_CALENDAR = process.env.SCOPE_CALENDAR;
const SCOPE_EVENTS = process.env.SCOPE_EVENTS;

function makeid(length) {
  var result = "";
  var characters =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  var charactersLength = characters.length;
  for (var i = 0; i < length; i++) {
    result += characters.charAt(Math.floor(Math.random() * charactersLength));
  }
  return result;
}

async function authenticate(key) {
  const jwtClient = new google.auth.JWT(
    key.client_email,
    null,
    key.private_key,
    [SCOPE_CALENDAR, SCOPE_EVENTS]
  );
  await jwtClient.authorize();
  return jwtClient;
}

async function createEvent(auth) {
  const event = {
    "summary": "test",
    "description": "test description",
    "start": {
      "dateTime": "2021-10-07T16:00:00+02:00",
      "timeZone": "Asia/Irkutsk",
    },
    "end": {
      "dateTime": "2021-10-09T18:00:00+02:00",
      "timeZone": "Asia/Irkutsk",
    },
    "conferenceData": {
      "createRequest": {
        "requestId": makeid(7),
      },
    },
  };

  let calendar = google.calendar("v3");
  const { data: newEvent } = await calendar.events.insert({
    auth: auth,
    calendarId: CALENDAR_ID,
    resource: event,
    "conferenceDataVersion": 1,
  });
  console.log(newEvent);
}
`
The event is successfully generated, but the link is not generated

this is the response from the server
`
{
  kind: 'calendar#event',
  etag: '"3264281379490000"',
  id: '0m8jomg7uhs2nid3og991i66dg',
  status: 'confirmed',
  htmlLink: 'https://www.google.com/calendar/event?eid=MG04am9tZzd1aHMybmlkM29nOTkxaTY2ZGcgNGluZ25pZ2YydjhvcDBjODdvaXVtZTVzazBAZw',
  created: '2021-09-20T12:24:49.000Z',
  updated: '2021-09-20T12:24:49.745Z',
  summary: 'тест',
  description: 'описание',
  creator: {
    email: 'telegabot@api-project-1094625154843.iam.gserviceaccount.com'
  },
  organizer: {
    email: '4ingnigf2v8op0c87oiume5sk0@group.calendar.google.com',
    displayName: 'API',
    self: true
  },
  start: { dateTime: '2021-10-07T22:00:00+08:00', timeZone: 'Asia/Irkutsk' },
  end: { dateTime: '2021-10-10T00:00:00+08:00', timeZone: 'Asia/Irkutsk' },
  iCalUID: '0m8jomg7uhs2nid3og991i66dg@google.com',
  sequence: 0,
  reminders: { useDefault: true },
  eventType: 'default'
}
`

**Comment by contributorpw** [comment]
Hi Erl!

Try to pass `conferenceDataVersion=1` as [an option](https://github.com/googleapis/google-api-nodejs-client/blob/01bf480d3e35354cc3fdc7d7aa2559611d459b50/src/apis/calendar/v3.ts#L5339).

```js
const { data: newEvent } = await calendar.events.insert({
    auth: auth,
    calendarId: CALENDAR_ID,
    resource: event
  },{
    "conferenceDataVersion": 1,
  });
```

**Comment by NooBiToo** [comment]
> ```js
> "conferenceDataVersion": 1,
> ```

unfortunately it didn't work (
is it possible that this doesn't work for a service account?

**Comment by tmatsuo** [comment]
https://stackoverflow.com/questions/64539847/how-to-create-a-new-google-meet-using-google-calendar-api

Maybe you can try adding `conferenceSolutionKey` parameter?

**Comment by NooBiToo** [comment]
> https://stackoverflow.com/questions/64539847/how-to-create-a-new-google-meet-using-google-calendar-api
> 
> Maybe you can try adding `conferenceSolutionKey` parameter?

I tried
```
Error: Invalid conference type value.
```

**Comment by contributorpw** [comment]
There are requests I tried

## With a Domain Service Account

```ts
import { google, calendar_v3 } from 'googleapis';
import path from 'path';

import env from '../env.json';
import event from './event.json';

(async () => {
  const auth = new google.auth.JWT({
    subject: env.DOMAIN_EFFECTIVE_USER_EMAIL,
    keyFile: path.join(__dirname, './..', env.DOMAIN_SERVICE_ACCOUNT),
    scopes: ['https://www.googleapis.com/auth/calendar'],
  });

  const calendar: calendar_v3.Calendar = google.calendar({
    version: 'v3',
    auth: auth,
  });

  const event_: calendar_v3.Schema$Event = {
    ...event,
  };

  try {
    const createResponse = await calendar.events.insert(
      {
        requestBody: event_,
        calendarId: env.CALENDAR_ID,
      },
      {
        params: {
          conferenceDataVersion: 1,
        },
      }
    );

    console.log(createResponse.data);
  } catch (err) {
    console.log(err);
  }
})();

```

## With an active web user

```ts
import { google, calendar_v3 } from 'googleapis';
import { authenticate } from '@google-cloud/local-auth';
import path from 'path';

import env from '../env.json';
import event from './event.json';

(async () => {
  const auth = await authenticate({
    keyfilePath: path.join(__dirname, './..', env.WEB_CLIENT_OAUTH),
    scopes: ['https://www.googleapis.com/auth/calendar'],
  });

  google.options({ auth });

  const calendar: calendar_v3.Calendar = google.calendar({
    version: 'v3',
    auth: auth,
  });

  const event_: calendar_v3.Schema$Event = {
    ...event,
  };

  try {
    const createResponse = await calendar.events.insert(
      {
        calendarId: env.CALENDAR_ID,
        requestBody: event,
      },
      {
        params: {
          conferenceDataVersion: 1,
        },
      }
    );

    console.log(createResponse.data);
  } catch (err) {
    console.log(err);
  }
})();

```

**Comment by NooBiToo** [comment]
> So... This is not working for me too.
> 
> You can override the feature via the REST request.
> 
> Before do anything else you have to know that **_you can't grant to a custom service account rights to create any conference request_**. This happened in the recent past (probably in 2020). This is most likely due to problems with the spread of spam.
> 
> _Be care, TS is on board._
> 
> With the `event.json` file
> 
> ```json
> {
>   "end": { "date": "2021-10-07" },
>   "start": { "date": "2021-10-07" },
>   "summary": "sadf",
>   "conferenceData": {
>     "createRequest": {
>       "conferenceSolutionKey": { "type": "hangoutsMeet" },
>       "requestId": "qqqqqq"
>     }
>   }
> }
> ```
> 
> ## With a Domain Service Account
> > Domain-wide Delegation settings are required!
> 
> ```ts
> import { calendar_v3, google } from 'googleapis';
> import event from './event.json';
> import * as https from 'https';
> import { GetAccessTokenResponse } from 'google-auth-library/build/src/auth/oauth2client';
> 
> import path from 'path';
> import env from '../env.json';
> import { ClientRequest } from 'http';
> 
> (async () => {
>   const auth = new google.auth.JWT({
>     subject: env.DOMAIN_EFFECTIVE_USER_EMAIL,
>     keyFile: path.join(__dirname, './..', env.DOMAIN_SERVICE_ACCOUNT),
>     scopes: ['https://www.googleapis.com/auth/calendar'],
>   });
> 
>   const accessToken: GetAccessTokenResponse = await auth.getAccessToken();
> 
>   const url: string = `https://www.googleapis.com/calendar/v3/calendars/${env.CALENDAR_ID}/events?conferenceDataVersion=1`;
> 
>   const event_: calendar_v3.Schema$Event = { ...event };
> 
>   const data: string = JSON.stringify(event_);
> 
>   const options: https.RequestOptions = {
>     method: 'POST',
>     headers: {
>       'Content-Type': 'application/json',
>       'Content-Length': data.length,
>       Authorization: `Bearer ${accessToken.token}`,
>       Accept: 'application/json',
>     },
>   };
> 
>   // There is not an async/await zone
>   const req: ClientRequest = https.request(url, options, (res) => {
>     res.on('data', (d) => {
>       process.stdout.write(d);
>     });
>   });
> 
>   req.on('error', (error) => {
>     console.error(error);
>   });
> 
>   req.write(data);
>   req.end();
> })();
> ```
> 
> ## With an active user
> ```ts
> import { authenticate } from '@google-cloud/local-auth';
> import path from 'path';
> import * as https from 'https';
> import { GetAccessTokenResponse } from 'google-auth-library/build/src/auth/oauth2client';
> import { calendar_v3 } from 'googleapis';
> 
> import env from '../env.json';
> import event from './event.json';
> 
> (async () => {
>   const auth = await authenticate({
>     keyfilePath: path.join(__dirname, './..', env.WEB_CLIENT_OAUTH),
>     scopes: ['https://www.googleapis.com/auth/calendar'],
>   });
> 
>   const accessToken: GetAccessTokenResponse = await auth.getAccessToken();
> 
>   const url = `https://www.googleapis.com/calendar/v3/calendars/${env.CALENDAR_ID}/events?conferenceDataVersion=1`;
> 
>   const event_: calendar_v3.Schema$Event = {
>     ...event,
>   };
> 
>   const data: string = JSON.stringify(event_);
> 
>   const options: https.RequestOptions = {
>     method: 'POST',
>     headers: {
>       'Content-Type': 'application/json',
>       'Content-Length': data.length,
>       Authorization: `Bearer ${accessToken.token}`,
>       Accept: 'application/json',
>     },
>   };
> 
>   // There is not an async/await zone
>   const req = https.request(url, options, (res) => {
>     res.on('data', (d) => {
>       process.stdout.write(d);
>     });
>   });
> 
>   req.on('error', (error) => {
>     console.error(error);
>   });
> 
>   req.write(data);
>   req.end();
> })();
> ```

Thanks for your feedback
1) is it obligatory to use jcion?
I tried to create an event through rest, but with the `type: "hangoutsMeet"` parameter
error 400 occurs, and without it, an event without video conferencing is generated
Is there a problem with the service account settings?
i created it in my google account and gave it calendar rights

**Comment by contributorpw** [comment]
Related to #2387

**Comment by NooBiToo** [comment]
> Related to #2387

thank for help

**Comment by RaulArmasBenavides** [comment]
Hello @NooBiToo . I have the same problem... The google event that I generate does not generate the google meeting.
I am using a service account and I have alredy added all the scopes..but still it doesn't work
Did you get a solution?
Thank you very much in advance!
