### ISSUE TITLE
Error: Required parameter: mimeType but already set

### ISSUE THREAD

**Issue by throrin19** [googleapis/google-api-nodejs-client#2754]
Hello,

I have a problem with googleapis with drive part to export files. Until yesterday, this code was working. And since this morning, for no reason, I have this error:

`Error: Required parameter: mimeType`

After research, the error is on the call of `drive.files.export` but, as you can see, the parameter mimeType is already passed : 

```js
const jwt = new google.auth.JWT(
    credentials.client_email,
    null,
    credentials.private_key,
    ['https://www.googleapis.com/auth/drive'],
    null
);

await jwt.authorize();

const metadata = await drive.files.get({
    fileId : 'myfileId',
    auth   : jwt,
});

const file = await drive.files.export({
    fileId      : metadata.data.id,
    auth        : jwt,
    mimeType    : 'text/csv',
});

return file.data;
```

**Edit** : 

If I try to make this request directly using axios, it works fine. The problem is certainly with the library validation ?

```js
const file = await axios.get(`https://www.googleapis.com/drive/v3/files/${metadata.data.id}/export`, {
    params : {
        mimeType : 'text/csv',
    },
    headers : {
        authorization : `Bearer ${jwt.credentials.access_token}`,
    },
});
```

#### Environment details

  - OS: macOs, Linux, ...
  - Node.js version: v14.15.4
  - npm version: 7.13.0
  - `googleapis` version: 87.0.0

#### Steps to reproduce

  1. Try to export file with mimeType set in options
  2. Get the error `Error: Required parameter: mimeType`

Thanks!

**Comment by sofisl** [comment]
Hi @throrin19,

I think this might actually be an authentication issue masquerading as something else. FWIW, this code worked for me:

```
const {google} = require('googleapis');
const {authenticate} = require('@google-cloud/local-auth');

const drive = google.drive('v3');

  const auth = await authenticate({
    keyfilePath: (PATH_TO_OAUTH2.0_CLIENT_ID),
    scopes: 'https://www.googleapis.com/auth/drive',
  });
  google.options({auth});

  const metadata = await drive.files.get({
    fileId : fileId,
});

  const file = await drive.files.export({
    fileId      : metadata.data.id,
    mimeType    : 'text/csv',
});

console.log(file);
``` 

I think you need to authenticate via Oauth credentials. Can you retry using the code above, and see if that works for you? 

Thanks!

**Comment by sofisl** [comment]
Hi @throrin19 , does this still occur for you? I can't reproduce the error, wondering if it was temporary due to a dependency upgrade.

**Comment by throrin19** [comment]
Hi @sofisl, I've just tested and it works fine now. Thanks
