### ISSUE TITLE
Parameters seems to not be serialized

### ISSUE THREAD

**Issue by jbpin** [googleapis/google-api-nodejs-client#2789]
Hi, 
we face issue calling androidentreprise api. When sending a request it seems that parameters are not added are not well serializaed. We provide a script that can reproduce the issue. When sending the request with the sdk we receive an error 
`The callback url does not have the https scheme.` (using another endpoint like list who need domain parameters give also an error 'Missing parameter: domain')

Doing the same call using node-fetch directly work like a charm. 

Maybe is an issue with gaxios. If necessary let me know I can also create an issue in the gaxios repo. 

#### Environment details

  - OS: MacOS
  - Node.js version: v14.17.6
  - npm version: 7.24.0
  - `googleapis` version: 85.0.0
  -  `gaxios` versions tested : 2.3.4 / 4.3.2 

#### Steps to reproduce

```js
const { google } = require('googleapis');
const path = require('path');
const fetch = require('node-fetch');

async function main() {
  const cauth = new google.auth.GoogleAuth({
    keyFile: path.join(__dirname, './service_account.json'),
    scopes: ['https://www.googleapis.com/auth/androidenterprise'],
  });

  const client = google.androidenterprise({ version: 'v1', auth: cauth });
  client.enterprises
    .generateSignupUrl({ callbackUrl: 'https://test.io' })
    .then(console.log)
    .catch(console.log);

  client.enterprises
    .list({ domain: 'test.io' })
    .then(console.log)
    .catch(console.log);

  let token = await cauth.getAccessToken();
  let url = new URL('https://androidenterprise.googleapis.com/androidenterprise/v1/enterprises/signupUrl');
  url.searchParams.set('callbackUrl', 'https://test.io');
  fetch(url, {
    method: 'POST',
    headers: {
      authorization: `Bearer ${token}`,
    },
  })
    .then(res => res.json())
    .then(console.log);
}

main();
```

Thanks!

**Comment by edgar86cru** [comment]
The issue is generated from library gaxios. I made the test with forced version of gaxios 4.3.0 and it works in both ways

**Comment by sofisl** [comment]
Hi @edgar86cru, does this still occur for you? I can't reproduce the error, wondering if it was temporary due to a dependency upgrade.
