### ISSUE TITLE
JWT "invalid_grant" in Signature in Google OAuth2

### ISSUE THREAD

**Issue by Omar7867** [googleapis/google-api-nodejs-client#2808]
I keep getting this error when I post the JWT to Google:

{ "error": "invalid_grant", "error_description": "Invalid JWT Signature." }

when i use your code it give me error   "redirect_uris" of undefined 
please guide me

**Comment by sofisl** [comment]
Hi @Omar7867, could you please include a reproducible environment and code snippet? Thanks!

**Comment by Omar7867** [comment]
![1](https://user-images.githubusercontent.com/91155297/135662573-80456ff4-a8e1-4f16-90ab-9dceda52d11f.png)

**Comment by Omar7867** [comment]
With redirect_uris its working now, But I have to implement Oauth2 token api and reporting api on my nodejs server, without redirect url how can I do that. Can you please give me any example with jwt token and how to signed that token.

**Comment by chingor13** [comment]
Some APIs may require 3-legged OAuth to work. Without knowing which API you are trying to use and a snippet of what you're trying to do, it's difficult for us to try to assist you.
