### ISSUE TITLE
Upload video to youtube using internal as user type in consent screen

### ISSUE THREAD

**Issue by siemah** [googleapis/google-api-nodejs-client#2832]
I tried to upload video to youtube when i open it to `external`(in consent screen) it works, however this app used internally so i selected `internal` in consent screen(i created an organization using **Google Workspace**) then when i try to upload the video i go through the authentication process so i select the email from the organization, i got this error:

```json
{
    "domain": "youtube.header",
    "reason": "youtubeSignupRequired",
    "message": "Unauthorized",
    "locationType": "header",
    "location": "Authorization"
}
```

I want to know if there is something wrong when i choose **internal**? or this error is related to **youtube**?

**Comment by chingor13** [comment]
This repository is for managing the generated API client for 100s of APIs. You may be able to get help from more knowledgeable folks on this YouTube auth error: https://developers.google.com/youtube/v3/support
