### ISSUE TITLE
Issue with linked google-auth-library version

### ISSUE THREAD

**Issue by Breathtender** [googleapis/google-api-nodejs-client#2855]
Using node version 16.13.0, npm version 8.1.0
Reproduced with googleapis version 91.0.0 and 92.0.0

Got this error when I would try to build
```
node_modules/googleapis-common/build/src/authplus.d.ts:1:131 - error TS2305: Module '"../../../google-auth-library/build/src"' has no exported member 'Impersonated'.

1 import { AwsClient, BaseExternalAccountClient, Compute, ExternalAccountClient, GoogleAuth, GoogleAuthOptions, IdentityPoolClient, Impersonated, JWT, OAuth2Client, ProjectIdCallback, UserRefreshClient } from 'google-auth-library';
```

I checked in my `package-lock.json` and I was linked to `google-auth-library`: `^7.0.2`
I actually failed to see what `google-auth-library` was actually installed, and now that I've fixed it, I'm having a hard time reproducing.
I fixed by specifying in my `package.json` `google-auth-library`: `7.10.2`

This isn't an issue for me anymore so close if it's irrelevant, but still filing as a potential bug.

**Comment by JustinBeckwith** [comment]
This is likely just going to happen when TypeScript types in `google-auth-library` move ahead, and folks are on older versions of it in their lock files.  The easy fix is to ask people to `rm -rf node_modules package-lock.json && npm install` when it happens, but a better approach may be to proactively keep the version of `google-auth-library` we depend on up to date down to the patch version in the `googleapis` module.
