### ISSUE TITLE
Web server application vs. Server to Server application – core difference ?

### ISSUE THREAD

**Issue by projektorius96** [googleapis/google-api-nodejs-client#2856]
Hi, whilst reading [this](https://developers.google.com/identity/protocols/oauth2#libraries) I've came up with **A) & B)**
Can someone explain the core difference between **A)** [Web Server Applications](https://developers.google.com/identity/protocols/oauth2/web-server) & **B)** [Server to Server Applications](https://developers.google.com/identity/protocols/oauth2/service-account) as for OAuth2 ? Both refer to this repo . I need to know the core difference so to know which documentation consume as a guidance . Thanks in advance !

**Comment by sofisl** [comment]
Closing as duplicate: https://github.com/googleapis/google-auth-library-nodejs/issues/1331
