### ISSUE TITLE
Gmail Service Account dont want authenticate

### ISSUE THREAD

**Issue by NonozgYtb** [googleapis/google-api-nodejs-client#2860]
Hi everyone,
After several long hours, I still cannot use my service account for Gmail. I'm a Google Workspace customer, but whether it's through JWT, OAuth, or other things (some of which the current version no longer supports), nothing helps and I get just errors. I don't really know what to do to be able to access information (via an OAuth client for my account only its walking) on ​​the gmail accounts of my members.
Can I have a (actual) solution ?
Thanks a lot.
PS: sorry for the text pad but it's late and I'm exhausted and quite frustrated with this problem

**Comment by NonozgYtb** [comment]
Hi,
After a lot of research, I found a solution that works (I use the promises):
```js
const credentials = require("./credentials.json") // File downloaded with the Service Account Keys
const getGmailAuth  = async ()=>{
       const auth = (new google.auth.JWT(
            credentials.global.client_email,
            null,
            credentials.global.private_key,
            GMAILSCOPES,
            person
        ))
        await (new Promise((resolve, reject) => {
            auth.authorize((err, tokens) => {
                if (err) {
                    reject(err);
                } else {
                    resolve(tokens);
                }
            });
        }))
        return (auth);
}
```
Good bye !

**Comment by frozen-a-b** [comment]
Hi @NonozgYtb ,

I think I ran into a similar issue

What is `person` in your code?

**Comment by NonozgYtb** [comment]
> Hi @NonozgYtb ,
> 
> I think I ran into a similar issue
> 
> What is `person` in your code?

`person` is a string with an email like :

```js
const person = "firstname.name@mydomain.com```
