### ISSUE TITLE
Where can I found the library documentation? 

### ISSUE THREAD

**Issue by shenshing** [googleapis/google-api-nodejs-client#2862]
I'm new to this, sorry if it is a bit weird. I want to know that where can I find library documentation because sometimes I don't know for example what is the function all about or what parameter should I pass or something.

Thank you everyone.

**Comment by chingor13** [comment]
Links to the docs can be found in the "API Reference" links on the README.

https://googleapis.dev/nodejs/googleapis/latest/index.html
