### ISSUE TITLE
androidpublisher edits.tracks.update api useless

### ISSUE THREAD

**Issue by wowkakloov** [googleapis/google-api-nodejs-client#2863]
OS:
  - Node.js version: v15.12.0
  - npm version: 7.6.3
  - `googleapis` version: ^92.0.0

Related Code:
```javascript
const {google} = require('googleapis'); 
const androidpublisher = google.androidpublisher('v3');

const PACKAGE_NAME = "com.xxx.xxx"
const PACKAGE_SCOPE = 'https://www.googleapis.com/auth/androidpublisher'

const auth = new google.auth.GoogleAuth({
    keyFile: "./api-xxx.json",
    scopes: [PACKAGE_SCOPE],
});

var hasAcquireAuthClient = false;

async function fetch() {

    if (hasAcquireAuthClient == false) {
        // Acquire an auth client, and bind it to all future calls
        const authClient = await auth.getClient();
        google.options({
            auth: authClient
        });
        hasAcquireAuthClient = true;
    }

    const insertRet = await androidpublisher.edits.insert({
        packageName: PACKAGE_NAME,
    });
    const editId = insertRet.data.id;

    const listRet = await androidpublisher.edits.tracks.list({
        editId: editId,
        packageName: PACKAGE_NAME,
    });

    const productionTrack = listRet.data.tracks.filter(track => track.track == 'production');

    const updateRet = await androidpublisher.edits.tracks.update({
        editId: editId,
        packageName: PACKAGE_NAME,
        track: 'production',
        requestBody: {
              releases: [{
                			name: "x.xx.x",
                			versionCodes: ["xxxxx","xxxxx"],
                                 releaseNotes: [{
                                language: "en-US",
                                text: "xxxx"
                            }],
                			status: "inProgress",
			        userFraction: 0.5
                		}],
              track: "production"
          },
    });
```

After call update method, the updateRet.data return seems success, include "track" and "releases" info.  but not really effect when i check google play console status.

Thanks!

**Comment by chingor13** [comment]
Apologies, we don't have expertise in every API that is contained in this repository. Would you be able to test your use case against the API Explorer at https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks/update?

Then we can determine if it's an issue with the backend API or an issue with the client library converting the request code into the backend request.

**Comment by wowkakloov** [comment]
@chingor13  thank your replied.
I try use the API Explorer, fillin all the parameters, and do OAuth 2.0 in popup window.
but execute will return 403 error.
{
  "error": {
    "code": 403,
    "message": "The project ID used to call the Google Play Developer API has not been linked in the Google Play Developer Console.",
    "status": "PERMISSION_DENIED"
  }
}
