### ISSUE TITLE
when i call googleapi people i get this error

### ISSUE THREAD

**Issue by Jakin-Liu** [googleapis/google-api-nodejs-client#2873]
Error: People API has not been used in project xxxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/people.googleapis.com/overview?project=xxxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry

how can i fix it? i also check i had open google api

**Comment by SurferJeffAtGoogle** [comment]
Please visit the link and enable the API.  The issue can only be resolved by visiting the link or running a gcloud command.  More details are here: https://cloud.google.com/endpoints/docs/openapi/enable-api
