### ISSUE TITLE
googleapis is depending on node-forge version that contains vulnerbilities

### ISSUE THREAD

**Issue by glenngijsberts** [googleapis/google-api-nodejs-client#2874]
We got a security warning in our repo saying `node-forge` contains vulnerabilities. We can't fix the security warning without setting a resolution.

![Screenshot 2022-01-10 at 22 20 24](https://user-images.githubusercontent.com/14276144/148841205-f931fd2a-b531-41f7-a432-bbc3cc6234af.png)

See: https://snyk.io/test/github/googleapis/google-api-nodejs-client

**Comment by SurferJeffAtGoogle** [comment]
This was fixed by https://github.com/googleapis/google-p12-pem/pull/387
