### ISSUE TITLE
Querying for appProperties doesn't return properly

### ISSUE THREAD

**Issue by TracerBuilt** [googleapis/google-api-nodejs-client#2875]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
This is a client library issue, as far as I'm aware.

2) Did someone already solve this?
  This issue is mentioned in [#426](https://github.com/googleapis/google-api-nodejs-client/issues/426) and [1166](https://github.com/googleapis/google-api-nodejs-client/issues/1166), but the methods given there are not currently working.

3) Do you have a support contract?
Nope.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: MacOS
  - Node.js version: 17.3.0
  - npm version: 8.3.0
  - `googleapis` version: 92.0.0

#### Steps to reproduce

  1.  Create a new spreadsheet, then update it with a custom `appProperties`. Currently I'm doing this:
  
  ```typescript
await sheetsClient.spreadsheets.create(
			{
				resource: resourceIndividual,
				fields: ['spreadsheetId']
			},
			async (err, spreadsheet) => {
				if (err) {
					// Handle error.
				} else {
					await driveClient.files.update(
						{
							resource: {
								appProperties: {
									key: 'backgroundId',
									value: `${body.uid}-individual`
								}
							},
							fileId: spreadsheet.data.spreadsheetId,
							fields: 'id, appProperties'
						},
						(err, file) => {
							if (err) {
								console.error(err)
							} else {
								console.log(file)
							}
						}
					)

					await driveClient.permissions.create(
						{
							resource: permission,
							fileId: spreadsheet.data.spreadsheetId,
							fields: 'id'
						},
						function (err, res) {
							if (err) {
								console.error(err)
							} else {
								console.log(res)
							}
						}
					)
				}
			}
		)
```

  2. Check that the `appProperties` are being properly applied, like so:
```typescript
	console.log(
		(await driveClient.files.list({ fields: 'files(id, name, appProperties)' })).data.files
	)
```
Which returns a list of the files and their applied custom property, a la

```js
{
    id: 'blahblahblah12345',
    name: 'Blah Blah',
    appProperties: { value: 'blah-blah-individual', key: 'backgroundId' }
}
```

3. Query using the appProperty to try to retrieve the file specifically by the new appProperty:

```typescript
const individualApplicationsFound = await drive.files.list({
fields: 'files(id, name, appProperties)',
q: `appProperties has { key='backgroundId' and value='${body.uid}-individual' }`
})

console.log(individualApplicationsFound.data.files)
```

4. Stare in desperation as an empty array is returned despite the properties being confirmed to exist.

**Comment by SurferJeffAtGoogle** [comment]
Have you tried the solution described here?
https://stackoverflow.com/questions/50301159/googleapis-appproperties-field-not-being-returned-for-files-in-node

**Comment by TracerBuilt** [comment]
@SurferJeffAtGoogle I have. Even though the `appProperties` are both set and queried for by the same Client ID, I attempted to do the same thing using normal `properties`, thinking that perhaps there was some sort of access issue going on. It has the same problem, however. A blank query returns all of the files, along with their `appProperties` and `properties` fields, but a query specifying a certain `property` or `appProperty` returns a blank file array.

**Comment by TracerBuilt** [comment]
Okay, I actually figured it out and it's not a bug; I'm just an idiot.

I was actually assigning two `appProperties`, `key: 'backgroundId'` and `value: 'blah-blah-individual'`

By changing the assignment from:

```typescript
driveClient.files.update({
    resource: {
        appProperties: {
            key: 'backgroundId',
            value: `${body.uid}-individual`
        }
    },
   fileId: spreadsheet.data.spreadsheetId,
   fields: 'id, appProperties'
})
```
to:
```typescript
driveClient.files.update({
    resource: {
        appProperties: {
            backgroundId: `${body.uid}-individual`
        }
    },
   fileId: spreadsheet.data.spreadsheetId,
   fields: 'id, appProperties'
})
```
the problem was solved and everything now works as expected.
