### ISSUE TITLE
Property 'on' does not exist on type 'GaxiosPromise<Schema$File>'

### ISSUE THREAD

**Issue by bl4ckck** [googleapis/google-api-nodejs-client#2887]
#### Environment details

  - OS: Ubuntu 20.04 LTS
  - Node.js version: 16.13.1
  - npm version: 8.1.2
  - `googleapis` version: ^39.2.0

#### Steps to reproduce

  1. I follow exactly like this code snippet https://developers.google.com/drive/api/v3/manage-downloads#node.js on Next js API project
  2. But the props 'on' is not found, pipe too

**Comment by sofisl** [comment]
Hi @bl4ckck,

I followed the code in the snippet, but I was unable to reproduce your issue. However, I did need to change a few things in order for it to work:

1) I needed to authenticate appropriately, as it says in the sample: `// TODO (developer) - Use appropriate auth mechanism for your app`. I did it like so:

```
 const {authenticate} = require('@google-cloud/local-auth');
  const {google} = require('googleapis');

  const auth = await authenticate({
    keyfilePath:
      'path-to-oath2-credentials',
    scopes: ['https://www.googleapis.com/auth/drive'],
  });
  google.options({auth});

  const service = google.drive({version: 'v3', auth});
``` 

2) It seems that files.get only applies to binary content, i.e., not docs files (something like a PDR. For that, you'd want to use [export](https://github.com/googleapis/google-api-nodejs-client/blob/main/samples/drive/export.js).


Feel free to paste your code here to see if I can reproduce better, in case there are any differences.
