### ISSUE TITLE
dailyLimitExceededUnreg for Drive API v3

### ISSUE THREAD

**Issue by projektorius96** [googleapis/google-api-nodejs-client#2899]
Hi, I read lots of docs on **developers.google**, set up my codebase recently, connected within service account's provided secret_key.json issued for the project on Google Cloud Console which I downloaded & put away safely (_hopefully its safe_) . Everything seemed fine . Although I get **status: 200** with `request : { responseURL: https://www.googleapis.com/drive/v3/files?q=trashed%3Dfalse&corpora=user' }` the expected JSON for responseURL contains the following message:

```diff
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
```

I've checked on documentation , it say quotas may be an issue . Answer is negative , my quotas for Google Drive API is only **0,01%**

I may missing a part, but do I need to add billing account before hand for such API "trialling" only ? I am just a regular developer trying to play around with G Workspace APIs.

#### Environment details

  - OS: Windows Home 10 Windows Feature Experience Pack 120.2212.3920.0
  - Node.js version: 16.13.2
  - npm version: 8.1.2
  - `googleapis` version: 0.3.0

#### Steps to reproduce

**My codebase**:
```javascript
'use strict';

const drive = require('@googleapis/drive');
const path = require('path');
/* const express = require('express'); */
/* const axios = require('axios'); */

async function main() {

  const auth = new drive.auth.GoogleAuth({ /* as if AuthPlus.GoogleAuth({options}) */
  keyFile: path.join(__dirname, 'secret_key.json'),
  /* keyFilename: path.join(__dirname, 'secret_key.json'), */
    scopes: [
       /* Full list of scopes : @https://developers.google.com/identity/protocols/oauth2/scopes#drive */
      'https://www.googleapis.com/auth/drive', /* : See, edit, create, and delete all of your Google Drive files */
      'https://www.googleapis.com/auth/drive.file', /* : View and manage Google Drive files and folders that you have opened or created with this app */
      'https://www.googleapis.com/auth/drive.appdata', /* : ... */
      'https://www.googleapis.com/auth/drive.metadata', /* : ... */
      'https://www.googleapis.com/auth/drive.metadata.readonly', /* : ... */
      'https://www.googleapis.com/auth/drive.photos.readonly', /* : ... */
      'https://www.googleapis.com/auth/drive.readonly', /* : ... */
    ],
  });

  // Raw reference : @https://googleapis.dev/nodejs/googleapis/latest/drive/classes/Resource$Files.html#list
  // Nice reference : @https://developers.google.com/drive/api/v3/reference/files/list
  
  const _authenticated = drive.drive({version: 'v3', auth})
  const res = await _authenticated.files.list({
    q: 'trashed=false',
    corpora: 'user'
  })

  console.log(res); // full response : for more , please refer to request.responseURL
  
  console.log(res.data.files.length); // 0 # not what expected

}
main().catch(e => {
  console.error(e);
  throw e;
});

```

**Full response I get**:
```javascript
{
  config: {
    url: 'https://www.googleapis.com/drive/v3/files?q=trashed%3Dfalse&corpora=user',
    method: 'GET',
    userAgentDirectives: [ [Object] ],
    paramsSerializer: [Function (anonymous)],
    headers: {
      'x-goog-api-client': 'gdcl/5.0.5 gl-node/16.13.2 auth/7.11.0',
      'Accept-Encoding': 'gzip',
      'User-Agent': 'google-api-nodejs-client/5.0.5 (gzip)',
      Authorization: 'Bearer some_opaque_string_hidden_from_you_guys',
      Accept: 'application/json'
    },
    params: { q: 'trashed=false', corpora: 'user' },
    validateStatus: [Function (anonymous)],
    retry: true,
    responseType: 'json'
  },
  data: { kind: 'drive#fileList', incompleteSearch: false, files: [] },
  headers: {
    'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
    'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "frame-ancestors 'self'",
    'content-type': 'application/json; charset=UTF-8',
    date: 'Sun, 06 Feb 2022 22:43:19 GMT',
    expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
    pragma: 'no-cache',
    server: 'GSE',
    'transfer-encoding': 'chunked',
    vary: 'Origin, X-Origin',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'SAMEORIGIN',
    'x-xss-protection': '1; mode=block'
  },
  status: 200,
  statusText: 'OK',
  request: {
    responseURL: 'https://www.googleapis.com/drive/v3/files?q=trashed%3Dfalse&corpora=user'
  }
}
```

**Worth to mention**: my **secret_key.json** expires in thousands of years (status: enabled)

---

It's not urgent, although some assistance may be appreciated to solve or register as potential bug for this library .

Thank you!

**Comment by projektorius96** [comment]
.

**Comment by projektorius96** [comment]
Any status on this ? Thanks .

**Comment by projektorius96** [comment]
...

**Comment by sofisl** [comment]
Hi @projektorius96,

I followed your code, but was unable to reproduce your specific error. To be positive, I attempted with an account that had billing enabled, and one that did not have billing enabled; both worked. However, it's worth noting that in order to see any specific files using my service account, I had to actually share that file with the service account, i.e., clicking "Share" in the picture below and entering the service account email, service-account@project-name.iam.gserviceaccount.com

<img width="291" alt="Screen Shot 2022-07-26 at 7 13 16 PM" src="https://user-images.githubusercontent.com/55454395/181145723-6afc4a59-df5e-4f6f-8739-725fe49ad905.png">

Other troubleshooting tips I'd recommend:

1) Make sure you're using a [service account](https://cloud.google.com/iam/docs/creating-managing-service-account-keys) key, vs. [oauth2 ](https://developers.google.com/identity/protocols/oauth2)credentials. You can also use [oauth2 credentials](https://github.com/googleapis/google-api-nodejs-client/blob/main/samples/oauth2.js), you would just need a different set up for authentication.

2) Make sure you have files in that project, and that they're shared with the right service account.

3) Maybe try setting up billing, and re-attempting the code (it should not charge you). If it works, we have a smoking gun, and you can disable billing right after.

4) Perhaps try the [sample itself](https://github.com/googleapis/google-api-nodejs-client/blob/main/samples/drive/list.js), to rule out any account-wide issues.

**Comment by projektorius96** [comment]
Hi again, thanks to replying me after all . I've tried the same scenario with Sheets API as a fresh library over Drive API & shared the file to service account as you told me herein and of course, it did work out . Thanks a lot @sofisl 

@melissarh57 try this 3rd party tutorial on [[fusebit](https://fusebit.io/blog/google-sheets-api-tutorial/?utm_source=search.brave.com&utm_medium=referral&utm_campaign=none)] for Sheets API . It seems much more up-to-date & it should work for you as a guideline whilst implementing Drive API solution . Cheers !

**Comment by projektorius96** [comment]
@sofisl I am not sure it's somewhere mentioned on **developers.google** or any other relevant docs (references) that "you must share the document (in this case – sheet) to service account to be accessible through for APIs, although it may be obvious to some advanced users , but not beginners whatsoever . Thanks !
