### ISSUE TITLE
Batch Request Alternative

### ISSUE THREAD

**Issue by edwardysun** [googleapis/google-api-nodejs-client#290]
I noticed that batch requests were removed in 1.0. I've been using batch requests to read a folder (and recursively subfolders as well) in Google Drive to find all documents and run a drive.files.get() on each of the documents. This is only possible using the batch request (hitting too many drive.files.get at the same time didn't work), and I was wondering -- what alternatives do you guys propose to do this without using batch request?

Thanks!

**Comment by sparkyfied** [comment]
Created this module as a short term alternative! https://github.com/wapisasa/Batchelor

**Comment by pradeep-mishra** [comment]
you can also look into this  https://www.npmjs.com/package/google-batch

**Comment by pradeep-mishra** [comment]
@RShergold that file patching was required for preventing googleapis to send http request right away after calling any function from it.
i should have mentioned that in readme, will update that.
