### ISSUE TITLE
Support for Picasa / G+ Photos API

### ISSUE THREAD

**Issue by simoneb** [googleapis/google-api-nodejs-client#292]
The Picasa / G+ Photos API seems to be missing, any chance to see it supported?

**Comment by esteban-uo** [comment]
Support +1

Why is almost unusable? @simoneb 

Seems to be it doesn't matter if is not shown in the Discovery service / Devs Console

"Activate the Picasa Web Albums Data API in the Google Developers Console. (If the API isn't listed in the Developers Console, then skip this step.)"

https://developers.google.com/picasa-web/docs/2.0/developers_guide_protocol#OAuth2Authorizing

**Comment by simoneb** [comment]
@esteban-uo because of [this](https://code.google.com/p/gdata-issues/issues/detail?id=6448), for example

**Comment by esteban-uo** [comment]
thanks for the answer @simoneb. 

But even if there still something like that broken, the need of an API client is required for other simpler functions, I built my own since I needed, hope it helps someone else. https://github.com/esteban-uo/picasa

**Comment by simoneb** [comment]
@JustinBeckwith why are you assigning this issue to me?
