### ISSUE TITLE
Bug? - Wrong type?

### ISSUE THREAD

**Issue by MichaelWalker-git** [googleapis/google-api-nodejs-client#2946]
https://github.com/googleapis/google-api-nodejs-client/blob/894bbd283c01bfbbf56f80e2551abde5e4dbc2cf/src/apis/calendar/v3.ts#L6871

### Description
sendUpdates
sendUpdates: [string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/string)
Type : [string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/string)
Optional
Whether to send notifications about the creation of the new event. Note that some emails might still be sent. The default is false.

### Problem
Since the default is false, would it not be easier / more clear if its type is a boolean?

### Expected:

I expect a parameter that I send as true or false to be a boolean not a string

**Comment by bcoe** [comment]
This library is generated automatically from the calendar API's discovery docs:

https://github.com/googleapis/google-api-nodejs-client/blob/main/discovery/calendar-v3.json#L807

I can confirm that the field should be a `string`, according to their API definition ☝️ 

Unfortunately, we can't fix this on our end. It may be worth opening a support ticket with the calendar product, to mention that this seems a bit off.
