### ISSUE TITLE
Can't query events from workspace ressource when using a service account

### ISSUE THREAD

**Issue by valen20Chx** [googleapis/google-api-nodejs-client#3000]
Hi,

I'm trying to retrieve events from the calendar of the resources (some meeting rooms) on my workspace using a **service account**.

I'm trying to get the intervals when they are busy using the [freebusy query](https://developers.google.com/calendar/api/v3/reference/freebusy/query).
I keep getting these errors:
```
"calendars": {
    "meetingRoom1@resource.calendar.google.com": {
      "errors": [
        {
          "domain": "global",
          "reason": "notFound"
        }
      ],
      "busy": []
    },
    "meetingRoom2@resource.calendar.google.com": {
      "errors": [
        {
          "domain": "global",
          "reason": "notFound"
        }
      ],
      "busy": []
    }
  }
```
On the "Try this method" section of the documentation I get this:
![GOOGLE_CAL_FREEBUSY_ERROR](https://user-images.githubusercontent.com/33943799/173875945-4fde6b83-2770-45d7-b7ee-1b316343ae8b.gif)

As you can see I get the correct data with the **OAuth 2** credentials (I won't be able to use them on the project), but with the **API key** I get the same data from the **service account**.

I've enabled **Domain-wide Delegation** for this service account id (although I'm not sure if it's necessary for resources).

Am I missing something ? If you're missing any information, I will make sure to answer as fast as I can.

**Comment by andreisaikouski** [comment]
@valen20Chx there are a few steps you need to make sure you did:
1. assign permissions to the service account (in IAM section)
2. domain-wide delegation
3. give access to the calendar to the service account email (I also had to enable "share with anyone external" setting on admin)
4. include the `clientOptions.subject` on auth.

e.g.
```
import { calendar_v3 as gCal, auth as gAuth } from '@googleapis/calendar';
const scopes = [
        'https://www.googleapis.com/auth/calendar',
        'https://www.googleapis.com/auth/calendar.events',
        'https://www.googleapis.com/auth/admin.directory.resource.calendar',
];
const auth = new gAuth.GoogleAuth({
        keyFile: filePath,
        scopes,
        projectId: 'project_id',
        clientOptions: {
                subject: 'target_email',
        },
});
const calendar = new gCal.Calendar({
        auth: authClient,
});
const resp = await calendar.freebusy.query({
        requestBody: {
                calendarExpansionMax: 1,
                items: [{ id: calendarId }],
                timeMax: '2023-02-01T10:00:00Z',
                timeMin: '2023-02-01T05:00:00Z',
        },
});
```

Above works for me

**Comment by molimauro** [comment]
If i add the "client_email" email i have in the json to my calendar settings i can correctly see all the events. Go to your calendar -> "share with people or specific groups" and add there the iam email

**Comment by valen20Chx** [comment]
Honestly, it's been a while, and I don't remember what I did. Must likely I used a userId on the workspace to be able to query resources. Sorry for the delay.
