### ISSUE TITLE
Where can I find the documentation for the Google Play Integrity API?

### ISSUE THREAD

**Issue by sjmach** [googleapis/google-api-nodejs-client#3021]
I am trying to implement in this API - https://github.com/googleapis/google-api-nodejs-client/tree/main/src/apis/playintegrity

However the documentation link present in the Readme in above link is broken, which is https://googleapis.dev/nodejs/googleapis/latest/playintegrity/classes/Playintegrity.html

**Comment by 1nikolas** [comment]
There is no documentation for this yet, you have to figure it out by yourself :)
([or use this example](https://stackoverflow.com/a/72566344/8627813))

**Comment by sjmach** [comment]
I ended up using Java: (

**Comment by kabamccortesdelafuente** [comment]
The link is still broken. Can you please provide a valid one?
