### ISSUE TITLE
Submodule googleapis-common dependency

### ISSUE THREAD

**Issue by Byeong-jun-Kim** [googleapis/google-api-nodejs-client#3022]
What is the reason for the low version of googleapis-common in the submodule?
It is ^6.0.0 for the whole module dependencies, but ^5.0.1 for the submodules.

**Comment by Byeong-jun-Kim** [comment]
@sofisl Can you check it?

**Comment by biro456** [comment]
It seems that the root package got upgraded to the latest `google-auth-library` and `googleapis-common` versions in https://github.com/googleapis/google-api-nodejs-client/pull/2979, but the template for the actual sub-packages didn't.

**Comment by Byeong-jun-Kim** [comment]
updated!
