### ISSUE TITLE
When will the @googleapis/playintegrity submolule be published to npm?

### ISSUE THREAD

**Issue by h6ah4i** [googleapis/google-api-nodejs-client#3023]
The following command fails because the submodule package is not published to the npm registry.  When will the submodule officially be released?

```bash
npm install @googleapis/playintegrity
```
ref.) https://www.npmjs.com/search?q=scope%3Agoogleapis%20playintegrity

**Comment by 1nikolas** [comment]
I agree this should be published

**Comment by sofisl** [comment]
Sorry that this took so long, it seems like it's been published: https://www.npmjs.com/package/@googleapis/playintegrity
