### ISSUE TITLE
Unable to stop channel

### ISSUE THREAD

**Issue by notsql** [googleapis/google-api-nodejs-client#3025]
Currently attempting to stop a channel that is already created. However, unable to do so.

This is the following code:
```js
oauth.setCredentials({ refresh_token });
const drive = google.drive({ version: "v3", auth: oauth });
                
const requestBody = {
	id: `${watchId}`,
	resourceId: `${gdriveFolderId}`
}

drive.channels.stop({ requestBody })
```
However, whenever I attempt to stop the channel, it keeps returning me an error stating that channel does not exist. I have also tried it using the REST API but got the same error.
Thanks for stopping by to ask us a question! Am I missing anything? Like for example, does my request body need to be exactly the same as the request body used to create the watcher?

Hope someone can help. Thank you!

**Comment by sofisl** [comment]
Hi @notsql,

Apologies for the delay in responding; hopefully this is still useful for you!

You have to grab the IDs in the response to stop the channel. See example below:

Request to create channel:

```
  const res = await drive.files.watch({
    fileId: 'field-Id',
    requestBody: {
      "kind": "api#channel",
      "id": "testing-channel",
      "resourceId": "test-channel",
      "resourceUri": "test-channel1",
      "type": "webhook",
      "address": "address",
    }
  })
```

This returns the response:

```
{
  kind: 'api#channel',
  id: 'testing-channel',
  resourceId: 'Ass7pcWq2U7-u2_nYDGrv70N-0I', <--- a new resourceId
  resourceUri: 'https://www.googleapis.com/drive/v3/files/'field-Id'?alt=json&null', <--- new resourceUri
  expiration: '1677195106000'
}
```

Then you can use those values to stop the channel:

```
    requestBody: {
      "id": "testing-channel",
      "resourceId": 'Ass7pcWq2U7-u2_nYDGrv70N-0I',
      "resourceUri": 'https://www.googleapis.com/drive/v3/files/'field-Id'?alt=json&null',
      "type": "webhook",
      "address": "address",
    }
```

Feel free to reopen if this doesn't work for you!
