### ISSUE TITLE
google.drivelabels is not a function

### ISSUE THREAD

**Issue by lewis-cobry** [googleapis/google-api-nodejs-client#3032]
1) Is this a client library issue or a product issue?: This is a client library issue.
2) Did someone already solve this?: Appears not
3) Do you have a support contract?: No

#### Environment details
  - OS: Windows 10 64bit
  - Node.js version: 16.15.0
  - npm version: 8.12.1
  - `googleapis` version: 39.2.0 (as used in the documentation), also tried 105.0.0 (latest)

#### Steps to reproduce

  1. run `npm install googleapis@39 --save` (note you can also try `npm install googleapis@latest`)
  2. use the following code according to the [quickstart](https://developers.google.com/drive/labels/quickstart/nodejs#step_2_set_up_the_sample): 
 ```js
const {google} = require('googleapis');
const auth = new GoogleAuth();  // uses env variable for path to json credential file

const service = google.drivelabels({version: 'v2', auth: auth});
```
3. You will get the error: `TypeError: google.drivelabels is not a function`

**Comment by sofisl** [comment]
Hi @lewis-cobry, 

Thanks for submitting this issue. We haven't merged the code for drivelabels yet, it's in [this PR](https://github.com/googleapis/google-api-nodejs-client/pull/3019), that is being held back by an unrelated issue. I will work to get this PR merged ASAP.
