### ISSUE TITLE
Analytics admin API - create GA4 audiences list

### ISSUE THREAD

**Issue by weilinzung** [googleapis/google-api-nodejs-client#3035]
- What you're trying to do
I am trying to use the client lib to create GA4 audiences list

- What code you've already tried
https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.audiences
According to the link, the API endpoint has all the GA4 audience methods, but the client lib doesn't seem to have the latest updates.

Could someone clarify if that is supported by the client lib? or will this be supported soon?  thanks!

**Comment by sofisl** [comment]
Blocked by https://github.com/googleapis/google-api-nodejs-client/pull/3019

**Comment by weilinzung** [comment]
@sofisl the CI seems good now, would that be released soon?

**Comment by sofisl** [comment]
Yes! It should already be released. Feel free to reopen if you run into any more issues.
