### ISSUE TITLE
API for contact recovery/undelete?

### ISSUE THREAD

**Issue by src200** [googleapis/google-api-nodejs-client#3041]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
Is there any API for contact recovery/undelete? I want to recover it from client(3rd party) application.
- What code you've already tried
I have searched API explorer, but couldn't find one.
- Any error messages you're getting
N/A

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by sofisl** [comment]
Hi @src200, this [list](https://github.com/googleapis/google-api-nodejs-client/tree/main/src/apis) and this one [nodejs client libraries](https://github.com/googleapis/google-cloud-node) comprises all the nodejs client libraries we've generated. From what I can tell, I don't think we have the library you're searching for but feel free to provide some more context and/or a link to documentation for the api itself.
