### ISSUE TITLE
@googleapis/displayvideo package is still in 5.0.1 while 5.0.3 seems to be available

### ISSUE THREAD

**Issue by aminebeh** [googleapis/google-api-nodejs-client#3090]
Hey,

Just wanted to know if by any chance, you know when the 5.0.3 version of the package @googleapis/displayvideo will be published ?

I wanted to use the client lib to make request to v2 endpoints 😃 

Side-question: how can I use the client (or other google libs) to make requests to the new endpoint using a service account credential file for the request ?

**Comment by bcoe** [comment]
5.0.3 is now published:

https://www.npmjs.com/package/@googleapis/displayvideo/v/5.0.3
