### ISSUE TITLE
is google-api-nodejs-client supports google keep api?

### ISSUE THREAD

**Issue by YutaOkoshi** [googleapis/google-api-nodejs-client#3091]
I would like to get a list of notes using the Google keep API.
https://developers.google.com/keep/api/reference/rest/v1/notes/list?hl=ja

is google-api-nodejs-client not supports this api yet?

should i use http client?

**Comment by bcoe** [comment]
Hello @YutaOkoshi, 

I do not see keep in the [list of apis](https://github.com/googleapis/google-api-nodejs-client/tree/main/src/apis), which means it is not listed as a discovery document (and we can't generate).

Your best bet currently would be using a library like fetch, to use the HTTP API. I recommend also reaching out to [keep support](https://developers.google.com/keep/api/support?hl=ja) (asking for a client).

**Comment by garetmckinley** [comment]
Not sure if this was a recent change, but keep is definitely in the list of APIs now. https://developers.google.com/keep/api/reference/rest/
