### ISSUE TITLE
Can I use conditionMatchedLog?

### ISSUE THREAD

**Issue by bayerlse** [googleapis/google-api-nodejs-client#3114]
Hey there!

I'm trying to create an alertPolicy via `AlertPolicyServiceClient` and its `createAlertPolicy` method.
If I include the `conditionMatchedLog` as condition key,  i'm getting the error:

```json
{"code":3,"details":"Field alert_policy.conditions[0].condition_case had an invalid value of \"0\": Condition subtype (e.g. \"condition_absent\",\"condition_threshold\", etc.) is absent or unknown.","metadata":{}}
```

But in the documentation https://cloud.google.com/logging/docs/alerting/log-based-alerts#lba-by-api it sounds like it should be possible.... Am I missing something?

Thanks in advance,

Sebi

**Comment by sofisl** [comment]
Hi @bayerlse, not sure how you wrote your condition statement, but this worked for me:

```
      "conditions": [
        {
          "displayName": "Log match condition: invalid IP addr (API)",
          "conditionMatchedLog": {
            "filter": "severity = \"NOTICE\"",
          },
        }
      ],
```

Could you share what you are trying to send?

**Comment by sofisl** [comment]
Going to close this for now, feel free to reopen if you're having the same issue!

**Comment by bayerlse** [comment]
Thanks @sofisl for your answer, I will try it out soon :)
