### ISSUE TITLE
Field interaction seems to be missing for card actions in type definition

### ISSUE THREAD

**Issue by GerroDen** [googleapis/google-api-nodejs-client#3115]
As documented [here](https://developers.google.com/chat/api/reference/rest/v1/cards?hl=en#action) actions can have a field `interaction` to open dialogs. This field seems to be missing in the TypeScript typing?

**Comment by bcoe** [comment]
@GerroDen it looks like this field was added in the latest release of the library, which is being published right now.

https://github.com/googleapis/google-api-nodejs-client/pull/3134

Let us know if you bump into any issues.
