### ISSUE TITLE
Authentication: Passing credentials without writing to filesystem (i.e. GOOGLE_APPLICATION_CREDENTIALS)

### ISSUE THREAD

**Issue by bertrand-caron** [googleapis/google-api-nodejs-client#3119]
Hi,

Is there a way to authenticate a `BetaAnalyticsDataClient` without writing to the filesystem (i.e. without passing an absolute path to `GOOGLE_APPLICATION_CREDENTIALS`)?

I'd rather not write secrets to the filesystem if I have the credentials in memory.

Thanks a lot :)

**Comment by remarcoble** [comment]
Try with this one:

```typescript
import { google } from "googleapis";

const auth = new google.auth.GoogleAuth({
    credentials: {
      client_email: "CLIENT_EMAIL",
      private_key: "CLIENT_PRIVATE_KEY"
    },
    scopes: ["NEEDED_SCOPES"],
  });

google.options({auth: auth});
```

**Comment by bertrand-caron** [comment]
Thanks @remarcoble !

Just for completeness' sake, the `BetaAnalyticsDataClient` also accepts the same credentials parameter, so I ended up doing:


```
const CLIENT = new BetaAnalyticsDataClient({
    credentials: {
        client_email:'....',
        private_key: '.....',
    },
})
```

Might be worth adding to the docs (if not there already)?

**Comment by danielbankhead** [comment]
This section (and included links) should cover this: https://github.com/googleapis/google-api-nodejs-client#authentication-and-authorization

Let us know if there's a particular section that should be expanded!
