### ISSUE TITLE
Adding label to gmail message.

### ISSUE THREAD

**Issue by ewein** [googleapis/google-api-nodejs-client#312]
Every request I make to users.messages.modify (https://developers.google.com/gmail/api/v1/reference/users/messages/modify) returns:

``` sh
{ errors:
    [ { domain: 'global',
        reason: 'invalidArgument',
        message: 'No label add or removes specified' } ],
   code: 400,
   message: 'No label add or removes specified' }
```

I am making the request like:

``` sh
var service = Google.gmail({version : 'v1', auth : oauth2Client});
service.users.messages.modify({
    'userId': 'some email address',
    'id': 'some message id',
    'addLabelIds': ['some label id'],
    'removeLabelIds': []
}, function (err) {
    if (!err) {
        callback(true);
    } else {
        console.log(err);
        callback(false);
    }
});
```

Not sure if I am just missing something or if this is an issue with the library.

**Comment by volumetric** [comment]
@ewein thanks for the tip. saved me some time.

**Comment by josegl** [comment]
It's incredible. 
The google api docs example specifies this:
```javascript
unction modifyMessage(userId, messageId, labelsToAdd, labelsToRemove, callback) {
  var request = gapi.client.gmail.users.messages.modify({
    'userId': userId,
    'id': messageId,
    'addLabelIds': labelsToAdd,
    'removeLabelIds': labelsToRemove
  });
  request.execute(callback);
}
```
Take a look to the javascript example at https://developers.google.com/gmail/api/v1/reference/users/messages/modify

I was doing it that way, and I was taking this error:
```
< { [Error: No label add or removes specified]
<   code: 400,
<   errors:
<    [ { domain: 'global',
<        reason: 'invalidArgument',
<        message: 'No label add or removes specified' } ] }
```
The solution found here worked great. 
thank you.

**Comment by Roilan** [comment]
Doc still hasn't been updated :(

Spent time trying to figure out what was wrong before I came across this.

**Comment by ctepeo** [comment]
Hi, guys! Writing to You from Feb 2019 (so ~4 years 3 months passed since the question has been asked here) and want to confirm that they still didn't fix the docs, API returns the same error and the solution @ewein [provided](https://github.com/googleapis/google-api-nodejs-client/issues/312#issuecomment-60006133) works perfectly!

**Comment by evan-churchill** [comment]
Long live @ewein ps we miss you at btag buddy =]

**Comment by bacali95** [comment]
I got that error also, even the solution of @ewein didn't work for me, so i have digged in the implimentation of the function and i found that the structure of the params argument looks like this:
```ts
interface Params$Resource$Users$Messages$Modify extends StandardParameters {
    /**
     * Auth client or API Key for the request
     */
    auth?: string | OAuth2Client | JWT | Compute | UserRefreshClient;
    /**
     * The ID of the message to modify.
     */
    id?: string;
    /**
     * The user's email address. The special value me can be used to indicate the authenticated user.
     */
    userId?: string;
    /**
     * Request body metadata
     */
    requestBody?: Schema$ModifyMessageRequest;
}
```
with `Schema$ModifyMessageRequest` looks like this:
```ts
interface Schema$ModifyMessageRequest {
    /**
     * A list of IDs of labels to add to this message.
     */
    addLabelIds?: string[];
    /**
     * A list IDs of labels to remove from this message.
     */
    removeLabelIds?: string[];
}
```
so the right way to write the params is:
```ts
function modifyMessage(userId, messageId, labelsToAdd, labelsToRemove, callback) {
    var request = gapi.client.gmail.users.messages.modify({
        'userId': userId,
        'id': messageId,
        'requestBody': {
            'addLabelIds': labelsToAdd,
            'removeLabelIds': labelsToRemove
        }
    });
    request.execute(callback);
}
```
hope that help you guys, and they update the docs.

**Comment by 100rab12** [comment]
> I got that error also, even the solution of @ewein didn't work for me, so i have digged in the implimentation of the function and i found that the structure of the params argument looks like this:
> 
> ```ts
> interface Params$Resource$Users$Messages$Modify extends StandardParameters {
>     /**
>      * Auth client or API Key for the request
>      */
>     auth?: string | OAuth2Client | JWT | Compute | UserRefreshClient;
>     /**
>      * The ID of the message to modify.
>      */
>     id?: string;
>     /**
>      * The user's email address. The special value me can be used to indicate the authenticated user.
>      */
>     userId?: string;
>     /**
>      * Request body metadata
>      */
>     requestBody?: Schema$ModifyMessageRequest;
> }
> ```
> 
> with `Schema$ModifyMessageRequest` looks like this:
> 
> ```ts
> interface Schema$ModifyMessageRequest {
>     /**
>      * A list of IDs of labels to add to this message.
>      */
>     addLabelIds?: string[];
>     /**
>      * A list IDs of labels to remove from this message.
>      */
>     removeLabelIds?: string[];
> }
> ```
> 
> so the right way to write the params is:
> 
> ```ts
> function modifyMessage(userId, messageId, labelsToAdd, labelsToRemove, callback) {
>     var request = gapi.client.gmail.users.messages.modify({
>         'userId': userId,
>         'id': messageId,
>         'requestBody': {
>             'addLabelIds': labelsToAdd,
>             'removeLabelIds': labelsToRemove
>         }
>     });
>     request.execute(callback);
> }
> ```
> 
> hope that help you guys, and they update the docs.

@bacali95 Thanks, brother. You are a lifesaver.

**Comment by 100rab12** [comment]
@bacali95 Thanks, brother. You are a lifesaver.

**Comment by KidA001** [comment]
@ewein so your example has `resource` spelled `resouce`. My request failed and when I googled the error I came across [this stackoverflow](https://stackoverflow.com/questions/34827580/error-no-label-add-or-removes-specified-when-trying-to-modify-labels-using-gma) and realized that me and others probably copied your response :)

Mind editing your post?

**Comment by 0Grit** [comment]
Why can't I remove a user label with a filter.... It's enraging

**Comment by astrocinco** [comment]
Hi! I had a similar problem, but with Python. 
The solution was the following:
`def add_label_to_thread(service, thread):
    labels = {
        "addLabelIds": [ "STARRED" ],
        "removeLabelIds": [ "UNREAD"]
    }
    service.users().threads().modify(userId='me', id=thread["id"], body=labels).execute()`

Not only do you have to create an object with addLabelIds and removeLabelIds, but the parameter in modify() has to named "**body**", not "resource".
I hope this helps.

**Comment by astrocinco** [comment]
Hi! I had a similar problem, but with Python.
The solution was the following:
```
def add_label_to_thread(service, thread): labels = { "addLabelIds": [ "STARRED" ], "removeLabelIds": [ "UNREAD"] } service.users().threads().modify(userId='me', id=thread["id"], body=labels).execute()
```

Not only do you have to create an object with addLabelIds and removeLabelIds, but the parameter in modify() has to named "**body**", not "resource".
I hope this helps.

**Comment by astrocinco** [comment]
Hi! I had the same problem in Python, but fixing it requieres an extra step:
The parameter in modify() needs to be called "body". "resource" doesnt work.

```
def add_label_to_thread(service, thread):
    myLabels = {
        "addLabelIds": [ "STARRED" ],
        "removeLabelIds": [ "UNREAD"]
    }
    service.users().threads().modify(userId='me', id=thread["id"], body=myLabels).execute()
```

Otherwise, you get the following error: `raise TypeError("Got an unexpected keyword argument {}".format(name))
TypeError: Got an unexpected keyword argument resource`
I hope this is useful for someone in the future
