### ISSUE TITLE
Missing offerDetails property in interface Schema$SubscriptionPurchaseLineItem

### ISSUE THREAD

**Issue by remarcoble** [googleapis/google-api-nodejs-client#3123]
[Documentation](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptionsv2#OfferDetails) reports that Android publisher's interface `Schema$SubscriptionPurchaseLineItem` has also a `offerDetails` property but here it's missing although the instance returned has it.

At the moment you can access it with this workaround but that's a bit annoying:

```typescript
const offerDetails = (subscriptionv2.lineItems![0] as any).offerDetails;
```

Here's the missing code for [Android publisher v3](https://github.com/googleapis/google-api-nodejs-client/blob/main/src/apis/androidpublisher/v3.ts#L1911):

```typescript
export interface Schema$SubscriptionPurchaseLineItem {
  // Omitted other properties...
  /**
   * Offer details information related to a purchase line item.
   */
  offerDetails?: Schema$OfferDetails;
}

/**
 * Offer details information related to a purchase line item.
 */
export interface Schema$OfferDetails {
  /**
   * The latest offer tags associated with the offer. It includes tags inherited from the base plan.
   */
  offerTags?: string[] | null,
  /**
   * The base plan ID. Present for all base plan and offers.
   */
  basePlanId?: string | null,
  /**
   * The offer ID. Only present for discounted offers.
   */
  offerId?: string | null
}
```

**Comment by sofisl** [comment]
Hi @remarcoble, I'm not quite sure I understand the question (this is perhaps because of the time it's taken me to get to it, sorry about that!) It seems like android publisher has the code you've listed as missing. Can you confirm this issue is still occurring and provide a way of reproducing, or else perhaps the question is out of date?

**Comment by remarcoble** [comment]
Hi @sofisl, I confirm that it has been added in the commit b029f60343727f4061947b534213eb26d276fb4a
