### ISSUE TITLE
calendar.events.insert({     sendUpdates: 'all', ...payload }) is not sending email to the attendees

### ISSUE THREAD

**Issue by nikhilthakur001** [googleapis/google-api-nodejs-client#3147]
I'm using the googleapis in NodeJs and trying to create events. Events are created successfully but the notification is not send to gmail accounts. 

```
const createEvent = async () => {
  const calendar = google.calendar({
    version: 'v3',
    auth: oauth2Client,
  });

const event = { ... };

const response = await calendar.events.insert({
    sendUpdates: 'all',
    calendarId: 'primary',
    requestBody: event,
    conferenceDataVersion: 1,
    supportsAttachments: true,
  });
}
```

**Comment by bcoe** [comment]
Hello @nikhilthakur001, given that the event is being created, this does not sound like an issue with the client library. My recommendation would be to reach out to the calendar team for support.

https://developers.google.com/workspace/support

**Comment by xdc0** [comment]
If anyone runs into this: Check if you are creating events in the past, Google will not send notifications for events created in the past.
