### ISSUE TITLE
Google Classroom sample

### ISSUE THREAD

**Issue by Duckbio** [googleapis/google-api-nodejs-client#3155]
Could you please add a google classroom sample? Thank you!

**Comment by sofisl** [comment]
Hi @Duckbio! I'd recommend looking through this file for samples, for [example](https://github.com/googleapis/google-api-nodejs-client/blob/31defea1dca2e32d2cfcea1649087a206e7254d1/src/apis/classroom/v1.ts#L1368).

There's also some more documentation [here](https://developers.google.com/classroom/reference/rest), and quickstarts and guides [here](https://developers.google.com/classroom/guides/get-started).

Finally, if you want more specific samples, I'd recommend logging a bug with documentation, here: 

<img width="1349" alt="Screenshot 2023-02-08 at 4 23 05 PM" src="https://user-images.githubusercontent.com/55454395/217682240-ddee1d2e-9ed5-44ce-a40b-ac30d6b3a221.png">


Feel free to open bugs later with any other questions :)
