### ISSUE TITLE
Using API key to authorize gmail API

### ISSUE THREAD

**Issue by bracesproul** [googleapis/google-api-nodejs-client#3165]
I'm using the gmail API to listen and read incoming messages from one gmail account. As of now I can't find a way to authorize gmail so it can use an API key instead of an OAuth2 client. This is preferable for me as it's running on a backend API and I do not want to deal with re-authorizing any credentials. Is it possible to use a static key or file to authorize the gmail API with or is that simply not an option?

**Comment by sofisl** [comment]
Hi @bracesproul, wanted to send over some quick resources before I dig into it, perhaps they might help:

https://github.com/googleapis/google-api-nodejs-client#using-api-keys

That README also has other info on different authentication methods for this library.
