### ISSUE TITLE
Split googleapis package into sub-packages

### ISSUE THREAD

**Issue by magic-m-johnson** [googleapis/google-api-nodejs-client#3170]
Currently the whole googleapis package is over 120MB large. It would be cool to have singular, dedicated sub-packages like `@aws/*`. For example, when you only need oauth and sheets API you only need to install those without the overhead.

So instead of

```js
import { google } from "googleapis" // HUGE

const oauth = google.oauth.something()
const sheets = google.sheets.something()

// do stuff
```

something like this:

```js
import oauth from "@googleapis/oauth" // smol
import sheets from "@googleapis/sheets" // also smol

// do stuff
```

This will hugely increase build times and deployments that bundle & transpile apps on a jenkins pipeline, for example.

**Comment by sofisl** [comment]
Hi @magic-m-johnson, we do this! See details [here](https://github.com/googleapis/google-api-nodejs-client#getting-started), you can also use our gapic clients [here](https://github.com/googleapis/google-api-nodejs-client#getting-started), depending on which libraries you need.

Example [sheets](https://www.npmjs.com/package/@googleapis/sheets). Hope this helps! Feel free to reopen if not.
