### ISSUE TITLE
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.

### ISSUE THREAD

**Issue by lestherbualan** [googleapis/google-api-nodejs-client#3171]
#### Environment details

  - Framework: Angular 15
  - OS: Windows 10
  - Node.js version: v18.14.0
  - npm version: 9.3.1
  - `googleapis` version: 111.0.0

#### Steps to reproduce

  1. recreated the quickstart in using google classroom api using angular [here](https://developers.google.com/classroom/quickstart/nodejs#set_up_the_sample)

Thanks!
![error](https://user-images.githubusercontent.com/54540433/221144808-dcbef15b-4537-467e-b8a7-6d94872f802d.png)

**Comment by GreyM22** [comment]
@lestherbualan why did you close it? I am having the same issue. Did you find a solution?
