### ISSUE TITLE
Insert event returning "Invalid conference type value"

### ISSUE THREAD

**Issue by oliveirabalsa** [googleapis/google-api-nodejs-client#3197]
I already spent 3 days searching about it and then finally decided to open this issue, I've tried a lot of things but can't create the event. When I remove the **conferenceData** it works but no meet link is provided and when I add I get an **Invalid conference type value**, I've tried to change **requestBody**, resource, using the API URL, etc. I checked the environment variables and it's ok too.

I read problems because of the Domain-wide Delegation but I've already created a workspace and added it there following these steps [https://developers.google.com/workspace/guides/create-credentials](url). Assigned a domain, but the problem is still happening, the code I'm using below:

```ts
 constructor(private readonly eventService: EventService) {
    // Set up the Google Calendar API client with credentials from the environment variables
    const auth = new google.auth.GoogleAuth({
      credentials: JSON.parse(process.env.GOOGLE_CREDENTIALS),
      scopes: ['https://www.googleapis.com/auth/calendar'],
    });
    this.calendar = google.calendar({ version: 'v3', auth });
  }

  @Mutation(() => Event)
  async createGoogleEvent(
    @Args('createEventInput') createEventInput: CreateEventInput,
  ) {
    // const { startDate, endDate, learnerId, mentorId } = createEventInput;

    // Create a new event with a Meet link included

    const event = await this.calendar.events.insert({
      calendarId: process.env.GOOGLE_CALENDAR_ID,
      requestBody: {
        summary: 'dummy',
        description: 'dummy',
        start: {
          dateTime: '2023-08-10T10:00:00-03:00',
        },
        end: {
          dateTime: '2023-08-10T11:00:00-03:00',
        },
        conferenceData: {
          createRequest: {
            requestId: '1234',
            conferenceSolutionKey: {
              type: 'hangoutsMeet',
            },
          },
        },
      },
      conferenceDataVersion: 1,
    });

    return console.log(event.data);
  }
  ```

**Comment by oliveirabalsa** [comment]
The solution i found is using the `auth.JWT` passing "user delegation wide email" and "client_id" authorized by delegation wide.

**Comment by MOIN-AKHTAR** [comment]
@oliveirabalsa i need help could you plz help me?
