### ISSUE TITLE
Google Calendar api integration without any access_token expire on Node.js

### ISSUE THREAD

**Issue by WebApp1018** [googleapis/google-api-nodejs-client#3251]
I am working on node.js back-end to integrate google calendar api.
I've got the access_token and refresh_token from ([https://developers.google.com/oauthplayground]).
And this was working well, but an hour later the access_token is expired and It is not working anymore.
so I used oauth2Client.refreshAccessToken() function to get access_token dynamically, but I am getting error.

Here is my code.

const { google } = require("googleapis");

// Function to refresh the access_token
const refreshToken = (oauth2Client) => {
  return new Promise((resolve, reject) => {
    oauth2Client.refreshAccessToken((err, tokens) => {
      if (err) {
        console.log("err ----- ++++++");
        reject(err);
      } else {
        oauth2Client.setCredentials(tokens);
        resolve(tokens.access_token);
      }
    });
  });
};

// Function to insert an event into the Google Calendar API
const insertEvent = (calendar, oauth2Client, event) => {
  calendar.events
    .insert({
      auth: oauth2Client,
      calendarId: "primary",
      resource: event,
    })
    .then((event) => console.log("Event created: %s", event))
    .catch((error) => {
      if (error.code === 401 && error.message === "Invalid Credentials") {
        refreshToken(oauth2Client)
          .then((newAccessToken) => {
            oauth2Client.setCredentials({
              access_token: newAccessToken,
              refresh_token: oauth2Client.credentials.refresh_token,
            });
            const updatedCalendar = google.calendar({
              version: "v3",
              oauth2Client,
            });
            retryRequest(updatedCalendar, oauth2Client, event); // Retry the API request
          })
          .catch((error) =>
            console.log("Error refreshing access token", error)
          );
      } else {
        console.log("Some error occurred", error);
      }
    });
};

// Function to retry the API request
const retryRequest = (calendar, oauth2Client, event) => {
  insertEvent(calendar, oauth2Client, event);
};

//@route    GET api/booking/save_booking
//@desc     Save booking route
//@access   Public
router.post("/save_booking", (req, res) => {
  const eventData = req.body;
  const oauth2Client = new google.auth.OAuth2(
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxx"
  );

  refreshToken(oauth2Client)
    .then((newAccessToken) => {
      oauth2Client.setCredentials({
        access_token: newAccessToken,
        refresh_token: oauth2Client.credentials.refresh_token,
      });
      const calendar = google.calendar({ version: "v3", oauth2Client });

      const event = {
        summary: eventData.category.name,
        description,
        start: {
          dateTime: eventData.start,
          timeZone: "America/Los_Angeles",
        },
        end: {
          dateTime: eventData.end,
          timeZone: "America/Los_Angeles",
        },
        reminders: {
          useDefault: false,
          overrides: [
            { method: "email", minutes: 24 * 60 },
            { method: "popup", minutes: 60 },
          ],
        },
      };

      // Make the initial API request
      insertEvent(calendar, oauth2Client, event);
    })
    .catch((error) => console.log("Error refreshing access token", error));
});

Here is console.
err ----- ++++++
Error refreshing access token Error: No refresh token is set.

**Comment by GiantPineappleStatue** [comment]
same question, bump.
