### ISSUE TITLE
I am getting error Invalid conference type value

### ISSUE THREAD

**Issue by MOIN-AKHTAR** [googleapis/google-api-nodejs-client#3272]
I want to create a google meet link for a google calander event.For that i have create a service-account.json  and also enabled calander api for my project and given access of my personal google account calander to email of this service-account.json.Now when i am trying to create a google calander and config calander event in such a way that it should create google meet link i am getting error Invalid conference type value but if i not configiguring google meet link thing than event is being created successfully.Kindly guide me what i am doing wrong.
My whole code is here:
https://github.com/MOIN-AKHTAR/calmder_event_via_service_account

**Comment by ddelgrosso1** [comment]
Hello @MOIN-AKHTAR please see the [documentation here](https://developers.google.com/calendar/api/guides/create-events#conferencing) on adding a conference to an event. It is possible calendar you are using does not support the type of conference you are trying to create or the calendar is not setup correctly.

**Comment by MOIN-AKHTAR** [comment]
@ddelgrosso1 while according to a blog it should be look like this:
![Uploading doc.PNG…]()

**Comment by MOIN-AKHTAR** [comment]
@ddelgrosso1 while according to a blog it should be look like this:
![doc](https://github.com/googleapis/google-api-nodejs-client/assets/47149401/bd3b3420-c29a-4eb2-a50f-a922bda01979)

**Comment by MOIN-AKHTAR** [comment]
Ok i got it i wasn't able to see this Access And Data Control option because of my role permissions.

**Comment by akshaychopra5207** [comment]
@MOIN-AKHTAR How did you fix this issue?

**Comment by akshaychopra5207** [comment]
do we need domain wide delegation just to create google meeting link via api? I do not want to access other users data, I just want to create a google meeting link in any calender will work.

**Comment by akshaychopra5207** [comment]
> Hello @MOIN-AKHTAR please see the [documentation here](https://developers.google.com/calendar/api/guides/create-events#conferencing) on adding a conference to an event. It is possible calendar you are using does not support the type of conference you are trying to create or the calendar is not setup correctly.

@ddelgrosso1 

I am using service account credentials with enabled google calender api.
My backend service just needs to create google meeting link and send the response with this link.
why do we need domain wide delegation for this. I am not using users data. I just want service account calender to be used and the google meet event is created there
