### ISSUE TITLE
const opn = require("open") not importing. 

### ISSUE THREAD

**Issue by Asw-S93** [googleapis/google-api-nodejs-client#3273]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
- Trying to import 'open' module after installing the npm package. [Trying out the auth sample](https://github.com/googleapis/google-api-nodejs-client/blob/main/samples/oauth2.js)
- What code you've already tried
- const opn = require("open");
- Any error messages you're getting
- login.js to a dynamic import() which is available in all CommonJS modules.
-Note: I am learning react/web dev. I was able to

**Comment by ddelgrosso1** [comment]
@Asw-S93 if this is a web application you will need to utilize `import` as opposed to `require`. The sample you are referencing is using Node style `require`.
