### ISSUE TITLE
Bump and publish a new @googleapis/run version

### ISSUE THREAD

**Issue by fduser1** [googleapis/google-api-nodejs-client#3308]
@sofisl Lots of good enhancements in the Cloud Run space this year. The last published update was 10 months ago for @googleapis/run package. I appreciate a version bump (e.g. 11.1.0) so I could directly import it to improve the startup time of my apps.

(Cloud Client Libraries currently do not have all of the features available so I am now relying on API Client Libraries)

**Comment by sofisl** [comment]
Hi @fduser1! Unfortunately this library's updates are autogenerated from whatever is updated internally. So, whatever functionality is currently available to the API Client libraries is already published. New updates get generated regularly though, so hopefully something will come down the pipeline soon. If you'd like, feel free to directly [request](https://cloud.google.com/support/docs/issue-trackers) a feature request to the API to expose a given functionality in the library (under Create new Cloud Run Issue)

**Comment by fduser1** [comment]
Thank you @sofisl. I hope a new version will get triggered soon also. In the meantime, I will consider the alternate request route. Thanks!
