### ISSUE TITLE
Is the @googleapis/oauth2 package deprecated?

### ISSUE THREAD

**Issue by awdr74100** [googleapis/google-api-nodejs-client#3375]
I want to obtain oauth user information through @googleapis/people, but @googleapis/oauth2 v1.0.5 prompts that the package has been deprecated. So which package should I use for oauth behavior?

Also, I would like to ask if the latest way to obtain the user's firstname and lastname is through the people api? I remember that it didn't seem to be needed before.

**Comment by ddelgrosso1** [comment]
Hi @awdr74100 You can use https://github.com/googleapis/google-auth-library-nodejs. Hope this helps.
