### ISSUE TITLE
Please try updating your code as follows to enable the confidence score. You should then see confidence scores in the `full_text_annotation` section of the response:

### ISSUE THREAD

**Issue by DYT5131** [googleapis/google-api-nodejs-client#3390]
How to do the same for Node JS? I am experiencing the same issue for a Node JS app.
              
Please try updating your code as follows to enable the confidence score. You should then see confidence scores in the `full_text_annotation` section of the response:

```python
text_detection_params = vision.TextDetectionParams(enable_text_detection_confidence_score=True)
image_context = vision.ImageContext(text_detection_params=text_detection_params)
response = client.text_detection(image=image, image_context=image_context)
```

_Originally posted by @kweinmeister in https://github.com/googleapis/python-vision/issues/266#issuecomment-973301113_

**Comment by ddelgrosso1** [comment]
Hi @DYT5131 please see the [vision documentation](https://cloud.google.com/nodejs/docs/reference/vision/latest/overview). You should be able to find the equivalent NodeJS function calls there.
