### ISSUE TITLE
Does `bucket.file(...).save(buffer)` throw on error?

### ISSUE THREAD

**Issue by heyarne** [googleapis/google-api-nodejs-client#3399]
Hi,

[The docs for `File.save`](https://googleapis.dev/nodejs/storage/latest/File.html#save-examples) seem to imply that the promisified version of the method throws an error when saving is not successful. I assumed so because it's common for other promisified APIs where the callback-based version matches the NodeJS convention of reserving the first callback parameter for a possible error.

Nevertheless I have just been bitten by code like this:

``` ts
console.log('before saving')
await bucket.file(path).save(buffer)
console.log('after saving')
```

This ran from top to bottom and did not throw any error even though the file was not stored in the bucket. Is this intentional? Did I hit a bug?

If this is intentional, should I explicitly check whether saving was successful myself or what is the suggested pattern? The following does not work because `save` returns a `Promise<void>`:

```ts
const err = await bucket.file(path).save(buffer)
```

Thanks!

**Comment by danielbankhead** [comment]
Hey @heyarne, we provide a better storage experience in `@google-cloud/storage` rather than the `@googleapis/storage` library:
- https://github.com/googleapis/nodejs-storage

The `@google-cloud/storage` library shouldn't have the mentioned issue.
