### ISSUE TITLE
 YouTube push notifications

### ISSUE THREAD

**Issue by Renari** [googleapis/google-api-nodejs-client#3415]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
Currently I'm polling YouTube for video updates, however it seems push notifications are a more reliable method of receiving updates:
https://developers.google.com/youtube/v3/guides/push_notifications
 **Describe the solution you'd like**
 The above pubsub system supported in the nodejs library.
 **Describe alternatives you've considered**
Currently I believe polling is the only alternative with this library.

**Comment by sofisl** [comment]
Hi @Renari, please suggest feature requests for the API in their issue tracker, this is only an autogenerated library:

 https://issuetracker.google.com/issues/new?component=186600&template=874803

Thank you!

**Comment by Renari** [comment]
Is this not already supported in the API? The linked page is for the YouTube Data API.
