### ISSUE TITLE
Implement exponential backoff when executing request

### ISSUE THREAD

**Issue by yetithefoot** [googleapis/google-api-nodejs-client#482]
Google suggests to use exponential backoff strategy for avoiding 4XX or 5XX errors. It can be implemented inside SDK and enabling by passing option to request constructor or request.execute. It would safe alot of time for developers who can't implement this strategy by some reasons.

**Comment by hutchike** [comment]
Check out my "ntil" NPM package. It makes exponential back-off very simple.
