### ISSUE TITLE
Come up with a way to automate releases (and detect if a release even needs to be cut)

### ISSUE THREAD

**Issue by jmdobry** [googleapis/google-api-nodejs-client#525]
Detecting whether a release needs to be cut might involve regenerating and checking if `git diff` is not empty.

**Comment by YasharF** [comment]
Do you have any update on this by any chance?  It would be really helpful to unblock https://github.com/googleapis/google-api-nodejs-client/issues/806

**Comment by YasharF** [comment]
@JustinBeckwith, @lukesneeringer , @jmdobry Is this assigned to anyone or actively on the radar?  I saw that it is stated as a blocker for resolving https://github.com/googleapis/google-api-nodejs-client/issues/806 but unlike that issue this one is not tagged as "Assigned" to anyone specific on Github.  I am hoping that it is not a forgotten issue.

**Comment by JustinBeckwith** [comment]
Greetings!  This is not forgotten :) As a matter of fact, #1905 is a nod in this direction.  The truth is, as the README states:

> These client libraries are officially supported by Google. However, these libraries are considered complete and are in maintenance mode. This means that we will address critical bugs and security issues but will not add any new features. For Google Cloud Platform APIs, we recommend using google-cloud-node which is under active development.

We do tend to fix bugs as they come up, but enhancement like this will generally take a back seat to the work going on in https://github.com/googleapis/google-cloud-node.

**Comment by JustinBeckwith** [comment]
What a way to end the week!  The first one of these automated PRs just landed.  
https://github.com/googleapis/google-api-nodejs-client/pull/2221

This is actually done!
