### ISSUE TITLE
Receiving 401 Invalid Credentials with oauth2Client

### ISSUE THREAD

**Issue by gabrielhpugliese** [googleapis/google-api-nodejs-client#55]
I get the access_token and refresh_token through another process (Meteor OAuth) and tries to pass it to the oauth2Client.credentials, but it's not refreshing:

```
[GA ERROR] getData:  { code: 401,
  message: 'Invalid Credentials',
  data: 
   [ { domain: 'global',
       reason: 'authError',
       message: 'Invalid Credentials',
       locationType: 'header',
       location: 'Authorization' } ] }
```

The code:

``` javascript
function getData (user, params) {
    var googleapis = Meteor.require('googleapis'),
        OAuth2Client = googleapis.OAuth2Client,
        oauth2Client = new OAuth2Client(CLIENT_ID, CLIENT_SECRET, REDIRECT_URL);
    var accessToken = user.services.google.accessToken,
           refreshToken = user.services.google.refreshToken; //works

    oauth2Client.credentials = {
        access_token: accessToken,
        refresh_token: refreshToken
    };
    googleapis.discover('analytics', 'v3').execute(function (err, client) {
            if (err) {
                console.log('[GA ERROR] getClient: ', err);
                return;
            }
            client.analytics.data.ga
                .get(params)
                .withAuthClient(oauth2Client)
                .execute(function (err, result) {
                    if (err) {
                        console.log('[GA ERROR] getData: ', err);
                        return;
                    }
                    console.log(result)
            });
    });
}
```

Can you give me a light ? I'm struggling with it for days.
Thanks

**Comment by domino14** [comment]
Hi Gabriel, could you explain what you mean? I think I'm seeing the same problem, where on development it doesn't refresh properly, but it works on production?

**Comment by gabrielhpugliese** [comment]
In that case I think I was trying to get a token generated from an app X created on Console API but with a client_id/secret from an app Y (probably because I dumped the db and restored on local db)

**Comment by verixomumbai** [comment]
Hi i m getting same issue when i am calling enroll of EMM Google api using OAuth. actually i have service_account json which i got from google console. and using that i m creating Google credential instance and initialize HttpRequest to call enroll. please help me out what i m doing wrong.
