### ISSUE TITLE
Sent requests via HTTP proxy

### ISSUE THREAD

**Issue by jrcryer** [googleapis/google-api-nodejs-client#64]
It would be nice to be able to use the google-api-nodejs-client via a HTTP proxy.  Request appears to support [proxy configuration](https://github.com/mikeal/request#requestoptions-callback).

Possibly via the withOpts:

``` js
discover('youtube', 'v3').withOpts({ proxy: 'http://mylocalproxy.com' });
```

**Comment by vaughnmuirhead** [comment]
Yep, process.env.HTTPS_PROXY = 'http://<url>:<port>'; worked for me. Thanks @aguegu

**Comment by mirismaili** [comment]
I tried `google.options({ proxy: 'http://SOMETHING_WRONG' })`. It works regularly! So it shouldn't be the correct setting.

I found the below option works as expected:
```js
const HttpsProxyAgent = require('https-proxy-agent')
const {google} = require('googleapis')
google.options({
	agent: new HttpsProxyAgent('http://127.0.0.1:8580')
})
```
This crashes on wrong proxies. OK.
***
Ref:
https://github.com/googleapis/google-api-nodejs-client#request-options says:
> For more fine-tuned control over how your API calls are made, we provide you with the ability to specify additional options that can be applied directly to the '[gaxios](https://github.com/JustinBeckwith/gaxios)' object used in this library to make network calls to the API.

And [gaxios](https://github.com/JustinBeckwith/gaxios) introduces itself:
> An HTTP request client that provides an axios like interface over top of node-fetch

And [node-fetch](https://github.com/node-fetch/node-fetch) uses [http-agent](https://nodejs.org/api/http.html#http_new_agent_options):

https://github.com/node-fetch/node-fetch#custom-agent
