### ISSUE TITLE
Unavailable unless you sign out of all other Google Accounts

### ISSUE THREAD

**Issue by suparnavg** [googleapis/google-api-nodejs-client#974]
I've looked all over for a solution to this only to find other equally frustrated developers. Stackoverflow does not have any relevant answers, so I'm asking this here to verify if this is even doable.

Background: My app (authorized by Oauth2.0) fetches a user's google drive files (this works fine) and I give the user a link to view / download the file, within my app.

Unfortunately on clicking the webViewLink, or webContentLink I get the errors below:
![image](https://user-images.githubusercontent.com/1419812/35479825-801bce0e-0426-11e8-9586-7e687c040f4e.png)
`webViewLink error`

![image](https://user-images.githubusercontent.com/1419812/35479830-9b70b070-0426-11e8-95f3-7bccf6a21c34.png)
`webContentLink error`

This seems to be happening because while opening the links, my browser assumes I'm opening them with my default (personal) account, when in fact my app has been authorized to use the secondary / work accounts.

I found a workaround online: which is to create a new "person" in chrome (with my secondary account) and open a new window with the new person to run my app. Everything works fine, but is a vastly inferior user experience.

Some stackoverflow answers suggested to modify the content links with an authuser=xx or a u/<secondary_email_id> before displaying to the user - unfortunately this does not work.

I'd appreciate any help from the good folks here.

Thanks in advance!

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share the code you're using here?  I'm having a little trouble reproducing this one.  Even a link to the API reference page like [this one](https://developers.google.com/drive/v3/reference/) would be super helpful.

**Comment by suparnavg** [comment]
Absolutely, thanks @JustinBeckwith 

To create a new file:

```
var fileMetadata = {
	'name': files.file.name,
	....,
	parents: [...]
};
var media = { mimeType: files.file.type, body: fs.createReadStream(files.file.path),};

driveService.files.create({	auth: oauth2Client, resource: fileMetadata, media: media, fields: '*'}, function (err, response) {
	if (err) {console.log(' error creating file ', err.response);}
	else {
		// use response
	}
```

This creates a file correctly, with webViewLink and webContentLink parameters

To display a user's files on the front end, I simply use the driveService.files.list method to fetch the files and send them to the front end.

It's here that things get tricky.

I am using Google Chrome, which as you know has a "default" user and then additional Google accounts that the default user may also sign into.

If the user is viewing their Drive belonging to a **non-default** account, I get the errors screenshotted in the previous comment.

I admit this might be the wrong place to post this issue, as it could be a Chrome thing. However I was wondering if there's any way to at least modify the webViewLink and webContentLink to make them accessible to the non-default user.

Thanks!

**Comment by grant** [comment]
Hey @suparnavg, thanks for the issue. I've experienced this too with different G Suite accounts / Chrome profiles.

It looks like this is a Drive file that is not shared publically. Opening this file in an incognito or logged-out account should get rid of the **403 forbidden** error. Can you try that?

If that works, but you don't want to open a sessionless browser everytime you click the `webViewLink`, then make sure that the Drive files that you are accessing have the correct sharing permissions. You may need to share the file with the G Suite email you desire to access the file from (you can do that manually or programmatically).

You can also share with a service account's email address to access the file without OAuth.

**Comment by suparnavg** [comment]
Hi @grant , the file is indeed not shared publicly. It is a private file - created by, or shared with the signed in Google / G Suite user who is trying to access it.

**Comment by tatil-design** [comment]
Hi everyone.

Is there any movement on this? I am having exactly the same issue.

**Comment by JustinBeckwith** [comment]
Nothing from me.  I'd be very surprised if this had anything to do with the npm module, which is generally what we're going to be able to help with.  Seems like some sort of buggy interaction between Chrome and the Google OAuth2 consent screen 🤔

**Comment by grant** [comment]
In order to better triage this issue, it would be useful:
- Have a complete code snippet and set of instructions to reproduce the error.
- Ensure the bug is still reproducible in Chrome Incognito.

As Justin mentioned, it is probably not an issue with the Node client, but rather with Google Drive / G Suite Accounts.

I'll plus @sqrrrl who might know how to triage this issue.

**Comment by tatil-design** [comment]
@JustinBeckwith That's what I thought, but since the issue was still open I thought there was a slim chance it could be the module's fault. Thanks for responding.

**Comment by Nyceane** [comment]
This is so annoying, why is it not fixed?

**Comment by JustinBeckwith** [comment]
Greetings folks!  Sadly, I don't think there's much we can do here in the library.  I suggest filing an issue directly on the Google Drive API tracker, since the issue has started there:
https://issuetracker.google.com/issues?q=componentid:191650%2B

**Comment by taygrave** [comment]
for others arriving here w/ the same issue: here is another link to the google issue tracker https://issuetracker.google.com/issues/243636252

Looks like google determined it as: 
```
"Status: Won't Fix (Intended Behavior)
This behavior is intended and it is described on [Fix issues with multiple Google Accounts](https://developers.google.com/apps-script/guides/projects#fix_issues_with_multiple_google_accounts):
```

And is going to ask you to tell your users to try opening the link in an incognito tab or logging out of their other accounts even though your app can't tell when they are going to have the problem or not.
